/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.0.v202012010944.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
#ifndef V1_VHAL_LOGR_LOGR__VHAL_INTERFACE_SOMEIP_PROXY_HPP_
#define V1_VHAL_LOGR_LOGR__VHAL_INTERFACE_SOMEIP_PROXY_HPP_

#include <v1/VHAL/LOGR/LOGR_VHALInterfaceProxyBase.hpp>
#include <VHAL/LOGR/LOGR_TypesSomeIPDeployment.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/SomeIP/Factory.hpp>
#include <CommonAPI/SomeIP/Proxy.hpp>
#include <CommonAPI/SomeIP/Types.hpp>
#include <CommonAPI/SomeIP/Event.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <string>

# if defined(_MSC_VER)
#  if _MSC_VER >= 1300
/*
 * Diamond inheritance is used for the CommonAPI::Proxy base class.
 * The Microsoft compiler put warning (C4250) using a desired c++ feature: "Delegating to a sister class"
 * A powerful technique that arises from using virtual inheritance is to delegate a method from a class in another class
 * by using a common abstract base class. This is also called cross delegation.
 */
#    pragma warning( disable : 4250 )
#  endif
# endif

namespace v1 {
namespace VHAL {
namespace LOGR {

class LOGR_VHALInterfaceSomeIPProxy
    : virtual public LOGR_VHALInterfaceProxyBase,
      virtual public CommonAPI::SomeIP::Proxy {
public:
    LOGR_VHALInterfaceSomeIPProxy(
        const CommonAPI::SomeIP::Address &_address,
        const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection);

    virtual ~LOGR_VHALInterfaceSomeIPProxy();

    virtual Request_finishedEvent& getRequest_finishedEvent();

    virtual void retrieve(::VHAL::LOGR::LOGR_Types::LOGR_verbosity _verbosity, std::vector< ::VHAL::LOGR::LOGR_Types::LOGR_source > _sources, ::VHAL::LOGR::LOGR_Types::t_time_UTC _starttime, ::VHAL::LOGR::LOGR_Types::t_time_UTC _endtime, CommonAPI::CallStatus &_internalCallStatus, ::VHAL::LOGR::LOGR_Types::LOGR_status &_status, const CommonAPI::CallInfo *_info);

    virtual std::future<CommonAPI::CallStatus> retrieveAsync(const ::VHAL::LOGR::LOGR_Types::LOGR_verbosity &_verbosity, const std::vector< ::VHAL::LOGR::LOGR_Types::LOGR_source > &_sources, const ::VHAL::LOGR::LOGR_Types::t_time_UTC &_starttime, const ::VHAL::LOGR::LOGR_Types::t_time_UTC &_endtime, RetrieveAsyncCallback _callback, const CommonAPI::CallInfo *_info);

    virtual void free(std::string _file_path, CommonAPI::CallStatus &_internalCallStatus, ::VHAL::LOGR::LOGR_Types::LOGR_status &_status, const CommonAPI::CallInfo *_info);

    virtual std::future<CommonAPI::CallStatus> freeAsync(const std::string &_file_path, FreeAsyncCallback _callback, const CommonAPI::CallInfo *_info);

    virtual void status(CommonAPI::CallStatus &_internalCallStatus, ::VHAL::LOGR::LOGR_Types::LOGR_status &_status, const CommonAPI::CallInfo *_info);

    virtual std::future<CommonAPI::CallStatus> statusAsync(StatusAsyncCallback _callback, const CommonAPI::CallInfo *_info);

    virtual void cancel(CommonAPI::CallStatus &_internalCallStatus, ::VHAL::LOGR::LOGR_Types::LOGR_status &_status, const CommonAPI::CallInfo *_info);

    virtual std::future<CommonAPI::CallStatus> cancelAsync(CancelAsyncCallback _callback, const CommonAPI::CallInfo *_info);

    virtual void system_timezone_offset(int32_t _timezone, CommonAPI::CallStatus &_internalCallStatus, const CommonAPI::CallInfo *_info);

    virtual std::future<CommonAPI::CallStatus> system_timezone_offsetAsync(const int32_t &_timezone, System_timezone_offsetAsyncCallback _callback, const CommonAPI::CallInfo *_info);

    virtual void getOwnVersion(uint16_t &_major, uint16_t &_minor) const;

    virtual std::future<void> getCompletionFuture();

private:
    CommonAPI::SomeIP::Event<Request_finishedEvent, CommonAPI::Deployable< ::VHAL::LOGR::LOGR_Types::LOGR_status, ::VHAL::LOGR::LOGR_Types_::LOGR_statusDeployment_t >, CommonAPI::Deployable< std::string, CommonAPI::SomeIP::StringDeployment >> request_finished_;

    std::promise<void> completed_;
};

} // namespace LOGR
} // namespace VHAL
} // namespace v1

#endif // V1_VHAL_LOGR_LOGR__VHAL_Interface_SOMEIP_PROXY_HPP_
