/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.0.v202012010944.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
#include <v1/VHAL/LOGR/LOGR_VHALInterfaceSomeIPStubAdapter.hpp>
#include <v1/VHAL/LOGR/LOGR_VHALInterface.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/SomeIP/AddressTranslator.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace VHAL {
namespace LOGR {

std::shared_ptr<CommonAPI::SomeIP::StubAdapter> createLOGR_VHALInterfaceSomeIPStubAdapter(
                   const CommonAPI::SomeIP::Address &_address,
                   const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection,
                   const std::shared_ptr<CommonAPI::StubBase> &_stub) {
    return std::make_shared< LOGR_VHALInterfaceSomeIPStubAdapter<::v1::VHAL::LOGR::LOGR_VHALInterfaceStub>>(_address, _connection, _stub);
}

void initializeLOGR_VHALInterfaceSomeIPStubAdapter() {
    CommonAPI::SomeIP::AddressTranslator::get()->insert(
        "local:VHAL.LOGR.LOGR_VHALInterface:v1_0:VHAL.LOGR.LOGR_VHALInterface",
         0x1a04, 0xa498, 1, 0);
    CommonAPI::SomeIP::Factory::get()->registerStubAdapterCreateMethod(
        "VHAL.LOGR.LOGR_VHALInterface:v1_0",
        &createLOGR_VHALInterfaceSomeIPStubAdapter);
}

INITIALIZER(registerLOGR_VHALInterfaceSomeIPStubAdapter) {
    CommonAPI::SomeIP::Factory::get()->registerInterface(initializeLOGR_VHALInterfaceSomeIPStubAdapter);
}

} // namespace LOGR
} // namespace VHAL
} // namespace v1
