/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.0.v202012010850.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef IMICRO_pm_Structs_HPP_
#define IMICRO_pm_Structs_HPP_



#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/Deployment.hpp>
#include <CommonAPI/InputStream.hpp>
#include <CommonAPI/OutputStream.hpp>
#include <CommonAPI/Struct.hpp>
#include <CommonAPI/Types.hpp>
#include <cstdint>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace iMicro {

struct pmStructs {
    
    struct phonecallstatus : CommonAPI::Enumeration< uint8_t> {
        enum Literal : uint8_t {
            PHONE_STATE_NEW = 0,
            PHONE_STATE_CONNECTING = 1,
            PHONE_STATE_SELECT_PHONE_ACCOUNT = 2,
            PHONE_STATE_DIALING = 3,
            PHONE_STATE_RINGING = 4,
            PHONE_STATE_ACTIVE = 5,
            PHONE_STATE_ON_HOLD = 6,
            PHONE_STATE_DISCONNECTED = 7,
            PHONE_STATE_ABORTED = 8,
            PHONE_STATE_DISCONNECTING = 9,
            PHONE_STATE_PULLING = 10,
            PHONE_STATE_ANSWERED = 11,
            PHONE_STATE_AUDIO_PROCESSING = 12,
            PHONE_STATE_SIMULATED_RINGING = 13
        };
    
        phonecallstatus()
            : CommonAPI::Enumeration< uint8_t>(static_cast< uint8_t>(Literal::PHONE_STATE_NEW)) {}
        phonecallstatus(Literal _literal)
            : CommonAPI::Enumeration< uint8_t>(static_cast< uint8_t>(_literal)) {}
    
        inline bool validate() const {
            switch (value_) {
                case static_cast< uint8_t>(Literal::PHONE_STATE_NEW):
                case static_cast< uint8_t>(Literal::PHONE_STATE_CONNECTING):
                case static_cast< uint8_t>(Literal::PHONE_STATE_SELECT_PHONE_ACCOUNT):
                case static_cast< uint8_t>(Literal::PHONE_STATE_DIALING):
                case static_cast< uint8_t>(Literal::PHONE_STATE_RINGING):
                case static_cast< uint8_t>(Literal::PHONE_STATE_ACTIVE):
                case static_cast< uint8_t>(Literal::PHONE_STATE_ON_HOLD):
                case static_cast< uint8_t>(Literal::PHONE_STATE_DISCONNECTED):
                case static_cast< uint8_t>(Literal::PHONE_STATE_ABORTED):
                case static_cast< uint8_t>(Literal::PHONE_STATE_DISCONNECTING):
                case static_cast< uint8_t>(Literal::PHONE_STATE_PULLING):
                case static_cast< uint8_t>(Literal::PHONE_STATE_ANSWERED):
                case static_cast< uint8_t>(Literal::PHONE_STATE_AUDIO_PROCESSING):
                case static_cast< uint8_t>(Literal::PHONE_STATE_SIMULATED_RINGING):
                return true;
            default:
                return false;
            }
        }
    
        inline bool operator==(const phonecallstatus &_other) const { return (value_ == _other.value_); }
        inline bool operator!=(const phonecallstatus &_other) const { return (value_ != _other.value_); }
        inline bool operator<=(const phonecallstatus &_other) const { return (value_ <= _other.value_); }
        inline bool operator>=(const phonecallstatus &_other) const { return (value_ >= _other.value_); }
        inline bool operator<(const phonecallstatus &_other) const { return (value_ < _other.value_); }
        inline bool operator>(const phonecallstatus &_other) const { return (value_ > _other.value_); }
    
        inline bool operator==(const Literal &_value) const { return (value_ == static_cast< uint8_t>(_value)); }
        inline bool operator!=(const Literal &_value) const { return (value_ != static_cast< uint8_t>(_value)); }
        inline bool operator<=(const Literal &_value) const { return (value_ <= static_cast< uint8_t>(_value)); }
        inline bool operator>=(const Literal &_value) const { return (value_ >= static_cast< uint8_t>(_value)); }
        inline bool operator<(const Literal &_value) const { return (value_ < static_cast< uint8_t>(_value)); }
        inline bool operator>(const Literal &_value) const { return (value_ > static_cast< uint8_t>(_value)); }
    
        const char* toString() const noexcept
        {
            switch(value_)
            {
            case static_cast< uint8_t>(Literal::PHONE_STATE_NEW): return "PHONE_STATE_NEW";
            case static_cast< uint8_t>(Literal::PHONE_STATE_CONNECTING): return "PHONE_STATE_CONNECTING";
            case static_cast< uint8_t>(Literal::PHONE_STATE_SELECT_PHONE_ACCOUNT): return "PHONE_STATE_SELECT_PHONE_ACCOUNT";
            case static_cast< uint8_t>(Literal::PHONE_STATE_DIALING): return "PHONE_STATE_DIALING";
            case static_cast< uint8_t>(Literal::PHONE_STATE_RINGING): return "PHONE_STATE_RINGING";
            case static_cast< uint8_t>(Literal::PHONE_STATE_ACTIVE): return "PHONE_STATE_ACTIVE";
            case static_cast< uint8_t>(Literal::PHONE_STATE_ON_HOLD): return "PHONE_STATE_ON_HOLD";
            case static_cast< uint8_t>(Literal::PHONE_STATE_DISCONNECTED): return "PHONE_STATE_DISCONNECTED";
            case static_cast< uint8_t>(Literal::PHONE_STATE_ABORTED): return "PHONE_STATE_ABORTED";
            case static_cast< uint8_t>(Literal::PHONE_STATE_DISCONNECTING): return "PHONE_STATE_DISCONNECTING";
            case static_cast< uint8_t>(Literal::PHONE_STATE_PULLING): return "PHONE_STATE_PULLING";
            case static_cast< uint8_t>(Literal::PHONE_STATE_ANSWERED): return "PHONE_STATE_ANSWERED";
            case static_cast< uint8_t>(Literal::PHONE_STATE_AUDIO_PROCESSING): return "PHONE_STATE_AUDIO_PROCESSING";
            case static_cast< uint8_t>(Literal::PHONE_STATE_SIMULATED_RINGING): return "PHONE_STATE_SIMULATED_RINGING";
            default: return "UNDEFINED";
            }
        }
    };
    
    struct smsStatus : CommonAPI::Enumeration< uint8_t> {
        enum Literal : uint8_t {
            SMS_RECEIVED = 1,
            MMS_RECEIVED = 2,
            WAP_PUSH_RECEIVED = 3
        };
    
        smsStatus()
            : CommonAPI::Enumeration< uint8_t>(static_cast< uint8_t>(Literal::SMS_RECEIVED)) {}
        smsStatus(Literal _literal)
            : CommonAPI::Enumeration< uint8_t>(static_cast< uint8_t>(_literal)) {}
    
        inline bool validate() const {
            switch (value_) {
                case static_cast< uint8_t>(Literal::SMS_RECEIVED):
                case static_cast< uint8_t>(Literal::MMS_RECEIVED):
                case static_cast< uint8_t>(Literal::WAP_PUSH_RECEIVED):
                return true;
            default:
                return false;
            }
        }
    
        inline bool operator==(const smsStatus &_other) const { return (value_ == _other.value_); }
        inline bool operator!=(const smsStatus &_other) const { return (value_ != _other.value_); }
        inline bool operator<=(const smsStatus &_other) const { return (value_ <= _other.value_); }
        inline bool operator>=(const smsStatus &_other) const { return (value_ >= _other.value_); }
        inline bool operator<(const smsStatus &_other) const { return (value_ < _other.value_); }
        inline bool operator>(const smsStatus &_other) const { return (value_ > _other.value_); }
    
        inline bool operator==(const Literal &_value) const { return (value_ == static_cast< uint8_t>(_value)); }
        inline bool operator!=(const Literal &_value) const { return (value_ != static_cast< uint8_t>(_value)); }
        inline bool operator<=(const Literal &_value) const { return (value_ <= static_cast< uint8_t>(_value)); }
        inline bool operator>=(const Literal &_value) const { return (value_ >= static_cast< uint8_t>(_value)); }
        inline bool operator<(const Literal &_value) const { return (value_ < static_cast< uint8_t>(_value)); }
        inline bool operator>(const Literal &_value) const { return (value_ > static_cast< uint8_t>(_value)); }
    
        const char* toString() const noexcept
        {
            switch(value_)
            {
            case static_cast< uint8_t>(Literal::SMS_RECEIVED): return "SMS_RECEIVED";
            case static_cast< uint8_t>(Literal::MMS_RECEIVED): return "MMS_RECEIVED";
            case static_cast< uint8_t>(Literal::WAP_PUSH_RECEIVED): return "WAP_PUSH_RECEIVED";
            default: return "UNDEFINED";
            }
        }
    };
    /*
     * description: 
     * ivi data
     */
    struct ivi_parameters_type : CommonAPI::Struct< phonecallstatus, uint8_t, smsStatus, uint8_t, uint8_t, uint8_t, uint8_t, uint8_t, uint8_t, uint8_t, uint8_t, uint8_t, uint8_t, uint8_t, uint8_t, uint8_t> {
    
        ivi_parameters_type()
        {
            std::get< 0>(values_) = phonecallstatus();
            std::get< 1>(values_) = 0u;
            std::get< 2>(values_) = smsStatus();
            std::get< 3>(values_) = 0u;
            std::get< 4>(values_) = 0u;
            std::get< 5>(values_) = 0u;
            std::get< 6>(values_) = 0u;
            std::get< 7>(values_) = 0u;
            std::get< 8>(values_) = 0u;
            std::get< 9>(values_) = 0u;
            std::get< 10>(values_) = 0u;
            std::get< 11>(values_) = 0u;
            std::get< 12>(values_) = 0u;
            std::get< 13>(values_) = 0u;
            std::get< 14>(values_) = 0u;
            std::get< 15>(values_) = 0u;
        }
        ivi_parameters_type(const phonecallstatus &_PHONECALL_STATUS, const uint8_t &_X_CALL_ACTIVE, const smsStatus &_SMS_STATUS, const uint8_t &_AUDIO_AUTO_STATUS, const uint8_t &_PARK_ASSIST_APP_STATUS, const uint8_t &_PARTIAL_OP_SCREEN_MODE, const uint8_t &_IDLE_SCREEN_MODE, const uint8_t &_STANDBY_SCREEN_MODE, const uint8_t &_SCREEN_TOUCH, const uint8_t &_ANTI_THEFT_STATUS, const uint8_t &_AUTO_SWITCH_ON, const uint8_t &_RADIO_OFF_DELAY, const uint8_t &_SWITCH_OFF_WITH_DOOR, const uint8_t &_DOOR_CONDITION_2, const uint8_t &_RADIO_OFF_WITH_DOOR, const uint8_t &_POWER_SOFT_BUTTON_PRESSED)
        {
            std::get< 0>(values_) = _PHONECALL_STATUS;
            std::get< 1>(values_) = _X_CALL_ACTIVE;
            std::get< 2>(values_) = _SMS_STATUS;
            std::get< 3>(values_) = _AUDIO_AUTO_STATUS;
            std::get< 4>(values_) = _PARK_ASSIST_APP_STATUS;
            std::get< 5>(values_) = _PARTIAL_OP_SCREEN_MODE;
            std::get< 6>(values_) = _IDLE_SCREEN_MODE;
            std::get< 7>(values_) = _STANDBY_SCREEN_MODE;
            std::get< 8>(values_) = _SCREEN_TOUCH;
            std::get< 9>(values_) = _ANTI_THEFT_STATUS;
            std::get< 10>(values_) = _AUTO_SWITCH_ON;
            std::get< 11>(values_) = _RADIO_OFF_DELAY;
            std::get< 12>(values_) = _SWITCH_OFF_WITH_DOOR;
            std::get< 13>(values_) = _DOOR_CONDITION_2;
            std::get< 14>(values_) = _RADIO_OFF_WITH_DOOR;
            std::get< 15>(values_) = _POWER_SOFT_BUTTON_PRESSED;
        }
        inline const phonecallstatus &getPHONECALL_STATUS() const { return std::get< 0>(values_); }
        inline void setPHONECALL_STATUS(const phonecallstatus &_value) { std::get< 0>(values_) = _value; }
        inline const uint8_t &getX_CALL_ACTIVE() const { return std::get< 1>(values_); }
        inline void setX_CALL_ACTIVE(const uint8_t &_value) { std::get< 1>(values_) = _value; }
        inline const smsStatus &getSMS_STATUS() const { return std::get< 2>(values_); }
        inline void setSMS_STATUS(const smsStatus &_value) { std::get< 2>(values_) = _value; }
        inline const uint8_t &getAUDIO_AUTO_STATUS() const { return std::get< 3>(values_); }
        inline void setAUDIO_AUTO_STATUS(const uint8_t &_value) { std::get< 3>(values_) = _value; }
        inline const uint8_t &getPARK_ASSIST_APP_STATUS() const { return std::get< 4>(values_); }
        inline void setPARK_ASSIST_APP_STATUS(const uint8_t &_value) { std::get< 4>(values_) = _value; }
        inline const uint8_t &getPARTIAL_OP_SCREEN_MODE() const { return std::get< 5>(values_); }
        inline void setPARTIAL_OP_SCREEN_MODE(const uint8_t &_value) { std::get< 5>(values_) = _value; }
        inline const uint8_t &getIDLE_SCREEN_MODE() const { return std::get< 6>(values_); }
        inline void setIDLE_SCREEN_MODE(const uint8_t &_value) { std::get< 6>(values_) = _value; }
        inline const uint8_t &getSTANDBY_SCREEN_MODE() const { return std::get< 7>(values_); }
        inline void setSTANDBY_SCREEN_MODE(const uint8_t &_value) { std::get< 7>(values_) = _value; }
        inline const uint8_t &getSCREEN_TOUCH() const { return std::get< 8>(values_); }
        inline void setSCREEN_TOUCH(const uint8_t &_value) { std::get< 8>(values_) = _value; }
        inline const uint8_t &getANTI_THEFT_STATUS() const { return std::get< 9>(values_); }
        inline void setANTI_THEFT_STATUS(const uint8_t &_value) { std::get< 9>(values_) = _value; }
        inline const uint8_t &getAUTO_SWITCH_ON() const { return std::get< 10>(values_); }
        inline void setAUTO_SWITCH_ON(const uint8_t &_value) { std::get< 10>(values_) = _value; }
        inline const uint8_t &getRADIO_OFF_DELAY() const { return std::get< 11>(values_); }
        inline void setRADIO_OFF_DELAY(const uint8_t &_value) { std::get< 11>(values_) = _value; }
        inline const uint8_t &getSWITCH_OFF_WITH_DOOR() const { return std::get< 12>(values_); }
        inline void setSWITCH_OFF_WITH_DOOR(const uint8_t &_value) { std::get< 12>(values_) = _value; }
        inline const uint8_t &getDOOR_CONDITION_2() const { return std::get< 13>(values_); }
        inline void setDOOR_CONDITION_2(const uint8_t &_value) { std::get< 13>(values_) = _value; }
        inline const uint8_t &getRADIO_OFF_WITH_DOOR() const { return std::get< 14>(values_); }
        inline void setRADIO_OFF_WITH_DOOR(const uint8_t &_value) { std::get< 14>(values_) = _value; }
        inline const uint8_t &getPOWER_SOFT_BUTTON_PRESSED() const { return std::get< 15>(values_); }
        inline void setPOWER_SOFT_BUTTON_PRESSED(const uint8_t &_value) { std::get< 15>(values_) = _value; }
        inline bool operator==(const ivi_parameters_type& _other) const {
        return (getPHONECALL_STATUS() == _other.getPHONECALL_STATUS() && getX_CALL_ACTIVE() == _other.getX_CALL_ACTIVE() && getSMS_STATUS() == _other.getSMS_STATUS() && getAUDIO_AUTO_STATUS() == _other.getAUDIO_AUTO_STATUS() && getPARK_ASSIST_APP_STATUS() == _other.getPARK_ASSIST_APP_STATUS() && getPARTIAL_OP_SCREEN_MODE() == _other.getPARTIAL_OP_SCREEN_MODE() && getIDLE_SCREEN_MODE() == _other.getIDLE_SCREEN_MODE() && getSTANDBY_SCREEN_MODE() == _other.getSTANDBY_SCREEN_MODE() && getSCREEN_TOUCH() == _other.getSCREEN_TOUCH() && getANTI_THEFT_STATUS() == _other.getANTI_THEFT_STATUS() && getAUTO_SWITCH_ON() == _other.getAUTO_SWITCH_ON() && getRADIO_OFF_DELAY() == _other.getRADIO_OFF_DELAY() && getSWITCH_OFF_WITH_DOOR() == _other.getSWITCH_OFF_WITH_DOOR() && getDOOR_CONDITION_2() == _other.getDOOR_CONDITION_2() && getRADIO_OFF_WITH_DOOR() == _other.getRADIO_OFF_WITH_DOOR() && getPOWER_SOFT_BUTTON_PRESSED() == _other.getPOWER_SOFT_BUTTON_PRESSED());
        }
        inline bool operator!=(const ivi_parameters_type &_other) const {
            return !((*this) == _other);
        }
    
    };
    /*
     * description: 
     * tcu data
     */
    struct tcu_parameters_type : CommonAPI::Struct< uint8_t, uint8_t, uint8_t, uint8_t> {
    
        tcu_parameters_type()
        {
            std::get< 0>(values_) = 0u;
            std::get< 1>(values_) = 0u;
            std::get< 2>(values_) = 0u;
            std::get< 3>(values_) = 0u;
        }
        tcu_parameters_type(const uint8_t &_REMOTE_START, const uint8_t &_PENDING_TCU_ACTION, const uint8_t &_SERVICE_PROVIDER_CONNECTION_STATUS, const uint8_t &_CONNECTION_UNLOCK_STATUS)
        {
            std::get< 0>(values_) = _REMOTE_START;
            std::get< 1>(values_) = _PENDING_TCU_ACTION;
            std::get< 2>(values_) = _SERVICE_PROVIDER_CONNECTION_STATUS;
            std::get< 3>(values_) = _CONNECTION_UNLOCK_STATUS;
        }
        inline const uint8_t &getREMOTE_START() const { return std::get< 0>(values_); }
        inline void setREMOTE_START(const uint8_t &_value) { std::get< 0>(values_) = _value; }
        inline const uint8_t &getPENDING_TCU_ACTION() const { return std::get< 1>(values_); }
        inline void setPENDING_TCU_ACTION(const uint8_t &_value) { std::get< 1>(values_) = _value; }
        inline const uint8_t &getSERVICE_PROVIDER_CONNECTION_STATUS() const { return std::get< 2>(values_); }
        inline void setSERVICE_PROVIDER_CONNECTION_STATUS(const uint8_t &_value) { std::get< 2>(values_) = _value; }
        inline const uint8_t &getCONNECTION_UNLOCK_STATUS() const { return std::get< 3>(values_); }
        inline void setCONNECTION_UNLOCK_STATUS(const uint8_t &_value) { std::get< 3>(values_) = _value; }
        inline bool operator==(const tcu_parameters_type& _other) const {
        return (getREMOTE_START() == _other.getREMOTE_START() && getPENDING_TCU_ACTION() == _other.getPENDING_TCU_ACTION() && getSERVICE_PROVIDER_CONNECTION_STATUS() == _other.getSERVICE_PROVIDER_CONNECTION_STATUS() && getCONNECTION_UNLOCK_STATUS() == _other.getCONNECTION_UNLOCK_STATUS());
        }
        inline bool operator!=(const tcu_parameters_type &_other) const {
            return !((*this) == _other);
        }
    
    };


static inline const char* getTypeCollectionName() {
    static const char* typeCollectionName = "iMicro.pmStructs";
    return typeCollectionName;
}


}; // struct pmStructs

} // namespace iMicro

namespace CommonAPI {
}


namespace std {
    //Hash for phonecallstatus
    template<>
    struct hash< ::iMicro::pmStructs::phonecallstatus> {
        inline size_t operator()(const ::iMicro::pmStructs::phonecallstatus& phonecallstatus) const {
            return static_cast< uint8_t>(phonecallstatus);
        }
    };
    //Hash for smsStatus
    template<>
    struct hash< ::iMicro::pmStructs::smsStatus> {
        inline size_t operator()(const ::iMicro::pmStructs::smsStatus& smsStatus) const {
            return static_cast< uint8_t>(smsStatus);
        }
    };
}



#endif // IMICRO_pm_Structs_HPP_
