/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.0.v202012010850.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V0_VHAL_VHAL__LIFECYCLE_STUB_DEFAULT_HPP_
#define V0_VHAL_VHAL__LIFECYCLE_STUB_DEFAULT_HPP_


#include <CommonAPI/Export.hpp>

#include <v0/VHAL/VHAL_LIFECYCLEStub.hpp>
#include <cassert>
#include <sstream>

# if defined(_MSC_VER)
#  if _MSC_VER >= 1300
/*
 * Diamond inheritance is used for the CommonAPI::Proxy base class.
 * The Microsoft compiler put warning (C4250) using a desired c++ feature: "Delegating to a sister class"
 * A powerful technique that arises from using virtual inheritance is to delegate a method from a class in another class
 * by using a common abstract base class. This is also called cross delegation.
 */
#    pragma warning( disable : 4250 )
#  endif
# endif

namespace v0 {
namespace VHAL {

/**
 * Provides a default implementation for VHAL_LIFECYCLEStubRemoteEvent and
 * VHAL_LIFECYCLEStub. Method callbacks have an empty implementation,
 * remote set calls on attributes will always change the value of the attribute
 * to the one received.
 *
 * Override this stub if you only want to provide a subset of the functionality
 * that would be defined for this service, and/or if you do not need any non-default
 * behaviour.
 */
class COMMONAPI_EXPORT_CLASS_EXPLICIT VHAL_LIFECYCLEStubDefault
    : public virtual VHAL_LIFECYCLEStub {
public:
    COMMONAPI_EXPORT VHAL_LIFECYCLEStubDefault()
        : remoteEventHandler_(this),
          interfaceVersion_(VHAL_LIFECYCLE::getInterfaceVersion()) {
    }

    COMMONAPI_EXPORT const CommonAPI::Version& getInterfaceVersion(std::shared_ptr<CommonAPI::ClientId> _client) {
        (void)_client;
        return interfaceVersion_;
    }

    COMMONAPI_EXPORT VHAL_LIFECYCLEStubRemoteEvent* initStubAdapter(const std::shared_ptr< VHAL_LIFECYCLEStubAdapter> &_adapter) {
        CommonAPI::Stub<VHAL_LIFECYCLEStubAdapter, VHAL_LIFECYCLEStubRemoteEvent>::stubAdapter_ = _adapter;
        return &remoteEventHandler_;
    }

    COMMONAPI_EXPORT virtual void ecallStatus_ack(const std::shared_ptr<CommonAPI::ClientId> _client, uint8_t _conf, ecallStatus_ackReply_t _reply) {
        (void)_client;
        (void)_conf;
        _reply();
    }
    COMMONAPI_EXPORT virtual const uint8_t &getEcallStatusAttribute() {
        return ecallStatusAttributeValue_;
    }
    COMMONAPI_EXPORT virtual const uint8_t &getEcallStatusAttribute(const std::shared_ptr<CommonAPI::ClientId> _client) {
        (void)_client;
        return getEcallStatusAttribute();
    }
    COMMONAPI_EXPORT virtual void setEcallStatusAttribute(uint8_t _value) {
        const bool valueChanged = trySetEcallStatusAttribute(std::move(_value));
        if (valueChanged) {
            fireEcallStatusAttributeChanged(ecallStatusAttributeValue_);
        }
    }
    COMMONAPI_EXPORT virtual void Receive_MsdTransmissionTime_TCU(const std::shared_ptr<CommonAPI::ClientId> _client, uint32_t _conf, Receive_MsdTransmissionTime_TCUReply_t _reply) {
        (void)_client;
        (void)_conf;
        _reply();
    }
    COMMONAPI_EXPORT virtual void Receive_EcallState_TCU(const std::shared_ptr<CommonAPI::ClientId> _client, uint32_t _conf, Receive_EcallState_TCUReply_t _reply) {
        (void)_client;
        (void)_conf;
        _reply();
    }
    COMMONAPI_EXPORT virtual void Receive_AcallState_TCU(const std::shared_ptr<CommonAPI::ClientId> _client, uint32_t _conf, Receive_AcallState_TCUReply_t _reply) {
        (void)_client;
        (void)_conf;
        _reply();
    }
    COMMONAPI_EXPORT virtual void Receive_UserXcallFeedback_TCU(const std::shared_ptr<CommonAPI::ClientId> _client, uint32_t _conf, Receive_UserXcallFeedback_TCUReply_t _reply) {
        (void)_client;
        (void)_conf;
        _reply();
    }
    COMMONAPI_EXPORT virtual void Receive_EcallDurationTimer_TCU(const std::shared_ptr<CommonAPI::ClientId> _client, uint32_t _conf, Receive_EcallDurationTimer_TCUReply_t _reply) {
        (void)_client;
        (void)_conf;
        _reply();
    }
    COMMONAPI_EXPORT virtual void Receive_EcallTpsState_TCU(const std::shared_ptr<CommonAPI::ClientId> _client, uint32_t _conf, Receive_EcallTpsState_TCUReply_t _reply) {
        (void)_client;
        (void)_conf;
        _reply();
    }
    COMMONAPI_EXPORT virtual void Receive_XcallStatus_TCU(const std::shared_ptr<CommonAPI::ClientId> _client, uint32_t _conf, Receive_XcallStatus_TCUReply_t _reply) {
        (void)_client;
        (void)_conf;
        _reply();
    }
    COMMONAPI_EXPORT virtual void Receive_EcallWcbTimer_TCU(const std::shared_ptr<CommonAPI::ClientId> _client, uint32_t _conf, Receive_EcallWcbTimer_TCUReply_t _reply) {
        (void)_client;
        (void)_conf;
        _reply();
    }
    COMMONAPI_EXPORT virtual void Receive_DmdMuteSual(const std::shared_ptr<CommonAPI::ClientId> _client, uint32_t _conf, Receive_DmdMuteSualReply_t _reply) {
        (void)_client;
        (void)_conf;
        _reply();
    }
    COMMONAPI_EXPORT virtual void Receive_AppUrgMds(const std::shared_ptr<CommonAPI::ClientId> _client, uint32_t _conf, Receive_AppUrgMdsReply_t _reply) {
        (void)_client;
        (void)_conf;
        _reply();
    }
    COMMONAPI_EXPORT virtual void Receive_SignalVoyantDysfunction(const std::shared_ptr<CommonAPI::ClientId> _client, uint32_t _conf, Receive_SignalVoyantDysfunctionReply_t _reply) {
        (void)_client;
        (void)_conf;
        _reply();
    }
    COMMONAPI_EXPORT virtual void Receive_SignalVoyantEtat(const std::shared_ptr<CommonAPI::ClientId> _client, uint32_t _conf, Receive_SignalVoyantEtatReply_t _reply) {
        (void)_client;
        (void)_conf;
        _reply();
    }
    COMMONAPI_EXPORT virtual void Receive_BoostrapRetryCount(const std::shared_ptr<CommonAPI::ClientId> _client, uint32_t _conf, Receive_BoostrapRetryCountReply_t _reply) {
        (void)_client;
        (void)_conf;
        _reply();
    }
    COMMONAPI_EXPORT virtual void Receive_CloudConnectionStatus_CConnState_connectionGateID(const std::shared_ptr<CommonAPI::ClientId> _client, uint32_t _conf, Receive_CloudConnectionStatus_CConnState_connectionGateIDReply_t _reply) {
        (void)_client;
        (void)_conf;
        _reply();
    }
    COMMONAPI_EXPORT virtual void Receive_CloudConnectionStatus_CConnState_isConnected(const std::shared_ptr<CommonAPI::ClientId> _client, uint32_t _conf, Receive_CloudConnectionStatus_CConnState_isConnectedReply_t _reply) {
        (void)_client;
        (void)_conf;
        _reply();
    }
    COMMONAPI_EXPORT virtual void Receive_CloudConnectionStatus_CConnState_connType(const std::shared_ptr<CommonAPI::ClientId> _client, uint32_t _conf, Receive_CloudConnectionStatus_CConnState_connTypeReply_t _reply) {
        (void)_client;
        (void)_conf;
        _reply();
    }
    COMMONAPI_EXPORT virtual void Receive_CloudConnectionStatus_CConnState_isRoaming(const std::shared_ptr<CommonAPI::ClientId> _client, uint32_t _conf, Receive_CloudConnectionStatus_CConnState_isRoamingReply_t _reply) {
        (void)_client;
        (void)_conf;
        _reply();
    }
    COMMONAPI_EXPORT virtual void Receive_CloudConnectionStatus_CConnState_sigStrength(const std::shared_ptr<CommonAPI::ClientId> _client, uint32_t _conf, Receive_CloudConnectionStatus_CConnState_sigStrengthReply_t _reply) {
        (void)_client;
        (void)_conf;
        _reply();
    }
    COMMONAPI_EXPORT virtual void Receive_CloudConnectionStatus_CConnState_ipVersion(const std::shared_ptr<CommonAPI::ClientId> _client, uint32_t _conf, Receive_CloudConnectionStatus_CConnState_ipVersionReply_t _reply) {
        (void)_client;
        (void)_conf;
        _reply();
    }
    COMMONAPI_EXPORT virtual void Receive_CellularNetworkType(const std::shared_ptr<CommonAPI::ClientId> _client, uint32_t _conf, Receive_CellularNetworkTypeReply_t _reply) {
        (void)_client;
        (void)_conf;
        _reply();
    }
    COMMONAPI_EXPORT virtual void Receive_NetConnection(const std::shared_ptr<CommonAPI::ClientId> _client, uint32_t _conf, Receive_NetConnectionReply_t _reply) {
        (void)_client;
        (void)_conf;
        _reply();
    }
    COMMONAPI_EXPORT virtual void Receive_Cellsignal(const std::shared_ptr<CommonAPI::ClientId> _client, uint32_t _conf, Receive_CellsignalReply_t _reply) {
        (void)_client;
        (void)_conf;
        _reply();
    }
    COMMONAPI_EXPORT virtual void Receive_CloudConnectionStatus_CConnCtrl_reqDisable(const std::shared_ptr<CommonAPI::ClientId> _client, uint32_t _conf, Receive_CloudConnectionStatus_CConnCtrl_reqDisableReply_t _reply) {
        (void)_client;
        (void)_conf;
        _reply();
    }
    COMMONAPI_EXPORT virtual void fireSend_UserXCallInput_TCUEvent(const uint32_t &_conf) {
        VHAL_LIFECYCLEStub::fireSend_UserXCallInput_TCUEvent(_conf);
    }
    COMMONAPI_EXPORT virtual void fireSend_Language_selectionEvent(const uint32_t &_conf) {
        VHAL_LIFECYCLEStub::fireSend_Language_selectionEvent(_conf);
    }
    COMMONAPI_EXPORT virtual void getLanguageSelectionOnBootup(const std::shared_ptr<CommonAPI::ClientId> _client, getLanguageSelectionOnBootupReply_t _reply) {
        (void)_client;
        uint32_t language = 0ul;
        _reply(language);
    }
    COMMONAPI_EXPORT virtual const uint32_t &getPrivacy_ModeAttribute() {
        return privacy_ModeAttributeValue_;
    }
    COMMONAPI_EXPORT virtual const uint32_t &getPrivacy_ModeAttribute(const std::shared_ptr<CommonAPI::ClientId> _client) {
        (void)_client;
        return getPrivacy_ModeAttribute();
    }
    COMMONAPI_EXPORT virtual void setPrivacy_ModeAttribute(uint32_t _value) {
        const bool valueChanged = trySetPrivacy_ModeAttribute(std::move(_value));
        if (valueChanged) {
            firePrivacy_ModeAttributeChanged(privacy_ModeAttributeValue_);
        }
    }
    COMMONAPI_EXPORT virtual void Receive_SLIRoadType(const std::shared_ptr<CommonAPI::ClientId> _client, uint32_t _conf, Receive_SLIRoadTypeReply_t _reply) {
        (void)_client;
        (void)_conf;
        _reply();
    }
    COMMONAPI_EXPORT virtual void Receive_SLISpeedLimit(const std::shared_ptr<CommonAPI::ClientId> _client, uint32_t _conf, Receive_SLISpeedLimitReply_t _reply) {
        (void)_client;
        (void)_conf;
        _reply();
    }
    COMMONAPI_EXPORT virtual void Receive_SLICountryCode(const std::shared_ptr<CommonAPI::ClientId> _client, uint32_t _conf, Receive_SLICountryCodeReply_t _reply) {
        (void)_client;
        (void)_conf;
        _reply();
    }
    COMMONAPI_EXPORT virtual void Flash_Unitid(const std::shared_ptr<CommonAPI::ClientId> _client, uint32_t _conf, Flash_UnitidReply_t _reply) {
        (void)_client;
        (void)_conf;
        _reply();
    }
    COMMONAPI_EXPORT virtual const uint32_t &getFlash_ResultAttribute() {
        return flash_ResultAttributeValue_;
    }
    COMMONAPI_EXPORT virtual const uint32_t &getFlash_ResultAttribute(const std::shared_ptr<CommonAPI::ClientId> _client) {
        (void)_client;
        return getFlash_ResultAttribute();
    }
    COMMONAPI_EXPORT virtual void setFlash_ResultAttribute(uint32_t _value) {
        const bool valueChanged = trySetFlash_ResultAttribute(std::move(_value));
        if (valueChanged) {
            fireFlash_ResultAttributeChanged(flash_ResultAttributeValue_);
        }
    }
    COMMONAPI_EXPORT virtual void Package_Path(const std::shared_ptr<CommonAPI::ClientId> _client, std::string _conf, Package_PathReply_t _reply) {
        (void)_client;
        (void)_conf;
        _reply();
    }
    COMMONAPI_EXPORT virtual void sIdsRegisterApp(const std::shared_ptr<CommonAPI::ClientId> _client, std::string _appId, std::string _appName, sIdsRegisterAppReply_t _reply) {
        (void)_client;
        (void)_appId;
        (void)_appName;
        std::string status = "";
        _reply(status);
    }
    COMMONAPI_EXPORT virtual void sIdsUnRegisterApp(const std::shared_ptr<CommonAPI::ClientId> _client, sIdsUnRegisterAppReply_t _reply) {
        (void)_client;
        std::string status = "";
        _reply(status);
    }
    COMMONAPI_EXPORT virtual void sIdsWriteSev(const std::shared_ptr<CommonAPI::ClientId> _client, ::VHAL::sIdsFramework_Types::sStSecurityEvent _sevEvent, ::VHAL::sIdsFramework_Types::sStLogIssuer _issuer1, ::VHAL::sIdsFramework_Types::sStEventSrc _issuer2, ::VHAL::sIdsFramework_Types::sStAction _issuer3, sIdsWriteSevReply_t _reply) {
        (void)_client;
        (void)_sevEvent;
        (void)_issuer1;
        (void)_issuer2;
        (void)_issuer3;
        std::string status = "";
        _reply(status);
    }
    COMMONAPI_EXPORT virtual const uint32_t &getXCallHmiControlAttribute() {
        return xCallHmiControlAttributeValue_;
    }
    COMMONAPI_EXPORT virtual const uint32_t &getXCallHmiControlAttribute(const std::shared_ptr<CommonAPI::ClientId> _client) {
        (void)_client;
        return getXCallHmiControlAttribute();
    }
    COMMONAPI_EXPORT virtual void setXCallHmiControlAttribute(uint32_t _value) {
        const bool valueChanged = trySetXCallHmiControlAttribute(std::move(_value));
        if (valueChanged) {
            fireXCallHmiControlAttributeChanged(xCallHmiControlAttributeValue_);
        }
    }
    COMMONAPI_EXPORT virtual const std::string &getHMI_FOTA_Update_historyAttribute() {
        return hMI_FOTA_Update_historyAttributeValue_;
    }
    COMMONAPI_EXPORT virtual const std::string &getHMI_FOTA_Update_historyAttribute(const std::shared_ptr<CommonAPI::ClientId> _client) {
        (void)_client;
        return getHMI_FOTA_Update_historyAttribute();
    }
    COMMONAPI_EXPORT virtual void setHMI_FOTA_Update_historyAttribute(std::string _value) {
        const bool valueChanged = trySetHMI_FOTA_Update_historyAttribute(std::move(_value));
        if (valueChanged) {
            fireHMI_FOTA_Update_historyAttributeChanged(hMI_FOTA_Update_historyAttributeValue_);
        }
    }
    COMMONAPI_EXPORT virtual const std::string &getHMI_FOTA_pending_updatesAttribute() {
        return hMI_FOTA_pending_updatesAttributeValue_;
    }
    COMMONAPI_EXPORT virtual const std::string &getHMI_FOTA_pending_updatesAttribute(const std::shared_ptr<CommonAPI::ClientId> _client) {
        (void)_client;
        return getHMI_FOTA_pending_updatesAttribute();
    }
    COMMONAPI_EXPORT virtual void setHMI_FOTA_pending_updatesAttribute(std::string _value) {
        const bool valueChanged = trySetHMI_FOTA_pending_updatesAttribute(std::move(_value));
        if (valueChanged) {
            fireHMI_FOTA_pending_updatesAttributeChanged(hMI_FOTA_pending_updatesAttributeValue_);
        }
    }
    COMMONAPI_EXPORT virtual void ReceiveFOTA_Check_for_Updates_Result(const std::shared_ptr<CommonAPI::ClientId> _client, std::string _conf, ReceiveFOTA_Check_for_Updates_ResultReply_t _reply) {
        (void)_client;
        (void)_conf;
        _reply();
    }
    COMMONAPI_EXPORT virtual void ReceiveFOTA_Update_Available(const std::shared_ptr<CommonAPI::ClientId> _client, std::string _conf, ReceiveFOTA_Update_AvailableReply_t _reply) {
        (void)_client;
        (void)_conf;
        _reply();
    }
    COMMONAPI_EXPORT virtual void ReceiveFOTA_Conditions_not_Met(const std::shared_ptr<CommonAPI::ClientId> _client, std::string _conf, ReceiveFOTA_Conditions_not_MetReply_t _reply) {
        (void)_client;
        (void)_conf;
        _reply();
    }
    COMMONAPI_EXPORT virtual void ReceiveFOTA_Installation_Status(const std::shared_ptr<CommonAPI::ClientId> _client, std::string _conf, ReceiveFOTA_Installation_StatusReply_t _reply) {
        (void)_client;
        (void)_conf;
        _reply();
    }
    COMMONAPI_EXPORT virtual void ReceiveFOTA_Update_Finished(const std::shared_ptr<CommonAPI::ClientId> _client, std::string _conf, ReceiveFOTA_Update_FinishedReply_t _reply) {
        (void)_client;
        (void)_conf;
        _reply();
    }
    COMMONAPI_EXPORT virtual void ReceiveFOTASchedule_Update_Response(const std::shared_ptr<CommonAPI::ClientId> _client, std::string _conf, ReceiveFOTASchedule_Update_ResponseReply_t _reply) {
        (void)_client;
        (void)_conf;
        _reply();
    }
    COMMONAPI_EXPORT virtual void ReceiveFOTAWhatsNew_Details_Response(const std::shared_ptr<CommonAPI::ClientId> _client, std::string _conf, ReceiveFOTAWhatsNew_Details_ResponseReply_t _reply) {
        (void)_client;
        (void)_conf;
        _reply();
    }
    COMMONAPI_EXPORT virtual void ReceiveFOTAUpdate_History_Response(const std::shared_ptr<CommonAPI::ClientId> _client, std::string _conf, ReceiveFOTAUpdate_History_ResponseReply_t _reply) {
        (void)_client;
        (void)_conf;
        _reply();
    }
    COMMONAPI_EXPORT virtual void ReceiveFOTAPending_Updates_Response(const std::shared_ptr<CommonAPI::ClientId> _client, std::string _conf, ReceiveFOTAPending_Updates_ResponseReply_t _reply) {
        (void)_client;
        (void)_conf;
        _reply();
    }
    COMMONAPI_EXPORT virtual const std::string &getFOTA_Installation_Finished_with_User_ConformationAttribute() {
        return fOTA_Installation_Finished_with_User_ConformationAttributeValue_;
    }
    COMMONAPI_EXPORT virtual const std::string &getFOTA_Installation_Finished_with_User_ConformationAttribute(const std::shared_ptr<CommonAPI::ClientId> _client) {
        (void)_client;
        return getFOTA_Installation_Finished_with_User_ConformationAttribute();
    }
    COMMONAPI_EXPORT virtual void setFOTA_Installation_Finished_with_User_ConformationAttribute(std::string _value) {
        const bool valueChanged = trySetFOTA_Installation_Finished_with_User_ConformationAttribute(std::move(_value));
        if (valueChanged) {
            fireFOTA_Installation_Finished_with_User_ConformationAttributeChanged(fOTA_Installation_Finished_with_User_ConformationAttributeValue_);
        }
    }
    COMMONAPI_EXPORT virtual const std::string &getFOTA_Start_InstallationAttribute() {
        return fOTA_Start_InstallationAttributeValue_;
    }
    COMMONAPI_EXPORT virtual const std::string &getFOTA_Start_InstallationAttribute(const std::shared_ptr<CommonAPI::ClientId> _client) {
        (void)_client;
        return getFOTA_Start_InstallationAttribute();
    }
    COMMONAPI_EXPORT virtual void setFOTA_Start_InstallationAttribute(std::string _value) {
        const bool valueChanged = trySetFOTA_Start_InstallationAttribute(std::move(_value));
        if (valueChanged) {
            fireFOTA_Start_InstallationAttributeChanged(fOTA_Start_InstallationAttributeValue_);
        }
    }
    COMMONAPI_EXPORT virtual const std::string &getFOTA_Check_for_UpdatesAttribute() {
        return fOTA_Check_for_UpdatesAttributeValue_;
    }
    COMMONAPI_EXPORT virtual const std::string &getFOTA_Check_for_UpdatesAttribute(const std::shared_ptr<CommonAPI::ClientId> _client) {
        (void)_client;
        return getFOTA_Check_for_UpdatesAttribute();
    }
    COMMONAPI_EXPORT virtual void setFOTA_Check_for_UpdatesAttribute(std::string _value) {
        const bool valueChanged = trySetFOTA_Check_for_UpdatesAttribute(std::move(_value));
        if (valueChanged) {
            fireFOTA_Check_for_UpdatesAttributeChanged(fOTA_Check_for_UpdatesAttributeValue_);
        }
    }
    COMMONAPI_EXPORT virtual const std::string &getFOTA_Update_DismissedAttribute() {
        return fOTA_Update_DismissedAttributeValue_;
    }
    COMMONAPI_EXPORT virtual const std::string &getFOTA_Update_DismissedAttribute(const std::shared_ptr<CommonAPI::ClientId> _client) {
        (void)_client;
        return getFOTA_Update_DismissedAttribute();
    }
    COMMONAPI_EXPORT virtual void setFOTA_Update_DismissedAttribute(std::string _value) {
        const bool valueChanged = trySetFOTA_Update_DismissedAttribute(std::move(_value));
        if (valueChanged) {
            fireFOTA_Update_DismissedAttributeChanged(fOTA_Update_DismissedAttributeValue_);
        }
    }
    COMMONAPI_EXPORT virtual const std::string &getFOTA_Schedule_UpdateAttribute() {
        return fOTA_Schedule_UpdateAttributeValue_;
    }
    COMMONAPI_EXPORT virtual const std::string &getFOTA_Schedule_UpdateAttribute(const std::shared_ptr<CommonAPI::ClientId> _client) {
        (void)_client;
        return getFOTA_Schedule_UpdateAttribute();
    }
    COMMONAPI_EXPORT virtual void setFOTA_Schedule_UpdateAttribute(std::string _value) {
        const bool valueChanged = trySetFOTA_Schedule_UpdateAttribute(std::move(_value));
        if (valueChanged) {
            fireFOTA_Schedule_UpdateAttributeChanged(fOTA_Schedule_UpdateAttributeValue_);
        }
    }
    COMMONAPI_EXPORT virtual const std::string &getFOTA_WhatsNew_DetailsAttribute() {
        return fOTA_WhatsNew_DetailsAttributeValue_;
    }
    COMMONAPI_EXPORT virtual const std::string &getFOTA_WhatsNew_DetailsAttribute(const std::shared_ptr<CommonAPI::ClientId> _client) {
        (void)_client;
        return getFOTA_WhatsNew_DetailsAttribute();
    }
    COMMONAPI_EXPORT virtual void setFOTA_WhatsNew_DetailsAttribute(std::string _value) {
        const bool valueChanged = trySetFOTA_WhatsNew_DetailsAttribute(std::move(_value));
        if (valueChanged) {
            fireFOTA_WhatsNew_DetailsAttributeChanged(fOTA_WhatsNew_DetailsAttributeValue_);
        }
    }
    COMMONAPI_EXPORT virtual const uint32_t &getActive_phone_callAttribute() {
        return active_phone_callAttributeValue_;
    }
    COMMONAPI_EXPORT virtual const uint32_t &getActive_phone_callAttribute(const std::shared_ptr<CommonAPI::ClientId> _client) {
        (void)_client;
        return getActive_phone_callAttribute();
    }
    COMMONAPI_EXPORT virtual void setActive_phone_callAttribute(uint32_t _value) {
        const bool valueChanged = trySetActive_phone_callAttribute(std::move(_value));
        if (valueChanged) {
            fireActive_phone_callAttributeChanged(active_phone_callAttributeValue_);
        }
    }
    COMMONAPI_EXPORT virtual const uint32_t &getSIVIDriverLockoutStsAttribute() {
        return sIVIDriverLockoutStsAttributeValue_;
    }
    COMMONAPI_EXPORT virtual const uint32_t &getSIVIDriverLockoutStsAttribute(const std::shared_ptr<CommonAPI::ClientId> _client) {
        (void)_client;
        return getSIVIDriverLockoutStsAttribute();
    }
    COMMONAPI_EXPORT virtual void setSIVIDriverLockoutStsAttribute(uint32_t _value) {
        const bool valueChanged = trySetSIVIDriverLockoutStsAttribute(std::move(_value));
        if (valueChanged) {
            fireSIVIDriverLockoutStsAttributeChanged(sIVIDriverLockoutStsAttributeValue_);
        }
    }
    COMMONAPI_EXPORT virtual void Receive_UIN_TCU(const std::shared_ptr<CommonAPI::ClientId> _client, std::string _conf, Receive_UIN_TCUReply_t _reply) {
        (void)_client;
        (void)_conf;
        _reply();
    }
    COMMONAPI_EXPORT virtual const bool &getUIN_Trigger_from_HMIAttribute() {
        return uIN_Trigger_from_HMIAttributeValue_;
    }
    COMMONAPI_EXPORT virtual const bool &getUIN_Trigger_from_HMIAttribute(const std::shared_ptr<CommonAPI::ClientId> _client) {
        (void)_client;
        return getUIN_Trigger_from_HMIAttribute();
    }
    COMMONAPI_EXPORT virtual void setUIN_Trigger_from_HMIAttribute(bool _value) {
        const bool valueChanged = trySetUIN_Trigger_from_HMIAttribute(std::move(_value));
        if (valueChanged) {
            fireUIN_Trigger_from_HMIAttributeChanged(uIN_Trigger_from_HMIAttributeValue_);
        }
    }
    COMMONAPI_EXPORT virtual const uint32_t &getBTCallHMI_StatusAttribute() {
        return bTCallHMI_StatusAttributeValue_;
    }
    COMMONAPI_EXPORT virtual const uint32_t &getBTCallHMI_StatusAttribute(const std::shared_ptr<CommonAPI::ClientId> _client) {
        (void)_client;
        return getBTCallHMI_StatusAttribute();
    }
    COMMONAPI_EXPORT virtual void setBTCallHMI_StatusAttribute(uint32_t _value) {
        const bool valueChanged = trySetBTCallHMI_StatusAttribute(std::move(_value));
        if (valueChanged) {
            fireBTCallHMI_StatusAttributeChanged(bTCallHMI_StatusAttributeValue_);
        }
    }
    COMMONAPI_EXPORT virtual const uint32_t &getBTDeviceAttached_StatusAttribute() {
        return bTDeviceAttached_StatusAttributeValue_;
    }
    COMMONAPI_EXPORT virtual const uint32_t &getBTDeviceAttached_StatusAttribute(const std::shared_ptr<CommonAPI::ClientId> _client) {
        (void)_client;
        return getBTDeviceAttached_StatusAttribute();
    }
    COMMONAPI_EXPORT virtual void setBTDeviceAttached_StatusAttribute(uint32_t _value) {
        const bool valueChanged = trySetBTDeviceAttached_StatusAttribute(std::move(_value));
        if (valueChanged) {
            fireBTDeviceAttached_StatusAttributeChanged(bTDeviceAttached_StatusAttributeValue_);
        }
    }
    COMMONAPI_EXPORT virtual const uint32_t &getBTTransferTime_DurationAttribute() {
        return bTTransferTime_DurationAttributeValue_;
    }
    COMMONAPI_EXPORT virtual const uint32_t &getBTTransferTime_DurationAttribute(const std::shared_ptr<CommonAPI::ClientId> _client) {
        (void)_client;
        return getBTTransferTime_DurationAttribute();
    }
    COMMONAPI_EXPORT virtual void setBTTransferTime_DurationAttribute(uint32_t _value) {
        const bool valueChanged = trySetBTTransferTime_DurationAttribute(std::move(_value));
        if (valueChanged) {
            fireBTTransferTime_DurationAttributeChanged(bTTransferTime_DurationAttributeValue_);
        }
    }
    COMMONAPI_EXPORT virtual void ReceiveTCU_Version_Number(const std::shared_ptr<CommonAPI::ClientId> _client, std::string _conf, ReceiveTCU_Version_NumberReply_t _reply) {
        (void)_client;
        (void)_conf;
        _reply();
    }
    COMMONAPI_EXPORT virtual void ReceiveAOSP_RBUA_Trigger(const std::shared_ptr<CommonAPI::ClientId> _client, std::string _conf, ReceiveAOSP_RBUA_TriggerReply_t _reply) {
        (void)_client;
        (void)_conf;
        _reply();
    }
    COMMONAPI_EXPORT virtual const std::string &getAOSP_Flash_ResultAttribute() {
        return aOSP_Flash_ResultAttributeValue_;
    }
    COMMONAPI_EXPORT virtual const std::string &getAOSP_Flash_ResultAttribute(const std::shared_ptr<CommonAPI::ClientId> _client) {
        (void)_client;
        return getAOSP_Flash_ResultAttribute();
    }
    COMMONAPI_EXPORT virtual void setAOSP_Flash_ResultAttribute(std::string _value) {
        const bool valueChanged = trySetAOSP_Flash_ResultAttribute(std::move(_value));
        if (valueChanged) {
            fireAOSP_Flash_ResultAttributeChanged(aOSP_Flash_ResultAttributeValue_);
        }
    }
    COMMONAPI_EXPORT virtual void sIdsExportSecurityEvents(const std::shared_ptr<CommonAPI::ClientId> _client, sIdsExportSecurityEventsReply_t _reply) {
        (void)_client;
        std::string status = "";
        _reply(status);
    }
    COMMONAPI_EXPORT virtual void sIdsSetVehiclePhase(const std::shared_ptr<CommonAPI::ClientId> _client, std::string _vehiclePhase, sIdsSetVehiclePhaseReply_t _reply) {
        (void)_client;
        (void)_vehiclePhase;
        std::string status = "";
        _reply(status);
    }
    COMMONAPI_EXPORT virtual const uint32_t &getHMI_Status_SWUpdateAttribute() {
        return hMI_Status_SWUpdateAttributeValue_;
    }
    COMMONAPI_EXPORT virtual const uint32_t &getHMI_Status_SWUpdateAttribute(const std::shared_ptr<CommonAPI::ClientId> _client) {
        (void)_client;
        return getHMI_Status_SWUpdateAttribute();
    }
    COMMONAPI_EXPORT virtual void setHMI_Status_SWUpdateAttribute(uint32_t _value) {
        const bool valueChanged = trySetHMI_Status_SWUpdateAttribute(std::move(_value));
        if (valueChanged) {
            fireHMI_Status_SWUpdateAttributeChanged(hMI_Status_SWUpdateAttributeValue_);
        }
    }
    COMMONAPI_EXPORT virtual const uint32_t &getIncomingPhoneCallAttribute() {
        return incomingPhoneCallAttributeValue_;
    }
    COMMONAPI_EXPORT virtual const uint32_t &getIncomingPhoneCallAttribute(const std::shared_ptr<CommonAPI::ClientId> _client) {
        (void)_client;
        return getIncomingPhoneCallAttribute();
    }
    COMMONAPI_EXPORT virtual void setIncomingPhoneCallAttribute(uint32_t _value) {
        const bool valueChanged = trySetIncomingPhoneCallAttribute(std::move(_value));
        if (valueChanged) {
            fireIncomingPhoneCallAttributeChanged(incomingPhoneCallAttributeValue_);
        }
    }
    COMMONAPI_EXPORT virtual const uint32_t &getOutgoingPhoneCallAttribute() {
        return outgoingPhoneCallAttributeValue_;
    }
    COMMONAPI_EXPORT virtual const uint32_t &getOutgoingPhoneCallAttribute(const std::shared_ptr<CommonAPI::ClientId> _client) {
        (void)_client;
        return getOutgoingPhoneCallAttribute();
    }
    COMMONAPI_EXPORT virtual void setOutgoingPhoneCallAttribute(uint32_t _value) {
        const bool valueChanged = trySetOutgoingPhoneCallAttribute(std::move(_value));
        if (valueChanged) {
            fireOutgoingPhoneCallAttributeChanged(outgoingPhoneCallAttributeValue_);
        }
    }
    COMMONAPI_EXPORT virtual const uint32_t &getBtTransferAcceptanceAttribute() {
        return btTransferAcceptanceAttributeValue_;
    }
    COMMONAPI_EXPORT virtual const uint32_t &getBtTransferAcceptanceAttribute(const std::shared_ptr<CommonAPI::ClientId> _client) {
        (void)_client;
        return getBtTransferAcceptanceAttribute();
    }
    COMMONAPI_EXPORT virtual void setBtTransferAcceptanceAttribute(uint32_t _value) {
        const bool valueChanged = trySetBtTransferAcceptanceAttribute(std::move(_value));
        if (valueChanged) {
            fireBtTransferAcceptanceAttributeChanged(btTransferAcceptanceAttributeValue_);
        }
    }
    COMMONAPI_EXPORT virtual const std::string &getHMIFOTA_InfoAttribute() {
        return hMIFOTA_InfoAttributeValue_;
    }
    COMMONAPI_EXPORT virtual const std::string &getHMIFOTA_InfoAttribute(const std::shared_ptr<CommonAPI::ClientId> _client) {
        (void)_client;
        return getHMIFOTA_InfoAttribute();
    }
    COMMONAPI_EXPORT virtual void setHMIFOTA_InfoAttribute(std::string _value) {
        const bool valueChanged = trySetHMIFOTA_InfoAttribute(std::move(_value));
        if (valueChanged) {
            fireHMIFOTA_InfoAttributeChanged(hMIFOTA_InfoAttributeValue_);
        }
    }
    COMMONAPI_EXPORT virtual void FOTAHMI_Info_Result(const std::shared_ptr<CommonAPI::ClientId> _client, std::string _conf, FOTAHMI_Info_ResultReply_t _reply) {
        (void)_client;
        (void)_conf;
        _reply();
    }
    COMMONAPI_EXPORT virtual void USBUpdate_Details(const std::shared_ptr<CommonAPI::ClientId> _client, std::string _conf, USBUpdate_DetailsReply_t _reply) {
        (void)_client;
        (void)_conf;
        _reply();
    }


protected:
    /*
     * description: 
     * ecall status for IVI
     */
    COMMONAPI_EXPORT virtual bool trySetEcallStatusAttribute(uint8_t _value) {
        if (!validateEcallStatusAttributeRequestedValue(_value))
            return false;

        bool valueChanged;
        std::shared_ptr<VHAL_LIFECYCLEStubAdapter> stubAdapter = CommonAPI::Stub<VHAL_LIFECYCLEStubAdapter, VHAL_LIFECYCLEStubRemoteEvent>::stubAdapter_.lock();
        if(stubAdapter) {
            stubAdapter->lockEcallStatusAttribute(true);
            valueChanged = (ecallStatusAttributeValue_ != _value);
            ecallStatusAttributeValue_ = std::move(_value);
            stubAdapter->lockEcallStatusAttribute(false);
        } else {
            valueChanged = (ecallStatusAttributeValue_ != _value);
            ecallStatusAttributeValue_ = std::move(_value);
        }

       return valueChanged;
    }
    COMMONAPI_EXPORT virtual bool validateEcallStatusAttributeRequestedValue(const uint8_t &_value) {
        (void)_value;
        return true;
    }
    COMMONAPI_EXPORT virtual bool trySetPrivacy_ModeAttribute(uint32_t _value) {
        if (!validatePrivacy_ModeAttributeRequestedValue(_value))
            return false;

        bool valueChanged;
        std::shared_ptr<VHAL_LIFECYCLEStubAdapter> stubAdapter = CommonAPI::Stub<VHAL_LIFECYCLEStubAdapter, VHAL_LIFECYCLEStubRemoteEvent>::stubAdapter_.lock();
        if(stubAdapter) {
            stubAdapter->lockPrivacy_ModeAttribute(true);
            valueChanged = (privacy_ModeAttributeValue_ != _value);
            privacy_ModeAttributeValue_ = std::move(_value);
            stubAdapter->lockPrivacy_ModeAttribute(false);
        } else {
            valueChanged = (privacy_ModeAttributeValue_ != _value);
            privacy_ModeAttributeValue_ = std::move(_value);
        }

       return valueChanged;
    }
    COMMONAPI_EXPORT virtual bool validatePrivacy_ModeAttributeRequestedValue(const uint32_t &_value) {
        (void)_value;
        return true;
    }
    COMMONAPI_EXPORT virtual bool trySetFlash_ResultAttribute(uint32_t _value) {
        if (!validateFlash_ResultAttributeRequestedValue(_value))
            return false;

        bool valueChanged;
        std::shared_ptr<VHAL_LIFECYCLEStubAdapter> stubAdapter = CommonAPI::Stub<VHAL_LIFECYCLEStubAdapter, VHAL_LIFECYCLEStubRemoteEvent>::stubAdapter_.lock();
        if(stubAdapter) {
            stubAdapter->lockFlash_ResultAttribute(true);
            valueChanged = (flash_ResultAttributeValue_ != _value);
            flash_ResultAttributeValue_ = std::move(_value);
            stubAdapter->lockFlash_ResultAttribute(false);
        } else {
            valueChanged = (flash_ResultAttributeValue_ != _value);
            flash_ResultAttributeValue_ = std::move(_value);
        }

       return valueChanged;
    }
    COMMONAPI_EXPORT virtual bool validateFlash_ResultAttributeRequestedValue(const uint32_t &_value) {
        (void)_value;
        return true;
    }
    COMMONAPI_EXPORT virtual bool trySetXCallHmiControlAttribute(uint32_t _value) {
        if (!validateXCallHmiControlAttributeRequestedValue(_value))
            return false;

        bool valueChanged;
        std::shared_ptr<VHAL_LIFECYCLEStubAdapter> stubAdapter = CommonAPI::Stub<VHAL_LIFECYCLEStubAdapter, VHAL_LIFECYCLEStubRemoteEvent>::stubAdapter_.lock();
        if(stubAdapter) {
            stubAdapter->lockXCallHmiControlAttribute(true);
            valueChanged = (xCallHmiControlAttributeValue_ != _value);
            xCallHmiControlAttributeValue_ = std::move(_value);
            stubAdapter->lockXCallHmiControlAttribute(false);
        } else {
            valueChanged = (xCallHmiControlAttributeValue_ != _value);
            xCallHmiControlAttributeValue_ = std::move(_value);
        }

       return valueChanged;
    }
    COMMONAPI_EXPORT virtual bool validateXCallHmiControlAttributeRequestedValue(const uint32_t &_value) {
        (void)_value;
        return true;
    }
    COMMONAPI_EXPORT virtual bool trySetHMI_FOTA_Update_historyAttribute(std::string _value) {
        if (!validateHMI_FOTA_Update_historyAttributeRequestedValue(_value))
            return false;

        bool valueChanged;
        std::shared_ptr<VHAL_LIFECYCLEStubAdapter> stubAdapter = CommonAPI::Stub<VHAL_LIFECYCLEStubAdapter, VHAL_LIFECYCLEStubRemoteEvent>::stubAdapter_.lock();
        if(stubAdapter) {
            stubAdapter->lockHMI_FOTA_Update_historyAttribute(true);
            valueChanged = (hMI_FOTA_Update_historyAttributeValue_ != _value);
            hMI_FOTA_Update_historyAttributeValue_ = std::move(_value);
            stubAdapter->lockHMI_FOTA_Update_historyAttribute(false);
        } else {
            valueChanged = (hMI_FOTA_Update_historyAttributeValue_ != _value);
            hMI_FOTA_Update_historyAttributeValue_ = std::move(_value);
        }

       return valueChanged;
    }
    COMMONAPI_EXPORT virtual bool validateHMI_FOTA_Update_historyAttributeRequestedValue(const std::string &_value) {
        (void)_value;
        return true;
    }
    COMMONAPI_EXPORT virtual bool trySetHMI_FOTA_pending_updatesAttribute(std::string _value) {
        if (!validateHMI_FOTA_pending_updatesAttributeRequestedValue(_value))
            return false;

        bool valueChanged;
        std::shared_ptr<VHAL_LIFECYCLEStubAdapter> stubAdapter = CommonAPI::Stub<VHAL_LIFECYCLEStubAdapter, VHAL_LIFECYCLEStubRemoteEvent>::stubAdapter_.lock();
        if(stubAdapter) {
            stubAdapter->lockHMI_FOTA_pending_updatesAttribute(true);
            valueChanged = (hMI_FOTA_pending_updatesAttributeValue_ != _value);
            hMI_FOTA_pending_updatesAttributeValue_ = std::move(_value);
            stubAdapter->lockHMI_FOTA_pending_updatesAttribute(false);
        } else {
            valueChanged = (hMI_FOTA_pending_updatesAttributeValue_ != _value);
            hMI_FOTA_pending_updatesAttributeValue_ = std::move(_value);
        }

       return valueChanged;
    }
    COMMONAPI_EXPORT virtual bool validateHMI_FOTA_pending_updatesAttributeRequestedValue(const std::string &_value) {
        (void)_value;
        return true;
    }
    COMMONAPI_EXPORT virtual bool trySetFOTA_Installation_Finished_with_User_ConformationAttribute(std::string _value) {
        if (!validateFOTA_Installation_Finished_with_User_ConformationAttributeRequestedValue(_value))
            return false;

        bool valueChanged;
        std::shared_ptr<VHAL_LIFECYCLEStubAdapter> stubAdapter = CommonAPI::Stub<VHAL_LIFECYCLEStubAdapter, VHAL_LIFECYCLEStubRemoteEvent>::stubAdapter_.lock();
        if(stubAdapter) {
            stubAdapter->lockFOTA_Installation_Finished_with_User_ConformationAttribute(true);
            valueChanged = (fOTA_Installation_Finished_with_User_ConformationAttributeValue_ != _value);
            fOTA_Installation_Finished_with_User_ConformationAttributeValue_ = std::move(_value);
            stubAdapter->lockFOTA_Installation_Finished_with_User_ConformationAttribute(false);
        } else {
            valueChanged = (fOTA_Installation_Finished_with_User_ConformationAttributeValue_ != _value);
            fOTA_Installation_Finished_with_User_ConformationAttributeValue_ = std::move(_value);
        }

       return valueChanged;
    }
    COMMONAPI_EXPORT virtual bool validateFOTA_Installation_Finished_with_User_ConformationAttributeRequestedValue(const std::string &_value) {
        (void)_value;
        return true;
    }
    COMMONAPI_EXPORT virtual bool trySetFOTA_Start_InstallationAttribute(std::string _value) {
        if (!validateFOTA_Start_InstallationAttributeRequestedValue(_value))
            return false;

        bool valueChanged;
        std::shared_ptr<VHAL_LIFECYCLEStubAdapter> stubAdapter = CommonAPI::Stub<VHAL_LIFECYCLEStubAdapter, VHAL_LIFECYCLEStubRemoteEvent>::stubAdapter_.lock();
        if(stubAdapter) {
            stubAdapter->lockFOTA_Start_InstallationAttribute(true);
            valueChanged = (fOTA_Start_InstallationAttributeValue_ != _value);
            fOTA_Start_InstallationAttributeValue_ = std::move(_value);
            stubAdapter->lockFOTA_Start_InstallationAttribute(false);
        } else {
            valueChanged = (fOTA_Start_InstallationAttributeValue_ != _value);
            fOTA_Start_InstallationAttributeValue_ = std::move(_value);
        }

       return valueChanged;
    }
    COMMONAPI_EXPORT virtual bool validateFOTA_Start_InstallationAttributeRequestedValue(const std::string &_value) {
        (void)_value;
        return true;
    }
    COMMONAPI_EXPORT virtual bool trySetFOTA_Check_for_UpdatesAttribute(std::string _value) {
        if (!validateFOTA_Check_for_UpdatesAttributeRequestedValue(_value))
            return false;

        bool valueChanged;
        std::shared_ptr<VHAL_LIFECYCLEStubAdapter> stubAdapter = CommonAPI::Stub<VHAL_LIFECYCLEStubAdapter, VHAL_LIFECYCLEStubRemoteEvent>::stubAdapter_.lock();
        if(stubAdapter) {
            stubAdapter->lockFOTA_Check_for_UpdatesAttribute(true);
            valueChanged = (fOTA_Check_for_UpdatesAttributeValue_ != _value);
            fOTA_Check_for_UpdatesAttributeValue_ = std::move(_value);
            stubAdapter->lockFOTA_Check_for_UpdatesAttribute(false);
        } else {
            valueChanged = (fOTA_Check_for_UpdatesAttributeValue_ != _value);
            fOTA_Check_for_UpdatesAttributeValue_ = std::move(_value);
        }

       return valueChanged;
    }
    COMMONAPI_EXPORT virtual bool validateFOTA_Check_for_UpdatesAttributeRequestedValue(const std::string &_value) {
        (void)_value;
        return true;
    }
    COMMONAPI_EXPORT virtual bool trySetFOTA_Update_DismissedAttribute(std::string _value) {
        if (!validateFOTA_Update_DismissedAttributeRequestedValue(_value))
            return false;

        bool valueChanged;
        std::shared_ptr<VHAL_LIFECYCLEStubAdapter> stubAdapter = CommonAPI::Stub<VHAL_LIFECYCLEStubAdapter, VHAL_LIFECYCLEStubRemoteEvent>::stubAdapter_.lock();
        if(stubAdapter) {
            stubAdapter->lockFOTA_Update_DismissedAttribute(true);
            valueChanged = (fOTA_Update_DismissedAttributeValue_ != _value);
            fOTA_Update_DismissedAttributeValue_ = std::move(_value);
            stubAdapter->lockFOTA_Update_DismissedAttribute(false);
        } else {
            valueChanged = (fOTA_Update_DismissedAttributeValue_ != _value);
            fOTA_Update_DismissedAttributeValue_ = std::move(_value);
        }

       return valueChanged;
    }
    COMMONAPI_EXPORT virtual bool validateFOTA_Update_DismissedAttributeRequestedValue(const std::string &_value) {
        (void)_value;
        return true;
    }
    COMMONAPI_EXPORT virtual bool trySetFOTA_Schedule_UpdateAttribute(std::string _value) {
        if (!validateFOTA_Schedule_UpdateAttributeRequestedValue(_value))
            return false;

        bool valueChanged;
        std::shared_ptr<VHAL_LIFECYCLEStubAdapter> stubAdapter = CommonAPI::Stub<VHAL_LIFECYCLEStubAdapter, VHAL_LIFECYCLEStubRemoteEvent>::stubAdapter_.lock();
        if(stubAdapter) {
            stubAdapter->lockFOTA_Schedule_UpdateAttribute(true);
            valueChanged = (fOTA_Schedule_UpdateAttributeValue_ != _value);
            fOTA_Schedule_UpdateAttributeValue_ = std::move(_value);
            stubAdapter->lockFOTA_Schedule_UpdateAttribute(false);
        } else {
            valueChanged = (fOTA_Schedule_UpdateAttributeValue_ != _value);
            fOTA_Schedule_UpdateAttributeValue_ = std::move(_value);
        }

       return valueChanged;
    }
    COMMONAPI_EXPORT virtual bool validateFOTA_Schedule_UpdateAttributeRequestedValue(const std::string &_value) {
        (void)_value;
        return true;
    }
    COMMONAPI_EXPORT virtual bool trySetFOTA_WhatsNew_DetailsAttribute(std::string _value) {
        if (!validateFOTA_WhatsNew_DetailsAttributeRequestedValue(_value))
            return false;

        bool valueChanged;
        std::shared_ptr<VHAL_LIFECYCLEStubAdapter> stubAdapter = CommonAPI::Stub<VHAL_LIFECYCLEStubAdapter, VHAL_LIFECYCLEStubRemoteEvent>::stubAdapter_.lock();
        if(stubAdapter) {
            stubAdapter->lockFOTA_WhatsNew_DetailsAttribute(true);
            valueChanged = (fOTA_WhatsNew_DetailsAttributeValue_ != _value);
            fOTA_WhatsNew_DetailsAttributeValue_ = std::move(_value);
            stubAdapter->lockFOTA_WhatsNew_DetailsAttribute(false);
        } else {
            valueChanged = (fOTA_WhatsNew_DetailsAttributeValue_ != _value);
            fOTA_WhatsNew_DetailsAttributeValue_ = std::move(_value);
        }

       return valueChanged;
    }
    COMMONAPI_EXPORT virtual bool validateFOTA_WhatsNew_DetailsAttributeRequestedValue(const std::string &_value) {
        (void)_value;
        return true;
    }
    COMMONAPI_EXPORT virtual bool trySetActive_phone_callAttribute(uint32_t _value) {
        if (!validateActive_phone_callAttributeRequestedValue(_value))
            return false;

        bool valueChanged;
        std::shared_ptr<VHAL_LIFECYCLEStubAdapter> stubAdapter = CommonAPI::Stub<VHAL_LIFECYCLEStubAdapter, VHAL_LIFECYCLEStubRemoteEvent>::stubAdapter_.lock();
        if(stubAdapter) {
            stubAdapter->lockActive_phone_callAttribute(true);
            valueChanged = (active_phone_callAttributeValue_ != _value);
            active_phone_callAttributeValue_ = std::move(_value);
            stubAdapter->lockActive_phone_callAttribute(false);
        } else {
            valueChanged = (active_phone_callAttributeValue_ != _value);
            active_phone_callAttributeValue_ = std::move(_value);
        }

       return valueChanged;
    }
    COMMONAPI_EXPORT virtual bool validateActive_phone_callAttributeRequestedValue(const uint32_t &_value) {
        (void)_value;
        return true;
    }
    COMMONAPI_EXPORT virtual bool trySetSIVIDriverLockoutStsAttribute(uint32_t _value) {
        if (!validateSIVIDriverLockoutStsAttributeRequestedValue(_value))
            return false;

        bool valueChanged;
        std::shared_ptr<VHAL_LIFECYCLEStubAdapter> stubAdapter = CommonAPI::Stub<VHAL_LIFECYCLEStubAdapter, VHAL_LIFECYCLEStubRemoteEvent>::stubAdapter_.lock();
        if(stubAdapter) {
            stubAdapter->lockSIVIDriverLockoutStsAttribute(true);
            valueChanged = (sIVIDriverLockoutStsAttributeValue_ != _value);
            sIVIDriverLockoutStsAttributeValue_ = std::move(_value);
            stubAdapter->lockSIVIDriverLockoutStsAttribute(false);
        } else {
            valueChanged = (sIVIDriverLockoutStsAttributeValue_ != _value);
            sIVIDriverLockoutStsAttributeValue_ = std::move(_value);
        }

       return valueChanged;
    }
    COMMONAPI_EXPORT virtual bool validateSIVIDriverLockoutStsAttributeRequestedValue(const uint32_t &_value) {
        (void)_value;
        return true;
    }
    COMMONAPI_EXPORT virtual bool trySetUIN_Trigger_from_HMIAttribute(bool _value) {
        if (!validateUIN_Trigger_from_HMIAttributeRequestedValue(_value))
            return false;

        bool valueChanged;
        std::shared_ptr<VHAL_LIFECYCLEStubAdapter> stubAdapter = CommonAPI::Stub<VHAL_LIFECYCLEStubAdapter, VHAL_LIFECYCLEStubRemoteEvent>::stubAdapter_.lock();
        if(stubAdapter) {
            stubAdapter->lockUIN_Trigger_from_HMIAttribute(true);
            valueChanged = (uIN_Trigger_from_HMIAttributeValue_ != _value);
            uIN_Trigger_from_HMIAttributeValue_ = std::move(_value);
            stubAdapter->lockUIN_Trigger_from_HMIAttribute(false);
        } else {
            valueChanged = (uIN_Trigger_from_HMIAttributeValue_ != _value);
            uIN_Trigger_from_HMIAttributeValue_ = std::move(_value);
        }

       return valueChanged;
    }
    COMMONAPI_EXPORT virtual bool validateUIN_Trigger_from_HMIAttributeRequestedValue(const bool &_value) {
        (void)_value;
        return true;
    }
    COMMONAPI_EXPORT virtual bool trySetBTCallHMI_StatusAttribute(uint32_t _value) {
        if (!validateBTCallHMI_StatusAttributeRequestedValue(_value))
            return false;

        bool valueChanged;
        std::shared_ptr<VHAL_LIFECYCLEStubAdapter> stubAdapter = CommonAPI::Stub<VHAL_LIFECYCLEStubAdapter, VHAL_LIFECYCLEStubRemoteEvent>::stubAdapter_.lock();
        if(stubAdapter) {
            stubAdapter->lockBTCallHMI_StatusAttribute(true);
            valueChanged = (bTCallHMI_StatusAttributeValue_ != _value);
            bTCallHMI_StatusAttributeValue_ = std::move(_value);
            stubAdapter->lockBTCallHMI_StatusAttribute(false);
        } else {
            valueChanged = (bTCallHMI_StatusAttributeValue_ != _value);
            bTCallHMI_StatusAttributeValue_ = std::move(_value);
        }

       return valueChanged;
    }
    COMMONAPI_EXPORT virtual bool validateBTCallHMI_StatusAttributeRequestedValue(const uint32_t &_value) {
        (void)_value;
        return true;
    }
    COMMONAPI_EXPORT virtual bool trySetBTDeviceAttached_StatusAttribute(uint32_t _value) {
        if (!validateBTDeviceAttached_StatusAttributeRequestedValue(_value))
            return false;

        bool valueChanged;
        std::shared_ptr<VHAL_LIFECYCLEStubAdapter> stubAdapter = CommonAPI::Stub<VHAL_LIFECYCLEStubAdapter, VHAL_LIFECYCLEStubRemoteEvent>::stubAdapter_.lock();
        if(stubAdapter) {
            stubAdapter->lockBTDeviceAttached_StatusAttribute(true);
            valueChanged = (bTDeviceAttached_StatusAttributeValue_ != _value);
            bTDeviceAttached_StatusAttributeValue_ = std::move(_value);
            stubAdapter->lockBTDeviceAttached_StatusAttribute(false);
        } else {
            valueChanged = (bTDeviceAttached_StatusAttributeValue_ != _value);
            bTDeviceAttached_StatusAttributeValue_ = std::move(_value);
        }

       return valueChanged;
    }
    COMMONAPI_EXPORT virtual bool validateBTDeviceAttached_StatusAttributeRequestedValue(const uint32_t &_value) {
        (void)_value;
        return true;
    }
    COMMONAPI_EXPORT virtual bool trySetBTTransferTime_DurationAttribute(uint32_t _value) {
        if (!validateBTTransferTime_DurationAttributeRequestedValue(_value))
            return false;

        bool valueChanged;
        std::shared_ptr<VHAL_LIFECYCLEStubAdapter> stubAdapter = CommonAPI::Stub<VHAL_LIFECYCLEStubAdapter, VHAL_LIFECYCLEStubRemoteEvent>::stubAdapter_.lock();
        if(stubAdapter) {
            stubAdapter->lockBTTransferTime_DurationAttribute(true);
            valueChanged = (bTTransferTime_DurationAttributeValue_ != _value);
            bTTransferTime_DurationAttributeValue_ = std::move(_value);
            stubAdapter->lockBTTransferTime_DurationAttribute(false);
        } else {
            valueChanged = (bTTransferTime_DurationAttributeValue_ != _value);
            bTTransferTime_DurationAttributeValue_ = std::move(_value);
        }

       return valueChanged;
    }
    COMMONAPI_EXPORT virtual bool validateBTTransferTime_DurationAttributeRequestedValue(const uint32_t &_value) {
        (void)_value;
        return true;
    }
    COMMONAPI_EXPORT virtual bool trySetAOSP_Flash_ResultAttribute(std::string _value) {
        if (!validateAOSP_Flash_ResultAttributeRequestedValue(_value))
            return false;

        bool valueChanged;
        std::shared_ptr<VHAL_LIFECYCLEStubAdapter> stubAdapter = CommonAPI::Stub<VHAL_LIFECYCLEStubAdapter, VHAL_LIFECYCLEStubRemoteEvent>::stubAdapter_.lock();
        if(stubAdapter) {
            stubAdapter->lockAOSP_Flash_ResultAttribute(true);
            valueChanged = (aOSP_Flash_ResultAttributeValue_ != _value);
            aOSP_Flash_ResultAttributeValue_ = std::move(_value);
            stubAdapter->lockAOSP_Flash_ResultAttribute(false);
        } else {
            valueChanged = (aOSP_Flash_ResultAttributeValue_ != _value);
            aOSP_Flash_ResultAttributeValue_ = std::move(_value);
        }

       return valueChanged;
    }
    COMMONAPI_EXPORT virtual bool validateAOSP_Flash_ResultAttributeRequestedValue(const std::string &_value) {
        (void)_value;
        return true;
    }
    COMMONAPI_EXPORT virtual bool trySetHMI_Status_SWUpdateAttribute(uint32_t _value) {
        if (!validateHMI_Status_SWUpdateAttributeRequestedValue(_value))
            return false;

        bool valueChanged;
        std::shared_ptr<VHAL_LIFECYCLEStubAdapter> stubAdapter = CommonAPI::Stub<VHAL_LIFECYCLEStubAdapter, VHAL_LIFECYCLEStubRemoteEvent>::stubAdapter_.lock();
        if(stubAdapter) {
            stubAdapter->lockHMI_Status_SWUpdateAttribute(true);
            valueChanged = (hMI_Status_SWUpdateAttributeValue_ != _value);
            hMI_Status_SWUpdateAttributeValue_ = std::move(_value);
            stubAdapter->lockHMI_Status_SWUpdateAttribute(false);
        } else {
            valueChanged = (hMI_Status_SWUpdateAttributeValue_ != _value);
            hMI_Status_SWUpdateAttributeValue_ = std::move(_value);
        }

       return valueChanged;
    }
    COMMONAPI_EXPORT virtual bool validateHMI_Status_SWUpdateAttributeRequestedValue(const uint32_t &_value) {
        (void)_value;
        return true;
    }
    COMMONAPI_EXPORT virtual bool trySetIncomingPhoneCallAttribute(uint32_t _value) {
        if (!validateIncomingPhoneCallAttributeRequestedValue(_value))
            return false;

        bool valueChanged;
        std::shared_ptr<VHAL_LIFECYCLEStubAdapter> stubAdapter = CommonAPI::Stub<VHAL_LIFECYCLEStubAdapter, VHAL_LIFECYCLEStubRemoteEvent>::stubAdapter_.lock();
        if(stubAdapter) {
            stubAdapter->lockIncomingPhoneCallAttribute(true);
            valueChanged = (incomingPhoneCallAttributeValue_ != _value);
            incomingPhoneCallAttributeValue_ = std::move(_value);
            stubAdapter->lockIncomingPhoneCallAttribute(false);
        } else {
            valueChanged = (incomingPhoneCallAttributeValue_ != _value);
            incomingPhoneCallAttributeValue_ = std::move(_value);
        }

       return valueChanged;
    }
    COMMONAPI_EXPORT virtual bool validateIncomingPhoneCallAttributeRequestedValue(const uint32_t &_value) {
        (void)_value;
        return true;
    }
    COMMONAPI_EXPORT virtual bool trySetOutgoingPhoneCallAttribute(uint32_t _value) {
        if (!validateOutgoingPhoneCallAttributeRequestedValue(_value))
            return false;

        bool valueChanged;
        std::shared_ptr<VHAL_LIFECYCLEStubAdapter> stubAdapter = CommonAPI::Stub<VHAL_LIFECYCLEStubAdapter, VHAL_LIFECYCLEStubRemoteEvent>::stubAdapter_.lock();
        if(stubAdapter) {
            stubAdapter->lockOutgoingPhoneCallAttribute(true);
            valueChanged = (outgoingPhoneCallAttributeValue_ != _value);
            outgoingPhoneCallAttributeValue_ = std::move(_value);
            stubAdapter->lockOutgoingPhoneCallAttribute(false);
        } else {
            valueChanged = (outgoingPhoneCallAttributeValue_ != _value);
            outgoingPhoneCallAttributeValue_ = std::move(_value);
        }

       return valueChanged;
    }
    COMMONAPI_EXPORT virtual bool validateOutgoingPhoneCallAttributeRequestedValue(const uint32_t &_value) {
        (void)_value;
        return true;
    }
    COMMONAPI_EXPORT virtual bool trySetBtTransferAcceptanceAttribute(uint32_t _value) {
        if (!validateBtTransferAcceptanceAttributeRequestedValue(_value))
            return false;

        bool valueChanged;
        std::shared_ptr<VHAL_LIFECYCLEStubAdapter> stubAdapter = CommonAPI::Stub<VHAL_LIFECYCLEStubAdapter, VHAL_LIFECYCLEStubRemoteEvent>::stubAdapter_.lock();
        if(stubAdapter) {
            stubAdapter->lockBtTransferAcceptanceAttribute(true);
            valueChanged = (btTransferAcceptanceAttributeValue_ != _value);
            btTransferAcceptanceAttributeValue_ = std::move(_value);
            stubAdapter->lockBtTransferAcceptanceAttribute(false);
        } else {
            valueChanged = (btTransferAcceptanceAttributeValue_ != _value);
            btTransferAcceptanceAttributeValue_ = std::move(_value);
        }

       return valueChanged;
    }
    COMMONAPI_EXPORT virtual bool validateBtTransferAcceptanceAttributeRequestedValue(const uint32_t &_value) {
        (void)_value;
        return true;
    }
    COMMONAPI_EXPORT virtual bool trySetHMIFOTA_InfoAttribute(std::string _value) {
        if (!validateHMIFOTA_InfoAttributeRequestedValue(_value))
            return false;

        bool valueChanged;
        std::shared_ptr<VHAL_LIFECYCLEStubAdapter> stubAdapter = CommonAPI::Stub<VHAL_LIFECYCLEStubAdapter, VHAL_LIFECYCLEStubRemoteEvent>::stubAdapter_.lock();
        if(stubAdapter) {
            stubAdapter->lockHMIFOTA_InfoAttribute(true);
            valueChanged = (hMIFOTA_InfoAttributeValue_ != _value);
            hMIFOTA_InfoAttributeValue_ = std::move(_value);
            stubAdapter->lockHMIFOTA_InfoAttribute(false);
        } else {
            valueChanged = (hMIFOTA_InfoAttributeValue_ != _value);
            hMIFOTA_InfoAttributeValue_ = std::move(_value);
        }

       return valueChanged;
    }
    COMMONAPI_EXPORT virtual bool validateHMIFOTA_InfoAttributeRequestedValue(const std::string &_value) {
        (void)_value;
        return true;
    }
    class COMMONAPI_EXPORT_CLASS_EXPLICIT RemoteEventHandler: public virtual VHAL_LIFECYCLEStubRemoteEvent {
    public:
        COMMONAPI_EXPORT RemoteEventHandler(VHAL_LIFECYCLEStubDefault *_defaultStub)
            : 
              defaultStub_(_defaultStub) {
        }

        /*
         * description: 
         * ecall status for IVI
         */

    private:
        VHAL_LIFECYCLEStubDefault *defaultStub_;
    };
protected:
    VHAL_LIFECYCLEStubDefault::RemoteEventHandler remoteEventHandler_;

private:

    /*
     * description: 
     * ecall status for IVI
     */
    uint8_t ecallStatusAttributeValue_ {};
    uint32_t privacy_ModeAttributeValue_ {};
    uint32_t flash_ResultAttributeValue_ {};
    uint32_t xCallHmiControlAttributeValue_ {};
    std::string hMI_FOTA_Update_historyAttributeValue_ {};
    std::string hMI_FOTA_pending_updatesAttributeValue_ {};
    std::string fOTA_Installation_Finished_with_User_ConformationAttributeValue_ {};
    std::string fOTA_Start_InstallationAttributeValue_ {};
    std::string fOTA_Check_for_UpdatesAttributeValue_ {};
    std::string fOTA_Update_DismissedAttributeValue_ {};
    std::string fOTA_Schedule_UpdateAttributeValue_ {};
    std::string fOTA_WhatsNew_DetailsAttributeValue_ {};
    uint32_t active_phone_callAttributeValue_ {};
    uint32_t sIVIDriverLockoutStsAttributeValue_ {};
    bool uIN_Trigger_from_HMIAttributeValue_ {};
    uint32_t bTCallHMI_StatusAttributeValue_ {};
    uint32_t bTDeviceAttached_StatusAttributeValue_ {};
    uint32_t bTTransferTime_DurationAttributeValue_ {};
    std::string aOSP_Flash_ResultAttributeValue_ {};
    uint32_t hMI_Status_SWUpdateAttributeValue_ {};
    uint32_t incomingPhoneCallAttributeValue_ {};
    uint32_t outgoingPhoneCallAttributeValue_ {};
    uint32_t btTransferAcceptanceAttributeValue_ {};
    std::string hMIFOTA_InfoAttributeValue_ {};

    CommonAPI::Version interfaceVersion_;
};

} // namespace VHAL
} // namespace v0


// Compatibility
namespace v0_1 = v0;

#endif // V0_VHAL_VHAL__LIFECYCLE_STUB_DEFAULT
