/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.0.v202012010944.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
#ifndef V0_VHAL_VHAL__LIFECYCLE_SOMEIP_STUB_ADAPTER_HPP_
#define V0_VHAL_VHAL__LIFECYCLE_SOMEIP_STUB_ADAPTER_HPP_

#include <v0/VHAL/VHAL_LIFECYCLEStub.hpp>
#include <VHAL/sIdsFramework_TypesSomeIPDeployment.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/SomeIP/AddressTranslator.hpp>
#include <CommonAPI/SomeIP/StubAdapterHelper.hpp>
#include <CommonAPI/SomeIP/StubAdapter.hpp>
#include <CommonAPI/SomeIP/Factory.hpp>
#include <CommonAPI/SomeIP/Types.hpp>
#include <CommonAPI/SomeIP/Constants.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v0 {
namespace VHAL {

template <typename _Stub = ::v0::VHAL::VHAL_LIFECYCLEStub, typename... _Stubs>
class VHAL_LIFECYCLESomeIPStubAdapterInternal
    : public virtual VHAL_LIFECYCLEStubAdapter,
      public CommonAPI::SomeIP::StubAdapterHelper< _Stub, _Stubs...>,
      public std::enable_shared_from_this< VHAL_LIFECYCLESomeIPStubAdapterInternal<_Stub, _Stubs...>>
{
public:
    typedef CommonAPI::SomeIP::StubAdapterHelper< _Stub, _Stubs...> VHAL_LIFECYCLESomeIPStubAdapterHelper;

    ~VHAL_LIFECYCLESomeIPStubAdapterInternal() {
        deactivateManagedInstances();
        VHAL_LIFECYCLESomeIPStubAdapterHelper::deinit();
    }

    /*
     * description: 
     * ecall status for IVI
     */
    void fireEcallStatusAttributeChanged(const uint8_t &_value);
    
    void firePrivacy_ModeAttributeChanged(const uint32_t &_value);
    
    void fireFlash_ResultAttributeChanged(const uint32_t &_value);
    
    void fireXCallHmiControlAttributeChanged(const uint32_t &_value);
    
    void fireHMI_FOTA_Update_historyAttributeChanged(const std::string &_value);
    
    void fireHMI_FOTA_pending_updatesAttributeChanged(const std::string &_value);
    
    void fireFOTA_Installation_Finished_with_User_ConformationAttributeChanged(const std::string &_value);
    
    void fireFOTA_Start_InstallationAttributeChanged(const std::string &_value);
    
    void fireFOTA_Check_for_UpdatesAttributeChanged(const std::string &_value);
    
    void fireFOTA_Update_DismissedAttributeChanged(const std::string &_value);
    
    void fireFOTA_Schedule_UpdateAttributeChanged(const std::string &_value);
    
    void fireFOTA_WhatsNew_DetailsAttributeChanged(const std::string &_value);
    
    void fireActive_phone_callAttributeChanged(const uint32_t &_value);
    
    void fireSIVIDriverLockoutStsAttributeChanged(const uint32_t &_value);
    
    void fireUIN_Trigger_from_HMIAttributeChanged(const bool &_value);
    
    void fireBTCallHMI_StatusAttributeChanged(const uint32_t &_value);
    
    void fireBTDeviceAttached_StatusAttributeChanged(const uint32_t &_value);
    
    void fireBTTransferTime_DurationAttributeChanged(const uint32_t &_value);
    
    void fireAOSP_Flash_ResultAttributeChanged(const std::string &_value);
    
    void fireHMI_Status_SWUpdateAttributeChanged(const uint32_t &_value);
    
    void fireIncomingPhoneCallAttributeChanged(const uint32_t &_value);
    
    void fireOutgoingPhoneCallAttributeChanged(const uint32_t &_value);
    
    void fireBtTransferAcceptanceAttributeChanged(const uint32_t &_value);
    
    void fireHMIFOTA_InfoAttributeChanged(const std::string &_value);
    
    void fireSend_UserXCallInput_TCUEvent(const uint32_t &_conf);

    void fireSend_Language_selectionEvent(const uint32_t &_conf);

    void deactivateManagedInstances() {}
    
    CommonAPI::SomeIP::GetAttributeStubDispatcher<
        ::v0::VHAL::VHAL_LIFECYCLEStub,
        CommonAPI::Version
    > getVHAL_LIFECYCLEInterfaceVersionStubDispatcher;

    /*
     * description: 
     * ecall status for IVI
     */
    CommonAPI::SomeIP::GetAttributeStubDispatcher<
        ::v0::VHAL::VHAL_LIFECYCLEStub,
        uint8_t,
        CommonAPI::SomeIP::IntegerDeployment<uint8_t>
    > getEcallStatusAttributeStubDispatcher;
    
    CommonAPI::SomeIP::GetAttributeStubDispatcher<
        ::v0::VHAL::VHAL_LIFECYCLEStub,
        uint32_t,
        CommonAPI::SomeIP::IntegerDeployment<uint32_t>
    > getPrivacy_ModeAttributeStubDispatcher;
    
    CommonAPI::SomeIP::GetAttributeStubDispatcher<
        ::v0::VHAL::VHAL_LIFECYCLEStub,
        uint32_t,
        CommonAPI::SomeIP::IntegerDeployment<uint32_t>
    > getFlash_ResultAttributeStubDispatcher;
    
    CommonAPI::SomeIP::GetAttributeStubDispatcher<
        ::v0::VHAL::VHAL_LIFECYCLEStub,
        uint32_t,
        CommonAPI::SomeIP::IntegerDeployment<uint32_t>
    > getXCallHmiControlAttributeStubDispatcher;
    
    CommonAPI::SomeIP::GetAttributeStubDispatcher<
        ::v0::VHAL::VHAL_LIFECYCLEStub,
        std::string,
        CommonAPI::SomeIP::StringDeployment
    > getHMI_FOTA_Update_historyAttributeStubDispatcher;
    
    CommonAPI::SomeIP::GetAttributeStubDispatcher<
        ::v0::VHAL::VHAL_LIFECYCLEStub,
        std::string,
        CommonAPI::SomeIP::StringDeployment
    > getHMI_FOTA_pending_updatesAttributeStubDispatcher;
    
    CommonAPI::SomeIP::GetAttributeStubDispatcher<
        ::v0::VHAL::VHAL_LIFECYCLEStub,
        std::string,
        CommonAPI::SomeIP::StringDeployment
    > getFOTA_Installation_Finished_with_User_ConformationAttributeStubDispatcher;
    
    CommonAPI::SomeIP::GetAttributeStubDispatcher<
        ::v0::VHAL::VHAL_LIFECYCLEStub,
        std::string,
        CommonAPI::SomeIP::StringDeployment
    > getFOTA_Start_InstallationAttributeStubDispatcher;
    
    CommonAPI::SomeIP::GetAttributeStubDispatcher<
        ::v0::VHAL::VHAL_LIFECYCLEStub,
        std::string,
        CommonAPI::SomeIP::StringDeployment
    > getFOTA_Check_for_UpdatesAttributeStubDispatcher;
    
    CommonAPI::SomeIP::GetAttributeStubDispatcher<
        ::v0::VHAL::VHAL_LIFECYCLEStub,
        std::string,
        CommonAPI::SomeIP::StringDeployment
    > getFOTA_Update_DismissedAttributeStubDispatcher;
    
    CommonAPI::SomeIP::GetAttributeStubDispatcher<
        ::v0::VHAL::VHAL_LIFECYCLEStub,
        std::string,
        CommonAPI::SomeIP::StringDeployment
    > getFOTA_Schedule_UpdateAttributeStubDispatcher;
    
    CommonAPI::SomeIP::GetAttributeStubDispatcher<
        ::v0::VHAL::VHAL_LIFECYCLEStub,
        std::string,
        CommonAPI::SomeIP::StringDeployment
    > getFOTA_WhatsNew_DetailsAttributeStubDispatcher;
    
    CommonAPI::SomeIP::GetAttributeStubDispatcher<
        ::v0::VHAL::VHAL_LIFECYCLEStub,
        uint32_t,
        CommonAPI::SomeIP::IntegerDeployment<uint32_t>
    > getActive_phone_callAttributeStubDispatcher;
    
    CommonAPI::SomeIP::GetAttributeStubDispatcher<
        ::v0::VHAL::VHAL_LIFECYCLEStub,
        uint32_t,
        CommonAPI::SomeIP::IntegerDeployment<uint32_t>
    > getSIVIDriverLockoutStsAttributeStubDispatcher;
    
    CommonAPI::SomeIP::GetAttributeStubDispatcher<
        ::v0::VHAL::VHAL_LIFECYCLEStub,
        bool
    > getUIN_Trigger_from_HMIAttributeStubDispatcher;
    
    CommonAPI::SomeIP::GetAttributeStubDispatcher<
        ::v0::VHAL::VHAL_LIFECYCLEStub,
        uint32_t,
        CommonAPI::SomeIP::IntegerDeployment<uint32_t>
    > getBTCallHMI_StatusAttributeStubDispatcher;
    
    CommonAPI::SomeIP::GetAttributeStubDispatcher<
        ::v0::VHAL::VHAL_LIFECYCLEStub,
        uint32_t,
        CommonAPI::SomeIP::IntegerDeployment<uint32_t>
    > getBTDeviceAttached_StatusAttributeStubDispatcher;
    
    CommonAPI::SomeIP::GetAttributeStubDispatcher<
        ::v0::VHAL::VHAL_LIFECYCLEStub,
        uint32_t,
        CommonAPI::SomeIP::IntegerDeployment<uint32_t>
    > getBTTransferTime_DurationAttributeStubDispatcher;
    
    CommonAPI::SomeIP::GetAttributeStubDispatcher<
        ::v0::VHAL::VHAL_LIFECYCLEStub,
        std::string,
        CommonAPI::SomeIP::StringDeployment
    > getAOSP_Flash_ResultAttributeStubDispatcher;
    
    CommonAPI::SomeIP::GetAttributeStubDispatcher<
        ::v0::VHAL::VHAL_LIFECYCLEStub,
        uint32_t,
        CommonAPI::SomeIP::IntegerDeployment<uint32_t>
    > getHMI_Status_SWUpdateAttributeStubDispatcher;
    
    CommonAPI::SomeIP::GetAttributeStubDispatcher<
        ::v0::VHAL::VHAL_LIFECYCLEStub,
        uint32_t,
        CommonAPI::SomeIP::IntegerDeployment<uint32_t>
    > getIncomingPhoneCallAttributeStubDispatcher;
    
    CommonAPI::SomeIP::GetAttributeStubDispatcher<
        ::v0::VHAL::VHAL_LIFECYCLEStub,
        uint32_t,
        CommonAPI::SomeIP::IntegerDeployment<uint32_t>
    > getOutgoingPhoneCallAttributeStubDispatcher;
    
    CommonAPI::SomeIP::GetAttributeStubDispatcher<
        ::v0::VHAL::VHAL_LIFECYCLEStub,
        uint32_t,
        CommonAPI::SomeIP::IntegerDeployment<uint32_t>
    > getBtTransferAcceptanceAttributeStubDispatcher;
    
    CommonAPI::SomeIP::GetAttributeStubDispatcher<
        ::v0::VHAL::VHAL_LIFECYCLEStub,
        std::string,
        CommonAPI::SomeIP::StringDeployment
    > getHMIFOTA_InfoAttributeStubDispatcher;
    
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v0::VHAL::VHAL_LIFECYCLEStub,
        std::tuple< uint8_t>,
        std::tuple< >,
        std::tuple< CommonAPI::SomeIP::IntegerDeployment<uint8_t>>,
        std::tuple< >
    > ecallStatus_ackStubDispatcher;
    
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v0::VHAL::VHAL_LIFECYCLEStub,
        std::tuple< uint32_t>,
        std::tuple< >,
        std::tuple< CommonAPI::SomeIP::IntegerDeployment<uint32_t>>,
        std::tuple< >
    > receive_MsdTransmissionTime_TCUStubDispatcher;
    
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v0::VHAL::VHAL_LIFECYCLEStub,
        std::tuple< uint32_t>,
        std::tuple< >,
        std::tuple< CommonAPI::SomeIP::IntegerDeployment<uint32_t>>,
        std::tuple< >
    > receive_EcallState_TCUStubDispatcher;
    
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v0::VHAL::VHAL_LIFECYCLEStub,
        std::tuple< uint32_t>,
        std::tuple< >,
        std::tuple< CommonAPI::SomeIP::IntegerDeployment<uint32_t>>,
        std::tuple< >
    > receive_AcallState_TCUStubDispatcher;
    
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v0::VHAL::VHAL_LIFECYCLEStub,
        std::tuple< uint32_t>,
        std::tuple< >,
        std::tuple< CommonAPI::SomeIP::IntegerDeployment<uint32_t>>,
        std::tuple< >
    > receive_UserXcallFeedback_TCUStubDispatcher;
    
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v0::VHAL::VHAL_LIFECYCLEStub,
        std::tuple< uint32_t>,
        std::tuple< >,
        std::tuple< CommonAPI::SomeIP::IntegerDeployment<uint32_t>>,
        std::tuple< >
    > receive_EcallDurationTimer_TCUStubDispatcher;
    
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v0::VHAL::VHAL_LIFECYCLEStub,
        std::tuple< uint32_t>,
        std::tuple< >,
        std::tuple< CommonAPI::SomeIP::IntegerDeployment<uint32_t>>,
        std::tuple< >
    > receive_EcallTpsState_TCUStubDispatcher;
    
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v0::VHAL::VHAL_LIFECYCLEStub,
        std::tuple< uint32_t>,
        std::tuple< >,
        std::tuple< CommonAPI::SomeIP::IntegerDeployment<uint32_t>>,
        std::tuple< >
    > receive_XcallStatus_TCUStubDispatcher;
    
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v0::VHAL::VHAL_LIFECYCLEStub,
        std::tuple< uint32_t>,
        std::tuple< >,
        std::tuple< CommonAPI::SomeIP::IntegerDeployment<uint32_t>>,
        std::tuple< >
    > receive_EcallWcbTimer_TCUStubDispatcher;
    
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v0::VHAL::VHAL_LIFECYCLEStub,
        std::tuple< uint32_t>,
        std::tuple< >,
        std::tuple< CommonAPI::SomeIP::IntegerDeployment<uint32_t>>,
        std::tuple< >
    > receive_DmdMuteSualStubDispatcher;
    
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v0::VHAL::VHAL_LIFECYCLEStub,
        std::tuple< uint32_t>,
        std::tuple< >,
        std::tuple< CommonAPI::SomeIP::IntegerDeployment<uint32_t>>,
        std::tuple< >
    > receive_AppUrgMdsStubDispatcher;
    
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v0::VHAL::VHAL_LIFECYCLEStub,
        std::tuple< uint32_t>,
        std::tuple< >,
        std::tuple< CommonAPI::SomeIP::IntegerDeployment<uint32_t>>,
        std::tuple< >
    > receive_SignalVoyantDysfunctionStubDispatcher;
    
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v0::VHAL::VHAL_LIFECYCLEStub,
        std::tuple< uint32_t>,
        std::tuple< >,
        std::tuple< CommonAPI::SomeIP::IntegerDeployment<uint32_t>>,
        std::tuple< >
    > receive_SignalVoyantEtatStubDispatcher;
    
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v0::VHAL::VHAL_LIFECYCLEStub,
        std::tuple< uint32_t>,
        std::tuple< >,
        std::tuple< CommonAPI::SomeIP::IntegerDeployment<uint32_t>>,
        std::tuple< >
    > receive_BoostrapRetryCountStubDispatcher;
    
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v0::VHAL::VHAL_LIFECYCLEStub,
        std::tuple< uint32_t>,
        std::tuple< >,
        std::tuple< CommonAPI::SomeIP::IntegerDeployment<uint32_t>>,
        std::tuple< >
    > receive_CloudConnectionStatus_CConnState_connectionGateIDStubDispatcher;
    
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v0::VHAL::VHAL_LIFECYCLEStub,
        std::tuple< uint32_t>,
        std::tuple< >,
        std::tuple< CommonAPI::SomeIP::IntegerDeployment<uint32_t>>,
        std::tuple< >
    > receive_CloudConnectionStatus_CConnState_isConnectedStubDispatcher;
    
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v0::VHAL::VHAL_LIFECYCLEStub,
        std::tuple< uint32_t>,
        std::tuple< >,
        std::tuple< CommonAPI::SomeIP::IntegerDeployment<uint32_t>>,
        std::tuple< >
    > receive_CloudConnectionStatus_CConnState_connTypeStubDispatcher;
    
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v0::VHAL::VHAL_LIFECYCLEStub,
        std::tuple< uint32_t>,
        std::tuple< >,
        std::tuple< CommonAPI::SomeIP::IntegerDeployment<uint32_t>>,
        std::tuple< >
    > receive_CloudConnectionStatus_CConnState_isRoamingStubDispatcher;
    
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v0::VHAL::VHAL_LIFECYCLEStub,
        std::tuple< uint32_t>,
        std::tuple< >,
        std::tuple< CommonAPI::SomeIP::IntegerDeployment<uint32_t>>,
        std::tuple< >
    > receive_CloudConnectionStatus_CConnState_sigStrengthStubDispatcher;
    
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v0::VHAL::VHAL_LIFECYCLEStub,
        std::tuple< uint32_t>,
        std::tuple< >,
        std::tuple< CommonAPI::SomeIP::IntegerDeployment<uint32_t>>,
        std::tuple< >
    > receive_CloudConnectionStatus_CConnState_ipVersionStubDispatcher;
    
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v0::VHAL::VHAL_LIFECYCLEStub,
        std::tuple< uint32_t>,
        std::tuple< >,
        std::tuple< CommonAPI::SomeIP::IntegerDeployment<uint32_t>>,
        std::tuple< >
    > receive_CellularNetworkTypeStubDispatcher;
    
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v0::VHAL::VHAL_LIFECYCLEStub,
        std::tuple< uint32_t>,
        std::tuple< >,
        std::tuple< CommonAPI::SomeIP::IntegerDeployment<uint32_t>>,
        std::tuple< >
    > receive_NetConnectionStubDispatcher;
    
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v0::VHAL::VHAL_LIFECYCLEStub,
        std::tuple< uint32_t>,
        std::tuple< >,
        std::tuple< CommonAPI::SomeIP::IntegerDeployment<uint32_t>>,
        std::tuple< >
    > receive_CellsignalStubDispatcher;
    
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v0::VHAL::VHAL_LIFECYCLEStub,
        std::tuple< uint32_t>,
        std::tuple< >,
        std::tuple< CommonAPI::SomeIP::IntegerDeployment<uint32_t>>,
        std::tuple< >
    > receive_CloudConnectionStatus_CConnCtrl_reqDisableStubDispatcher;
    
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v0::VHAL::VHAL_LIFECYCLEStub,
        std::tuple< >,
        std::tuple< uint32_t>,
        std::tuple< >,
        std::tuple< CommonAPI::SomeIP::IntegerDeployment<uint32_t>>
    > getLanguageSelectionOnBootupStubDispatcher;
    
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v0::VHAL::VHAL_LIFECYCLEStub,
        std::tuple< uint32_t>,
        std::tuple< >,
        std::tuple< CommonAPI::SomeIP::IntegerDeployment<uint32_t>>,
        std::tuple< >
    > receive_SLIRoadTypeStubDispatcher;
    
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v0::VHAL::VHAL_LIFECYCLEStub,
        std::tuple< uint32_t>,
        std::tuple< >,
        std::tuple< CommonAPI::SomeIP::IntegerDeployment<uint32_t>>,
        std::tuple< >
    > receive_SLISpeedLimitStubDispatcher;
    
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v0::VHAL::VHAL_LIFECYCLEStub,
        std::tuple< uint32_t>,
        std::tuple< >,
        std::tuple< CommonAPI::SomeIP::IntegerDeployment<uint32_t>>,
        std::tuple< >
    > receive_SLICountryCodeStubDispatcher;
    
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v0::VHAL::VHAL_LIFECYCLEStub,
        std::tuple< uint32_t>,
        std::tuple< >,
        std::tuple< CommonAPI::SomeIP::IntegerDeployment<uint32_t>>,
        std::tuple< >
    > flash_UnitidStubDispatcher;
    
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v0::VHAL::VHAL_LIFECYCLEStub,
        std::tuple< std::string>,
        std::tuple< >,
        std::tuple< CommonAPI::SomeIP::StringDeployment>,
        std::tuple< >
    > package_PathStubDispatcher;
    
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v0::VHAL::VHAL_LIFECYCLEStub,
        std::tuple< std::string, std::string>,
        std::tuple< std::string>,
        std::tuple< CommonAPI::SomeIP::StringDeployment, CommonAPI::SomeIP::StringDeployment>,
        std::tuple< CommonAPI::SomeIP::StringDeployment>
    > sIdsRegisterAppStubDispatcher;
    
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v0::VHAL::VHAL_LIFECYCLEStub,
        std::tuple< >,
        std::tuple< std::string>,
        std::tuple< >,
        std::tuple< CommonAPI::SomeIP::StringDeployment>
    > sIdsUnRegisterAppStubDispatcher;
    
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v0::VHAL::VHAL_LIFECYCLEStub,
        std::tuple< ::VHAL::sIdsFramework_Types::sStSecurityEvent, ::VHAL::sIdsFramework_Types::sStLogIssuer, ::VHAL::sIdsFramework_Types::sStEventSrc, ::VHAL::sIdsFramework_Types::sStAction>,
        std::tuple< std::string>,
        std::tuple< ::VHAL::sIdsFramework_Types_::sStSecurityEventDeployment_t, ::VHAL::sIdsFramework_Types_::sStLogIssuerDeployment_t, ::VHAL::sIdsFramework_Types_::sStEventSrcDeployment_t, ::VHAL::sIdsFramework_Types_::sStActionDeployment_t>,
        std::tuple< CommonAPI::SomeIP::StringDeployment>
    > sIdsWriteSevStubDispatcher;
    
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v0::VHAL::VHAL_LIFECYCLEStub,
        std::tuple< std::string>,
        std::tuple< >,
        std::tuple< CommonAPI::SomeIP::StringDeployment>,
        std::tuple< >
    > receiveFOTA_Check_for_Updates_ResultStubDispatcher;
    
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v0::VHAL::VHAL_LIFECYCLEStub,
        std::tuple< std::string>,
        std::tuple< >,
        std::tuple< CommonAPI::SomeIP::StringDeployment>,
        std::tuple< >
    > receiveFOTA_Update_AvailableStubDispatcher;
    
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v0::VHAL::VHAL_LIFECYCLEStub,
        std::tuple< std::string>,
        std::tuple< >,
        std::tuple< CommonAPI::SomeIP::StringDeployment>,
        std::tuple< >
    > receiveFOTA_Conditions_not_MetStubDispatcher;
    
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v0::VHAL::VHAL_LIFECYCLEStub,
        std::tuple< std::string>,
        std::tuple< >,
        std::tuple< CommonAPI::SomeIP::StringDeployment>,
        std::tuple< >
    > receiveFOTA_Installation_StatusStubDispatcher;
    
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v0::VHAL::VHAL_LIFECYCLEStub,
        std::tuple< std::string>,
        std::tuple< >,
        std::tuple< CommonAPI::SomeIP::StringDeployment>,
        std::tuple< >
    > receiveFOTA_Update_FinishedStubDispatcher;
    
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v0::VHAL::VHAL_LIFECYCLEStub,
        std::tuple< std::string>,
        std::tuple< >,
        std::tuple< CommonAPI::SomeIP::StringDeployment>,
        std::tuple< >
    > receiveFOTASchedule_Update_ResponseStubDispatcher;
    
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v0::VHAL::VHAL_LIFECYCLEStub,
        std::tuple< std::string>,
        std::tuple< >,
        std::tuple< CommonAPI::SomeIP::StringDeployment>,
        std::tuple< >
    > receiveFOTAWhatsNew_Details_ResponseStubDispatcher;
    
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v0::VHAL::VHAL_LIFECYCLEStub,
        std::tuple< std::string>,
        std::tuple< >,
        std::tuple< CommonAPI::SomeIP::StringDeployment>,
        std::tuple< >
    > receiveFOTAUpdate_History_ResponseStubDispatcher;
    
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v0::VHAL::VHAL_LIFECYCLEStub,
        std::tuple< std::string>,
        std::tuple< >,
        std::tuple< CommonAPI::SomeIP::StringDeployment>,
        std::tuple< >
    > receiveFOTAPending_Updates_ResponseStubDispatcher;
    
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v0::VHAL::VHAL_LIFECYCLEStub,
        std::tuple< std::string>,
        std::tuple< >,
        std::tuple< CommonAPI::SomeIP::StringDeployment>,
        std::tuple< >
    > receive_UIN_TCUStubDispatcher;
    
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v0::VHAL::VHAL_LIFECYCLEStub,
        std::tuple< std::string>,
        std::tuple< >,
        std::tuple< CommonAPI::SomeIP::StringDeployment>,
        std::tuple< >
    > receiveTCU_Version_NumberStubDispatcher;
    
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v0::VHAL::VHAL_LIFECYCLEStub,
        std::tuple< std::string>,
        std::tuple< >,
        std::tuple< CommonAPI::SomeIP::StringDeployment>,
        std::tuple< >
    > receiveAOSP_RBUA_TriggerStubDispatcher;
    
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v0::VHAL::VHAL_LIFECYCLEStub,
        std::tuple< >,
        std::tuple< std::string>,
        std::tuple< >,
        std::tuple< CommonAPI::SomeIP::StringDeployment>
    > sIdsExportSecurityEventsStubDispatcher;
    
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v0::VHAL::VHAL_LIFECYCLEStub,
        std::tuple< std::string>,
        std::tuple< std::string>,
        std::tuple< CommonAPI::SomeIP::StringDeployment>,
        std::tuple< CommonAPI::SomeIP::StringDeployment>
    > sIdsSetVehiclePhaseStubDispatcher;
    
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v0::VHAL::VHAL_LIFECYCLEStub,
        std::tuple< std::string>,
        std::tuple< >,
        std::tuple< CommonAPI::SomeIP::StringDeployment>,
        std::tuple< >
    > fOTAHMI_Info_ResultStubDispatcher;
    
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v0::VHAL::VHAL_LIFECYCLEStub,
        std::tuple< std::string>,
        std::tuple< >,
        std::tuple< CommonAPI::SomeIP::StringDeployment>,
        std::tuple< >
    > uSBUpdate_DetailsStubDispatcher;
    
    VHAL_LIFECYCLESomeIPStubAdapterInternal(
        const CommonAPI::SomeIP::Address &_address,
        const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection,
        const std::shared_ptr<CommonAPI::StubBase> &_stub):
        CommonAPI::SomeIP::StubAdapter(_address, _connection),
        VHAL_LIFECYCLESomeIPStubAdapterHelper(
            _address,
            _connection,
            std::dynamic_pointer_cast< VHAL_LIFECYCLEStub>(_stub)),
        getVHAL_LIFECYCLEInterfaceVersionStubDispatcher(&VHAL_LIFECYCLEStub::lockInterfaceVersionAttribute, &VHAL_LIFECYCLEStub::getInterfaceVersion, false, true),
        getEcallStatusAttributeStubDispatcher(
            &::v0::VHAL::VHAL_LIFECYCLEStub::lockEcallStatusAttribute,
            &::v0::VHAL::VHAL_LIFECYCLEStub::getEcallStatusAttribute,
            false,
            _stub->hasElement(1))
        ,
        getPrivacy_ModeAttributeStubDispatcher(
            &::v0::VHAL::VHAL_LIFECYCLEStub::lockPrivacy_ModeAttribute,
            &::v0::VHAL::VHAL_LIFECYCLEStub::getPrivacy_ModeAttribute,
            false,
            _stub->hasElement(28))
        ,
        getFlash_ResultAttributeStubDispatcher(
            &::v0::VHAL::VHAL_LIFECYCLEStub::lockFlash_ResultAttribute,
            &::v0::VHAL::VHAL_LIFECYCLEStub::getFlash_ResultAttribute,
            false,
            _stub->hasElement(33))
        ,
        getXCallHmiControlAttributeStubDispatcher(
            &::v0::VHAL::VHAL_LIFECYCLEStub::lockXCallHmiControlAttribute,
            &::v0::VHAL::VHAL_LIFECYCLEStub::getXCallHmiControlAttribute,
            false,
            _stub->hasElement(38))
        ,
        getHMI_FOTA_Update_historyAttributeStubDispatcher(
            &::v0::VHAL::VHAL_LIFECYCLEStub::lockHMI_FOTA_Update_historyAttribute,
            &::v0::VHAL::VHAL_LIFECYCLEStub::getHMI_FOTA_Update_historyAttribute,
            false,
            _stub->hasElement(39))
        ,
        getHMI_FOTA_pending_updatesAttributeStubDispatcher(
            &::v0::VHAL::VHAL_LIFECYCLEStub::lockHMI_FOTA_pending_updatesAttribute,
            &::v0::VHAL::VHAL_LIFECYCLEStub::getHMI_FOTA_pending_updatesAttribute,
            false,
            _stub->hasElement(40))
        ,
        getFOTA_Installation_Finished_with_User_ConformationAttributeStubDispatcher(
            &::v0::VHAL::VHAL_LIFECYCLEStub::lockFOTA_Installation_Finished_with_User_ConformationAttribute,
            &::v0::VHAL::VHAL_LIFECYCLEStub::getFOTA_Installation_Finished_with_User_ConformationAttribute,
            false,
            _stub->hasElement(50))
        ,
        getFOTA_Start_InstallationAttributeStubDispatcher(
            &::v0::VHAL::VHAL_LIFECYCLEStub::lockFOTA_Start_InstallationAttribute,
            &::v0::VHAL::VHAL_LIFECYCLEStub::getFOTA_Start_InstallationAttribute,
            false,
            _stub->hasElement(51))
        ,
        getFOTA_Check_for_UpdatesAttributeStubDispatcher(
            &::v0::VHAL::VHAL_LIFECYCLEStub::lockFOTA_Check_for_UpdatesAttribute,
            &::v0::VHAL::VHAL_LIFECYCLEStub::getFOTA_Check_for_UpdatesAttribute,
            false,
            _stub->hasElement(52))
        ,
        getFOTA_Update_DismissedAttributeStubDispatcher(
            &::v0::VHAL::VHAL_LIFECYCLEStub::lockFOTA_Update_DismissedAttribute,
            &::v0::VHAL::VHAL_LIFECYCLEStub::getFOTA_Update_DismissedAttribute,
            false,
            _stub->hasElement(53))
        ,
        getFOTA_Schedule_UpdateAttributeStubDispatcher(
            &::v0::VHAL::VHAL_LIFECYCLEStub::lockFOTA_Schedule_UpdateAttribute,
            &::v0::VHAL::VHAL_LIFECYCLEStub::getFOTA_Schedule_UpdateAttribute,
            false,
            _stub->hasElement(54))
        ,
        getFOTA_WhatsNew_DetailsAttributeStubDispatcher(
            &::v0::VHAL::VHAL_LIFECYCLEStub::lockFOTA_WhatsNew_DetailsAttribute,
            &::v0::VHAL::VHAL_LIFECYCLEStub::getFOTA_WhatsNew_DetailsAttribute,
            false,
            _stub->hasElement(55))
        ,
        getActive_phone_callAttributeStubDispatcher(
            &::v0::VHAL::VHAL_LIFECYCLEStub::lockActive_phone_callAttribute,
            &::v0::VHAL::VHAL_LIFECYCLEStub::getActive_phone_callAttribute,
            false,
            _stub->hasElement(56))
        ,
        getSIVIDriverLockoutStsAttributeStubDispatcher(
            &::v0::VHAL::VHAL_LIFECYCLEStub::lockSIVIDriverLockoutStsAttribute,
            &::v0::VHAL::VHAL_LIFECYCLEStub::getSIVIDriverLockoutStsAttribute,
            false,
            _stub->hasElement(57))
        ,
        getUIN_Trigger_from_HMIAttributeStubDispatcher(
            &::v0::VHAL::VHAL_LIFECYCLEStub::lockUIN_Trigger_from_HMIAttribute,
            &::v0::VHAL::VHAL_LIFECYCLEStub::getUIN_Trigger_from_HMIAttribute,
            false,
            _stub->hasElement(59))
        ,
        getBTCallHMI_StatusAttributeStubDispatcher(
            &::v0::VHAL::VHAL_LIFECYCLEStub::lockBTCallHMI_StatusAttribute,
            &::v0::VHAL::VHAL_LIFECYCLEStub::getBTCallHMI_StatusAttribute,
            false,
            _stub->hasElement(60))
        ,
        getBTDeviceAttached_StatusAttributeStubDispatcher(
            &::v0::VHAL::VHAL_LIFECYCLEStub::lockBTDeviceAttached_StatusAttribute,
            &::v0::VHAL::VHAL_LIFECYCLEStub::getBTDeviceAttached_StatusAttribute,
            false,
            _stub->hasElement(61))
        ,
        getBTTransferTime_DurationAttributeStubDispatcher(
            &::v0::VHAL::VHAL_LIFECYCLEStub::lockBTTransferTime_DurationAttribute,
            &::v0::VHAL::VHAL_LIFECYCLEStub::getBTTransferTime_DurationAttribute,
            false,
            _stub->hasElement(62))
        ,
        getAOSP_Flash_ResultAttributeStubDispatcher(
            &::v0::VHAL::VHAL_LIFECYCLEStub::lockAOSP_Flash_ResultAttribute,
            &::v0::VHAL::VHAL_LIFECYCLEStub::getAOSP_Flash_ResultAttribute,
            false,
            _stub->hasElement(65))
        ,
        getHMI_Status_SWUpdateAttributeStubDispatcher(
            &::v0::VHAL::VHAL_LIFECYCLEStub::lockHMI_Status_SWUpdateAttribute,
            &::v0::VHAL::VHAL_LIFECYCLEStub::getHMI_Status_SWUpdateAttribute,
            false,
            _stub->hasElement(68))
        ,
        getIncomingPhoneCallAttributeStubDispatcher(
            &::v0::VHAL::VHAL_LIFECYCLEStub::lockIncomingPhoneCallAttribute,
            &::v0::VHAL::VHAL_LIFECYCLEStub::getIncomingPhoneCallAttribute,
            false,
            _stub->hasElement(69))
        ,
        getOutgoingPhoneCallAttributeStubDispatcher(
            &::v0::VHAL::VHAL_LIFECYCLEStub::lockOutgoingPhoneCallAttribute,
            &::v0::VHAL::VHAL_LIFECYCLEStub::getOutgoingPhoneCallAttribute,
            false,
            _stub->hasElement(70))
        ,
        getBtTransferAcceptanceAttributeStubDispatcher(
            &::v0::VHAL::VHAL_LIFECYCLEStub::lockBtTransferAcceptanceAttribute,
            &::v0::VHAL::VHAL_LIFECYCLEStub::getBtTransferAcceptanceAttribute,
            false,
            _stub->hasElement(71))
        ,
        getHMIFOTA_InfoAttributeStubDispatcher(
            &::v0::VHAL::VHAL_LIFECYCLEStub::lockHMIFOTA_InfoAttribute,
            &::v0::VHAL::VHAL_LIFECYCLEStub::getHMIFOTA_InfoAttribute,
            false,
            _stub->hasElement(72))
        ,
        ecallStatus_ackStubDispatcher(
            &VHAL_LIFECYCLEStub::ecallStatus_ack,
            false,
            _stub->hasElement(0),
            std::make_tuple(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint8_t>* >(nullptr)),
            std::make_tuple())
        
        ,
        receive_MsdTransmissionTime_TCUStubDispatcher(
            &VHAL_LIFECYCLEStub::Receive_MsdTransmissionTime_TCU,
            false,
            _stub->hasElement(2),
            std::make_tuple(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr)),
            std::make_tuple())
        
        ,
        receive_EcallState_TCUStubDispatcher(
            &VHAL_LIFECYCLEStub::Receive_EcallState_TCU,
            false,
            _stub->hasElement(3),
            std::make_tuple(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr)),
            std::make_tuple())
        
        ,
        receive_AcallState_TCUStubDispatcher(
            &VHAL_LIFECYCLEStub::Receive_AcallState_TCU,
            false,
            _stub->hasElement(4),
            std::make_tuple(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr)),
            std::make_tuple())
        
        ,
        receive_UserXcallFeedback_TCUStubDispatcher(
            &VHAL_LIFECYCLEStub::Receive_UserXcallFeedback_TCU,
            false,
            _stub->hasElement(5),
            std::make_tuple(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr)),
            std::make_tuple())
        
        ,
        receive_EcallDurationTimer_TCUStubDispatcher(
            &VHAL_LIFECYCLEStub::Receive_EcallDurationTimer_TCU,
            false,
            _stub->hasElement(6),
            std::make_tuple(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr)),
            std::make_tuple())
        
        ,
        receive_EcallTpsState_TCUStubDispatcher(
            &VHAL_LIFECYCLEStub::Receive_EcallTpsState_TCU,
            false,
            _stub->hasElement(7),
            std::make_tuple(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr)),
            std::make_tuple())
        
        ,
        receive_XcallStatus_TCUStubDispatcher(
            &VHAL_LIFECYCLEStub::Receive_XcallStatus_TCU,
            false,
            _stub->hasElement(8),
            std::make_tuple(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr)),
            std::make_tuple())
        
        ,
        receive_EcallWcbTimer_TCUStubDispatcher(
            &VHAL_LIFECYCLEStub::Receive_EcallWcbTimer_TCU,
            false,
            _stub->hasElement(9),
            std::make_tuple(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr)),
            std::make_tuple())
        
        ,
        receive_DmdMuteSualStubDispatcher(
            &VHAL_LIFECYCLEStub::Receive_DmdMuteSual,
            false,
            _stub->hasElement(10),
            std::make_tuple(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr)),
            std::make_tuple())
        
        ,
        receive_AppUrgMdsStubDispatcher(
            &VHAL_LIFECYCLEStub::Receive_AppUrgMds,
            false,
            _stub->hasElement(11),
            std::make_tuple(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr)),
            std::make_tuple())
        
        ,
        receive_SignalVoyantDysfunctionStubDispatcher(
            &VHAL_LIFECYCLEStub::Receive_SignalVoyantDysfunction,
            false,
            _stub->hasElement(12),
            std::make_tuple(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr)),
            std::make_tuple())
        
        ,
        receive_SignalVoyantEtatStubDispatcher(
            &VHAL_LIFECYCLEStub::Receive_SignalVoyantEtat,
            false,
            _stub->hasElement(13),
            std::make_tuple(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr)),
            std::make_tuple())
        
        ,
        receive_BoostrapRetryCountStubDispatcher(
            &VHAL_LIFECYCLEStub::Receive_BoostrapRetryCount,
            false,
            _stub->hasElement(14),
            std::make_tuple(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr)),
            std::make_tuple())
        
        ,
        receive_CloudConnectionStatus_CConnState_connectionGateIDStubDispatcher(
            &VHAL_LIFECYCLEStub::Receive_CloudConnectionStatus_CConnState_connectionGateID,
            false,
            _stub->hasElement(15),
            std::make_tuple(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr)),
            std::make_tuple())
        
        ,
        receive_CloudConnectionStatus_CConnState_isConnectedStubDispatcher(
            &VHAL_LIFECYCLEStub::Receive_CloudConnectionStatus_CConnState_isConnected,
            false,
            _stub->hasElement(16),
            std::make_tuple(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr)),
            std::make_tuple())
        
        ,
        receive_CloudConnectionStatus_CConnState_connTypeStubDispatcher(
            &VHAL_LIFECYCLEStub::Receive_CloudConnectionStatus_CConnState_connType,
            false,
            _stub->hasElement(17),
            std::make_tuple(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr)),
            std::make_tuple())
        
        ,
        receive_CloudConnectionStatus_CConnState_isRoamingStubDispatcher(
            &VHAL_LIFECYCLEStub::Receive_CloudConnectionStatus_CConnState_isRoaming,
            false,
            _stub->hasElement(18),
            std::make_tuple(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr)),
            std::make_tuple())
        
        ,
        receive_CloudConnectionStatus_CConnState_sigStrengthStubDispatcher(
            &VHAL_LIFECYCLEStub::Receive_CloudConnectionStatus_CConnState_sigStrength,
            false,
            _stub->hasElement(19),
            std::make_tuple(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr)),
            std::make_tuple())
        
        ,
        receive_CloudConnectionStatus_CConnState_ipVersionStubDispatcher(
            &VHAL_LIFECYCLEStub::Receive_CloudConnectionStatus_CConnState_ipVersion,
            false,
            _stub->hasElement(20),
            std::make_tuple(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr)),
            std::make_tuple())
        
        ,
        receive_CellularNetworkTypeStubDispatcher(
            &VHAL_LIFECYCLEStub::Receive_CellularNetworkType,
            false,
            _stub->hasElement(21),
            std::make_tuple(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr)),
            std::make_tuple())
        
        ,
        receive_NetConnectionStubDispatcher(
            &VHAL_LIFECYCLEStub::Receive_NetConnection,
            false,
            _stub->hasElement(22),
            std::make_tuple(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr)),
            std::make_tuple())
        
        ,
        receive_CellsignalStubDispatcher(
            &VHAL_LIFECYCLEStub::Receive_Cellsignal,
            false,
            _stub->hasElement(23),
            std::make_tuple(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr)),
            std::make_tuple())
        
        ,
        receive_CloudConnectionStatus_CConnCtrl_reqDisableStubDispatcher(
            &VHAL_LIFECYCLEStub::Receive_CloudConnectionStatus_CConnCtrl_reqDisable,
            false,
            _stub->hasElement(24),
            std::make_tuple(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr)),
            std::make_tuple())
        
        ,
        getLanguageSelectionOnBootupStubDispatcher(
            &VHAL_LIFECYCLEStub::getLanguageSelectionOnBootup,
            false,
            _stub->hasElement(27),
            std::make_tuple(),
            std::make_tuple(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr)))
        
        ,
        receive_SLIRoadTypeStubDispatcher(
            &VHAL_LIFECYCLEStub::Receive_SLIRoadType,
            false,
            _stub->hasElement(29),
            std::make_tuple(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr)),
            std::make_tuple())
        
        ,
        receive_SLISpeedLimitStubDispatcher(
            &VHAL_LIFECYCLEStub::Receive_SLISpeedLimit,
            false,
            _stub->hasElement(30),
            std::make_tuple(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr)),
            std::make_tuple())
        
        ,
        receive_SLICountryCodeStubDispatcher(
            &VHAL_LIFECYCLEStub::Receive_SLICountryCode,
            false,
            _stub->hasElement(31),
            std::make_tuple(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr)),
            std::make_tuple())
        
        ,
        flash_UnitidStubDispatcher(
            &VHAL_LIFECYCLEStub::Flash_Unitid,
            false,
            _stub->hasElement(32),
            std::make_tuple(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr)),
            std::make_tuple())
        
        ,
        package_PathStubDispatcher(
            &VHAL_LIFECYCLEStub::Package_Path,
            false,
            _stub->hasElement(34),
            std::make_tuple(static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr)),
            std::make_tuple())
        
        ,
        sIdsRegisterAppStubDispatcher(
            &VHAL_LIFECYCLEStub::sIdsRegisterApp,
            false,
            _stub->hasElement(35),
            std::make_tuple(static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr), static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr)),
            std::make_tuple(static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr)))
        
        ,
        sIdsUnRegisterAppStubDispatcher(
            &VHAL_LIFECYCLEStub::sIdsUnRegisterApp,
            false,
            _stub->hasElement(36),
            std::make_tuple(),
            std::make_tuple(static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr)))
        
        ,
        sIdsWriteSevStubDispatcher(
            &VHAL_LIFECYCLEStub::sIdsWriteSev,
            false,
            _stub->hasElement(37),
            std::make_tuple(static_cast< ::VHAL::sIdsFramework_Types_::sStSecurityEventDeployment_t* >(nullptr), static_cast< ::VHAL::sIdsFramework_Types_::sStLogIssuerDeployment_t* >(nullptr), static_cast< ::VHAL::sIdsFramework_Types_::sStEventSrcDeployment_t* >(nullptr), static_cast< ::VHAL::sIdsFramework_Types_::sStActionDeployment_t* >(nullptr)),
            std::make_tuple(static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr)))
        
        ,
        receiveFOTA_Check_for_Updates_ResultStubDispatcher(
            &VHAL_LIFECYCLEStub::ReceiveFOTA_Check_for_Updates_Result,
            false,
            _stub->hasElement(41),
            std::make_tuple(static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr)),
            std::make_tuple())
        
        ,
        receiveFOTA_Update_AvailableStubDispatcher(
            &VHAL_LIFECYCLEStub::ReceiveFOTA_Update_Available,
            false,
            _stub->hasElement(42),
            std::make_tuple(static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr)),
            std::make_tuple())
        
        ,
        receiveFOTA_Conditions_not_MetStubDispatcher(
            &VHAL_LIFECYCLEStub::ReceiveFOTA_Conditions_not_Met,
            false,
            _stub->hasElement(43),
            std::make_tuple(static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr)),
            std::make_tuple())
        
        ,
        receiveFOTA_Installation_StatusStubDispatcher(
            &VHAL_LIFECYCLEStub::ReceiveFOTA_Installation_Status,
            false,
            _stub->hasElement(44),
            std::make_tuple(static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr)),
            std::make_tuple())
        
        ,
        receiveFOTA_Update_FinishedStubDispatcher(
            &VHAL_LIFECYCLEStub::ReceiveFOTA_Update_Finished,
            false,
            _stub->hasElement(45),
            std::make_tuple(static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr)),
            std::make_tuple())
        
        ,
        receiveFOTASchedule_Update_ResponseStubDispatcher(
            &VHAL_LIFECYCLEStub::ReceiveFOTASchedule_Update_Response,
            false,
            _stub->hasElement(46),
            std::make_tuple(static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr)),
            std::make_tuple())
        
        ,
        receiveFOTAWhatsNew_Details_ResponseStubDispatcher(
            &VHAL_LIFECYCLEStub::ReceiveFOTAWhatsNew_Details_Response,
            false,
            _stub->hasElement(47),
            std::make_tuple(static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr)),
            std::make_tuple())
        
        ,
        receiveFOTAUpdate_History_ResponseStubDispatcher(
            &VHAL_LIFECYCLEStub::ReceiveFOTAUpdate_History_Response,
            false,
            _stub->hasElement(48),
            std::make_tuple(static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr)),
            std::make_tuple())
        
        ,
        receiveFOTAPending_Updates_ResponseStubDispatcher(
            &VHAL_LIFECYCLEStub::ReceiveFOTAPending_Updates_Response,
            false,
            _stub->hasElement(49),
            std::make_tuple(static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr)),
            std::make_tuple())
        
        ,
        receive_UIN_TCUStubDispatcher(
            &VHAL_LIFECYCLEStub::Receive_UIN_TCU,
            false,
            _stub->hasElement(58),
            std::make_tuple(static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr)),
            std::make_tuple())
        
        ,
        receiveTCU_Version_NumberStubDispatcher(
            &VHAL_LIFECYCLEStub::ReceiveTCU_Version_Number,
            false,
            _stub->hasElement(63),
            std::make_tuple(static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr)),
            std::make_tuple())
        
        ,
        receiveAOSP_RBUA_TriggerStubDispatcher(
            &VHAL_LIFECYCLEStub::ReceiveAOSP_RBUA_Trigger,
            false,
            _stub->hasElement(64),
            std::make_tuple(static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr)),
            std::make_tuple())
        
        ,
        sIdsExportSecurityEventsStubDispatcher(
            &VHAL_LIFECYCLEStub::sIdsExportSecurityEvents,
            false,
            _stub->hasElement(66),
            std::make_tuple(),
            std::make_tuple(static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr)))
        
        ,
        sIdsSetVehiclePhaseStubDispatcher(
            &VHAL_LIFECYCLEStub::sIdsSetVehiclePhase,
            false,
            _stub->hasElement(67),
            std::make_tuple(static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr)),
            std::make_tuple(static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr)))
        
        ,
        fOTAHMI_Info_ResultStubDispatcher(
            &VHAL_LIFECYCLEStub::FOTAHMI_Info_Result,
            false,
            _stub->hasElement(73),
            std::make_tuple(static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr)),
            std::make_tuple())
        
        ,
        uSBUpdate_DetailsStubDispatcher(
            &VHAL_LIFECYCLEStub::USBUpdate_Details,
            false,
            _stub->hasElement(74),
            std::make_tuple(static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr)),
            std::make_tuple())
        
    {
        /*
         * description: 
         * ecall status for IVI
         */
        VHAL_LIFECYCLESomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x15) }, &getEcallStatusAttributeStubDispatcher );
        VHAL_LIFECYCLESomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x19) }, &getPrivacy_ModeAttributeStubDispatcher );
        VHAL_LIFECYCLESomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x1c) }, &getFlash_ResultAttributeStubDispatcher );
        VHAL_LIFECYCLESomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x1a) }, &getXCallHmiControlAttributeStubDispatcher );
        VHAL_LIFECYCLESomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x21) }, &getHMI_FOTA_Update_historyAttributeStubDispatcher );
        VHAL_LIFECYCLESomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x22) }, &getHMI_FOTA_pending_updatesAttributeStubDispatcher );
        VHAL_LIFECYCLESomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x1d) }, &getFOTA_Installation_Finished_with_User_ConformationAttributeStubDispatcher );
        VHAL_LIFECYCLESomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x1e) }, &getFOTA_Start_InstallationAttributeStubDispatcher );
        VHAL_LIFECYCLESomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x1f) }, &getFOTA_Check_for_UpdatesAttributeStubDispatcher );
        VHAL_LIFECYCLESomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x29) }, &getFOTA_Update_DismissedAttributeStubDispatcher );
        VHAL_LIFECYCLESomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x2a) }, &getFOTA_Schedule_UpdateAttributeStubDispatcher );
        VHAL_LIFECYCLESomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x28) }, &getFOTA_WhatsNew_DetailsAttributeStubDispatcher );
        VHAL_LIFECYCLESomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x23) }, &getActive_phone_callAttributeStubDispatcher );
        VHAL_LIFECYCLESomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x24) }, &getSIVIDriverLockoutStsAttributeStubDispatcher );
        VHAL_LIFECYCLESomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x2b) }, &getUIN_Trigger_from_HMIAttributeStubDispatcher );
        VHAL_LIFECYCLESomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x25) }, &getBTCallHMI_StatusAttributeStubDispatcher );
        VHAL_LIFECYCLESomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x26) }, &getBTDeviceAttached_StatusAttributeStubDispatcher );
        VHAL_LIFECYCLESomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x27) }, &getBTTransferTime_DurationAttributeStubDispatcher );
        VHAL_LIFECYCLESomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x2d) }, &getAOSP_Flash_ResultAttributeStubDispatcher );
        VHAL_LIFECYCLESomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x2e) }, &getHMI_Status_SWUpdateAttributeStubDispatcher );
        VHAL_LIFECYCLESomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x2f) }, &getIncomingPhoneCallAttributeStubDispatcher );
        VHAL_LIFECYCLESomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x30) }, &getOutgoingPhoneCallAttributeStubDispatcher );
        VHAL_LIFECYCLESomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x31) }, &getBtTransferAcceptanceAttributeStubDispatcher );
        VHAL_LIFECYCLESomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x32) }, &getHMIFOTA_InfoAttributeStubDispatcher );
        VHAL_LIFECYCLESomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x53) }, &ecallStatus_ackStubDispatcher );
        VHAL_LIFECYCLESomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x54) }, &receive_MsdTransmissionTime_TCUStubDispatcher );
        VHAL_LIFECYCLESomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x55) }, &receive_EcallState_TCUStubDispatcher );
        VHAL_LIFECYCLESomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x56) }, &receive_AcallState_TCUStubDispatcher );
        VHAL_LIFECYCLESomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x57) }, &receive_UserXcallFeedback_TCUStubDispatcher );
        VHAL_LIFECYCLESomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x58) }, &receive_EcallDurationTimer_TCUStubDispatcher );
        VHAL_LIFECYCLESomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x59) }, &receive_EcallTpsState_TCUStubDispatcher );
        VHAL_LIFECYCLESomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x5a) }, &receive_XcallStatus_TCUStubDispatcher );
        VHAL_LIFECYCLESomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x5b) }, &receive_EcallWcbTimer_TCUStubDispatcher );
        VHAL_LIFECYCLESomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x5c) }, &receive_DmdMuteSualStubDispatcher );
        VHAL_LIFECYCLESomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x5d) }, &receive_AppUrgMdsStubDispatcher );
        VHAL_LIFECYCLESomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x5e) }, &receive_SignalVoyantDysfunctionStubDispatcher );
        VHAL_LIFECYCLESomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x5f) }, &receive_SignalVoyantEtatStubDispatcher );
        VHAL_LIFECYCLESomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x60) }, &receive_BoostrapRetryCountStubDispatcher );
        VHAL_LIFECYCLESomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x61) }, &receive_CloudConnectionStatus_CConnState_connectionGateIDStubDispatcher );
        VHAL_LIFECYCLESomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x62) }, &receive_CloudConnectionStatus_CConnState_isConnectedStubDispatcher );
        VHAL_LIFECYCLESomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x63) }, &receive_CloudConnectionStatus_CConnState_connTypeStubDispatcher );
        VHAL_LIFECYCLESomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x64) }, &receive_CloudConnectionStatus_CConnState_isRoamingStubDispatcher );
        VHAL_LIFECYCLESomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x65) }, &receive_CloudConnectionStatus_CConnState_sigStrengthStubDispatcher );
        VHAL_LIFECYCLESomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x66) }, &receive_CloudConnectionStatus_CConnState_ipVersionStubDispatcher );
        VHAL_LIFECYCLESomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x67) }, &receive_CellularNetworkTypeStubDispatcher );
        VHAL_LIFECYCLESomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x68) }, &receive_NetConnectionStubDispatcher );
        VHAL_LIFECYCLESomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x69) }, &receive_CellsignalStubDispatcher );
        VHAL_LIFECYCLESomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x6a) }, &receive_CloudConnectionStatus_CConnCtrl_reqDisableStubDispatcher );
        VHAL_LIFECYCLESomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x6b) }, &getLanguageSelectionOnBootupStubDispatcher );
        VHAL_LIFECYCLESomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x6c) }, &receive_SLIRoadTypeStubDispatcher );
        VHAL_LIFECYCLESomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x6d) }, &receive_SLISpeedLimitStubDispatcher );
        VHAL_LIFECYCLESomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x6e) }, &receive_SLICountryCodeStubDispatcher );
        VHAL_LIFECYCLESomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x72) }, &flash_UnitidStubDispatcher );
        VHAL_LIFECYCLESomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x74) }, &package_PathStubDispatcher );
        VHAL_LIFECYCLESomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x1a4) }, &sIdsRegisterAppStubDispatcher );
        VHAL_LIFECYCLESomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x1a5) }, &sIdsUnRegisterAppStubDispatcher );
        VHAL_LIFECYCLESomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x1a6) }, &sIdsWriteSevStubDispatcher );
        VHAL_LIFECYCLESomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x70) }, &receiveFOTA_Check_for_Updates_ResultStubDispatcher );
        VHAL_LIFECYCLESomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x71) }, &receiveFOTA_Update_AvailableStubDispatcher );
        VHAL_LIFECYCLESomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x75) }, &receiveFOTA_Conditions_not_MetStubDispatcher );
        VHAL_LIFECYCLESomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x76) }, &receiveFOTA_Installation_StatusStubDispatcher );
        VHAL_LIFECYCLESomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x7d) }, &receiveFOTA_Update_FinishedStubDispatcher );
        VHAL_LIFECYCLESomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x7e) }, &receiveFOTASchedule_Update_ResponseStubDispatcher );
        VHAL_LIFECYCLESomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x7f) }, &receiveFOTAWhatsNew_Details_ResponseStubDispatcher );
        VHAL_LIFECYCLESomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x81) }, &receiveFOTAUpdate_History_ResponseStubDispatcher );
        VHAL_LIFECYCLESomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x82) }, &receiveFOTAPending_Updates_ResponseStubDispatcher );
        VHAL_LIFECYCLESomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x7c) }, &receive_UIN_TCUStubDispatcher );
        VHAL_LIFECYCLESomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x83) }, &receiveTCU_Version_NumberStubDispatcher );
        VHAL_LIFECYCLESomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x84) }, &receiveAOSP_RBUA_TriggerStubDispatcher );
        VHAL_LIFECYCLESomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x1a7) }, &sIdsExportSecurityEventsStubDispatcher );
        VHAL_LIFECYCLESomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x1a8) }, &sIdsSetVehiclePhaseStubDispatcher );
        VHAL_LIFECYCLESomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x85) }, &fOTAHMI_Info_ResultStubDispatcher );
        VHAL_LIFECYCLESomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x86) }, &uSBUpdate_DetailsStubDispatcher );
        std::shared_ptr<CommonAPI::SomeIP::ClientId> itsClient = std::make_shared<CommonAPI::SomeIP::ClientId>(0xFFFF, 0xFFFFFFFF, 0xFFFFFFFF);

        // Provided events/fields
        {
            std::set<CommonAPI::SomeIP::eventgroup_id_t> itsEventGroups;
            itsEventGroups.insert(CommonAPI::SomeIP::eventgroup_id_t(0x84d0));
            CommonAPI::SomeIP::StubAdapter::registerEvent(CommonAPI::SomeIP::event_id_t(0x84d0), itsEventGroups, CommonAPI::SomeIP::event_type_e::ET_EVENT, CommonAPI::SomeIP::reliability_type_e::RT_UNRELIABLE);
        }
        {
            std::set<CommonAPI::SomeIP::eventgroup_id_t> itsEventGroups;
            itsEventGroups.insert(CommonAPI::SomeIP::eventgroup_id_t(0x84d1));
            CommonAPI::SomeIP::StubAdapter::registerEvent(CommonAPI::SomeIP::event_id_t(0x84d1), itsEventGroups, CommonAPI::SomeIP::event_type_e::ET_EVENT, CommonAPI::SomeIP::reliability_type_e::RT_UNRELIABLE);
        }
        if (_stub->hasElement(1)) {
            std::set<CommonAPI::SomeIP::eventgroup_id_t> itsEventGroups;
            itsEventGroups.insert(CommonAPI::SomeIP::eventgroup_id_t(CommonAPI::SomeIP::eventgroup_id_t(0x4001)));
            CommonAPI::SomeIP::StubAdapter::registerEvent(CommonAPI::SomeIP::event_id_t(0xbfff), itsEventGroups, CommonAPI::SomeIP::event_type_e::ET_FIELD, CommonAPI::SomeIP::reliability_type_e::RT_UNRELIABLE);
            fireEcallStatusAttributeChanged(std::dynamic_pointer_cast< ::v0::VHAL::VHAL_LIFECYCLEStub>(_stub)->getEcallStatusAttribute(itsClient));
        }

        if (_stub->hasElement(28)) {
            std::set<CommonAPI::SomeIP::eventgroup_id_t> itsEventGroups;
            itsEventGroups.insert(CommonAPI::SomeIP::eventgroup_id_t(CommonAPI::SomeIP::eventgroup_id_t(0x4001)));
            CommonAPI::SomeIP::StubAdapter::registerEvent(CommonAPI::SomeIP::event_id_t(0xc003), itsEventGroups, CommonAPI::SomeIP::event_type_e::ET_FIELD, CommonAPI::SomeIP::reliability_type_e::RT_UNRELIABLE);
            firePrivacy_ModeAttributeChanged(std::dynamic_pointer_cast< ::v0::VHAL::VHAL_LIFECYCLEStub>(_stub)->getPrivacy_ModeAttribute(itsClient));
        }

        if (_stub->hasElement(33)) {
            std::set<CommonAPI::SomeIP::eventgroup_id_t> itsEventGroups;
            itsEventGroups.insert(CommonAPI::SomeIP::eventgroup_id_t(CommonAPI::SomeIP::eventgroup_id_t(0x4001)));
            CommonAPI::SomeIP::StubAdapter::registerEvent(CommonAPI::SomeIP::event_id_t(0xc006), itsEventGroups, CommonAPI::SomeIP::event_type_e::ET_FIELD, CommonAPI::SomeIP::reliability_type_e::RT_UNRELIABLE);
            fireFlash_ResultAttributeChanged(std::dynamic_pointer_cast< ::v0::VHAL::VHAL_LIFECYCLEStub>(_stub)->getFlash_ResultAttribute(itsClient));
        }

        if (_stub->hasElement(38)) {
            std::set<CommonAPI::SomeIP::eventgroup_id_t> itsEventGroups;
            itsEventGroups.insert(CommonAPI::SomeIP::eventgroup_id_t(CommonAPI::SomeIP::eventgroup_id_t(0x4001)));
            CommonAPI::SomeIP::StubAdapter::registerEvent(CommonAPI::SomeIP::event_id_t(0xc004), itsEventGroups, CommonAPI::SomeIP::event_type_e::ET_FIELD, CommonAPI::SomeIP::reliability_type_e::RT_UNRELIABLE);
            fireXCallHmiControlAttributeChanged(std::dynamic_pointer_cast< ::v0::VHAL::VHAL_LIFECYCLEStub>(_stub)->getXCallHmiControlAttribute(itsClient));
        }

        if (_stub->hasElement(39)) {
            std::set<CommonAPI::SomeIP::eventgroup_id_t> itsEventGroups;
            itsEventGroups.insert(CommonAPI::SomeIP::eventgroup_id_t(CommonAPI::SomeIP::eventgroup_id_t(0x4001)));
            CommonAPI::SomeIP::StubAdapter::registerEvent(CommonAPI::SomeIP::event_id_t(0xc00b), itsEventGroups, CommonAPI::SomeIP::event_type_e::ET_FIELD, CommonAPI::SomeIP::reliability_type_e::RT_UNRELIABLE);
            fireHMI_FOTA_Update_historyAttributeChanged(std::dynamic_pointer_cast< ::v0::VHAL::VHAL_LIFECYCLEStub>(_stub)->getHMI_FOTA_Update_historyAttribute(itsClient));
        }

        if (_stub->hasElement(40)) {
            std::set<CommonAPI::SomeIP::eventgroup_id_t> itsEventGroups;
            itsEventGroups.insert(CommonAPI::SomeIP::eventgroup_id_t(CommonAPI::SomeIP::eventgroup_id_t(0x4001)));
            CommonAPI::SomeIP::StubAdapter::registerEvent(CommonAPI::SomeIP::event_id_t(0xc00c), itsEventGroups, CommonAPI::SomeIP::event_type_e::ET_FIELD, CommonAPI::SomeIP::reliability_type_e::RT_UNRELIABLE);
            fireHMI_FOTA_pending_updatesAttributeChanged(std::dynamic_pointer_cast< ::v0::VHAL::VHAL_LIFECYCLEStub>(_stub)->getHMI_FOTA_pending_updatesAttribute(itsClient));
        }

        if (_stub->hasElement(50)) {
            std::set<CommonAPI::SomeIP::eventgroup_id_t> itsEventGroups;
            itsEventGroups.insert(CommonAPI::SomeIP::eventgroup_id_t(CommonAPI::SomeIP::eventgroup_id_t(0x4001)));
            CommonAPI::SomeIP::StubAdapter::registerEvent(CommonAPI::SomeIP::event_id_t(0xc007), itsEventGroups, CommonAPI::SomeIP::event_type_e::ET_FIELD, CommonAPI::SomeIP::reliability_type_e::RT_UNRELIABLE);
            fireFOTA_Installation_Finished_with_User_ConformationAttributeChanged(std::dynamic_pointer_cast< ::v0::VHAL::VHAL_LIFECYCLEStub>(_stub)->getFOTA_Installation_Finished_with_User_ConformationAttribute(itsClient));
        }

        if (_stub->hasElement(51)) {
            std::set<CommonAPI::SomeIP::eventgroup_id_t> itsEventGroups;
            itsEventGroups.insert(CommonAPI::SomeIP::eventgroup_id_t(CommonAPI::SomeIP::eventgroup_id_t(0x4001)));
            CommonAPI::SomeIP::StubAdapter::registerEvent(CommonAPI::SomeIP::event_id_t(0xc008), itsEventGroups, CommonAPI::SomeIP::event_type_e::ET_FIELD, CommonAPI::SomeIP::reliability_type_e::RT_UNRELIABLE);
            fireFOTA_Start_InstallationAttributeChanged(std::dynamic_pointer_cast< ::v0::VHAL::VHAL_LIFECYCLEStub>(_stub)->getFOTA_Start_InstallationAttribute(itsClient));
        }

        if (_stub->hasElement(52)) {
            std::set<CommonAPI::SomeIP::eventgroup_id_t> itsEventGroups;
            itsEventGroups.insert(CommonAPI::SomeIP::eventgroup_id_t(CommonAPI::SomeIP::eventgroup_id_t(0x4001)));
            CommonAPI::SomeIP::StubAdapter::registerEvent(CommonAPI::SomeIP::event_id_t(0xc009), itsEventGroups, CommonAPI::SomeIP::event_type_e::ET_FIELD, CommonAPI::SomeIP::reliability_type_e::RT_UNRELIABLE);
            fireFOTA_Check_for_UpdatesAttributeChanged(std::dynamic_pointer_cast< ::v0::VHAL::VHAL_LIFECYCLEStub>(_stub)->getFOTA_Check_for_UpdatesAttribute(itsClient));
        }

        if (_stub->hasElement(53)) {
            std::set<CommonAPI::SomeIP::eventgroup_id_t> itsEventGroups;
            itsEventGroups.insert(CommonAPI::SomeIP::eventgroup_id_t(CommonAPI::SomeIP::eventgroup_id_t(0x4001)));
            CommonAPI::SomeIP::StubAdapter::registerEvent(CommonAPI::SomeIP::event_id_t(0xc013), itsEventGroups, CommonAPI::SomeIP::event_type_e::ET_FIELD, CommonAPI::SomeIP::reliability_type_e::RT_UNRELIABLE);
            fireFOTA_Update_DismissedAttributeChanged(std::dynamic_pointer_cast< ::v0::VHAL::VHAL_LIFECYCLEStub>(_stub)->getFOTA_Update_DismissedAttribute(itsClient));
        }

        if (_stub->hasElement(54)) {
            std::set<CommonAPI::SomeIP::eventgroup_id_t> itsEventGroups;
            itsEventGroups.insert(CommonAPI::SomeIP::eventgroup_id_t(CommonAPI::SomeIP::eventgroup_id_t(0x4001)));
            CommonAPI::SomeIP::StubAdapter::registerEvent(CommonAPI::SomeIP::event_id_t(0xc014), itsEventGroups, CommonAPI::SomeIP::event_type_e::ET_FIELD, CommonAPI::SomeIP::reliability_type_e::RT_UNRELIABLE);
            fireFOTA_Schedule_UpdateAttributeChanged(std::dynamic_pointer_cast< ::v0::VHAL::VHAL_LIFECYCLEStub>(_stub)->getFOTA_Schedule_UpdateAttribute(itsClient));
        }

        if (_stub->hasElement(55)) {
            std::set<CommonAPI::SomeIP::eventgroup_id_t> itsEventGroups;
            itsEventGroups.insert(CommonAPI::SomeIP::eventgroup_id_t(CommonAPI::SomeIP::eventgroup_id_t(0x4001)));
            CommonAPI::SomeIP::StubAdapter::registerEvent(CommonAPI::SomeIP::event_id_t(0xc012), itsEventGroups, CommonAPI::SomeIP::event_type_e::ET_FIELD, CommonAPI::SomeIP::reliability_type_e::RT_UNRELIABLE);
            fireFOTA_WhatsNew_DetailsAttributeChanged(std::dynamic_pointer_cast< ::v0::VHAL::VHAL_LIFECYCLEStub>(_stub)->getFOTA_WhatsNew_DetailsAttribute(itsClient));
        }

        if (_stub->hasElement(56)) {
            std::set<CommonAPI::SomeIP::eventgroup_id_t> itsEventGroups;
            itsEventGroups.insert(CommonAPI::SomeIP::eventgroup_id_t(CommonAPI::SomeIP::eventgroup_id_t(0x4001)));
            CommonAPI::SomeIP::StubAdapter::registerEvent(CommonAPI::SomeIP::event_id_t(0xc00d), itsEventGroups, CommonAPI::SomeIP::event_type_e::ET_FIELD, CommonAPI::SomeIP::reliability_type_e::RT_UNRELIABLE);
            fireActive_phone_callAttributeChanged(std::dynamic_pointer_cast< ::v0::VHAL::VHAL_LIFECYCLEStub>(_stub)->getActive_phone_callAttribute(itsClient));
        }

        if (_stub->hasElement(57)) {
            std::set<CommonAPI::SomeIP::eventgroup_id_t> itsEventGroups;
            itsEventGroups.insert(CommonAPI::SomeIP::eventgroup_id_t(CommonAPI::SomeIP::eventgroup_id_t(0x4001)));
            CommonAPI::SomeIP::StubAdapter::registerEvent(CommonAPI::SomeIP::event_id_t(0xc00e), itsEventGroups, CommonAPI::SomeIP::event_type_e::ET_FIELD, CommonAPI::SomeIP::reliability_type_e::RT_UNRELIABLE);
            fireSIVIDriverLockoutStsAttributeChanged(std::dynamic_pointer_cast< ::v0::VHAL::VHAL_LIFECYCLEStub>(_stub)->getSIVIDriverLockoutStsAttribute(itsClient));
        }

        if (_stub->hasElement(59)) {
            std::set<CommonAPI::SomeIP::eventgroup_id_t> itsEventGroups;
            itsEventGroups.insert(CommonAPI::SomeIP::eventgroup_id_t(CommonAPI::SomeIP::eventgroup_id_t(0x4001)));
            CommonAPI::SomeIP::StubAdapter::registerEvent(CommonAPI::SomeIP::event_id_t(0xc015), itsEventGroups, CommonAPI::SomeIP::event_type_e::ET_FIELD, CommonAPI::SomeIP::reliability_type_e::RT_UNRELIABLE);
            fireUIN_Trigger_from_HMIAttributeChanged(std::dynamic_pointer_cast< ::v0::VHAL::VHAL_LIFECYCLEStub>(_stub)->getUIN_Trigger_from_HMIAttribute(itsClient));
        }

        if (_stub->hasElement(60)) {
            std::set<CommonAPI::SomeIP::eventgroup_id_t> itsEventGroups;
            itsEventGroups.insert(CommonAPI::SomeIP::eventgroup_id_t(CommonAPI::SomeIP::eventgroup_id_t(0x4001)));
            CommonAPI::SomeIP::StubAdapter::registerEvent(CommonAPI::SomeIP::event_id_t(0xc00f), itsEventGroups, CommonAPI::SomeIP::event_type_e::ET_FIELD, CommonAPI::SomeIP::reliability_type_e::RT_UNRELIABLE);
            fireBTCallHMI_StatusAttributeChanged(std::dynamic_pointer_cast< ::v0::VHAL::VHAL_LIFECYCLEStub>(_stub)->getBTCallHMI_StatusAttribute(itsClient));
        }

        if (_stub->hasElement(61)) {
            std::set<CommonAPI::SomeIP::eventgroup_id_t> itsEventGroups;
            itsEventGroups.insert(CommonAPI::SomeIP::eventgroup_id_t(CommonAPI::SomeIP::eventgroup_id_t(0x4001)));
            CommonAPI::SomeIP::StubAdapter::registerEvent(CommonAPI::SomeIP::event_id_t(0xc010), itsEventGroups, CommonAPI::SomeIP::event_type_e::ET_FIELD, CommonAPI::SomeIP::reliability_type_e::RT_UNRELIABLE);
            fireBTDeviceAttached_StatusAttributeChanged(std::dynamic_pointer_cast< ::v0::VHAL::VHAL_LIFECYCLEStub>(_stub)->getBTDeviceAttached_StatusAttribute(itsClient));
        }

        if (_stub->hasElement(62)) {
            std::set<CommonAPI::SomeIP::eventgroup_id_t> itsEventGroups;
            itsEventGroups.insert(CommonAPI::SomeIP::eventgroup_id_t(CommonAPI::SomeIP::eventgroup_id_t(0x4001)));
            CommonAPI::SomeIP::StubAdapter::registerEvent(CommonAPI::SomeIP::event_id_t(0xc011), itsEventGroups, CommonAPI::SomeIP::event_type_e::ET_FIELD, CommonAPI::SomeIP::reliability_type_e::RT_UNRELIABLE);
            fireBTTransferTime_DurationAttributeChanged(std::dynamic_pointer_cast< ::v0::VHAL::VHAL_LIFECYCLEStub>(_stub)->getBTTransferTime_DurationAttribute(itsClient));
        }

        if (_stub->hasElement(65)) {
            std::set<CommonAPI::SomeIP::eventgroup_id_t> itsEventGroups;
            itsEventGroups.insert(CommonAPI::SomeIP::eventgroup_id_t(CommonAPI::SomeIP::eventgroup_id_t(0x4001)));
            CommonAPI::SomeIP::StubAdapter::registerEvent(CommonAPI::SomeIP::event_id_t(0xc017), itsEventGroups, CommonAPI::SomeIP::event_type_e::ET_FIELD, CommonAPI::SomeIP::reliability_type_e::RT_UNRELIABLE);
            fireAOSP_Flash_ResultAttributeChanged(std::dynamic_pointer_cast< ::v0::VHAL::VHAL_LIFECYCLEStub>(_stub)->getAOSP_Flash_ResultAttribute(itsClient));
        }

        if (_stub->hasElement(68)) {
            std::set<CommonAPI::SomeIP::eventgroup_id_t> itsEventGroups;
            itsEventGroups.insert(CommonAPI::SomeIP::eventgroup_id_t(CommonAPI::SomeIP::eventgroup_id_t(0x4001)));
            CommonAPI::SomeIP::StubAdapter::registerEvent(CommonAPI::SomeIP::event_id_t(0xc018), itsEventGroups, CommonAPI::SomeIP::event_type_e::ET_FIELD, CommonAPI::SomeIP::reliability_type_e::RT_UNRELIABLE);
            fireHMI_Status_SWUpdateAttributeChanged(std::dynamic_pointer_cast< ::v0::VHAL::VHAL_LIFECYCLEStub>(_stub)->getHMI_Status_SWUpdateAttribute(itsClient));
        }

        if (_stub->hasElement(69)) {
            std::set<CommonAPI::SomeIP::eventgroup_id_t> itsEventGroups;
            itsEventGroups.insert(CommonAPI::SomeIP::eventgroup_id_t(CommonAPI::SomeIP::eventgroup_id_t(0x4001)));
            CommonAPI::SomeIP::StubAdapter::registerEvent(CommonAPI::SomeIP::event_id_t(0xc019), itsEventGroups, CommonAPI::SomeIP::event_type_e::ET_FIELD, CommonAPI::SomeIP::reliability_type_e::RT_UNRELIABLE);
            fireIncomingPhoneCallAttributeChanged(std::dynamic_pointer_cast< ::v0::VHAL::VHAL_LIFECYCLEStub>(_stub)->getIncomingPhoneCallAttribute(itsClient));
        }

        if (_stub->hasElement(70)) {
            std::set<CommonAPI::SomeIP::eventgroup_id_t> itsEventGroups;
            itsEventGroups.insert(CommonAPI::SomeIP::eventgroup_id_t(CommonAPI::SomeIP::eventgroup_id_t(0x4001)));
            CommonAPI::SomeIP::StubAdapter::registerEvent(CommonAPI::SomeIP::event_id_t(0xc01a), itsEventGroups, CommonAPI::SomeIP::event_type_e::ET_FIELD, CommonAPI::SomeIP::reliability_type_e::RT_UNRELIABLE);
            fireOutgoingPhoneCallAttributeChanged(std::dynamic_pointer_cast< ::v0::VHAL::VHAL_LIFECYCLEStub>(_stub)->getOutgoingPhoneCallAttribute(itsClient));
        }

        if (_stub->hasElement(71)) {
            std::set<CommonAPI::SomeIP::eventgroup_id_t> itsEventGroups;
            itsEventGroups.insert(CommonAPI::SomeIP::eventgroup_id_t(CommonAPI::SomeIP::eventgroup_id_t(0x4001)));
            CommonAPI::SomeIP::StubAdapter::registerEvent(CommonAPI::SomeIP::event_id_t(0xc01b), itsEventGroups, CommonAPI::SomeIP::event_type_e::ET_FIELD, CommonAPI::SomeIP::reliability_type_e::RT_UNRELIABLE);
            fireBtTransferAcceptanceAttributeChanged(std::dynamic_pointer_cast< ::v0::VHAL::VHAL_LIFECYCLEStub>(_stub)->getBtTransferAcceptanceAttribute(itsClient));
        }

        if (_stub->hasElement(72)) {
            std::set<CommonAPI::SomeIP::eventgroup_id_t> itsEventGroups;
            itsEventGroups.insert(CommonAPI::SomeIP::eventgroup_id_t(CommonAPI::SomeIP::eventgroup_id_t(0x4001)));
            CommonAPI::SomeIP::StubAdapter::registerEvent(CommonAPI::SomeIP::event_id_t(0xc01c), itsEventGroups, CommonAPI::SomeIP::event_type_e::ET_FIELD, CommonAPI::SomeIP::reliability_type_e::RT_UNRELIABLE);
            fireHMIFOTA_InfoAttributeChanged(std::dynamic_pointer_cast< ::v0::VHAL::VHAL_LIFECYCLEStub>(_stub)->getHMIFOTA_InfoAttribute(itsClient));
        }

    }

    // Register/Unregister event handlers for selective broadcasts
    void registerSelectiveEventHandlers();
    void unregisterSelectiveEventHandlers();

};

/*
 * description: 
 * ecall status for IVI
 */
template <typename _Stub, typename... _Stubs>
void VHAL_LIFECYCLESomeIPStubAdapterInternal<_Stub, _Stubs...>::fireEcallStatusAttributeChanged(const uint8_t &_value) {
    CommonAPI::Deployable< uint8_t, CommonAPI::SomeIP::IntegerDeployment<uint8_t>> deployedValue(_value, static_cast< CommonAPI::SomeIP::IntegerDeployment<uint8_t>* >(nullptr));
    CommonAPI::SomeIP::StubEventHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                uint8_t,
                CommonAPI::SomeIP::IntegerDeployment<uint8_t>
            >
            >
    >::sendEvent(
        *this,
        CommonAPI::SomeIP::event_id_t(0xbfff),
        false,
        deployedValue
    );
}

template <typename _Stub, typename... _Stubs>
void VHAL_LIFECYCLESomeIPStubAdapterInternal<_Stub, _Stubs...>::firePrivacy_ModeAttributeChanged(const uint32_t &_value) {
    CommonAPI::Deployable< uint32_t, CommonAPI::SomeIP::IntegerDeployment<uint32_t>> deployedValue(_value, static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr));
    CommonAPI::SomeIP::StubEventHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                uint32_t,
                CommonAPI::SomeIP::IntegerDeployment<uint32_t>
            >
            >
    >::sendEvent(
        *this,
        CommonAPI::SomeIP::event_id_t(0xc003),
        false,
        deployedValue
    );
}

template <typename _Stub, typename... _Stubs>
void VHAL_LIFECYCLESomeIPStubAdapterInternal<_Stub, _Stubs...>::fireFlash_ResultAttributeChanged(const uint32_t &_value) {
    CommonAPI::Deployable< uint32_t, CommonAPI::SomeIP::IntegerDeployment<uint32_t>> deployedValue(_value, static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr));
    CommonAPI::SomeIP::StubEventHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                uint32_t,
                CommonAPI::SomeIP::IntegerDeployment<uint32_t>
            >
            >
    >::sendEvent(
        *this,
        CommonAPI::SomeIP::event_id_t(0xc006),
        false,
        deployedValue
    );
}

template <typename _Stub, typename... _Stubs>
void VHAL_LIFECYCLESomeIPStubAdapterInternal<_Stub, _Stubs...>::fireXCallHmiControlAttributeChanged(const uint32_t &_value) {
    CommonAPI::Deployable< uint32_t, CommonAPI::SomeIP::IntegerDeployment<uint32_t>> deployedValue(_value, static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr));
    CommonAPI::SomeIP::StubEventHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                uint32_t,
                CommonAPI::SomeIP::IntegerDeployment<uint32_t>
            >
            >
    >::sendEvent(
        *this,
        CommonAPI::SomeIP::event_id_t(0xc004),
        false,
        deployedValue
    );
}

template <typename _Stub, typename... _Stubs>
void VHAL_LIFECYCLESomeIPStubAdapterInternal<_Stub, _Stubs...>::fireHMI_FOTA_Update_historyAttributeChanged(const std::string &_value) {
    CommonAPI::Deployable< std::string, CommonAPI::SomeIP::StringDeployment> deployedValue(_value, static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr));
    CommonAPI::SomeIP::StubEventHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                std::string,
                CommonAPI::SomeIP::StringDeployment
            >
            >
    >::sendEvent(
        *this,
        CommonAPI::SomeIP::event_id_t(0xc00b),
        false,
        deployedValue
    );
}

template <typename _Stub, typename... _Stubs>
void VHAL_LIFECYCLESomeIPStubAdapterInternal<_Stub, _Stubs...>::fireHMI_FOTA_pending_updatesAttributeChanged(const std::string &_value) {
    CommonAPI::Deployable< std::string, CommonAPI::SomeIP::StringDeployment> deployedValue(_value, static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr));
    CommonAPI::SomeIP::StubEventHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                std::string,
                CommonAPI::SomeIP::StringDeployment
            >
            >
    >::sendEvent(
        *this,
        CommonAPI::SomeIP::event_id_t(0xc00c),
        false,
        deployedValue
    );
}

template <typename _Stub, typename... _Stubs>
void VHAL_LIFECYCLESomeIPStubAdapterInternal<_Stub, _Stubs...>::fireFOTA_Installation_Finished_with_User_ConformationAttributeChanged(const std::string &_value) {
    CommonAPI::Deployable< std::string, CommonAPI::SomeIP::StringDeployment> deployedValue(_value, static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr));
    CommonAPI::SomeIP::StubEventHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                std::string,
                CommonAPI::SomeIP::StringDeployment
            >
            >
    >::sendEvent(
        *this,
        CommonAPI::SomeIP::event_id_t(0xc007),
        false,
        deployedValue
    );
}

template <typename _Stub, typename... _Stubs>
void VHAL_LIFECYCLESomeIPStubAdapterInternal<_Stub, _Stubs...>::fireFOTA_Start_InstallationAttributeChanged(const std::string &_value) {
    CommonAPI::Deployable< std::string, CommonAPI::SomeIP::StringDeployment> deployedValue(_value, static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr));
    CommonAPI::SomeIP::StubEventHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                std::string,
                CommonAPI::SomeIP::StringDeployment
            >
            >
    >::sendEvent(
        *this,
        CommonAPI::SomeIP::event_id_t(0xc008),
        false,
        deployedValue
    );
}

template <typename _Stub, typename... _Stubs>
void VHAL_LIFECYCLESomeIPStubAdapterInternal<_Stub, _Stubs...>::fireFOTA_Check_for_UpdatesAttributeChanged(const std::string &_value) {
    CommonAPI::Deployable< std::string, CommonAPI::SomeIP::StringDeployment> deployedValue(_value, static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr));
    CommonAPI::SomeIP::StubEventHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                std::string,
                CommonAPI::SomeIP::StringDeployment
            >
            >
    >::sendEvent(
        *this,
        CommonAPI::SomeIP::event_id_t(0xc009),
        false,
        deployedValue
    );
}

template <typename _Stub, typename... _Stubs>
void VHAL_LIFECYCLESomeIPStubAdapterInternal<_Stub, _Stubs...>::fireFOTA_Update_DismissedAttributeChanged(const std::string &_value) {
    CommonAPI::Deployable< std::string, CommonAPI::SomeIP::StringDeployment> deployedValue(_value, static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr));
    CommonAPI::SomeIP::StubEventHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                std::string,
                CommonAPI::SomeIP::StringDeployment
            >
            >
    >::sendEvent(
        *this,
        CommonAPI::SomeIP::event_id_t(0xc013),
        false,
        deployedValue
    );
}

template <typename _Stub, typename... _Stubs>
void VHAL_LIFECYCLESomeIPStubAdapterInternal<_Stub, _Stubs...>::fireFOTA_Schedule_UpdateAttributeChanged(const std::string &_value) {
    CommonAPI::Deployable< std::string, CommonAPI::SomeIP::StringDeployment> deployedValue(_value, static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr));
    CommonAPI::SomeIP::StubEventHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                std::string,
                CommonAPI::SomeIP::StringDeployment
            >
            >
    >::sendEvent(
        *this,
        CommonAPI::SomeIP::event_id_t(0xc014),
        false,
        deployedValue
    );
}

template <typename _Stub, typename... _Stubs>
void VHAL_LIFECYCLESomeIPStubAdapterInternal<_Stub, _Stubs...>::fireFOTA_WhatsNew_DetailsAttributeChanged(const std::string &_value) {
    CommonAPI::Deployable< std::string, CommonAPI::SomeIP::StringDeployment> deployedValue(_value, static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr));
    CommonAPI::SomeIP::StubEventHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                std::string,
                CommonAPI::SomeIP::StringDeployment
            >
            >
    >::sendEvent(
        *this,
        CommonAPI::SomeIP::event_id_t(0xc012),
        false,
        deployedValue
    );
}

template <typename _Stub, typename... _Stubs>
void VHAL_LIFECYCLESomeIPStubAdapterInternal<_Stub, _Stubs...>::fireActive_phone_callAttributeChanged(const uint32_t &_value) {
    CommonAPI::Deployable< uint32_t, CommonAPI::SomeIP::IntegerDeployment<uint32_t>> deployedValue(_value, static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr));
    CommonAPI::SomeIP::StubEventHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                uint32_t,
                CommonAPI::SomeIP::IntegerDeployment<uint32_t>
            >
            >
    >::sendEvent(
        *this,
        CommonAPI::SomeIP::event_id_t(0xc00d),
        false,
        deployedValue
    );
}

template <typename _Stub, typename... _Stubs>
void VHAL_LIFECYCLESomeIPStubAdapterInternal<_Stub, _Stubs...>::fireSIVIDriverLockoutStsAttributeChanged(const uint32_t &_value) {
    CommonAPI::Deployable< uint32_t, CommonAPI::SomeIP::IntegerDeployment<uint32_t>> deployedValue(_value, static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr));
    CommonAPI::SomeIP::StubEventHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                uint32_t,
                CommonAPI::SomeIP::IntegerDeployment<uint32_t>
            >
            >
    >::sendEvent(
        *this,
        CommonAPI::SomeIP::event_id_t(0xc00e),
        false,
        deployedValue
    );
}

template <typename _Stub, typename... _Stubs>
void VHAL_LIFECYCLESomeIPStubAdapterInternal<_Stub, _Stubs...>::fireUIN_Trigger_from_HMIAttributeChanged(const bool &_value) {
    CommonAPI::SomeIP::StubEventHelper<
        CommonAPI::SomeIP::SerializableArguments<
            bool
            >
    >::sendEvent(
        *this,
        CommonAPI::SomeIP::event_id_t(0xc015),
        false,
        _value
    );
}

template <typename _Stub, typename... _Stubs>
void VHAL_LIFECYCLESomeIPStubAdapterInternal<_Stub, _Stubs...>::fireBTCallHMI_StatusAttributeChanged(const uint32_t &_value) {
    CommonAPI::Deployable< uint32_t, CommonAPI::SomeIP::IntegerDeployment<uint32_t>> deployedValue(_value, static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr));
    CommonAPI::SomeIP::StubEventHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                uint32_t,
                CommonAPI::SomeIP::IntegerDeployment<uint32_t>
            >
            >
    >::sendEvent(
        *this,
        CommonAPI::SomeIP::event_id_t(0xc00f),
        false,
        deployedValue
    );
}

template <typename _Stub, typename... _Stubs>
void VHAL_LIFECYCLESomeIPStubAdapterInternal<_Stub, _Stubs...>::fireBTDeviceAttached_StatusAttributeChanged(const uint32_t &_value) {
    CommonAPI::Deployable< uint32_t, CommonAPI::SomeIP::IntegerDeployment<uint32_t>> deployedValue(_value, static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr));
    CommonAPI::SomeIP::StubEventHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                uint32_t,
                CommonAPI::SomeIP::IntegerDeployment<uint32_t>
            >
            >
    >::sendEvent(
        *this,
        CommonAPI::SomeIP::event_id_t(0xc010),
        false,
        deployedValue
    );
}

template <typename _Stub, typename... _Stubs>
void VHAL_LIFECYCLESomeIPStubAdapterInternal<_Stub, _Stubs...>::fireBTTransferTime_DurationAttributeChanged(const uint32_t &_value) {
    CommonAPI::Deployable< uint32_t, CommonAPI::SomeIP::IntegerDeployment<uint32_t>> deployedValue(_value, static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr));
    CommonAPI::SomeIP::StubEventHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                uint32_t,
                CommonAPI::SomeIP::IntegerDeployment<uint32_t>
            >
            >
    >::sendEvent(
        *this,
        CommonAPI::SomeIP::event_id_t(0xc011),
        false,
        deployedValue
    );
}

template <typename _Stub, typename... _Stubs>
void VHAL_LIFECYCLESomeIPStubAdapterInternal<_Stub, _Stubs...>::fireAOSP_Flash_ResultAttributeChanged(const std::string &_value) {
    CommonAPI::Deployable< std::string, CommonAPI::SomeIP::StringDeployment> deployedValue(_value, static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr));
    CommonAPI::SomeIP::StubEventHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                std::string,
                CommonAPI::SomeIP::StringDeployment
            >
            >
    >::sendEvent(
        *this,
        CommonAPI::SomeIP::event_id_t(0xc017),
        false,
        deployedValue
    );
}

template <typename _Stub, typename... _Stubs>
void VHAL_LIFECYCLESomeIPStubAdapterInternal<_Stub, _Stubs...>::fireHMI_Status_SWUpdateAttributeChanged(const uint32_t &_value) {
    CommonAPI::Deployable< uint32_t, CommonAPI::SomeIP::IntegerDeployment<uint32_t>> deployedValue(_value, static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr));
    CommonAPI::SomeIP::StubEventHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                uint32_t,
                CommonAPI::SomeIP::IntegerDeployment<uint32_t>
            >
            >
    >::sendEvent(
        *this,
        CommonAPI::SomeIP::event_id_t(0xc018),
        false,
        deployedValue
    );
}

template <typename _Stub, typename... _Stubs>
void VHAL_LIFECYCLESomeIPStubAdapterInternal<_Stub, _Stubs...>::fireIncomingPhoneCallAttributeChanged(const uint32_t &_value) {
    CommonAPI::Deployable< uint32_t, CommonAPI::SomeIP::IntegerDeployment<uint32_t>> deployedValue(_value, static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr));
    CommonAPI::SomeIP::StubEventHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                uint32_t,
                CommonAPI::SomeIP::IntegerDeployment<uint32_t>
            >
            >
    >::sendEvent(
        *this,
        CommonAPI::SomeIP::event_id_t(0xc019),
        false,
        deployedValue
    );
}

template <typename _Stub, typename... _Stubs>
void VHAL_LIFECYCLESomeIPStubAdapterInternal<_Stub, _Stubs...>::fireOutgoingPhoneCallAttributeChanged(const uint32_t &_value) {
    CommonAPI::Deployable< uint32_t, CommonAPI::SomeIP::IntegerDeployment<uint32_t>> deployedValue(_value, static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr));
    CommonAPI::SomeIP::StubEventHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                uint32_t,
                CommonAPI::SomeIP::IntegerDeployment<uint32_t>
            >
            >
    >::sendEvent(
        *this,
        CommonAPI::SomeIP::event_id_t(0xc01a),
        false,
        deployedValue
    );
}

template <typename _Stub, typename... _Stubs>
void VHAL_LIFECYCLESomeIPStubAdapterInternal<_Stub, _Stubs...>::fireBtTransferAcceptanceAttributeChanged(const uint32_t &_value) {
    CommonAPI::Deployable< uint32_t, CommonAPI::SomeIP::IntegerDeployment<uint32_t>> deployedValue(_value, static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr));
    CommonAPI::SomeIP::StubEventHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                uint32_t,
                CommonAPI::SomeIP::IntegerDeployment<uint32_t>
            >
            >
    >::sendEvent(
        *this,
        CommonAPI::SomeIP::event_id_t(0xc01b),
        false,
        deployedValue
    );
}

template <typename _Stub, typename... _Stubs>
void VHAL_LIFECYCLESomeIPStubAdapterInternal<_Stub, _Stubs...>::fireHMIFOTA_InfoAttributeChanged(const std::string &_value) {
    CommonAPI::Deployable< std::string, CommonAPI::SomeIP::StringDeployment> deployedValue(_value, static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr));
    CommonAPI::SomeIP::StubEventHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                std::string,
                CommonAPI::SomeIP::StringDeployment
            >
            >
    >::sendEvent(
        *this,
        CommonAPI::SomeIP::event_id_t(0xc01c),
        false,
        deployedValue
    );
}

template <typename _Stub, typename... _Stubs>
void VHAL_LIFECYCLESomeIPStubAdapterInternal<_Stub, _Stubs...>::fireSend_UserXCallInput_TCUEvent(const uint32_t &_conf) {
    CommonAPI::Deployable< uint32_t, CommonAPI::SomeIP::IntegerDeployment<uint32_t>> deployed_conf(_conf, static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr));
    CommonAPI::SomeIP::StubEventHelper<CommonAPI::SomeIP::SerializableArguments<  CommonAPI::Deployable< uint32_t, CommonAPI::SomeIP::IntegerDeployment<uint32_t> > 
    >>
        ::sendEvent(
            *this,
            CommonAPI::SomeIP::event_id_t(0x84d0),
            false,
             deployed_conf 
    );
}

template <typename _Stub, typename... _Stubs>
void VHAL_LIFECYCLESomeIPStubAdapterInternal<_Stub, _Stubs...>::fireSend_Language_selectionEvent(const uint32_t &_conf) {
    CommonAPI::Deployable< uint32_t, CommonAPI::SomeIP::IntegerDeployment<uint32_t>> deployed_conf(_conf, static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr));
    CommonAPI::SomeIP::StubEventHelper<CommonAPI::SomeIP::SerializableArguments<  CommonAPI::Deployable< uint32_t, CommonAPI::SomeIP::IntegerDeployment<uint32_t> > 
    >>
        ::sendEvent(
            *this,
            CommonAPI::SomeIP::event_id_t(0x84d1),
            false,
             deployed_conf 
    );
}


template <typename _Stub, typename... _Stubs>
void VHAL_LIFECYCLESomeIPStubAdapterInternal<_Stub, _Stubs...>::registerSelectiveEventHandlers() {
}

template <typename _Stub, typename... _Stubs>
void VHAL_LIFECYCLESomeIPStubAdapterInternal<_Stub, _Stubs...>::unregisterSelectiveEventHandlers() {
}

template <typename _Stub = ::v0::VHAL::VHAL_LIFECYCLEStub, typename... _Stubs>
class VHAL_LIFECYCLESomeIPStubAdapter
    : public VHAL_LIFECYCLESomeIPStubAdapterInternal<_Stub, _Stubs...> {
public:
    VHAL_LIFECYCLESomeIPStubAdapter(const CommonAPI::SomeIP::Address &_address,
                                            const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection,
                                            const std::shared_ptr<CommonAPI::StubBase> &_stub)
        : CommonAPI::SomeIP::StubAdapter(_address, _connection),
          VHAL_LIFECYCLESomeIPStubAdapterInternal<_Stub, _Stubs...>(_address, _connection, _stub) {
    }
};

} // namespace VHAL
} // namespace v0

#endif // V0_VHAL_VHAL__LIFECYCLE_SOMEIP_STUB_ADAPTER_HPP_
