/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.0.v202012010850.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V0_IMICRO_SOC__DIAG_PROXY_HPP_
#define V0_IMICRO_SOC__DIAG_PROXY_HPP_

#include <v0/iMicro/SOC_DIAGProxyBase.hpp>


#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif


#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v0 {
namespace iMicro {

template <typename ... _AttributeExtensions>
class SOC_DIAGProxy
    : virtual public SOC_DIAG,
      virtual public SOC_DIAGProxyBase,
      virtual public _AttributeExtensions... {
public:
    SOC_DIAGProxy(std::shared_ptr<CommonAPI::Proxy> delegate);
    ~SOC_DIAGProxy();

    typedef SOC_DIAG InterfaceType;


    /**
     * Returns the CommonAPI address of the remote partner this proxy communicates with.
     */
    virtual const CommonAPI::Address &getAddress() const;

    /**
     * Returns true if the remote partner for this proxy is currently known to be available.
     */
    virtual bool isAvailable() const;

    /**
     * Returns true if the remote partner for this proxy is available.
     */
    virtual bool isAvailableBlocking() const;

    /**
     * Returns the wrapper class that is used to (de-)register for notifications about
     * the availability of the remote partner of this proxy.
     */
    virtual CommonAPI::ProxyStatusEvent& getProxyStatusEvent();

    /**
     * Returns the wrapper class that is used to access version information of the remote
     * partner of this proxy.
     */
    virtual CommonAPI::InterfaceVersionAttribute& getInterfaceVersionAttribute();

    virtual std::future<void> getCompletionFuture();

    /**
     * Calls SendEvent_DIAG_SendtoVuc with synchronous semantics.
     *
     * All const parameters are input parameters to this method.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void SendEvent_DIAG_SendtoVuc(::iMicro::iMicroStructs::diag_message_type _DIAG_SendtoVuc, CommonAPI::CallStatus &_internalCallStatus, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls SendEvent_DIAG_SendtoVuc with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> SendEvent_DIAG_SendtoVucAsync(const ::iMicro::iMicroStructs::diag_message_type &_DIAG_SendtoVuc, SendEvent_DIAG_SendtoVucAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls SendEvent_SelfTestMode_Start with synchronous semantics.
     *
     * All const parameters are input parameters to this method.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void SendEvent_SelfTestMode_Start(uint8_t _SelfTestMode_Start, CommonAPI::CallStatus &_internalCallStatus, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls SendEvent_SelfTestMode_Start with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> SendEvent_SelfTestMode_StartAsync(const uint8_t &_SelfTestMode_Start, SendEvent_SelfTestMode_StartAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls SendEvent_DIAG_Wakeup_EventStatus with synchronous semantics.
     *
     * All const parameters are input parameters to this method.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void SendEvent_DIAG_Wakeup_EventStatus(::iMicro::iMicroStructs::diag_wakeup_message_type _DIAG_Wakeup_EventStatus, CommonAPI::CallStatus &_internalCallStatus, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls SendEvent_DIAG_Wakeup_EventStatus with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> SendEvent_DIAG_Wakeup_EventStatusAsync(const ::iMicro::iMicroStructs::diag_wakeup_message_type &_DIAG_Wakeup_EventStatus, SendEvent_DIAG_Wakeup_EventStatusAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls GetEvent_DIAG_SendtoModem with synchronous semantics.
     *
     * All non-const parameters will be filled with the returned values.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void GetEvent_DIAG_SendtoModem(CommonAPI::CallStatus &_internalCallStatus, ::iMicro::iMicroStructs::diag_message_type &_DIAG_SendtoModem, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls GetEvent_DIAG_SendtoModem with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> GetEvent_DIAG_SendtoModemAsync(GetEvent_DIAG_SendtoModemAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Returns the wrapper class that provides access to the broadcast SignalEvent_DIAG_SendtoModem.
     */
    virtual SignalEvent_DIAG_SendtoModemEvent& getSignalEvent_DIAG_SendtoModemEvent() {
        return delegate_->getSignalEvent_DIAG_SendtoModemEvent();
    }
    /**
     * Calls GetEvent_SelfTestMode_DTCList with synchronous semantics.
     *
     * All non-const parameters will be filled with the returned values.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void GetEvent_SelfTestMode_DTCList(CommonAPI::CallStatus &_internalCallStatus, ::iMicro::iMicroStructs::SelfTestMode_DTCList_type &_SelfTestMode_DTCList, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls GetEvent_SelfTestMode_DTCList with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> GetEvent_SelfTestMode_DTCListAsync(GetEvent_SelfTestMode_DTCListAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Returns the wrapper class that provides access to the broadcast SignalEvent_SelfTestMode_DTCList.
     */
    virtual SignalEvent_SelfTestMode_DTCListEvent& getSignalEvent_SelfTestMode_DTCListEvent() {
        return delegate_->getSignalEvent_SelfTestMode_DTCListEvent();
    }
    /**
     * Returns the wrapper class that provides access to the broadcast SignalResponse_DIAG_Wakeup_SetEventStatusIMicro.
     */
    virtual SignalResponse_DIAG_Wakeup_SetEventStatusIMicroEvent& getSignalResponse_DIAG_Wakeup_SetEventStatusIMicroEvent() {
        return delegate_->getSignalResponse_DIAG_Wakeup_SetEventStatusIMicroEvent();
    }



 private:
    std::shared_ptr< SOC_DIAGProxyBase> delegate_;
};

typedef SOC_DIAGProxy<> SOC_DIAGProxyDefault;


//
// SOC_DIAGProxy Implementation
//
template <typename ... _AttributeExtensions>
SOC_DIAGProxy<_AttributeExtensions...>::SOC_DIAGProxy(std::shared_ptr<CommonAPI::Proxy> delegate):
        _AttributeExtensions(*(std::dynamic_pointer_cast< SOC_DIAGProxyBase>(delegate)))...,
        delegate_(std::dynamic_pointer_cast< SOC_DIAGProxyBase>(delegate)) {
}

template <typename ... _AttributeExtensions>
SOC_DIAGProxy<_AttributeExtensions...>::~SOC_DIAGProxy() {
}

template <typename ... _AttributeExtensions>
void SOC_DIAGProxy<_AttributeExtensions...>::SendEvent_DIAG_SendtoVuc(::iMicro::iMicroStructs::diag_message_type _DIAG_SendtoVuc, CommonAPI::CallStatus &_internalCallStatus, const CommonAPI::CallInfo *_info) {
    delegate_->SendEvent_DIAG_SendtoVuc(_DIAG_SendtoVuc, _internalCallStatus, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> SOC_DIAGProxy<_AttributeExtensions...>::SendEvent_DIAG_SendtoVucAsync(const ::iMicro::iMicroStructs::diag_message_type &_DIAG_SendtoVuc, SendEvent_DIAG_SendtoVucAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    return delegate_->SendEvent_DIAG_SendtoVucAsync(_DIAG_SendtoVuc, _callback, _info);
}
template <typename ... _AttributeExtensions>
void SOC_DIAGProxy<_AttributeExtensions...>::SendEvent_SelfTestMode_Start(uint8_t _SelfTestMode_Start, CommonAPI::CallStatus &_internalCallStatus, const CommonAPI::CallInfo *_info) {
    delegate_->SendEvent_SelfTestMode_Start(_SelfTestMode_Start, _internalCallStatus, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> SOC_DIAGProxy<_AttributeExtensions...>::SendEvent_SelfTestMode_StartAsync(const uint8_t &_SelfTestMode_Start, SendEvent_SelfTestMode_StartAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    return delegate_->SendEvent_SelfTestMode_StartAsync(_SelfTestMode_Start, _callback, _info);
}
template <typename ... _AttributeExtensions>
void SOC_DIAGProxy<_AttributeExtensions...>::SendEvent_DIAG_Wakeup_EventStatus(::iMicro::iMicroStructs::diag_wakeup_message_type _DIAG_Wakeup_EventStatus, CommonAPI::CallStatus &_internalCallStatus, const CommonAPI::CallInfo *_info) {
    delegate_->SendEvent_DIAG_Wakeup_EventStatus(_DIAG_Wakeup_EventStatus, _internalCallStatus, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> SOC_DIAGProxy<_AttributeExtensions...>::SendEvent_DIAG_Wakeup_EventStatusAsync(const ::iMicro::iMicroStructs::diag_wakeup_message_type &_DIAG_Wakeup_EventStatus, SendEvent_DIAG_Wakeup_EventStatusAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    return delegate_->SendEvent_DIAG_Wakeup_EventStatusAsync(_DIAG_Wakeup_EventStatus, _callback, _info);
}
template <typename ... _AttributeExtensions>
void SOC_DIAGProxy<_AttributeExtensions...>::GetEvent_DIAG_SendtoModem(CommonAPI::CallStatus &_internalCallStatus, ::iMicro::iMicroStructs::diag_message_type &_DIAG_SendtoModem, const CommonAPI::CallInfo *_info) {
    delegate_->GetEvent_DIAG_SendtoModem(_internalCallStatus, _DIAG_SendtoModem, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> SOC_DIAGProxy<_AttributeExtensions...>::GetEvent_DIAG_SendtoModemAsync(GetEvent_DIAG_SendtoModemAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    return delegate_->GetEvent_DIAG_SendtoModemAsync(_callback, _info);
}
template <typename ... _AttributeExtensions>
void SOC_DIAGProxy<_AttributeExtensions...>::GetEvent_SelfTestMode_DTCList(CommonAPI::CallStatus &_internalCallStatus, ::iMicro::iMicroStructs::SelfTestMode_DTCList_type &_SelfTestMode_DTCList, const CommonAPI::CallInfo *_info) {
    delegate_->GetEvent_SelfTestMode_DTCList(_internalCallStatus, _SelfTestMode_DTCList, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> SOC_DIAGProxy<_AttributeExtensions...>::GetEvent_SelfTestMode_DTCListAsync(GetEvent_SelfTestMode_DTCListAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    return delegate_->GetEvent_SelfTestMode_DTCListAsync(_callback, _info);
}

template <typename ... _AttributeExtensions>
const CommonAPI::Address &SOC_DIAGProxy<_AttributeExtensions...>::getAddress() const {
    return delegate_->getAddress();
}

template <typename ... _AttributeExtensions>
bool SOC_DIAGProxy<_AttributeExtensions...>::isAvailable() const {
    return delegate_->isAvailable();
}

template <typename ... _AttributeExtensions>
bool SOC_DIAGProxy<_AttributeExtensions...>::isAvailableBlocking() const {
    return delegate_->isAvailableBlocking();
}

template <typename ... _AttributeExtensions>
CommonAPI::ProxyStatusEvent& SOC_DIAGProxy<_AttributeExtensions...>::getProxyStatusEvent() {
    return delegate_->getProxyStatusEvent();
}

template <typename ... _AttributeExtensions>
CommonAPI::InterfaceVersionAttribute& SOC_DIAGProxy<_AttributeExtensions...>::getInterfaceVersionAttribute() {
    return delegate_->getInterfaceVersionAttribute();
}


template <typename ... _AttributeExtensions>
std::future<void> SOC_DIAGProxy<_AttributeExtensions...>::getCompletionFuture() {
    return delegate_->getCompletionFuture();
}

} // namespace iMicro
} // namespace v0



// Compatibility
namespace v0_1 = v0;

#endif // V0_IMICRO_SOC__DIAG_PROXY_HPP_
