/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.0.v202012010850.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V0_IMICRO_SOC__System_STUB_DEFAULT_HPP_
#define V0_IMICRO_SOC__System_STUB_DEFAULT_HPP_


#include <CommonAPI/Export.hpp>

#include <v0/iMicro/SOC_SystemStub.hpp>
#include <cassert>
#include <sstream>

# if defined(_MSC_VER)
#  if _MSC_VER >= 1300
/*
 * Diamond inheritance is used for the CommonAPI::Proxy base class.
 * The Microsoft compiler put warning (C4250) using a desired c++ feature: "Delegating to a sister class"
 * A powerful technique that arises from using virtual inheritance is to delegate a method from a class in another class
 * by using a common abstract base class. This is also called cross delegation.
 */
#    pragma warning( disable : 4250 )
#  endif
# endif

namespace v0 {
namespace iMicro {

/**
 * Provides a default implementation for SOC_SystemStubRemoteEvent and
 * SOC_SystemStub. Method callbacks have an empty implementation,
 * remote set calls on attributes will always change the value of the attribute
 * to the one received.
 *
 * Override this stub if you only want to provide a subset of the functionality
 * that would be defined for this service, and/or if you do not need any non-default
 * behaviour.
 */
class COMMONAPI_EXPORT_CLASS_EXPLICIT SOC_SystemStubDefault
    : public virtual SOC_SystemStub {
public:
    COMMONAPI_EXPORT SOC_SystemStubDefault()
        : remoteEventHandler_(this),
          interfaceVersion_(SOC_System::getInterfaceVersion()) {
    }

    COMMONAPI_EXPORT const CommonAPI::Version& getInterfaceVersion(std::shared_ptr<CommonAPI::ClientId> _client) {
        (void)_client;
        return interfaceVersion_;
    }

    COMMONAPI_EXPORT SOC_SystemStubRemoteEvent* initStubAdapter(const std::shared_ptr< SOC_SystemStubAdapter> &_adapter) {
        CommonAPI::Stub<SOC_SystemStubAdapter, SOC_SystemStubRemoteEvent>::stubAdapter_ = _adapter;
        return &remoteEventHandler_;
    }

    COMMONAPI_EXPORT virtual void SendEvent_NAD_SetTime(const std::shared_ptr<CommonAPI::ClientId> _client, ::iMicro::iMicroStructs::GNSSTime_type _NAD_SetTime, SendEvent_NAD_SetTimeReply_t _reply) {
        (void)_client;
        (void)_NAD_SetTime;
        _reply();
    }
    COMMONAPI_EXPORT virtual void SendCommand_Ask_RTCTime(const std::shared_ptr<CommonAPI::ClientId> _client, uint8_t _Ask_RTCTime) {
        (void)_client;
        (void)_Ask_RTCTime;
    }
    COMMONAPI_EXPORT virtual void fireSignalResponse_Response_RTCTimeEvent(const ::iMicro::iMicroStructs::GNSSTime_type &_Response_RTCTime) {
        SOC_SystemStub::fireSignalResponse_Response_RTCTimeEvent(_Response_RTCTime);
    }


protected:
    class COMMONAPI_EXPORT_CLASS_EXPLICIT RemoteEventHandler: public virtual SOC_SystemStubRemoteEvent {
    public:
        COMMONAPI_EXPORT RemoteEventHandler(SOC_SystemStubDefault *_defaultStub)
            : 
              defaultStub_(_defaultStub) {
        }


    private:
        SOC_SystemStubDefault *defaultStub_;
    };
protected:
    SOC_SystemStubDefault::RemoteEventHandler remoteEventHandler_;

private:


    CommonAPI::Version interfaceVersion_;
};

} // namespace iMicro
} // namespace v0


// Compatibility
namespace v0_1 = v0;

#endif // V0_IMICRO_SOC__System_STUB_DEFAULT
