/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.0.v202012010944.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
#ifndef V0_IMICRO_SOC__SAM_SOMEIP_STUB_ADAPTER_HPP_
#define V0_IMICRO_SOC__SAM_SOMEIP_STUB_ADAPTER_HPP_

#include <v0/iMicro/SOC_SAMStub.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/SomeIP/AddressTranslator.hpp>
#include <CommonAPI/SomeIP/StubAdapterHelper.hpp>
#include <CommonAPI/SomeIP/StubAdapter.hpp>
#include <CommonAPI/SomeIP/Factory.hpp>
#include <CommonAPI/SomeIP/Types.hpp>
#include <CommonAPI/SomeIP/Constants.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v0 {
namespace iMicro {

template <typename _Stub = ::v0::iMicro::SOC_SAMStub, typename... _Stubs>
class SOC_SAMSomeIPStubAdapterInternal
    : public virtual SOC_SAMStubAdapter,
      public CommonAPI::SomeIP::StubAdapterHelper< _Stub, _Stubs...>,
      public std::enable_shared_from_this< SOC_SAMSomeIPStubAdapterInternal<_Stub, _Stubs...>>
{
public:
    typedef CommonAPI::SomeIP::StubAdapterHelper< _Stub, _Stubs...> SOC_SAMSomeIPStubAdapterHelper;

    ~SOC_SAMSomeIPStubAdapterInternal() {
        deactivateManagedInstances();
        SOC_SAMSomeIPStubAdapterHelper::deinit();
    }

    void deactivateManagedInstances() {}
    
    CommonAPI::SomeIP::GetAttributeStubDispatcher<
        ::v0::iMicro::SOC_SAMStub,
        CommonAPI::Version
    > getSOC_SAMInterfaceVersionStubDispatcher;

    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v0::iMicro::SOC_SAMStub,
        std::tuple< uint32_t>,
        std::tuple< >,
        std::tuple< CommonAPI::SomeIP::IntegerDeployment<uint32_t>>,
        std::tuple< >
    > sendEvent_DLT_ConfigurationStubDispatcher;
    
    SOC_SAMSomeIPStubAdapterInternal(
        const CommonAPI::SomeIP::Address &_address,
        const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection,
        const std::shared_ptr<CommonAPI::StubBase> &_stub):
        CommonAPI::SomeIP::StubAdapter(_address, _connection),
        SOC_SAMSomeIPStubAdapterHelper(
            _address,
            _connection,
            std::dynamic_pointer_cast< SOC_SAMStub>(_stub)),
        getSOC_SAMInterfaceVersionStubDispatcher(&SOC_SAMStub::lockInterfaceVersionAttribute, &SOC_SAMStub::getInterfaceVersion, false, true),
        sendEvent_DLT_ConfigurationStubDispatcher(
            &SOC_SAMStub::SendEvent_DLT_Configuration,
            false,
            _stub->hasElement(0),
            std::make_tuple(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr)),
            std::make_tuple())
        
    {
        SOC_SAMSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x4c) }, &sendEvent_DLT_ConfigurationStubDispatcher );
        // Provided events/fields
    }

    // Register/Unregister event handlers for selective broadcasts
    void registerSelectiveEventHandlers();
    void unregisterSelectiveEventHandlers();

};


template <typename _Stub, typename... _Stubs>
void SOC_SAMSomeIPStubAdapterInternal<_Stub, _Stubs...>::registerSelectiveEventHandlers() {
}

template <typename _Stub, typename... _Stubs>
void SOC_SAMSomeIPStubAdapterInternal<_Stub, _Stubs...>::unregisterSelectiveEventHandlers() {
}

template <typename _Stub = ::v0::iMicro::SOC_SAMStub, typename... _Stubs>
class SOC_SAMSomeIPStubAdapter
    : public SOC_SAMSomeIPStubAdapterInternal<_Stub, _Stubs...> {
public:
    SOC_SAMSomeIPStubAdapter(const CommonAPI::SomeIP::Address &_address,
                                            const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection,
                                            const std::shared_ptr<CommonAPI::StubBase> &_stub)
        : CommonAPI::SomeIP::StubAdapter(_address, _connection),
          SOC_SAMSomeIPStubAdapterInternal<_Stub, _Stubs...>(_address, _connection, _stub) {
    }
};

} // namespace iMicro
} // namespace v0

#endif // V0_IMICRO_SOC__SAM_SOMEIP_STUB_ADAPTER_HPP_
