/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.0.v202012010850.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V0_IMICRO_SOC__Button_STUB_DEFAULT_HPP_
#define V0_IMICRO_SOC__Button_STUB_DEFAULT_HPP_


#include <CommonAPI/Export.hpp>

#include <v0/iMicro/SOC_ButtonStub.hpp>
#include <cassert>
#include <sstream>

# if defined(_MSC_VER)
#  if _MSC_VER >= 1300
/*
 * Diamond inheritance is used for the CommonAPI::Proxy base class.
 * The Microsoft compiler put warning (C4250) using a desired c++ feature: "Delegating to a sister class"
 * A powerful technique that arises from using virtual inheritance is to delegate a method from a class in another class
 * by using a common abstract base class. This is also called cross delegation.
 */
#    pragma warning( disable : 4250 )
#  endif
# endif

namespace v0 {
namespace iMicro {

/**
 * Provides a default implementation for SOC_ButtonStubRemoteEvent and
 * SOC_ButtonStub. Method callbacks have an empty implementation,
 * remote set calls on attributes will always change the value of the attribute
 * to the one received.
 *
 * Override this stub if you only want to provide a subset of the functionality
 * that would be defined for this service, and/or if you do not need any non-default
 * behaviour.
 */
class COMMONAPI_EXPORT_CLASS_EXPLICIT SOC_ButtonStubDefault
    : public virtual SOC_ButtonStub {
public:
    COMMONAPI_EXPORT SOC_ButtonStubDefault()
        : remoteEventHandler_(this),
          interfaceVersion_(SOC_Button::getInterfaceVersion()) {
    }

    COMMONAPI_EXPORT const CommonAPI::Version& getInterfaceVersion(std::shared_ptr<CommonAPI::ClientId> _client) {
        (void)_client;
        return interfaceVersion_;
    }

    COMMONAPI_EXPORT SOC_ButtonStubRemoteEvent* initStubAdapter(const std::shared_ptr< SOC_ButtonStubAdapter> &_adapter) {
        CommonAPI::Stub<SOC_ButtonStubAdapter, SOC_ButtonStubRemoteEvent>::stubAdapter_ = _adapter;
        return &remoteEventHandler_;
    }

    COMMONAPI_EXPORT virtual void SendCommand_Button_req_status(const std::shared_ptr<CommonAPI::ClientId> _client, ::iMicro::iMicroTypes::button_id_enum _Button_req_status) {
        (void)_client;
        (void)_Button_req_status;
    }
    COMMONAPI_EXPORT virtual void GetEvent_Button_pressEvent(const std::shared_ptr<CommonAPI::ClientId> _client, GetEvent_Button_pressEventReply_t _reply) {
        (void)_client;
        ::iMicro::iMicroStructs::button_status_type Button_pressEvent = {};
        _reply(Button_pressEvent);
    }
    COMMONAPI_EXPORT virtual void fireSignalCommand_Button_pressEventEvent(const ::iMicro::iMicroStructs::button_status_type &_Button_pressEvent) {
        SOC_ButtonStub::fireSignalCommand_Button_pressEventEvent(_Button_pressEvent);
    }
    COMMONAPI_EXPORT virtual void fireSignalResponse_Button_StatusEvent(const ::iMicro::iMicroStructs::button_status_type &_Button_Status) {
        SOC_ButtonStub::fireSignalResponse_Button_StatusEvent(_Button_Status);
    }


protected:
    class COMMONAPI_EXPORT_CLASS_EXPLICIT RemoteEventHandler: public virtual SOC_ButtonStubRemoteEvent {
    public:
        COMMONAPI_EXPORT RemoteEventHandler(SOC_ButtonStubDefault *_defaultStub)
            : 
              defaultStub_(_defaultStub) {
        }


    private:
        SOC_ButtonStubDefault *defaultStub_;
    };
protected:
    SOC_ButtonStubDefault::RemoteEventHandler remoteEventHandler_;

private:


    CommonAPI::Version interfaceVersion_;
};

} // namespace iMicro
} // namespace v0


// Compatibility
namespace v0_1 = v0;

#endif // V0_IMICRO_SOC__Button_STUB_DEFAULT
