/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.0.v202012010850.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V0_IMICRO_SOC__MUTE_PROXY_HPP_
#define V0_IMICRO_SOC__MUTE_PROXY_HPP_

#include <v0/iMicro/SOC_MUTEProxyBase.hpp>


#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif


#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v0 {
namespace iMicro {

template <typename ... _AttributeExtensions>
class SOC_MUTEProxy
    : virtual public SOC_MUTE,
      virtual public SOC_MUTEProxyBase,
      virtual public _AttributeExtensions... {
public:
    SOC_MUTEProxy(std::shared_ptr<CommonAPI::Proxy> delegate);
    ~SOC_MUTEProxy();

    typedef SOC_MUTE InterfaceType;


    /**
     * Returns the CommonAPI address of the remote partner this proxy communicates with.
     */
    virtual const CommonAPI::Address &getAddress() const;

    /**
     * Returns true if the remote partner for this proxy is currently known to be available.
     */
    virtual bool isAvailable() const;

    /**
     * Returns true if the remote partner for this proxy is available.
     */
    virtual bool isAvailableBlocking() const;

    /**
     * Returns the wrapper class that is used to (de-)register for notifications about
     * the availability of the remote partner of this proxy.
     */
    virtual CommonAPI::ProxyStatusEvent& getProxyStatusEvent();

    /**
     * Returns the wrapper class that is used to access version information of the remote
     * partner of this proxy.
     */
    virtual CommonAPI::InterfaceVersionAttribute& getInterfaceVersionAttribute();

    virtual std::future<void> getCompletionFuture();

    /**
     * Calls SendCommand_Mute_enable with Fire&Forget semantics.
     *
     * All const parameters are input parameters to this method.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void SendCommand_Mute_enable(::iMicro::iMicroTypes::mute_enum _Mute_enable, CommonAPI::CallStatus &_internalCallStatus);
    /**
     * Calls SendCommand_Mute_reqStatus with Fire&Forget semantics.
     *
     * All const parameters are input parameters to this method.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void SendCommand_Mute_reqStatus(uint8_t _Mute_reqStatus, CommonAPI::CallStatus &_internalCallStatus);
    /**
     * Returns the wrapper class that provides access to the broadcast SignalResponse_Mute_status.
     */
    virtual SignalResponse_Mute_statusEvent& getSignalResponse_Mute_statusEvent() {
        return delegate_->getSignalResponse_Mute_statusEvent();
    }



 private:
    std::shared_ptr< SOC_MUTEProxyBase> delegate_;
};

typedef SOC_MUTEProxy<> SOC_MUTEProxyDefault;


//
// SOC_MUTEProxy Implementation
//
template <typename ... _AttributeExtensions>
SOC_MUTEProxy<_AttributeExtensions...>::SOC_MUTEProxy(std::shared_ptr<CommonAPI::Proxy> delegate):
        _AttributeExtensions(*(std::dynamic_pointer_cast< SOC_MUTEProxyBase>(delegate)))...,
        delegate_(std::dynamic_pointer_cast< SOC_MUTEProxyBase>(delegate)) {
}

template <typename ... _AttributeExtensions>
SOC_MUTEProxy<_AttributeExtensions...>::~SOC_MUTEProxy() {
}

template <typename ... _AttributeExtensions>
void SOC_MUTEProxy<_AttributeExtensions...>::SendCommand_Mute_enable(::iMicro::iMicroTypes::mute_enum _Mute_enable, CommonAPI::CallStatus &_internalCallStatus) {
    if (!_Mute_enable.validate()) {
        _internalCallStatus = CommonAPI::CallStatus::INVALID_VALUE;
        return;
    }
    delegate_->SendCommand_Mute_enable(_Mute_enable, _internalCallStatus);
}
template <typename ... _AttributeExtensions>
void SOC_MUTEProxy<_AttributeExtensions...>::SendCommand_Mute_reqStatus(uint8_t _Mute_reqStatus, CommonAPI::CallStatus &_internalCallStatus) {
    delegate_->SendCommand_Mute_reqStatus(_Mute_reqStatus, _internalCallStatus);
}

template <typename ... _AttributeExtensions>
const CommonAPI::Address &SOC_MUTEProxy<_AttributeExtensions...>::getAddress() const {
    return delegate_->getAddress();
}

template <typename ... _AttributeExtensions>
bool SOC_MUTEProxy<_AttributeExtensions...>::isAvailable() const {
    return delegate_->isAvailable();
}

template <typename ... _AttributeExtensions>
bool SOC_MUTEProxy<_AttributeExtensions...>::isAvailableBlocking() const {
    return delegate_->isAvailableBlocking();
}

template <typename ... _AttributeExtensions>
CommonAPI::ProxyStatusEvent& SOC_MUTEProxy<_AttributeExtensions...>::getProxyStatusEvent() {
    return delegate_->getProxyStatusEvent();
}

template <typename ... _AttributeExtensions>
CommonAPI::InterfaceVersionAttribute& SOC_MUTEProxy<_AttributeExtensions...>::getInterfaceVersionAttribute() {
    return delegate_->getInterfaceVersionAttribute();
}


template <typename ... _AttributeExtensions>
std::future<void> SOC_MUTEProxy<_AttributeExtensions...>::getCompletionFuture() {
    return delegate_->getCompletionFuture();
}

} // namespace iMicro
} // namespace v0



// Compatibility
namespace v0_1 = v0;

#endif // V0_IMICRO_SOC__MUTE_PROXY_HPP_
