/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.0.v202012010850.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V0_IMICRO_SOC__DEM_PROXY_HPP_
#define V0_IMICRO_SOC__DEM_PROXY_HPP_

#include <v0/iMicro/SOC_DEMProxyBase.hpp>


#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif


#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v0 {
namespace iMicro {

template <typename ... _AttributeExtensions>
class SOC_DEMProxy
    : virtual public SOC_DEM,
      virtual public SOC_DEMProxyBase,
      virtual public _AttributeExtensions... {
public:
    SOC_DEMProxy(std::shared_ptr<CommonAPI::Proxy> delegate);
    ~SOC_DEMProxy();

    typedef SOC_DEM InterfaceType;


    /**
     * Returns the CommonAPI address of the remote partner this proxy communicates with.
     */
    virtual const CommonAPI::Address &getAddress() const;

    /**
     * Returns true if the remote partner for this proxy is currently known to be available.
     */
    virtual bool isAvailable() const;

    /**
     * Returns true if the remote partner for this proxy is available.
     */
    virtual bool isAvailableBlocking() const;

    /**
     * Returns the wrapper class that is used to (de-)register for notifications about
     * the availability of the remote partner of this proxy.
     */
    virtual CommonAPI::ProxyStatusEvent& getProxyStatusEvent();

    /**
     * Returns the wrapper class that is used to access version information of the remote
     * partner of this proxy.
     */
    virtual CommonAPI::InterfaceVersionAttribute& getInterfaceVersionAttribute();

    virtual std::future<void> getCompletionFuture();

    /**
     * Calls SendEvent_DEM_SetEventStatusIMicro with synchronous semantics.
     *
     * All const parameters are input parameters to this method.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void SendEvent_DEM_SetEventStatusIMicro(::iMicro::iMicroStructs::dem_eventstatus_type _DEM_SetEventStatusIMicro, CommonAPI::CallStatus &_internalCallStatus, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls SendEvent_DEM_SetEventStatusIMicro with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> SendEvent_DEM_SetEventStatusIMicroAsync(const ::iMicro::iMicroStructs::dem_eventstatus_type &_DEM_SetEventStatusIMicro, SendEvent_DEM_SetEventStatusIMicroAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls SendCommand_DEM_GetEventStatusIMicro with Fire&Forget semantics.
     *
     * All const parameters are input parameters to this method.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void SendCommand_DEM_GetEventStatusIMicro(uint8_t _DEM_GetEventStatusIMicro, CommonAPI::CallStatus &_internalCallStatus);
    /**
     * Returns the wrapper class that provides access to the broadcast SignalResponse_DEM_EventStatus.
     */
    virtual SignalResponse_DEM_EventStatusEvent& getSignalResponse_DEM_EventStatusEvent() {
        return delegate_->getSignalResponse_DEM_EventStatusEvent();
    }



 private:
    std::shared_ptr< SOC_DEMProxyBase> delegate_;
};

typedef SOC_DEMProxy<> SOC_DEMProxyDefault;


//
// SOC_DEMProxy Implementation
//
template <typename ... _AttributeExtensions>
SOC_DEMProxy<_AttributeExtensions...>::SOC_DEMProxy(std::shared_ptr<CommonAPI::Proxy> delegate):
        _AttributeExtensions(*(std::dynamic_pointer_cast< SOC_DEMProxyBase>(delegate)))...,
        delegate_(std::dynamic_pointer_cast< SOC_DEMProxyBase>(delegate)) {
}

template <typename ... _AttributeExtensions>
SOC_DEMProxy<_AttributeExtensions...>::~SOC_DEMProxy() {
}

template <typename ... _AttributeExtensions>
void SOC_DEMProxy<_AttributeExtensions...>::SendEvent_DEM_SetEventStatusIMicro(::iMicro::iMicroStructs::dem_eventstatus_type _DEM_SetEventStatusIMicro, CommonAPI::CallStatus &_internalCallStatus, const CommonAPI::CallInfo *_info) {
    delegate_->SendEvent_DEM_SetEventStatusIMicro(_DEM_SetEventStatusIMicro, _internalCallStatus, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> SOC_DEMProxy<_AttributeExtensions...>::SendEvent_DEM_SetEventStatusIMicroAsync(const ::iMicro::iMicroStructs::dem_eventstatus_type &_DEM_SetEventStatusIMicro, SendEvent_DEM_SetEventStatusIMicroAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    return delegate_->SendEvent_DEM_SetEventStatusIMicroAsync(_DEM_SetEventStatusIMicro, _callback, _info);
}
template <typename ... _AttributeExtensions>
void SOC_DEMProxy<_AttributeExtensions...>::SendCommand_DEM_GetEventStatusIMicro(uint8_t _DEM_GetEventStatusIMicro, CommonAPI::CallStatus &_internalCallStatus) {
    delegate_->SendCommand_DEM_GetEventStatusIMicro(_DEM_GetEventStatusIMicro, _internalCallStatus);
}

template <typename ... _AttributeExtensions>
const CommonAPI::Address &SOC_DEMProxy<_AttributeExtensions...>::getAddress() const {
    return delegate_->getAddress();
}

template <typename ... _AttributeExtensions>
bool SOC_DEMProxy<_AttributeExtensions...>::isAvailable() const {
    return delegate_->isAvailable();
}

template <typename ... _AttributeExtensions>
bool SOC_DEMProxy<_AttributeExtensions...>::isAvailableBlocking() const {
    return delegate_->isAvailableBlocking();
}

template <typename ... _AttributeExtensions>
CommonAPI::ProxyStatusEvent& SOC_DEMProxy<_AttributeExtensions...>::getProxyStatusEvent() {
    return delegate_->getProxyStatusEvent();
}

template <typename ... _AttributeExtensions>
CommonAPI::InterfaceVersionAttribute& SOC_DEMProxy<_AttributeExtensions...>::getInterfaceVersionAttribute() {
    return delegate_->getInterfaceVersionAttribute();
}


template <typename ... _AttributeExtensions>
std::future<void> SOC_DEMProxy<_AttributeExtensions...>::getCompletionFuture() {
    return delegate_->getCompletionFuture();
}

} // namespace iMicro
} // namespace v0



// Compatibility
namespace v0_1 = v0;

#endif // V0_IMICRO_SOC__DEM_PROXY_HPP_
