/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.0.v202012010850.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V0_IMICRO_SOC__MIC_STUB_DEFAULT_HPP_
#define V0_IMICRO_SOC__MIC_STUB_DEFAULT_HPP_


#include <CommonAPI/Export.hpp>

#include <v0/iMicro/SOC_MICStub.hpp>
#include <cassert>
#include <sstream>

# if defined(_MSC_VER)
#  if _MSC_VER >= 1300
/*
 * Diamond inheritance is used for the CommonAPI::Proxy base class.
 * The Microsoft compiler put warning (C4250) using a desired c++ feature: "Delegating to a sister class"
 * A powerful technique that arises from using virtual inheritance is to delegate a method from a class in another class
 * by using a common abstract base class. This is also called cross delegation.
 */
#    pragma warning( disable : 4250 )
#  endif
# endif

namespace v0 {
namespace iMicro {

/**
 * Provides a default implementation for SOC_MICStubRemoteEvent and
 * SOC_MICStub. Method callbacks have an empty implementation,
 * remote set calls on attributes will always change the value of the attribute
 * to the one received.
 *
 * Override this stub if you only want to provide a subset of the functionality
 * that would be defined for this service, and/or if you do not need any non-default
 * behaviour.
 */
class COMMONAPI_EXPORT_CLASS_EXPLICIT SOC_MICStubDefault
    : public virtual SOC_MICStub {
public:
    COMMONAPI_EXPORT SOC_MICStubDefault()
        : remoteEventHandler_(this),
          interfaceVersion_(SOC_MIC::getInterfaceVersion()) {
    }

    COMMONAPI_EXPORT const CommonAPI::Version& getInterfaceVersion(std::shared_ptr<CommonAPI::ClientId> _client) {
        (void)_client;
        return interfaceVersion_;
    }

    COMMONAPI_EXPORT SOC_MICStubRemoteEvent* initStubAdapter(const std::shared_ptr< SOC_MICStubAdapter> &_adapter) {
        CommonAPI::Stub<SOC_MICStubAdapter, SOC_MICStubRemoteEvent>::stubAdapter_ = _adapter;
        return &remoteEventHandler_;
    }

    COMMONAPI_EXPORT virtual void SendCommand_Mic_reqStatus(const std::shared_ptr<CommonAPI::ClientId> _client, ::iMicro::iMicroTypes::mic_id_enum _Mic_reqStatus) {
        (void)_client;
        (void)_Mic_reqStatus;
    }
    COMMONAPI_EXPORT virtual void SendCommand_Mic_setStatus(const std::shared_ptr<CommonAPI::ClientId> _client, ::iMicro::iMicroStructs::mic_status_type _Mic_setStatus) {
        (void)_client;
        (void)_Mic_setStatus;
    }
    COMMONAPI_EXPORT virtual void fireSignalResponse_Mic_statusEvent(const ::iMicro::iMicroStructs::mic_status_type &_Mic_status) {
        SOC_MICStub::fireSignalResponse_Mic_statusEvent(_Mic_status);
    }


protected:
    class COMMONAPI_EXPORT_CLASS_EXPLICIT RemoteEventHandler: public virtual SOC_MICStubRemoteEvent {
    public:
        COMMONAPI_EXPORT RemoteEventHandler(SOC_MICStubDefault *_defaultStub)
            : 
              defaultStub_(_defaultStub) {
        }


    private:
        SOC_MICStubDefault *defaultStub_;
    };
protected:
    SOC_MICStubDefault::RemoteEventHandler remoteEventHandler_;

private:


    CommonAPI::Version interfaceVersion_;
};

} // namespace iMicro
} // namespace v0


// Compatibility
namespace v0_1 = v0;

#endif // V0_IMICRO_SOC__MIC_STUB_DEFAULT
