/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.0.v202012010944.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
#ifndef V0_IMICRO_SOC__IMU_SOMEIP_PROXY_HPP_
#define V0_IMICRO_SOC__IMU_SOMEIP_PROXY_HPP_

#include <v0/iMicro/SOC_IMUProxyBase.hpp>
#include <iMicro/iMicroStructsSomeIPDeployment.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/SomeIP/Factory.hpp>
#include <CommonAPI/SomeIP/Proxy.hpp>
#include <CommonAPI/SomeIP/Types.hpp>
#include <CommonAPI/SomeIP/Attribute.hpp>
#include <CommonAPI/SomeIP/Event.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <string>

# if defined(_MSC_VER)
#  if _MSC_VER >= 1300
/*
 * Diamond inheritance is used for the CommonAPI::Proxy base class.
 * The Microsoft compiler put warning (C4250) using a desired c++ feature: "Delegating to a sister class"
 * A powerful technique that arises from using virtual inheritance is to delegate a method from a class in another class
 * by using a common abstract base class. This is also called cross delegation.
 */
#    pragma warning( disable : 4250 )
#  endif
# endif

namespace v0 {
namespace iMicro {

class SOC_IMUSomeIPProxy
    : virtual public SOC_IMUProxyBase,
      virtual public CommonAPI::SomeIP::Proxy {
public:
    SOC_IMUSomeIPProxy(
        const CommonAPI::SomeIP::Address &_address,
        const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection);

    virtual ~SOC_IMUSomeIPProxy();

    virtual IMUDataManagerAttribute& getIMUDataManagerAttribute();

    virtual SignalEvent_IMU_ackEvent& getSignalEvent_IMU_ackEvent();

    virtual SignalEvent_IMU_WakeUpEvent& getSignalEvent_IMU_WakeUpEvent();

    virtual void SendCommand_IMU_setWakeupThs(::iMicro::iMicroStructs::IMU_setWakeupThs_type _IMU_setWakeupThs, CommonAPI::CallStatus &_internalCallStatus);

    virtual void SendEvent_IMU_asyncSubStatus(::iMicro::iMicroStructs::IMU_asyncSubStatus_type _IMU_asyncSubStatus, CommonAPI::CallStatus &_internalCallStatus, const CommonAPI::CallInfo *_info);

    virtual std::future<CommonAPI::CallStatus> SendEvent_IMU_asyncSubStatusAsync(const ::iMicro::iMicroStructs::IMU_asyncSubStatus_type &_IMU_asyncSubStatus, SendEvent_IMU_asyncSubStatusAsyncCallback _callback, const CommonAPI::CallInfo *_info);

    virtual void SendEvent_IMU_NadAck(::iMicro::iMicroStructs::IMU_NadAck_type _IMU_NadAck, CommonAPI::CallStatus &_internalCallStatus, const CommonAPI::CallInfo *_info);

    virtual std::future<CommonAPI::CallStatus> SendEvent_IMU_NadAckAsync(const ::iMicro::iMicroStructs::IMU_NadAck_type &_IMU_NadAck, SendEvent_IMU_NadAckAsyncCallback _callback, const CommonAPI::CallInfo *_info);

    virtual void GetEvent_IMU_ack(CommonAPI::CallStatus &_internalCallStatus, ::iMicro::iMicroStructs::IMU_ack_type &_IMU_ack, const CommonAPI::CallInfo *_info);

    virtual std::future<CommonAPI::CallStatus> GetEvent_IMU_ackAsync(GetEvent_IMU_ackAsyncCallback _callback, const CommonAPI::CallInfo *_info);

    virtual void GetEvent_IMU_WakeUp(CommonAPI::CallStatus &_internalCallStatus, ::iMicro::iMicroStructs::IMU_WakeUp_type &_IMU_WakeUp, const CommonAPI::CallInfo *_info);

    virtual std::future<CommonAPI::CallStatus> GetEvent_IMU_WakeUpAsync(GetEvent_IMU_WakeUpAsyncCallback _callback, const CommonAPI::CallInfo *_info);

    virtual void getOwnVersion(uint16_t &_major, uint16_t &_minor) const;

    virtual std::future<void> getCompletionFuture();

private:
    CommonAPI::SomeIP::ObservableAttribute<CommonAPI::SomeIP::ReadonlyAttribute<IMUDataManagerAttribute, ::iMicro::iMicroStructs_::IMUDataManager_MCU_tDeployment_t>> iMUDataManager_;
    CommonAPI::SomeIP::Event<SignalEvent_IMU_ackEvent, CommonAPI::Deployable< ::iMicro::iMicroStructs::IMU_ack_type, ::iMicro::iMicroStructs_::IMU_ack_typeDeployment_t >> signalEvent_IMU_ack_;
    CommonAPI::SomeIP::Event<SignalEvent_IMU_WakeUpEvent, CommonAPI::Deployable< ::iMicro::iMicroStructs::IMU_WakeUp_type, ::iMicro::iMicroStructs_::IMU_WakeUp_typeDeployment_t >> signalEvent_IMU_WakeUp_;

    std::promise<void> completed_;
};

} // namespace iMicro
} // namespace v0

#endif // V0_IMICRO_SOC__IMU_SOMEIP_PROXY_HPP_
