/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.0.v202012010944.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
#ifndef V0_IMICRO_SOC__BUTTON_SOMEIP_STUB_ADAPTER_HPP_
#define V0_IMICRO_SOC__BUTTON_SOMEIP_STUB_ADAPTER_HPP_

#include <v0/iMicro/SOC_ButtonStub.hpp>
#include <iMicro/iMicroStructsSomeIPDeployment.hpp>
#include <iMicro/iMicroTypesSomeIPDeployment.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/SomeIP/AddressTranslator.hpp>
#include <CommonAPI/SomeIP/StubAdapterHelper.hpp>
#include <CommonAPI/SomeIP/StubAdapter.hpp>
#include <CommonAPI/SomeIP/Factory.hpp>
#include <CommonAPI/SomeIP/Types.hpp>
#include <CommonAPI/SomeIP/Constants.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v0 {
namespace iMicro {

template <typename _Stub = ::v0::iMicro::SOC_ButtonStub, typename... _Stubs>
class SOC_ButtonSomeIPStubAdapterInternal
    : public virtual SOC_ButtonStubAdapter,
      public CommonAPI::SomeIP::StubAdapterHelper< _Stub, _Stubs...>,
      public std::enable_shared_from_this< SOC_ButtonSomeIPStubAdapterInternal<_Stub, _Stubs...>>
{
public:
    typedef CommonAPI::SomeIP::StubAdapterHelper< _Stub, _Stubs...> SOC_ButtonSomeIPStubAdapterHelper;

    ~SOC_ButtonSomeIPStubAdapterInternal() {
        deactivateManagedInstances();
        SOC_ButtonSomeIPStubAdapterHelper::deinit();
    }

    void fireSignalCommand_Button_pressEventEvent(const ::iMicro::iMicroStructs::button_status_type &_Button_pressEvent);

    void fireSignalResponse_Button_StatusEvent(const ::iMicro::iMicroStructs::button_status_type &_Button_Status);

    void deactivateManagedInstances() {}
    
    CommonAPI::SomeIP::GetAttributeStubDispatcher<
        ::v0::iMicro::SOC_ButtonStub,
        CommonAPI::Version
    > getSOC_ButtonInterfaceVersionStubDispatcher;

    CommonAPI::SomeIP::MethodStubDispatcher<
        ::v0::iMicro::SOC_ButtonStub,
        std::tuple< ::iMicro::iMicroTypes::button_id_enum>,
        std::tuple< ::iMicro::iMicroTypes_::button_id_enumDeployment_t>
    > sendCommand_Button_req_statusStubDispatcher;
    
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v0::iMicro::SOC_ButtonStub,
        std::tuple< >,
        std::tuple< ::iMicro::iMicroStructs::button_status_type>,
        std::tuple< >,
        std::tuple< ::iMicro::iMicroStructs_::button_status_typeDeployment_t>
    > getEvent_Button_pressEventStubDispatcher;
    
    SOC_ButtonSomeIPStubAdapterInternal(
        const CommonAPI::SomeIP::Address &_address,
        const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection,
        const std::shared_ptr<CommonAPI::StubBase> &_stub):
        CommonAPI::SomeIP::StubAdapter(_address, _connection),
        SOC_ButtonSomeIPStubAdapterHelper(
            _address,
            _connection,
            std::dynamic_pointer_cast< SOC_ButtonStub>(_stub)),
        getSOC_ButtonInterfaceVersionStubDispatcher(&SOC_ButtonStub::lockInterfaceVersionAttribute, &SOC_ButtonStub::getInterfaceVersion, false, true),
        sendCommand_Button_req_statusStubDispatcher(
            &SOC_ButtonStub::SendCommand_Button_req_status,
            false,
            _stub->hasElement(0),
            std::make_tuple(static_cast< ::iMicro::iMicroTypes_::button_id_enumDeployment_t* >(nullptr)))
        
        ,
        getEvent_Button_pressEventStubDispatcher(
            &SOC_ButtonStub::GetEvent_Button_pressEvent,
            false,
            _stub->hasElement(1),
            std::make_tuple(),
            std::make_tuple(static_cast< ::iMicro::iMicroStructs_::button_status_typeDeployment_t* >(nullptr)))
        
    {
        SOC_ButtonSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x23) }, &sendCommand_Button_req_statusStubDispatcher );
        SOC_ButtonSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x4d) }, &getEvent_Button_pressEventStubDispatcher );
        // Provided events/fields
        {
            std::set<CommonAPI::SomeIP::eventgroup_id_t> itsEventGroups;
            itsEventGroups.insert(CommonAPI::SomeIP::eventgroup_id_t(0x810b));
            CommonAPI::SomeIP::StubAdapter::registerEvent(CommonAPI::SomeIP::event_id_t(0x810b), itsEventGroups, CommonAPI::SomeIP::event_type_e::ET_EVENT, CommonAPI::SomeIP::reliability_type_e::RT_UNRELIABLE);
        }
        {
            std::set<CommonAPI::SomeIP::eventgroup_id_t> itsEventGroups;
            itsEventGroups.insert(CommonAPI::SomeIP::eventgroup_id_t(0x810a));
            CommonAPI::SomeIP::StubAdapter::registerEvent(CommonAPI::SomeIP::event_id_t(0x810a), itsEventGroups, CommonAPI::SomeIP::event_type_e::ET_EVENT, CommonAPI::SomeIP::reliability_type_e::RT_UNRELIABLE);
        }
    }

    // Register/Unregister event handlers for selective broadcasts
    void registerSelectiveEventHandlers();
    void unregisterSelectiveEventHandlers();

};

template <typename _Stub, typename... _Stubs>
void SOC_ButtonSomeIPStubAdapterInternal<_Stub, _Stubs...>::fireSignalCommand_Button_pressEventEvent(const ::iMicro::iMicroStructs::button_status_type &_Button_pressEvent) {
    CommonAPI::Deployable< ::iMicro::iMicroStructs::button_status_type, ::iMicro::iMicroStructs_::button_status_typeDeployment_t> deployed_Button_pressEvent(_Button_pressEvent, static_cast< ::iMicro::iMicroStructs_::button_status_typeDeployment_t* >(nullptr));
    CommonAPI::SomeIP::StubEventHelper<CommonAPI::SomeIP::SerializableArguments<  CommonAPI::Deployable< ::iMicro::iMicroStructs::button_status_type, ::iMicro::iMicroStructs_::button_status_typeDeployment_t > 
    >>
        ::sendEvent(
            *this,
            CommonAPI::SomeIP::event_id_t(0x810b),
            false,
             deployed_Button_pressEvent 
    );
}

template <typename _Stub, typename... _Stubs>
void SOC_ButtonSomeIPStubAdapterInternal<_Stub, _Stubs...>::fireSignalResponse_Button_StatusEvent(const ::iMicro::iMicroStructs::button_status_type &_Button_Status) {
    CommonAPI::Deployable< ::iMicro::iMicroStructs::button_status_type, ::iMicro::iMicroStructs_::button_status_typeDeployment_t> deployed_Button_Status(_Button_Status, static_cast< ::iMicro::iMicroStructs_::button_status_typeDeployment_t* >(nullptr));
    CommonAPI::SomeIP::StubEventHelper<CommonAPI::SomeIP::SerializableArguments<  CommonAPI::Deployable< ::iMicro::iMicroStructs::button_status_type, ::iMicro::iMicroStructs_::button_status_typeDeployment_t > 
    >>
        ::sendEvent(
            *this,
            CommonAPI::SomeIP::event_id_t(0x810a),
            false,
             deployed_Button_Status 
    );
}


template <typename _Stub, typename... _Stubs>
void SOC_ButtonSomeIPStubAdapterInternal<_Stub, _Stubs...>::registerSelectiveEventHandlers() {
}

template <typename _Stub, typename... _Stubs>
void SOC_ButtonSomeIPStubAdapterInternal<_Stub, _Stubs...>::unregisterSelectiveEventHandlers() {
}

template <typename _Stub = ::v0::iMicro::SOC_ButtonStub, typename... _Stubs>
class SOC_ButtonSomeIPStubAdapter
    : public SOC_ButtonSomeIPStubAdapterInternal<_Stub, _Stubs...> {
public:
    SOC_ButtonSomeIPStubAdapter(const CommonAPI::SomeIP::Address &_address,
                                            const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection,
                                            const std::shared_ptr<CommonAPI::StubBase> &_stub)
        : CommonAPI::SomeIP::StubAdapter(_address, _connection),
          SOC_ButtonSomeIPStubAdapterInternal<_Stub, _Stubs...>(_address, _connection, _stub) {
    }
};

} // namespace iMicro
} // namespace v0

#endif // V0_IMICRO_SOC__Button_SOMEIP_STUB_ADAPTER_HPP_
