/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.0.v202012010850.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V0_IMICRO_SOC__IMU_PROXY_HPP_
#define V0_IMICRO_SOC__IMU_PROXY_HPP_

#include <v0/iMicro/SOC_IMUProxyBase.hpp>


#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/AttributeExtension.hpp>
#include <CommonAPI/Factory.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v0 {
namespace iMicro {

template <typename ... _AttributeExtensions>
class SOC_IMUProxy
    : virtual public SOC_IMU,
      virtual public SOC_IMUProxyBase,
      virtual public _AttributeExtensions... {
public:
    SOC_IMUProxy(std::shared_ptr<CommonAPI::Proxy> delegate);
    ~SOC_IMUProxy();

    typedef SOC_IMU InterfaceType;


    /**
     * Returns the CommonAPI address of the remote partner this proxy communicates with.
     */
    virtual const CommonAPI::Address &getAddress() const;

    /**
     * Returns true if the remote partner for this proxy is currently known to be available.
     */
    virtual bool isAvailable() const;

    /**
     * Returns true if the remote partner for this proxy is available.
     */
    virtual bool isAvailableBlocking() const;

    /**
     * Returns the wrapper class that is used to (de-)register for notifications about
     * the availability of the remote partner of this proxy.
     */
    virtual CommonAPI::ProxyStatusEvent& getProxyStatusEvent();

    /**
     * Returns the wrapper class that is used to access version information of the remote
     * partner of this proxy.
     */
    virtual CommonAPI::InterfaceVersionAttribute& getInterfaceVersionAttribute();

    virtual std::future<void> getCompletionFuture();

    /**
     * Calls SendCommand_IMU_setWakeupThs with Fire&Forget semantics.
     *
     * All const parameters are input parameters to this method.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void SendCommand_IMU_setWakeupThs(::iMicro::iMicroStructs::IMU_setWakeupThs_type _IMU_setWakeupThs, CommonAPI::CallStatus &_internalCallStatus);
    /**
     * Calls SendEvent_IMU_asyncSubStatus with synchronous semantics.
     *
     * All const parameters are input parameters to this method.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void SendEvent_IMU_asyncSubStatus(::iMicro::iMicroStructs::IMU_asyncSubStatus_type _IMU_asyncSubStatus, CommonAPI::CallStatus &_internalCallStatus, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls SendEvent_IMU_asyncSubStatus with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> SendEvent_IMU_asyncSubStatusAsync(const ::iMicro::iMicroStructs::IMU_asyncSubStatus_type &_IMU_asyncSubStatus, SendEvent_IMU_asyncSubStatusAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls SendEvent_IMU_NadAck with synchronous semantics.
     *
     * All const parameters are input parameters to this method.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void SendEvent_IMU_NadAck(::iMicro::iMicroStructs::IMU_NadAck_type _IMU_NadAck, CommonAPI::CallStatus &_internalCallStatus, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls SendEvent_IMU_NadAck with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> SendEvent_IMU_NadAckAsync(const ::iMicro::iMicroStructs::IMU_NadAck_type &_IMU_NadAck, SendEvent_IMU_NadAckAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls GetEvent_IMU_ack with synchronous semantics.
     *
     * All non-const parameters will be filled with the returned values.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void GetEvent_IMU_ack(CommonAPI::CallStatus &_internalCallStatus, ::iMicro::iMicroStructs::IMU_ack_type &_IMU_ack, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls GetEvent_IMU_ack with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> GetEvent_IMU_ackAsync(GetEvent_IMU_ackAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Returns the wrapper class that provides access to the broadcast SignalEvent_IMU_ack.
     */
    virtual SignalEvent_IMU_ackEvent& getSignalEvent_IMU_ackEvent() {
        return delegate_->getSignalEvent_IMU_ackEvent();
    }
    /**
     * Calls GetEvent_IMU_WakeUp with synchronous semantics.
     *
     * All non-const parameters will be filled with the returned values.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void GetEvent_IMU_WakeUp(CommonAPI::CallStatus &_internalCallStatus, ::iMicro::iMicroStructs::IMU_WakeUp_type &_IMU_WakeUp, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls GetEvent_IMU_WakeUp with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> GetEvent_IMU_WakeUpAsync(GetEvent_IMU_WakeUpAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Returns the wrapper class that provides access to the broadcast SignalEvent_IMU_WakeUp.
     */
    virtual SignalEvent_IMU_WakeUpEvent& getSignalEvent_IMU_WakeUpEvent() {
        return delegate_->getSignalEvent_IMU_WakeUpEvent();
    }
    /*
     * description: 
     * IMU data from MCU
     */
    /**
     * Returns the wrapper class that provides access to the attribute IMUDataManager.
     */
    virtual IMUDataManagerAttribute& getIMUDataManagerAttribute() {
        return delegate_->getIMUDataManagerAttribute();
    }



 private:
    std::shared_ptr< SOC_IMUProxyBase> delegate_;
};

typedef SOC_IMUProxy<> SOC_IMUProxyDefault;

namespace SOC_IMUExtensions {
    /*
     * description: 
     * IMU data from MCU
     */
    template <template <typename > class _ExtensionType>
    class IMUDataManagerAttributeExtension {
     public:
        typedef _ExtensionType< SOC_IMUProxyBase::IMUDataManagerAttribute> extension_type;
    
        static_assert(std::is_base_of<typename CommonAPI::AttributeExtension< SOC_IMUProxyBase::IMUDataManagerAttribute>, extension_type>::value,
                      "Not CommonAPI Attribute Extension!");
    
        IMUDataManagerAttributeExtension(SOC_IMUProxyBase& proxy): attributeExtension_(proxy.getIMUDataManagerAttribute()) {
        }
    
        inline extension_type& getIMUDataManagerAttributeExtension() {
            return attributeExtension_;
        }
    
     private:
        extension_type attributeExtension_;
    };

} // namespace SOC_IMUExtensions

//
// SOC_IMUProxy Implementation
//
template <typename ... _AttributeExtensions>
SOC_IMUProxy<_AttributeExtensions...>::SOC_IMUProxy(std::shared_ptr<CommonAPI::Proxy> delegate):
        _AttributeExtensions(*(std::dynamic_pointer_cast< SOC_IMUProxyBase>(delegate)))...,
        delegate_(std::dynamic_pointer_cast< SOC_IMUProxyBase>(delegate)) {
}

template <typename ... _AttributeExtensions>
SOC_IMUProxy<_AttributeExtensions...>::~SOC_IMUProxy() {
}

template <typename ... _AttributeExtensions>
void SOC_IMUProxy<_AttributeExtensions...>::SendCommand_IMU_setWakeupThs(::iMicro::iMicroStructs::IMU_setWakeupThs_type _IMU_setWakeupThs, CommonAPI::CallStatus &_internalCallStatus) {
    delegate_->SendCommand_IMU_setWakeupThs(_IMU_setWakeupThs, _internalCallStatus);
}
template <typename ... _AttributeExtensions>
void SOC_IMUProxy<_AttributeExtensions...>::SendEvent_IMU_asyncSubStatus(::iMicro::iMicroStructs::IMU_asyncSubStatus_type _IMU_asyncSubStatus, CommonAPI::CallStatus &_internalCallStatus, const CommonAPI::CallInfo *_info) {
    delegate_->SendEvent_IMU_asyncSubStatus(_IMU_asyncSubStatus, _internalCallStatus, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> SOC_IMUProxy<_AttributeExtensions...>::SendEvent_IMU_asyncSubStatusAsync(const ::iMicro::iMicroStructs::IMU_asyncSubStatus_type &_IMU_asyncSubStatus, SendEvent_IMU_asyncSubStatusAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    return delegate_->SendEvent_IMU_asyncSubStatusAsync(_IMU_asyncSubStatus, _callback, _info);
}
template <typename ... _AttributeExtensions>
void SOC_IMUProxy<_AttributeExtensions...>::SendEvent_IMU_NadAck(::iMicro::iMicroStructs::IMU_NadAck_type _IMU_NadAck, CommonAPI::CallStatus &_internalCallStatus, const CommonAPI::CallInfo *_info) {
    delegate_->SendEvent_IMU_NadAck(_IMU_NadAck, _internalCallStatus, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> SOC_IMUProxy<_AttributeExtensions...>::SendEvent_IMU_NadAckAsync(const ::iMicro::iMicroStructs::IMU_NadAck_type &_IMU_NadAck, SendEvent_IMU_NadAckAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    return delegate_->SendEvent_IMU_NadAckAsync(_IMU_NadAck, _callback, _info);
}
template <typename ... _AttributeExtensions>
void SOC_IMUProxy<_AttributeExtensions...>::GetEvent_IMU_ack(CommonAPI::CallStatus &_internalCallStatus, ::iMicro::iMicroStructs::IMU_ack_type &_IMU_ack, const CommonAPI::CallInfo *_info) {
    delegate_->GetEvent_IMU_ack(_internalCallStatus, _IMU_ack, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> SOC_IMUProxy<_AttributeExtensions...>::GetEvent_IMU_ackAsync(GetEvent_IMU_ackAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    return delegate_->GetEvent_IMU_ackAsync(_callback, _info);
}
template <typename ... _AttributeExtensions>
void SOC_IMUProxy<_AttributeExtensions...>::GetEvent_IMU_WakeUp(CommonAPI::CallStatus &_internalCallStatus, ::iMicro::iMicroStructs::IMU_WakeUp_type &_IMU_WakeUp, const CommonAPI::CallInfo *_info) {
    delegate_->GetEvent_IMU_WakeUp(_internalCallStatus, _IMU_WakeUp, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> SOC_IMUProxy<_AttributeExtensions...>::GetEvent_IMU_WakeUpAsync(GetEvent_IMU_WakeUpAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    return delegate_->GetEvent_IMU_WakeUpAsync(_callback, _info);
}

template <typename ... _AttributeExtensions>
const CommonAPI::Address &SOC_IMUProxy<_AttributeExtensions...>::getAddress() const {
    return delegate_->getAddress();
}

template <typename ... _AttributeExtensions>
bool SOC_IMUProxy<_AttributeExtensions...>::isAvailable() const {
    return delegate_->isAvailable();
}

template <typename ... _AttributeExtensions>
bool SOC_IMUProxy<_AttributeExtensions...>::isAvailableBlocking() const {
    return delegate_->isAvailableBlocking();
}

template <typename ... _AttributeExtensions>
CommonAPI::ProxyStatusEvent& SOC_IMUProxy<_AttributeExtensions...>::getProxyStatusEvent() {
    return delegate_->getProxyStatusEvent();
}

template <typename ... _AttributeExtensions>
CommonAPI::InterfaceVersionAttribute& SOC_IMUProxy<_AttributeExtensions...>::getInterfaceVersionAttribute() {
    return delegate_->getInterfaceVersionAttribute();
}


template <typename ... _AttributeExtensions>
std::future<void> SOC_IMUProxy<_AttributeExtensions...>::getCompletionFuture() {
    return delegate_->getCompletionFuture();
}

} // namespace iMicro
} // namespace v0

namespace CommonAPI {
template<template<typename > class _AttributeExtension>
struct DefaultAttributeProxyHelper< ::v0::iMicro::SOC_IMUProxy,
    _AttributeExtension> {
    typedef typename ::v0::iMicro::SOC_IMUProxy<
            ::v0::iMicro::SOC_IMUExtensions::IMUDataManagerAttributeExtension<_AttributeExtension>
    > class_t;
};
}


// Compatibility
namespace v0_1 = v0;

#endif // V0_IMICRO_SOC__IMU_PROXY_HPP_
