/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.0.v202012010850.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V0_IMICRO_SOC__SQD_Fdiagserver_STUB_HPP_
#define V0_IMICRO_SOC__SQD_Fdiagserver_STUB_HPP_

#include <functional>
#include <sstream>



#include <iMicro/iMicroStructs.hpp>
#include <iMicro/iMicroTypes.hpp>

#include <v0/iMicro/SOC_SQDFdiagserver.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/Deployment.hpp>
#include <CommonAPI/InputStream.hpp>
#include <CommonAPI/OutputStream.hpp>
#include <CommonAPI/Struct.hpp>
#include <cstdint>
#include <unordered_set>
#include <vector>


#include <CommonAPI/Stub.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v0 {
namespace iMicro {

/**
 * Receives messages from remote and handles all dispatching of deserialized calls
 * to a stub for the service SOC_SQDFdiagserver. Also provides means to send broadcasts
 * and attribute-changed-notifications of observable attributes as defined by this service.
 * An application developer should not need to bother with this class.
 */
class SOC_SQDFdiagserverStubAdapter
    : public virtual CommonAPI::StubAdapter,
      public virtual SOC_SQDFdiagserver {
 public:
    /**
    * Sends a broadcast event for SignalResponse_DiagnosticRequest_resp. Should not be called directly.
    * Instead, the "fire<broadcastName>Event" methods of the stub should be used.
    */
    virtual void fireSignalResponse_DiagnosticRequest_respEvent(const ::iMicro::iMicroStructs::DiagnosticRequest_resp_type &_DiagnosticRequest_resp) = 0;
    /**
    * Sends a broadcast event for SignalResponse_EcuProtocolDetection_resp. Should not be called directly.
    * Instead, the "fire<broadcastName>Event" methods of the stub should be used.
    */
    virtual void fireSignalResponse_EcuProtocolDetection_respEvent(const ::iMicro::iMicroStructs::EcuProtocolDetection_resp_type &_EcuProtocolDetection_resp) = 0;
    /**
    * Sends a broadcast event for SignalResponse_Configure_resp. Should not be called directly.
    * Instead, the "fire<broadcastName>Event" methods of the stub should be used.
    */
    virtual void fireSignalResponse_Configure_respEvent(const ::iMicro::iMicroStructs::Configure_resp_type &_Configure_resp) = 0;
    /**
    * Sends a broadcast event for SignalEvent_TesterActivityDetected. Should not be called directly.
    * Instead, the "fire<broadcastName>Event" methods of the stub should be used.
    */
    virtual void fireSignalEvent_TesterActivityDetectedEvent(const ::iMicro::iMicroStructs::TesterActivityDetected_type &_TesterActivityDetected) = 0;
    /**
    * Sends a broadcast event for SignalResponse_GetTesterActivity_resp. Should not be called directly.
    * Instead, the "fire<broadcastName>Event" methods of the stub should be used.
    */
    virtual void fireSignalResponse_GetTesterActivity_respEvent(const ::iMicro::iMicroStructs::GetTesterActivity_resp_type &_GetTesterActivity_resp) = 0;
    /**
    * Sends a broadcast event for SignalResponse_RDASession_resp. Should not be called directly.
    * Instead, the "fire<broadcastName>Event" methods of the stub should be used.
    */
    virtual void fireSignalResponse_RDASession_respEvent(const ::iMicro::iMicroStructs::RDASession_resp_type &_RDASession_resp) = 0;
    /**
    * Sends a broadcast event for SignalResponse_RDAConfiguration_resp. Should not be called directly.
    * Instead, the "fire<broadcastName>Event" methods of the stub should be used.
    */
    virtual void fireSignalResponse_RDAConfiguration_respEvent(const ::iMicro::iMicroStructs::RDAConfiguration_resp_type &_RDAConfiguration_resp) = 0;
    /**
    * Sends a broadcast event for SignalResponse_RDADiagnosticRequestACK. Should not be called directly.
    * Instead, the "fire<broadcastName>Event" methods of the stub should be used.
    */
    virtual void fireSignalResponse_RDADiagnosticRequestACKEvent(const ::iMicro::iMicroStructs::RDADiagnosticRequestACK_type &_RDADiagnosticRequestACK) = 0;
    /**
    * Sends a broadcast event for SignalResponse_RDADiagnostic_resp. Should not be called directly.
    * Instead, the "fire<broadcastName>Event" methods of the stub should be used.
    */
    virtual void fireSignalResponse_RDADiagnostic_respEvent(const ::iMicro::iMicroStructs::RDADiagnostic_resp_type &_RDADiagnostic_resp) = 0;


    virtual void deactivateManagedInstances() = 0;


protected:
    /**
     * Defines properties for storing the ClientIds of clients / proxies that have
     * subscribed to the selective broadcasts
     */

};

/**
 * Defines the necessary callbacks to handle remote set events related to the attributes
 * defined in the IDL description for SOC_SQDFdiagserver.
 * For each attribute two callbacks are defined:
 * - a verification callback that allows to verify the requested value and to prevent setting
 *   e.g. an invalid value ("onRemoteSet<AttributeName>").
 * - an action callback to do local work after the attribute value has been changed
 *   ("onRemote<AttributeName>Changed").
 *
 * This class and the one below are the ones an application developer needs to have
 * a look at if he wants to implement a service.
 */
class SOC_SQDFdiagserverStubRemoteEvent
{
public:
    virtual ~SOC_SQDFdiagserverStubRemoteEvent() { }

};

/**
 * Defines the interface that must be implemented by any class that should provide
 * the service SOC_SQDFdiagserver to remote clients.
 * This class and the one above are the ones an application developer needs to have
 * a look at if he wants to implement a service.
 */
class SOC_SQDFdiagserverStub
    : public virtual CommonAPI::Stub<SOC_SQDFdiagserverStubAdapter, SOC_SQDFdiagserverStubRemoteEvent>
{
public:
    typedef std::function<void ()> SendEvent_RDASession_RequestReply_t;
    typedef std::function<void ()> SendEvent_RDAConfiguration_RequestReply_t;
    typedef std::function<void ()> SendEvent_RDADiagnostic_RequestReply_t;
    typedef std::function<void (::iMicro::iMicroStructs::TesterActivityDetected_type _TesterActivityDetected)> GetEvent_TesterActivityDetectedReply_t;

    virtual ~SOC_SQDFdiagserverStub() {}
    void lockInterfaceVersionAttribute(bool _lockAccess) { static_cast<void>(_lockAccess); }
    bool hasElement(const uint32_t _id) const {
        return (_id < 17);
    }
    virtual const CommonAPI::Version& getInterfaceVersion(std::shared_ptr<CommonAPI::ClientId> _client) = 0;

    /// This is the method that will be called on remote calls on the method SendCommand_DiagnosticRequest_cmd.
    virtual void SendCommand_DiagnosticRequest_cmd(const std::shared_ptr<CommonAPI::ClientId> _client, ::iMicro::iMicroStructs::DiagnosticRequest_cmd_type _DiagnosticRequest_cmd) = 0;
    /// This is the method that will be called on remote calls on the method SendCommand_EcuProtocolDetection_cmd.
    virtual void SendCommand_EcuProtocolDetection_cmd(const std::shared_ptr<CommonAPI::ClientId> _client, ::iMicro::iMicroStructs::EcuProtocolDetection_cmd_type _EcuProtocolDetection_cmd) = 0;
    /// This is the method that will be called on remote calls on the method SendCommand_Configure_cmd.
    virtual void SendCommand_Configure_cmd(const std::shared_ptr<CommonAPI::ClientId> _client, ::iMicro::iMicroStructs::Configure_cmd_type _Configure_cmd) = 0;
    /// This is the method that will be called on remote calls on the method SendCommand_GetTesterActivity_cmd.
    virtual void SendCommand_GetTesterActivity_cmd(const std::shared_ptr<CommonAPI::ClientId> _client, uint8_t _GetTesterActivity_cmd) = 0;
    /// This is the method that will be called on remote calls on the method SendEvent_RDASession_Request.
    virtual void SendEvent_RDASession_Request(const std::shared_ptr<CommonAPI::ClientId> _client, ::iMicro::iMicroStructs::RDASessionRequest_Type _RDASession_Request, SendEvent_RDASession_RequestReply_t _reply) = 0;
    /// This is the method that will be called on remote calls on the method SendEvent_RDAConfiguration_Request.
    virtual void SendEvent_RDAConfiguration_Request(const std::shared_ptr<CommonAPI::ClientId> _client, ::iMicro::iMicroStructs::RDAConfigurationRequest_type _RDAConfiguration_Request, SendEvent_RDAConfiguration_RequestReply_t _reply) = 0;
    /// This is the method that will be called on remote calls on the method SendEvent_RDADiagnostic_Request.
    virtual void SendEvent_RDADiagnostic_Request(const std::shared_ptr<CommonAPI::ClientId> _client, ::iMicro::iMicroStructs::RDADiagnosticRequest_type _RDADiagnostic_Request, SendEvent_RDADiagnostic_RequestReply_t _reply) = 0;
    /// Sends a broadcast event for SignalResponse_DiagnosticRequest_resp.
    virtual void fireSignalResponse_DiagnosticRequest_respEvent(const ::iMicro::iMicroStructs::DiagnosticRequest_resp_type &_DiagnosticRequest_resp) {
        auto stubAdapter = CommonAPI::Stub<SOC_SQDFdiagserverStubAdapter, SOC_SQDFdiagserverStubRemoteEvent>::stubAdapter_.lock();
        if (stubAdapter)
            stubAdapter->fireSignalResponse_DiagnosticRequest_respEvent(_DiagnosticRequest_resp);
    }
    /// Sends a broadcast event for SignalResponse_EcuProtocolDetection_resp.
    virtual void fireSignalResponse_EcuProtocolDetection_respEvent(const ::iMicro::iMicroStructs::EcuProtocolDetection_resp_type &_EcuProtocolDetection_resp) {
        auto stubAdapter = CommonAPI::Stub<SOC_SQDFdiagserverStubAdapter, SOC_SQDFdiagserverStubRemoteEvent>::stubAdapter_.lock();
        if (stubAdapter)
            stubAdapter->fireSignalResponse_EcuProtocolDetection_respEvent(_EcuProtocolDetection_resp);
    }
    /// Sends a broadcast event for SignalResponse_Configure_resp.
    virtual void fireSignalResponse_Configure_respEvent(const ::iMicro::iMicroStructs::Configure_resp_type &_Configure_resp) {
        auto stubAdapter = CommonAPI::Stub<SOC_SQDFdiagserverStubAdapter, SOC_SQDFdiagserverStubRemoteEvent>::stubAdapter_.lock();
        if (stubAdapter)
            stubAdapter->fireSignalResponse_Configure_respEvent(_Configure_resp);
    }
    /// This is the method that will be called on remote calls on the method GetEvent_TesterActivityDetected.
    virtual void GetEvent_TesterActivityDetected(const std::shared_ptr<CommonAPI::ClientId> _client, GetEvent_TesterActivityDetectedReply_t _reply) = 0;
    /// Sends a broadcast event for SignalEvent_TesterActivityDetected.
    virtual void fireSignalEvent_TesterActivityDetectedEvent(const ::iMicro::iMicroStructs::TesterActivityDetected_type &_TesterActivityDetected) {
        auto stubAdapter = CommonAPI::Stub<SOC_SQDFdiagserverStubAdapter, SOC_SQDFdiagserverStubRemoteEvent>::stubAdapter_.lock();
        if (stubAdapter)
            stubAdapter->fireSignalEvent_TesterActivityDetectedEvent(_TesterActivityDetected);
    }
    /// Sends a broadcast event for SignalResponse_GetTesterActivity_resp.
    virtual void fireSignalResponse_GetTesterActivity_respEvent(const ::iMicro::iMicroStructs::GetTesterActivity_resp_type &_GetTesterActivity_resp) {
        auto stubAdapter = CommonAPI::Stub<SOC_SQDFdiagserverStubAdapter, SOC_SQDFdiagserverStubRemoteEvent>::stubAdapter_.lock();
        if (stubAdapter)
            stubAdapter->fireSignalResponse_GetTesterActivity_respEvent(_GetTesterActivity_resp);
    }
    /// Sends a broadcast event for SignalResponse_RDASession_resp.
    virtual void fireSignalResponse_RDASession_respEvent(const ::iMicro::iMicroStructs::RDASession_resp_type &_RDASession_resp) {
        auto stubAdapter = CommonAPI::Stub<SOC_SQDFdiagserverStubAdapter, SOC_SQDFdiagserverStubRemoteEvent>::stubAdapter_.lock();
        if (stubAdapter)
            stubAdapter->fireSignalResponse_RDASession_respEvent(_RDASession_resp);
    }
    /// Sends a broadcast event for SignalResponse_RDAConfiguration_resp.
    virtual void fireSignalResponse_RDAConfiguration_respEvent(const ::iMicro::iMicroStructs::RDAConfiguration_resp_type &_RDAConfiguration_resp) {
        auto stubAdapter = CommonAPI::Stub<SOC_SQDFdiagserverStubAdapter, SOC_SQDFdiagserverStubRemoteEvent>::stubAdapter_.lock();
        if (stubAdapter)
            stubAdapter->fireSignalResponse_RDAConfiguration_respEvent(_RDAConfiguration_resp);
    }
    /// Sends a broadcast event for SignalResponse_RDADiagnosticRequestACK.
    virtual void fireSignalResponse_RDADiagnosticRequestACKEvent(const ::iMicro::iMicroStructs::RDADiagnosticRequestACK_type &_RDADiagnosticRequestACK) {
        auto stubAdapter = CommonAPI::Stub<SOC_SQDFdiagserverStubAdapter, SOC_SQDFdiagserverStubRemoteEvent>::stubAdapter_.lock();
        if (stubAdapter)
            stubAdapter->fireSignalResponse_RDADiagnosticRequestACKEvent(_RDADiagnosticRequestACK);
    }
    /// Sends a broadcast event for SignalResponse_RDADiagnostic_resp.
    virtual void fireSignalResponse_RDADiagnostic_respEvent(const ::iMicro::iMicroStructs::RDADiagnostic_resp_type &_RDADiagnostic_resp) {
        auto stubAdapter = CommonAPI::Stub<SOC_SQDFdiagserverStubAdapter, SOC_SQDFdiagserverStubRemoteEvent>::stubAdapter_.lock();
        if (stubAdapter)
            stubAdapter->fireSignalResponse_RDADiagnostic_respEvent(_RDADiagnostic_resp);
    }


    using CommonAPI::Stub<SOC_SQDFdiagserverStubAdapter, SOC_SQDFdiagserverStubRemoteEvent>::initStubAdapter;
    typedef CommonAPI::Stub<SOC_SQDFdiagserverStubAdapter, SOC_SQDFdiagserverStubRemoteEvent>::StubAdapterType StubAdapterType;
    typedef CommonAPI::Stub<SOC_SQDFdiagserverStubAdapter, SOC_SQDFdiagserverStubRemoteEvent>::RemoteEventHandlerType RemoteEventHandlerType;
    typedef SOC_SQDFdiagserverStubRemoteEvent RemoteEventType;
    typedef SOC_SQDFdiagserver StubInterface;
};

} // namespace iMicro
} // namespace v0


// Compatibility
namespace v0_1 = v0;

#endif // V0_IMICRO_SOC__SQD_Fdiagserver_STUB_HPP_
