/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.0.v202012010850.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V0_IMICRO_SOC__SAM_PROXY_HPP_
#define V0_IMICRO_SOC__SAM_PROXY_HPP_

#include <v0/iMicro/SOC_SAMProxyBase.hpp>


#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif


#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v0 {
namespace iMicro {

template <typename ... _AttributeExtensions>
class SOC_SAMProxy
    : virtual public SOC_SAM,
      virtual public SOC_SAMProxyBase,
      virtual public _AttributeExtensions... {
public:
    SOC_SAMProxy(std::shared_ptr<CommonAPI::Proxy> delegate);
    ~SOC_SAMProxy();

    typedef SOC_SAM InterfaceType;


    /**
     * Returns the CommonAPI address of the remote partner this proxy communicates with.
     */
    virtual const CommonAPI::Address &getAddress() const;

    /**
     * Returns true if the remote partner for this proxy is currently known to be available.
     */
    virtual bool isAvailable() const;

    /**
     * Returns true if the remote partner for this proxy is available.
     */
    virtual bool isAvailableBlocking() const;

    /**
     * Returns the wrapper class that is used to (de-)register for notifications about
     * the availability of the remote partner of this proxy.
     */
    virtual CommonAPI::ProxyStatusEvent& getProxyStatusEvent();

    /**
     * Returns the wrapper class that is used to access version information of the remote
     * partner of this proxy.
     */
    virtual CommonAPI::InterfaceVersionAttribute& getInterfaceVersionAttribute();

    virtual std::future<void> getCompletionFuture();

    /**
     * Calls SendEvent_DLT_Configuration with synchronous semantics.
     *
     * All const parameters are input parameters to this method.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void SendEvent_DLT_Configuration(uint32_t _DLT_Configuration, CommonAPI::CallStatus &_internalCallStatus, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls SendEvent_DLT_Configuration with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> SendEvent_DLT_ConfigurationAsync(const uint32_t &_DLT_Configuration, SendEvent_DLT_ConfigurationAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);



 private:
    std::shared_ptr< SOC_SAMProxyBase> delegate_;
};

typedef SOC_SAMProxy<> SOC_SAMProxyDefault;


//
// SOC_SAMProxy Implementation
//
template <typename ... _AttributeExtensions>
SOC_SAMProxy<_AttributeExtensions...>::SOC_SAMProxy(std::shared_ptr<CommonAPI::Proxy> delegate):
        _AttributeExtensions(*(std::dynamic_pointer_cast< SOC_SAMProxyBase>(delegate)))...,
        delegate_(std::dynamic_pointer_cast< SOC_SAMProxyBase>(delegate)) {
}

template <typename ... _AttributeExtensions>
SOC_SAMProxy<_AttributeExtensions...>::~SOC_SAMProxy() {
}

template <typename ... _AttributeExtensions>
void SOC_SAMProxy<_AttributeExtensions...>::SendEvent_DLT_Configuration(uint32_t _DLT_Configuration, CommonAPI::CallStatus &_internalCallStatus, const CommonAPI::CallInfo *_info) {
    delegate_->SendEvent_DLT_Configuration(_DLT_Configuration, _internalCallStatus, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> SOC_SAMProxy<_AttributeExtensions...>::SendEvent_DLT_ConfigurationAsync(const uint32_t &_DLT_Configuration, SendEvent_DLT_ConfigurationAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    return delegate_->SendEvent_DLT_ConfigurationAsync(_DLT_Configuration, _callback, _info);
}

template <typename ... _AttributeExtensions>
const CommonAPI::Address &SOC_SAMProxy<_AttributeExtensions...>::getAddress() const {
    return delegate_->getAddress();
}

template <typename ... _AttributeExtensions>
bool SOC_SAMProxy<_AttributeExtensions...>::isAvailable() const {
    return delegate_->isAvailable();
}

template <typename ... _AttributeExtensions>
bool SOC_SAMProxy<_AttributeExtensions...>::isAvailableBlocking() const {
    return delegate_->isAvailableBlocking();
}

template <typename ... _AttributeExtensions>
CommonAPI::ProxyStatusEvent& SOC_SAMProxy<_AttributeExtensions...>::getProxyStatusEvent() {
    return delegate_->getProxyStatusEvent();
}

template <typename ... _AttributeExtensions>
CommonAPI::InterfaceVersionAttribute& SOC_SAMProxy<_AttributeExtensions...>::getInterfaceVersionAttribute() {
    return delegate_->getInterfaceVersionAttribute();
}


template <typename ... _AttributeExtensions>
std::future<void> SOC_SAMProxy<_AttributeExtensions...>::getCompletionFuture() {
    return delegate_->getCompletionFuture();
}

} // namespace iMicro
} // namespace v0



// Compatibility
namespace v0_1 = v0;

#endif // V0_IMICRO_SOC__SAM_PROXY_HPP_
