/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.0.v202012010944.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
#include <v0/iMicro/SOC_NTW_APISomeIPProxy.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/SomeIP/AddressTranslator.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v0 {
namespace iMicro {

std::shared_ptr<CommonAPI::SomeIP::Proxy> createSOC_NTW_APISomeIPProxy(
    const CommonAPI::SomeIP::Address &_address,
    const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection) {
    return std::make_shared< SOC_NTW_APISomeIPProxy>(_address, _connection);
}

void initializeSOC_NTW_APISomeIPProxy() {
    CommonAPI::SomeIP::AddressTranslator::get()->insert(
        "local:iMicro.SOC_NTW_API:v0_1:iMicro.SOC_NTW_API",
        0x125b, 0x5699, 0, 1);
    CommonAPI::SomeIP::Factory::get()->registerProxyCreateMethod(
        "iMicro.SOC_NTW_API:v0_1",
        &createSOC_NTW_APISomeIPProxy);
}

INITIALIZER(registerSOC_NTW_APISomeIPProxy) {
    CommonAPI::SomeIP::Factory::get()->registerInterface(initializeSOC_NTW_APISomeIPProxy);
}

SOC_NTW_APISomeIPProxy::SOC_NTW_APISomeIPProxy(
    const CommonAPI::SomeIP::Address &_address,
    const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection)
        : CommonAPI::SomeIP::Proxy(_address, _connection),
          nTW_ComSync_(*this, CommonAPI::SomeIP::eventgroup_id_t(0x4001), CommonAPI::SomeIP::event_id_t(0xc000), CommonAPI::SomeIP::method_id_t(0x1b6), false, CommonAPI::SomeIP::reliability_type_e::RT_UNRELIABLE, false, static_cast< CommonAPI::SomeIP::IntegerDeployment<uint8_t>* >(nullptr))
{
}

SOC_NTW_APISomeIPProxy::~SOC_NTW_APISomeIPProxy() {
    completed_.set_value();
}

SOC_NTW_APISomeIPProxy::NTW_ComSyncAttribute& SOC_NTW_APISomeIPProxy::getNTW_ComSyncAttribute() {
    return nTW_ComSync_;
}


void SOC_NTW_APISomeIPProxy::SendEvent_NTW_COMM_StayActive(uint8_t _NTW_COMM_StayActive, CommonAPI::CallStatus &_internalCallStatus, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< uint8_t, CommonAPI::SomeIP::IntegerDeployment<uint8_t>> deploy_NTW_COMM_StayActive(_NTW_COMM_StayActive, static_cast< CommonAPI::SomeIP::IntegerDeployment<uint8_t>* >(nullptr));
    CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                uint8_t,
                CommonAPI::SomeIP::IntegerDeployment<uint8_t>
            >
        >,
        CommonAPI::SomeIP::SerializableArguments<
        >
    >::callMethodWithReply(
        *this,
        CommonAPI::SomeIP::method_id_t(0x1b5),
        false,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        deploy_NTW_COMM_StayActive,
        _internalCallStatus);
}

std::future<CommonAPI::CallStatus> SOC_NTW_APISomeIPProxy::SendEvent_NTW_COMM_StayActiveAsync(const uint8_t &_NTW_COMM_StayActive, SendEvent_NTW_COMM_StayActiveAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< uint8_t, CommonAPI::SomeIP::IntegerDeployment<uint8_t>> deploy_NTW_COMM_StayActive(_NTW_COMM_StayActive, static_cast< CommonAPI::SomeIP::IntegerDeployment<uint8_t>* >(nullptr));
    return CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                uint8_t,
                CommonAPI::SomeIP::IntegerDeployment<uint8_t>
            >
        >,
        CommonAPI::SomeIP::SerializableArguments<
        >
    >::callMethodAsync(
        *this,
        CommonAPI::SomeIP::method_id_t(0x1b5),
        false,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        deploy_NTW_COMM_StayActive,
        [_callback] (CommonAPI::CallStatus _internalCallStatus) {
            if (_callback)
                _callback(_internalCallStatus);
        },
        std::make_tuple());
}

void SOC_NTW_APISomeIPProxy::getOwnVersion(uint16_t& ownVersionMajor, uint16_t& ownVersionMinor) const {
    ownVersionMajor = 0;
    ownVersionMinor = 1;
}

std::future<void> SOC_NTW_APISomeIPProxy::getCompletionFuture() {
    return completed_.get_future();
}

} // namespace iMicro
} // namespace v0
