/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.0.v202012010944.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
#ifndef V0_IMICRO_SOC__CHANNEL__DLT_SOMEIP_STUB_ADAPTER_HPP_
#define V0_IMICRO_SOC__CHANNEL__DLT_SOMEIP_STUB_ADAPTER_HPP_

#include <v0/iMicro/SOC_Channel_DLTStub.hpp>
#include <v0/iMicro/SOC_Channel_DLTSomeIPDeployment.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/SomeIP/AddressTranslator.hpp>
#include <CommonAPI/SomeIP/StubAdapterHelper.hpp>
#include <CommonAPI/SomeIP/StubAdapter.hpp>
#include <CommonAPI/SomeIP/Factory.hpp>
#include <CommonAPI/SomeIP/Types.hpp>
#include <CommonAPI/SomeIP/Constants.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v0 {
namespace iMicro {

template <typename _Stub = ::v0::iMicro::SOC_Channel_DLTStub, typename... _Stubs>
class SOC_Channel_DLTSomeIPStubAdapterInternal
    : public virtual SOC_Channel_DLTStubAdapter,
      public CommonAPI::SomeIP::StubAdapterHelper< _Stub, _Stubs...>,
      public std::enable_shared_from_this< SOC_Channel_DLTSomeIPStubAdapterInternal<_Stub, _Stubs...>>
{
public:
    typedef CommonAPI::SomeIP::StubAdapterHelper< _Stub, _Stubs...> SOC_Channel_DLTSomeIPStubAdapterHelper;

    ~SOC_Channel_DLTSomeIPStubAdapterInternal() {
        deactivateManagedInstances();
        SOC_Channel_DLTSomeIPStubAdapterHelper::deinit();
    }

    void fireGetRawEvent(const CommonAPI::ByteBuffer &_data);

    void deactivateManagedInstances() {}
    
    CommonAPI::SomeIP::GetAttributeStubDispatcher<
        ::v0::iMicro::SOC_Channel_DLTStub,
        CommonAPI::Version
    > getSOC_Channel_DLTInterfaceVersionStubDispatcher;

    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v0::iMicro::SOC_Channel_DLTStub,
        std::tuple< CommonAPI::ByteBuffer>,
        std::tuple< uint32_t>,
        std::tuple< CommonAPI::SomeIP::ByteBufferDeployment>,
        std::tuple< CommonAPI::SomeIP::IntegerDeployment<uint32_t>>
    > sendRawStubDispatcher;
    
    SOC_Channel_DLTSomeIPStubAdapterInternal(
        const CommonAPI::SomeIP::Address &_address,
        const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection,
        const std::shared_ptr<CommonAPI::StubBase> &_stub):
        CommonAPI::SomeIP::StubAdapter(_address, _connection),
        SOC_Channel_DLTSomeIPStubAdapterHelper(
            _address,
            _connection,
            std::dynamic_pointer_cast< SOC_Channel_DLTStub>(_stub)),
        getSOC_Channel_DLTInterfaceVersionStubDispatcher(&SOC_Channel_DLTStub::lockInterfaceVersionAttribute, &SOC_Channel_DLTStub::getInterfaceVersion, false, true),
        sendRawStubDispatcher(
            &SOC_Channel_DLTStub::SendRaw,
            false,
            _stub->hasElement(1),
            std::make_tuple(static_cast< CommonAPI::SomeIP::ByteBufferDeployment* >(nullptr)),
            std::make_tuple(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr)))
        
    {
        SOC_Channel_DLTSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x13) }, &sendRawStubDispatcher );
        // Provided events/fields
        {
            std::set<CommonAPI::SomeIP::eventgroup_id_t> itsEventGroups;
            itsEventGroups.insert(CommonAPI::SomeIP::eventgroup_id_t(0x80f7));
            CommonAPI::SomeIP::StubAdapter::registerEvent(CommonAPI::SomeIP::event_id_t(0x80f7), itsEventGroups, CommonAPI::SomeIP::event_type_e::ET_EVENT, CommonAPI::SomeIP::reliability_type_e::RT_UNRELIABLE);
        }
    }

    // Register/Unregister event handlers for selective broadcasts
    void registerSelectiveEventHandlers();
    void unregisterSelectiveEventHandlers();

};

template <typename _Stub, typename... _Stubs>
void SOC_Channel_DLTSomeIPStubAdapterInternal<_Stub, _Stubs...>::fireGetRawEvent(const CommonAPI::ByteBuffer &_data) {
    CommonAPI::Deployable< CommonAPI::ByteBuffer, CommonAPI::SomeIP::ByteBufferDeployment> deployed_data(_data, static_cast< CommonAPI::SomeIP::ByteBufferDeployment* >(nullptr));
    CommonAPI::SomeIP::StubEventHelper<CommonAPI::SomeIP::SerializableArguments<  CommonAPI::Deployable< CommonAPI::ByteBuffer, CommonAPI::SomeIP::ByteBufferDeployment > 
    >>
        ::sendEvent(
            *this,
            CommonAPI::SomeIP::event_id_t(0x80f7),
            false,
             deployed_data 
    );
}


template <typename _Stub, typename... _Stubs>
void SOC_Channel_DLTSomeIPStubAdapterInternal<_Stub, _Stubs...>::registerSelectiveEventHandlers() {
}

template <typename _Stub, typename... _Stubs>
void SOC_Channel_DLTSomeIPStubAdapterInternal<_Stub, _Stubs...>::unregisterSelectiveEventHandlers() {
}

template <typename _Stub = ::v0::iMicro::SOC_Channel_DLTStub, typename... _Stubs>
class SOC_Channel_DLTSomeIPStubAdapter
    : public SOC_Channel_DLTSomeIPStubAdapterInternal<_Stub, _Stubs...> {
public:
    SOC_Channel_DLTSomeIPStubAdapter(const CommonAPI::SomeIP::Address &_address,
                                            const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection,
                                            const std::shared_ptr<CommonAPI::StubBase> &_stub)
        : CommonAPI::SomeIP::StubAdapter(_address, _connection),
          SOC_Channel_DLTSomeIPStubAdapterInternal<_Stub, _Stubs...>(_address, _connection, _stub) {
    }
};

} // namespace iMicro
} // namespace v0

#endif // V0_IMICRO_SOC__Channel__DLT_SOMEIP_STUB_ADAPTER_HPP_
