/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.0.v202012010850.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V0_IMICRO_SOC__ACC_Gyro_PROXY_BASE_HPP_
#define V0_IMICRO_SOC__ACC_Gyro_PROXY_BASE_HPP_

#include <v0/iMicro/SOC_ACCGyro.hpp>


#include <iMicro/iMicroStructs.hpp>
#include <iMicro/iMicroTypes.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/Deployment.hpp>
#include <CommonAPI/InputStream.hpp>
#include <CommonAPI/OutputStream.hpp>
#include <CommonAPI/Struct.hpp>
#include <cstdint>
#include <vector>

#include <CommonAPI/Event.hpp>
#include <CommonAPI/Proxy.hpp>
#include <functional>
#include <future>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v0 {
namespace iMicro {

class SOC_ACCGyroProxyBase
    : virtual public CommonAPI::Proxy {
public:
    typedef CommonAPI::Event<
        ::iMicro::iMicroStructs::accgyro_6Dvalue_type
    > SignalResponse_AccGyro_6DValueEvent;
    typedef CommonAPI::Event<
        ::iMicro::iMicroStructs::accgyro_settingacquisition_type
    > SignalResponse_AccGyro_settingAcquisitionEvent;
    typedef CommonAPI::Event<
        ::iMicro::iMicroStructs::accgyro_powermodestatus_type
    > SignalResponse_AccGyro_powerModeStatusEvent;


    /**
     * @invariant Fire And Forget
     */
    virtual void SendCommand_AccGyro_req_6DValue(uint8_t _AccGyro_req_6DValue, CommonAPI::CallStatus &_internalCallStatus) = 0;
    /**
     * @invariant Fire And Forget
     */
    virtual void SendCommand_AccGyro_setSettingAcquisition(::iMicro::iMicroStructs::accgyro_set_settingacquisition_type _AccGyro_setSettingAcquisition, CommonAPI::CallStatus &_internalCallStatus) = 0;
    /**
     * @invariant Fire And Forget
     */
    virtual void SendCommand_AccGyro_reqSettingAcquisition(uint8_t _AccGyro_reqSettingAcquisition, CommonAPI::CallStatus &_internalCallStatus) = 0;
    /**
     * @invariant Fire And Forget
     */
    virtual void SendCommand_AccGyro_setPowerMode(::iMicro::iMicroStructs::accgyro_setpowermode_type _AccGyro_setPowerMode, CommonAPI::CallStatus &_internalCallStatus) = 0;
    /**
     * @invariant Fire And Forget
     */
    virtual void SendCommand_AccGyro_setSlopeThreshold(::iMicro::iMicroStructs::accgyro_setslopethreshold_type _AccGyro_setSlopeThreshold, CommonAPI::CallStatus &_internalCallStatus) = 0;
    /**
     * @invariant Fire And Forget
     */
    virtual void SendCommand_AccGyro_enableUnsolicited(::iMicro::iMicroStructs::accgyro_enableunsolicited_type _AccGyro_enableUnsolicited, CommonAPI::CallStatus &_internalCallStatus) = 0;
    virtual SignalResponse_AccGyro_6DValueEvent& getSignalResponse_AccGyro_6DValueEvent() = 0;
    virtual SignalResponse_AccGyro_settingAcquisitionEvent& getSignalResponse_AccGyro_settingAcquisitionEvent() = 0;
    virtual SignalResponse_AccGyro_powerModeStatusEvent& getSignalResponse_AccGyro_powerModeStatusEvent() = 0;

    virtual std::future<void> getCompletionFuture() = 0;
};

} // namespace iMicro
} // namespace v0


// Compatibility
namespace v0_1 = v0;

#endif // V0_IMICRO_SOC__ACC_Gyro_PROXY_BASE_HPP_
