/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.0.v202012010850.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V0_IMICRO_SOC__NAD_PROXY_HPP_
#define V0_IMICRO_SOC__NAD_PROXY_HPP_

#include <v0/iMicro/SOC_NADProxyBase.hpp>


#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif


#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v0 {
namespace iMicro {

template <typename ... _AttributeExtensions>
class SOC_NADProxy
    : virtual public SOC_NAD,
      virtual public SOC_NADProxyBase,
      virtual public _AttributeExtensions... {
public:
    SOC_NADProxy(std::shared_ptr<CommonAPI::Proxy> delegate);
    ~SOC_NADProxy();

    typedef SOC_NAD InterfaceType;


    /**
     * Returns the CommonAPI address of the remote partner this proxy communicates with.
     */
    virtual const CommonAPI::Address &getAddress() const;

    /**
     * Returns true if the remote partner for this proxy is currently known to be available.
     */
    virtual bool isAvailable() const;

    /**
     * Returns true if the remote partner for this proxy is available.
     */
    virtual bool isAvailableBlocking() const;

    /**
     * Returns the wrapper class that is used to (de-)register for notifications about
     * the availability of the remote partner of this proxy.
     */
    virtual CommonAPI::ProxyStatusEvent& getProxyStatusEvent();

    /**
     * Returns the wrapper class that is used to access version information of the remote
     * partner of this proxy.
     */
    virtual CommonAPI::InterfaceVersionAttribute& getInterfaceVersionAttribute();

    virtual std::future<void> getCompletionFuture();

    /**
     * Calls GetEvent_Modem_softReset with synchronous semantics.
     *
     * All non-const parameters will be filled with the returned values.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void GetEvent_Modem_softReset(CommonAPI::CallStatus &_internalCallStatus, uint8_t &_Modem_softReset, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls GetEvent_Modem_softReset with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> GetEvent_Modem_softResetAsync(GetEvent_Modem_softResetAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Returns the wrapper class that provides access to the broadcast SignalEvent_Modem_softReset.
     */
    virtual SignalEvent_Modem_softResetEvent& getSignalEvent_Modem_softResetEvent() {
        return delegate_->getSignalEvent_Modem_softResetEvent();
    }
    /**
     * Calls GetEvent_Modem_shutDown with synchronous semantics.
     *
     * All non-const parameters will be filled with the returned values.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void GetEvent_Modem_shutDown(CommonAPI::CallStatus &_internalCallStatus, uint8_t &_Modem_shutDown, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls GetEvent_Modem_shutDown with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> GetEvent_Modem_shutDownAsync(GetEvent_Modem_shutDownAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Returns the wrapper class that provides access to the broadcast SignalEvent_Modem_shutDown.
     */
    virtual SignalEvent_Modem_shutDownEvent& getSignalEvent_Modem_shutDownEvent() {
        return delegate_->getSignalEvent_Modem_shutDownEvent();
    }



 private:
    std::shared_ptr< SOC_NADProxyBase> delegate_;
};

typedef SOC_NADProxy<> SOC_NADProxyDefault;


//
// SOC_NADProxy Implementation
//
template <typename ... _AttributeExtensions>
SOC_NADProxy<_AttributeExtensions...>::SOC_NADProxy(std::shared_ptr<CommonAPI::Proxy> delegate):
        _AttributeExtensions(*(std::dynamic_pointer_cast< SOC_NADProxyBase>(delegate)))...,
        delegate_(std::dynamic_pointer_cast< SOC_NADProxyBase>(delegate)) {
}

template <typename ... _AttributeExtensions>
SOC_NADProxy<_AttributeExtensions...>::~SOC_NADProxy() {
}

template <typename ... _AttributeExtensions>
void SOC_NADProxy<_AttributeExtensions...>::GetEvent_Modem_softReset(CommonAPI::CallStatus &_internalCallStatus, uint8_t &_Modem_softReset, const CommonAPI::CallInfo *_info) {
    delegate_->GetEvent_Modem_softReset(_internalCallStatus, _Modem_softReset, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> SOC_NADProxy<_AttributeExtensions...>::GetEvent_Modem_softResetAsync(GetEvent_Modem_softResetAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    return delegate_->GetEvent_Modem_softResetAsync(_callback, _info);
}
template <typename ... _AttributeExtensions>
void SOC_NADProxy<_AttributeExtensions...>::GetEvent_Modem_shutDown(CommonAPI::CallStatus &_internalCallStatus, uint8_t &_Modem_shutDown, const CommonAPI::CallInfo *_info) {
    delegate_->GetEvent_Modem_shutDown(_internalCallStatus, _Modem_shutDown, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> SOC_NADProxy<_AttributeExtensions...>::GetEvent_Modem_shutDownAsync(GetEvent_Modem_shutDownAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    return delegate_->GetEvent_Modem_shutDownAsync(_callback, _info);
}

template <typename ... _AttributeExtensions>
const CommonAPI::Address &SOC_NADProxy<_AttributeExtensions...>::getAddress() const {
    return delegate_->getAddress();
}

template <typename ... _AttributeExtensions>
bool SOC_NADProxy<_AttributeExtensions...>::isAvailable() const {
    return delegate_->isAvailable();
}

template <typename ... _AttributeExtensions>
bool SOC_NADProxy<_AttributeExtensions...>::isAvailableBlocking() const {
    return delegate_->isAvailableBlocking();
}

template <typename ... _AttributeExtensions>
CommonAPI::ProxyStatusEvent& SOC_NADProxy<_AttributeExtensions...>::getProxyStatusEvent() {
    return delegate_->getProxyStatusEvent();
}

template <typename ... _AttributeExtensions>
CommonAPI::InterfaceVersionAttribute& SOC_NADProxy<_AttributeExtensions...>::getInterfaceVersionAttribute() {
    return delegate_->getInterfaceVersionAttribute();
}


template <typename ... _AttributeExtensions>
std::future<void> SOC_NADProxy<_AttributeExtensions...>::getCompletionFuture() {
    return delegate_->getCompletionFuture();
}

} // namespace iMicro
} // namespace v0



// Compatibility
namespace v0_1 = v0;

#endif // V0_IMICRO_SOC__NAD_PROXY_HPP_
