/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.0.v202012010944.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
#include <v0/iMicro/SOC_SENSORSomeIPProxy.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/SomeIP/AddressTranslator.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v0 {
namespace iMicro {

std::shared_ptr<CommonAPI::SomeIP::Proxy> createSOC_SENSORSomeIPProxy(
    const CommonAPI::SomeIP::Address &_address,
    const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection) {
    return std::make_shared< SOC_SENSORSomeIPProxy>(_address, _connection);
}

void initializeSOC_SENSORSomeIPProxy() {
    CommonAPI::SomeIP::AddressTranslator::get()->insert(
        "local:iMicro.SOC_SENSOR:v0_1:iMicro.SOC_SENSOR",
        0x123e, 0x5684, 0, 1);
    CommonAPI::SomeIP::Factory::get()->registerProxyCreateMethod(
        "iMicro.SOC_SENSOR:v0_1",
        &createSOC_SENSORSomeIPProxy);
}

INITIALIZER(registerSOC_SENSORSomeIPProxy) {
    CommonAPI::SomeIP::Factory::get()->registerInterface(initializeSOC_SENSORSomeIPProxy);
}

SOC_SENSORSomeIPProxy::SOC_SENSORSomeIPProxy(
    const CommonAPI::SomeIP::Address &_address,
    const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection)
        : CommonAPI::SomeIP::Proxy(_address, _connection),
          signalResponse_Ntc_value_(*this, 0x8105, CommonAPI::SomeIP::event_id_t(0x8105), CommonAPI::SomeIP::event_type_e::ET_EVENT , CommonAPI::SomeIP::reliability_type_e::RT_UNRELIABLE, false, std::make_tuple(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr)))
{
}

SOC_SENSORSomeIPProxy::~SOC_SENSORSomeIPProxy() {
    completed_.set_value();
}


SOC_SENSORSomeIPProxy::SignalResponse_Ntc_valueEvent& SOC_SENSORSomeIPProxy::getSignalResponse_Ntc_valueEvent() {
    return signalResponse_Ntc_value_;
}

void SOC_SENSORSomeIPProxy::SendCommand_Ntc_reqValue(uint8_t _Ntc_reqValue, CommonAPI::CallStatus &_internalCallStatus) {
    CommonAPI::Deployable< uint8_t, CommonAPI::SomeIP::IntegerDeployment<uint8_t>> deploy_Ntc_reqValue(_Ntc_reqValue, static_cast< CommonAPI::SomeIP::IntegerDeployment<uint8_t>* >(nullptr));
    CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                uint8_t,
                CommonAPI::SomeIP::IntegerDeployment<uint8_t>
            >
        >,
        CommonAPI::SomeIP::SerializableArguments<
        >
    >::callMethod(
        *this,
        CommonAPI::SomeIP::method_id_t(0x2d),
        false,
        false,
        deploy_Ntc_reqValue,
        _internalCallStatus);
}

void SOC_SENSORSomeIPProxy::getOwnVersion(uint16_t& ownVersionMajor, uint16_t& ownVersionMinor) const {
    ownVersionMajor = 0;
    ownVersionMinor = 1;
}

std::future<void> SOC_SENSORSomeIPProxy::getCompletionFuture() {
    return completed_.get_future();
}

} // namespace iMicro
} // namespace v0
