/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.0.v202012010944.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
#include <v0/iMicro/SOC_ButtonSomeIPStubAdapter.hpp>
#include <v0/iMicro/SOC_Button.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/SomeIP/AddressTranslator.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v0 {
namespace iMicro {

std::shared_ptr<CommonAPI::SomeIP::StubAdapter> createSOC_ButtonSomeIPStubAdapter(
                   const CommonAPI::SomeIP::Address &_address,
                   const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection,
                   const std::shared_ptr<CommonAPI::StubBase> &_stub) {
    return std::make_shared< SOC_ButtonSomeIPStubAdapter<::v0::iMicro::SOC_ButtonStub>>(_address, _connection, _stub);
}

void initializeSOC_ButtonSomeIPStubAdapter() {
    CommonAPI::SomeIP::AddressTranslator::get()->insert(
        "local:iMicro.SOC_Button:v0_1:iMicro.SOC_Button",
         0x123a, 0x5680, 0, 1);
    CommonAPI::SomeIP::Factory::get()->registerStubAdapterCreateMethod(
        "iMicro.SOC_Button:v0_1",
        &createSOC_ButtonSomeIPStubAdapter);
}

INITIALIZER(registerSOC_ButtonSomeIPStubAdapter) {
    CommonAPI::SomeIP::Factory::get()->registerInterface(initializeSOC_ButtonSomeIPStubAdapter);
}

} // namespace iMicro
} // namespace v0
