/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.0.v202012010944.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
#include <v0/iMicro/SOC_SQDFdiagserverSomeIPProxy.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/SomeIP/AddressTranslator.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v0 {
namespace iMicro {

std::shared_ptr<CommonAPI::SomeIP::Proxy> createSOC_SQDFdiagserverSomeIPProxy(
    const CommonAPI::SomeIP::Address &_address,
    const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection) {
    return std::make_shared< SOC_SQDFdiagserverSomeIPProxy>(_address, _connection);
}

void initializeSOC_SQDFdiagserverSomeIPProxy() {
    CommonAPI::SomeIP::AddressTranslator::get()->insert(
        "local:iMicro.SOC_SQDFdiagserver:v0_1:iMicro.SOC_SQDFdiagserver",
        0x1247, 0x568d, 0, 1);
    CommonAPI::SomeIP::Factory::get()->registerProxyCreateMethod(
        "iMicro.SOC_SQDFdiagserver:v0_1",
        &createSOC_SQDFdiagserverSomeIPProxy);
}

INITIALIZER(registerSOC_SQDFdiagserverSomeIPProxy) {
    CommonAPI::SomeIP::Factory::get()->registerInterface(initializeSOC_SQDFdiagserverSomeIPProxy);
}

SOC_SQDFdiagserverSomeIPProxy::SOC_SQDFdiagserverSomeIPProxy(
    const CommonAPI::SomeIP::Address &_address,
    const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection)
        : CommonAPI::SomeIP::Proxy(_address, _connection),
          signalResponse_DiagnosticRequest_resp_(*this, 0x8114, CommonAPI::SomeIP::event_id_t(0x8114), CommonAPI::SomeIP::event_type_e::ET_EVENT , CommonAPI::SomeIP::reliability_type_e::RT_UNRELIABLE, false, std::make_tuple(static_cast< ::iMicro::iMicroStructs_::DiagnosticRequest_resp_typeDeployment_t* >(nullptr))),
          signalResponse_EcuProtocolDetection_resp_(*this, 0x8126, CommonAPI::SomeIP::event_id_t(0x8126), CommonAPI::SomeIP::event_type_e::ET_EVENT , CommonAPI::SomeIP::reliability_type_e::RT_UNRELIABLE, false, std::make_tuple(static_cast< ::iMicro::iMicroStructs_::EcuProtocolDetection_resp_typeDeployment_t* >(nullptr))),
          signalResponse_Configure_resp_(*this, 0x8115, CommonAPI::SomeIP::event_id_t(0x8115), CommonAPI::SomeIP::event_type_e::ET_EVENT , CommonAPI::SomeIP::reliability_type_e::RT_UNRELIABLE, false, std::make_tuple(static_cast< ::iMicro::iMicroStructs_::Configure_resp_typeDeployment_t* >(nullptr))),
          signalEvent_TesterActivityDetected_(*this, 0x8116, CommonAPI::SomeIP::event_id_t(0x8116), CommonAPI::SomeIP::event_type_e::ET_EVENT , CommonAPI::SomeIP::reliability_type_e::RT_UNRELIABLE, false, std::make_tuple(static_cast< ::iMicro::iMicroStructs_::TesterActivityDetected_typeDeployment_t* >(nullptr))),
          signalResponse_GetTesterActivity_resp_(*this, 0x8117, CommonAPI::SomeIP::event_id_t(0x8117), CommonAPI::SomeIP::event_type_e::ET_EVENT , CommonAPI::SomeIP::reliability_type_e::RT_UNRELIABLE, false, std::make_tuple(static_cast< ::iMicro::iMicroStructs_::GetTesterActivity_resp_typeDeployment_t* >(nullptr))),
          signalResponse_RDASession_resp_(*this, 0x8118, CommonAPI::SomeIP::event_id_t(0x8118), CommonAPI::SomeIP::event_type_e::ET_EVENT , CommonAPI::SomeIP::reliability_type_e::RT_UNRELIABLE, false, std::make_tuple(static_cast< ::iMicro::iMicroStructs_::RDASession_resp_typeDeployment_t* >(nullptr))),
          signalResponse_RDAConfiguration_resp_(*this, 0x8119, CommonAPI::SomeIP::event_id_t(0x8119), CommonAPI::SomeIP::event_type_e::ET_EVENT , CommonAPI::SomeIP::reliability_type_e::RT_UNRELIABLE, false, std::make_tuple(static_cast< ::iMicro::iMicroStructs_::RDAConfiguration_resp_typeDeployment_t* >(nullptr))),
          signalResponse_RDADiagnosticRequestACK_(*this, 0x811a, CommonAPI::SomeIP::event_id_t(0x811a), CommonAPI::SomeIP::event_type_e::ET_EVENT , CommonAPI::SomeIP::reliability_type_e::RT_UNRELIABLE, false, std::make_tuple(static_cast< ::iMicro::iMicroStructs_::RDADiagnosticRequestACK_typeDeployment_t* >(nullptr))),
          signalResponse_RDADiagnostic_resp_(*this, 0x811b, CommonAPI::SomeIP::event_id_t(0x811b), CommonAPI::SomeIP::event_type_e::ET_EVENT , CommonAPI::SomeIP::reliability_type_e::RT_UNRELIABLE, false, std::make_tuple(static_cast< ::iMicro::iMicroStructs_::RDADiagnostic_resp_typeDeployment_t* >(nullptr)))
{
}

SOC_SQDFdiagserverSomeIPProxy::~SOC_SQDFdiagserverSomeIPProxy() {
    completed_.set_value();
}


SOC_SQDFdiagserverSomeIPProxy::SignalResponse_DiagnosticRequest_respEvent& SOC_SQDFdiagserverSomeIPProxy::getSignalResponse_DiagnosticRequest_respEvent() {
    return signalResponse_DiagnosticRequest_resp_;
}
SOC_SQDFdiagserverSomeIPProxy::SignalResponse_EcuProtocolDetection_respEvent& SOC_SQDFdiagserverSomeIPProxy::getSignalResponse_EcuProtocolDetection_respEvent() {
    return signalResponse_EcuProtocolDetection_resp_;
}
SOC_SQDFdiagserverSomeIPProxy::SignalResponse_Configure_respEvent& SOC_SQDFdiagserverSomeIPProxy::getSignalResponse_Configure_respEvent() {
    return signalResponse_Configure_resp_;
}
SOC_SQDFdiagserverSomeIPProxy::SignalEvent_TesterActivityDetectedEvent& SOC_SQDFdiagserverSomeIPProxy::getSignalEvent_TesterActivityDetectedEvent() {
    return signalEvent_TesterActivityDetected_;
}
SOC_SQDFdiagserverSomeIPProxy::SignalResponse_GetTesterActivity_respEvent& SOC_SQDFdiagserverSomeIPProxy::getSignalResponse_GetTesterActivity_respEvent() {
    return signalResponse_GetTesterActivity_resp_;
}
SOC_SQDFdiagserverSomeIPProxy::SignalResponse_RDASession_respEvent& SOC_SQDFdiagserverSomeIPProxy::getSignalResponse_RDASession_respEvent() {
    return signalResponse_RDASession_resp_;
}
SOC_SQDFdiagserverSomeIPProxy::SignalResponse_RDAConfiguration_respEvent& SOC_SQDFdiagserverSomeIPProxy::getSignalResponse_RDAConfiguration_respEvent() {
    return signalResponse_RDAConfiguration_resp_;
}
SOC_SQDFdiagserverSomeIPProxy::SignalResponse_RDADiagnosticRequestACKEvent& SOC_SQDFdiagserverSomeIPProxy::getSignalResponse_RDADiagnosticRequestACKEvent() {
    return signalResponse_RDADiagnosticRequestACK_;
}
SOC_SQDFdiagserverSomeIPProxy::SignalResponse_RDADiagnostic_respEvent& SOC_SQDFdiagserverSomeIPProxy::getSignalResponse_RDADiagnostic_respEvent() {
    return signalResponse_RDADiagnostic_resp_;
}

void SOC_SQDFdiagserverSomeIPProxy::SendCommand_DiagnosticRequest_cmd(::iMicro::iMicroStructs::DiagnosticRequest_cmd_type _DiagnosticRequest_cmd, CommonAPI::CallStatus &_internalCallStatus) {
    CommonAPI::Deployable< ::iMicro::iMicroStructs::DiagnosticRequest_cmd_type, ::iMicro::iMicroStructs_::DiagnosticRequest_cmd_typeDeployment_t> deploy_DiagnosticRequest_cmd(_DiagnosticRequest_cmd, static_cast< ::iMicro::iMicroStructs_::DiagnosticRequest_cmd_typeDeployment_t* >(nullptr));
    CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                ::iMicro::iMicroStructs::DiagnosticRequest_cmd_type,
                ::iMicro::iMicroStructs_::DiagnosticRequest_cmd_typeDeployment_t
            >
        >,
        CommonAPI::SomeIP::SerializableArguments<
        >
    >::callMethod(
        *this,
        CommonAPI::SomeIP::method_id_t(0x3b),
        false,
        false,
        deploy_DiagnosticRequest_cmd,
        _internalCallStatus);
}

void SOC_SQDFdiagserverSomeIPProxy::SendCommand_EcuProtocolDetection_cmd(::iMicro::iMicroStructs::EcuProtocolDetection_cmd_type _EcuProtocolDetection_cmd, CommonAPI::CallStatus &_internalCallStatus) {
    CommonAPI::Deployable< ::iMicro::iMicroStructs::EcuProtocolDetection_cmd_type, ::iMicro::iMicroStructs_::EcuProtocolDetection_cmd_typeDeployment_t> deploy_EcuProtocolDetection_cmd(_EcuProtocolDetection_cmd, static_cast< ::iMicro::iMicroStructs_::EcuProtocolDetection_cmd_typeDeployment_t* >(nullptr));
    CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                ::iMicro::iMicroStructs::EcuProtocolDetection_cmd_type,
                ::iMicro::iMicroStructs_::EcuProtocolDetection_cmd_typeDeployment_t
            >
        >,
        CommonAPI::SomeIP::SerializableArguments<
        >
    >::callMethod(
        *this,
        CommonAPI::SomeIP::method_id_t(0x3c),
        false,
        false,
        deploy_EcuProtocolDetection_cmd,
        _internalCallStatus);
}

void SOC_SQDFdiagserverSomeIPProxy::SendCommand_Configure_cmd(::iMicro::iMicroStructs::Configure_cmd_type _Configure_cmd, CommonAPI::CallStatus &_internalCallStatus) {
    CommonAPI::Deployable< ::iMicro::iMicroStructs::Configure_cmd_type, ::iMicro::iMicroStructs_::Configure_cmd_typeDeployment_t> deploy_Configure_cmd(_Configure_cmd, static_cast< ::iMicro::iMicroStructs_::Configure_cmd_typeDeployment_t* >(nullptr));
    CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                ::iMicro::iMicroStructs::Configure_cmd_type,
                ::iMicro::iMicroStructs_::Configure_cmd_typeDeployment_t
            >
        >,
        CommonAPI::SomeIP::SerializableArguments<
        >
    >::callMethod(
        *this,
        CommonAPI::SomeIP::method_id_t(0x3d),
        false,
        false,
        deploy_Configure_cmd,
        _internalCallStatus);
}

void SOC_SQDFdiagserverSomeIPProxy::SendCommand_GetTesterActivity_cmd(uint8_t _GetTesterActivity_cmd, CommonAPI::CallStatus &_internalCallStatus) {
    CommonAPI::Deployable< uint8_t, CommonAPI::SomeIP::IntegerDeployment<uint8_t>> deploy_GetTesterActivity_cmd(_GetTesterActivity_cmd, static_cast< CommonAPI::SomeIP::IntegerDeployment<uint8_t>* >(nullptr));
    CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                uint8_t,
                CommonAPI::SomeIP::IntegerDeployment<uint8_t>
            >
        >,
        CommonAPI::SomeIP::SerializableArguments<
        >
    >::callMethod(
        *this,
        CommonAPI::SomeIP::method_id_t(0x3e),
        false,
        false,
        deploy_GetTesterActivity_cmd,
        _internalCallStatus);
}

void SOC_SQDFdiagserverSomeIPProxy::SendEvent_RDASession_Request(::iMicro::iMicroStructs::RDASessionRequest_Type _RDASession_Request, CommonAPI::CallStatus &_internalCallStatus, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< ::iMicro::iMicroStructs::RDASessionRequest_Type, ::iMicro::iMicroStructs_::RDASessionRequest_TypeDeployment_t> deploy_RDASession_Request(_RDASession_Request, static_cast< ::iMicro::iMicroStructs_::RDASessionRequest_TypeDeployment_t* >(nullptr));
    CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                ::iMicro::iMicroStructs::RDASessionRequest_Type,
                ::iMicro::iMicroStructs_::RDASessionRequest_TypeDeployment_t
            >
        >,
        CommonAPI::SomeIP::SerializableArguments<
        >
    >::callMethodWithReply(
        *this,
        CommonAPI::SomeIP::method_id_t(0x3f),
        false,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        deploy_RDASession_Request,
        _internalCallStatus);
}

std::future<CommonAPI::CallStatus> SOC_SQDFdiagserverSomeIPProxy::SendEvent_RDASession_RequestAsync(const ::iMicro::iMicroStructs::RDASessionRequest_Type &_RDASession_Request, SendEvent_RDASession_RequestAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< ::iMicro::iMicroStructs::RDASessionRequest_Type, ::iMicro::iMicroStructs_::RDASessionRequest_TypeDeployment_t> deploy_RDASession_Request(_RDASession_Request, static_cast< ::iMicro::iMicroStructs_::RDASessionRequest_TypeDeployment_t* >(nullptr));
    return CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                ::iMicro::iMicroStructs::RDASessionRequest_Type,
                ::iMicro::iMicroStructs_::RDASessionRequest_TypeDeployment_t
            >
        >,
        CommonAPI::SomeIP::SerializableArguments<
        >
    >::callMethodAsync(
        *this,
        CommonAPI::SomeIP::method_id_t(0x3f),
        false,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        deploy_RDASession_Request,
        [_callback] (CommonAPI::CallStatus _internalCallStatus) {
            if (_callback)
                _callback(_internalCallStatus);
        },
        std::make_tuple());
}

void SOC_SQDFdiagserverSomeIPProxy::SendEvent_RDAConfiguration_Request(::iMicro::iMicroStructs::RDAConfigurationRequest_type _RDAConfiguration_Request, CommonAPI::CallStatus &_internalCallStatus, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< ::iMicro::iMicroStructs::RDAConfigurationRequest_type, ::iMicro::iMicroStructs_::RDAConfigurationRequest_typeDeployment_t> deploy_RDAConfiguration_Request(_RDAConfiguration_Request, static_cast< ::iMicro::iMicroStructs_::RDAConfigurationRequest_typeDeployment_t* >(nullptr));
    CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                ::iMicro::iMicroStructs::RDAConfigurationRequest_type,
                ::iMicro::iMicroStructs_::RDAConfigurationRequest_typeDeployment_t
            >
        >,
        CommonAPI::SomeIP::SerializableArguments<
        >
    >::callMethodWithReply(
        *this,
        CommonAPI::SomeIP::method_id_t(0x40),
        false,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        deploy_RDAConfiguration_Request,
        _internalCallStatus);
}

std::future<CommonAPI::CallStatus> SOC_SQDFdiagserverSomeIPProxy::SendEvent_RDAConfiguration_RequestAsync(const ::iMicro::iMicroStructs::RDAConfigurationRequest_type &_RDAConfiguration_Request, SendEvent_RDAConfiguration_RequestAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< ::iMicro::iMicroStructs::RDAConfigurationRequest_type, ::iMicro::iMicroStructs_::RDAConfigurationRequest_typeDeployment_t> deploy_RDAConfiguration_Request(_RDAConfiguration_Request, static_cast< ::iMicro::iMicroStructs_::RDAConfigurationRequest_typeDeployment_t* >(nullptr));
    return CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                ::iMicro::iMicroStructs::RDAConfigurationRequest_type,
                ::iMicro::iMicroStructs_::RDAConfigurationRequest_typeDeployment_t
            >
        >,
        CommonAPI::SomeIP::SerializableArguments<
        >
    >::callMethodAsync(
        *this,
        CommonAPI::SomeIP::method_id_t(0x40),
        false,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        deploy_RDAConfiguration_Request,
        [_callback] (CommonAPI::CallStatus _internalCallStatus) {
            if (_callback)
                _callback(_internalCallStatus);
        },
        std::make_tuple());
}

void SOC_SQDFdiagserverSomeIPProxy::SendEvent_RDADiagnostic_Request(::iMicro::iMicroStructs::RDADiagnosticRequest_type _RDADiagnostic_Request, CommonAPI::CallStatus &_internalCallStatus, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< ::iMicro::iMicroStructs::RDADiagnosticRequest_type, ::iMicro::iMicroStructs_::RDADiagnosticRequest_typeDeployment_t> deploy_RDADiagnostic_Request(_RDADiagnostic_Request, static_cast< ::iMicro::iMicroStructs_::RDADiagnosticRequest_typeDeployment_t* >(nullptr));
    CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                ::iMicro::iMicroStructs::RDADiagnosticRequest_type,
                ::iMicro::iMicroStructs_::RDADiagnosticRequest_typeDeployment_t
            >
        >,
        CommonAPI::SomeIP::SerializableArguments<
        >
    >::callMethodWithReply(
        *this,
        CommonAPI::SomeIP::method_id_t(0x41),
        false,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        deploy_RDADiagnostic_Request,
        _internalCallStatus);
}

std::future<CommonAPI::CallStatus> SOC_SQDFdiagserverSomeIPProxy::SendEvent_RDADiagnostic_RequestAsync(const ::iMicro::iMicroStructs::RDADiagnosticRequest_type &_RDADiagnostic_Request, SendEvent_RDADiagnostic_RequestAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< ::iMicro::iMicroStructs::RDADiagnosticRequest_type, ::iMicro::iMicroStructs_::RDADiagnosticRequest_typeDeployment_t> deploy_RDADiagnostic_Request(_RDADiagnostic_Request, static_cast< ::iMicro::iMicroStructs_::RDADiagnosticRequest_typeDeployment_t* >(nullptr));
    return CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                ::iMicro::iMicroStructs::RDADiagnosticRequest_type,
                ::iMicro::iMicroStructs_::RDADiagnosticRequest_typeDeployment_t
            >
        >,
        CommonAPI::SomeIP::SerializableArguments<
        >
    >::callMethodAsync(
        *this,
        CommonAPI::SomeIP::method_id_t(0x41),
        false,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        deploy_RDADiagnostic_Request,
        [_callback] (CommonAPI::CallStatus _internalCallStatus) {
            if (_callback)
                _callback(_internalCallStatus);
        },
        std::make_tuple());
}

void SOC_SQDFdiagserverSomeIPProxy::GetEvent_TesterActivityDetected(CommonAPI::CallStatus &_internalCallStatus, ::iMicro::iMicroStructs::TesterActivityDetected_type &_TesterActivityDetected, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< ::iMicro::iMicroStructs::TesterActivityDetected_type, ::iMicro::iMicroStructs_::TesterActivityDetected_typeDeployment_t> deploy_TesterActivityDetected(static_cast< ::iMicro::iMicroStructs_::TesterActivityDetected_typeDeployment_t* >(nullptr));
    CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
        >,
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                ::iMicro::iMicroStructs::TesterActivityDetected_type,
                ::iMicro::iMicroStructs_::TesterActivityDetected_typeDeployment_t
            >
        >
    >::callMethodWithReply(
        *this,
        CommonAPI::SomeIP::method_id_t(0xdd),
        false,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        _internalCallStatus,
        deploy_TesterActivityDetected);
    _TesterActivityDetected = deploy_TesterActivityDetected.getValue();
}

std::future<CommonAPI::CallStatus> SOC_SQDFdiagserverSomeIPProxy::GetEvent_TesterActivityDetectedAsync(GetEvent_TesterActivityDetectedAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< ::iMicro::iMicroStructs::TesterActivityDetected_type, ::iMicro::iMicroStructs_::TesterActivityDetected_typeDeployment_t> deploy_TesterActivityDetected(static_cast< ::iMicro::iMicroStructs_::TesterActivityDetected_typeDeployment_t* >(nullptr));
    return CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
        >,
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                ::iMicro::iMicroStructs::TesterActivityDetected_type,
                ::iMicro::iMicroStructs_::TesterActivityDetected_typeDeployment_t
            >
        >
    >::callMethodAsync(
        *this,
        CommonAPI::SomeIP::method_id_t(0xdd),
        false,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        [_callback] (CommonAPI::CallStatus _internalCallStatus, CommonAPI::Deployable< ::iMicro::iMicroStructs::TesterActivityDetected_type, ::iMicro::iMicroStructs_::TesterActivityDetected_typeDeployment_t > _TesterActivityDetected) {
            if (_callback)
                _callback(_internalCallStatus, _TesterActivityDetected.getValue());
        },
        std::make_tuple(deploy_TesterActivityDetected));
}

void SOC_SQDFdiagserverSomeIPProxy::getOwnVersion(uint16_t& ownVersionMajor, uint16_t& ownVersionMinor) const {
    ownVersionMajor = 0;
    ownVersionMinor = 1;
}

std::future<void> SOC_SQDFdiagserverSomeIPProxy::getCompletionFuture() {
    return completed_.get_future();
}

} // namespace iMicro
} // namespace v0
