/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.0.v202012010944.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
#ifndef V0_IMICRO_SOC__DEM_SOMEIP_STUB_ADAPTER_HPP_
#define V0_IMICRO_SOC__DEM_SOMEIP_STUB_ADAPTER_HPP_

#include <v0/iMicro/SOC_DEMStub.hpp>
#include <iMicro/iMicroStructsSomeIPDeployment.hpp>
#include <iMicro/iMicroTypesSomeIPDeployment.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/SomeIP/AddressTranslator.hpp>
#include <CommonAPI/SomeIP/StubAdapterHelper.hpp>
#include <CommonAPI/SomeIP/StubAdapter.hpp>
#include <CommonAPI/SomeIP/Factory.hpp>
#include <CommonAPI/SomeIP/Types.hpp>
#include <CommonAPI/SomeIP/Constants.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v0 {
namespace iMicro {

template <typename _Stub = ::v0::iMicro::SOC_DEMStub, typename... _Stubs>
class SOC_DEMSomeIPStubAdapterInternal
    : public virtual SOC_DEMStubAdapter,
      public CommonAPI::SomeIP::StubAdapterHelper< _Stub, _Stubs...>,
      public std::enable_shared_from_this< SOC_DEMSomeIPStubAdapterInternal<_Stub, _Stubs...>>
{
public:
    typedef CommonAPI::SomeIP::StubAdapterHelper< _Stub, _Stubs...> SOC_DEMSomeIPStubAdapterHelper;

    ~SOC_DEMSomeIPStubAdapterInternal() {
        deactivateManagedInstances();
        SOC_DEMSomeIPStubAdapterHelper::deinit();
    }

    void fireSignalResponse_DEM_EventStatusEvent(const ::iMicro::iMicroStructs::dem_eventstatus_type &_DEM_EventStatus);

    void deactivateManagedInstances() {}
    
    CommonAPI::SomeIP::GetAttributeStubDispatcher<
        ::v0::iMicro::SOC_DEMStub,
        CommonAPI::Version
    > getSOC_DEMInterfaceVersionStubDispatcher;

    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v0::iMicro::SOC_DEMStub,
        std::tuple< ::iMicro::iMicroStructs::dem_eventstatus_type>,
        std::tuple< >,
        std::tuple< ::iMicro::iMicroStructs_::dem_eventstatus_typeDeployment_t>,
        std::tuple< >
    > sendEvent_DEM_SetEventStatusIMicroStubDispatcher;
    
    CommonAPI::SomeIP::MethodStubDispatcher<
        ::v0::iMicro::SOC_DEMStub,
        std::tuple< uint8_t>,
        std::tuple< CommonAPI::SomeIP::IntegerDeployment<uint8_t>>
    > sendCommand_DEM_GetEventStatusIMicroStubDispatcher;
    
    SOC_DEMSomeIPStubAdapterInternal(
        const CommonAPI::SomeIP::Address &_address,
        const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection,
        const std::shared_ptr<CommonAPI::StubBase> &_stub):
        CommonAPI::SomeIP::StubAdapter(_address, _connection),
        SOC_DEMSomeIPStubAdapterHelper(
            _address,
            _connection,
            std::dynamic_pointer_cast< SOC_DEMStub>(_stub)),
        getSOC_DEMInterfaceVersionStubDispatcher(&SOC_DEMStub::lockInterfaceVersionAttribute, &SOC_DEMStub::getInterfaceVersion, false, true),
        sendEvent_DEM_SetEventStatusIMicroStubDispatcher(
            &SOC_DEMStub::SendEvent_DEM_SetEventStatusIMicro,
            false,
            _stub->hasElement(0),
            std::make_tuple(static_cast< ::iMicro::iMicroStructs_::dem_eventstatus_typeDeployment_t* >(nullptr)),
            std::make_tuple())
        
        ,
        sendCommand_DEM_GetEventStatusIMicroStubDispatcher(
            &SOC_DEMStub::SendCommand_DEM_GetEventStatusIMicro,
            false,
            _stub->hasElement(1),
            std::make_tuple(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint8_t>* >(nullptr)))
        
    {
        SOC_DEMSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x36) }, &sendEvent_DEM_SetEventStatusIMicroStubDispatcher );
        SOC_DEMSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x37) }, &sendCommand_DEM_GetEventStatusIMicroStubDispatcher );
        // Provided events/fields
        {
            std::set<CommonAPI::SomeIP::eventgroup_id_t> itsEventGroups;
            itsEventGroups.insert(CommonAPI::SomeIP::eventgroup_id_t(0x80ff));
            CommonAPI::SomeIP::StubAdapter::registerEvent(CommonAPI::SomeIP::event_id_t(0x80ff), itsEventGroups, CommonAPI::SomeIP::event_type_e::ET_EVENT, CommonAPI::SomeIP::reliability_type_e::RT_UNRELIABLE);
        }
    }

    // Register/Unregister event handlers for selective broadcasts
    void registerSelectiveEventHandlers();
    void unregisterSelectiveEventHandlers();

};

template <typename _Stub, typename... _Stubs>
void SOC_DEMSomeIPStubAdapterInternal<_Stub, _Stubs...>::fireSignalResponse_DEM_EventStatusEvent(const ::iMicro::iMicroStructs::dem_eventstatus_type &_DEM_EventStatus) {
    CommonAPI::Deployable< ::iMicro::iMicroStructs::dem_eventstatus_type, ::iMicro::iMicroStructs_::dem_eventstatus_typeDeployment_t> deployed_DEM_EventStatus(_DEM_EventStatus, static_cast< ::iMicro::iMicroStructs_::dem_eventstatus_typeDeployment_t* >(nullptr));
    CommonAPI::SomeIP::StubEventHelper<CommonAPI::SomeIP::SerializableArguments<  CommonAPI::Deployable< ::iMicro::iMicroStructs::dem_eventstatus_type, ::iMicro::iMicroStructs_::dem_eventstatus_typeDeployment_t > 
    >>
        ::sendEvent(
            *this,
            CommonAPI::SomeIP::event_id_t(0x80ff),
            false,
             deployed_DEM_EventStatus 
    );
}


template <typename _Stub, typename... _Stubs>
void SOC_DEMSomeIPStubAdapterInternal<_Stub, _Stubs...>::registerSelectiveEventHandlers() {
}

template <typename _Stub, typename... _Stubs>
void SOC_DEMSomeIPStubAdapterInternal<_Stub, _Stubs...>::unregisterSelectiveEventHandlers() {
}

template <typename _Stub = ::v0::iMicro::SOC_DEMStub, typename... _Stubs>
class SOC_DEMSomeIPStubAdapter
    : public SOC_DEMSomeIPStubAdapterInternal<_Stub, _Stubs...> {
public:
    SOC_DEMSomeIPStubAdapter(const CommonAPI::SomeIP::Address &_address,
                                            const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection,
                                            const std::shared_ptr<CommonAPI::StubBase> &_stub)
        : CommonAPI::SomeIP::StubAdapter(_address, _connection),
          SOC_DEMSomeIPStubAdapterInternal<_Stub, _Stubs...>(_address, _connection, _stub) {
    }
};

} // namespace iMicro
} // namespace v0

#endif // V0_IMICRO_SOC__DEM_SOMEIP_STUB_ADAPTER_HPP_
