/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.0.v202012010944.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
#include <v0/iMicro/SOC_NADSomeIPProxy.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/SomeIP/AddressTranslator.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v0 {
namespace iMicro {

std::shared_ptr<CommonAPI::SomeIP::Proxy> createSOC_NADSomeIPProxy(
    const CommonAPI::SomeIP::Address &_address,
    const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection) {
    return std::make_shared< SOC_NADSomeIPProxy>(_address, _connection);
}

void initializeSOC_NADSomeIPProxy() {
    CommonAPI::SomeIP::AddressTranslator::get()->insert(
        "local:iMicro.SOC_NAD:v0_1:iMicro.SOC_NAD",
        0x1251, 0x5696, 0, 1);
    CommonAPI::SomeIP::Factory::get()->registerProxyCreateMethod(
        "iMicro.SOC_NAD:v0_1",
        &createSOC_NADSomeIPProxy);
}

INITIALIZER(registerSOC_NADSomeIPProxy) {
    CommonAPI::SomeIP::Factory::get()->registerInterface(initializeSOC_NADSomeIPProxy);
}

SOC_NADSomeIPProxy::SOC_NADSomeIPProxy(
    const CommonAPI::SomeIP::Address &_address,
    const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection)
        : CommonAPI::SomeIP::Proxy(_address, _connection),
          signalEvent_Modem_softReset_(*this, 0x80fd, CommonAPI::SomeIP::event_id_t(0x80fd), CommonAPI::SomeIP::event_type_e::ET_EVENT , CommonAPI::SomeIP::reliability_type_e::RT_UNRELIABLE, false, std::make_tuple(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint8_t>* >(nullptr))),
          signalEvent_Modem_shutDown_(*this, 0x80fc, CommonAPI::SomeIP::event_id_t(0x80fc), CommonAPI::SomeIP::event_type_e::ET_EVENT , CommonAPI::SomeIP::reliability_type_e::RT_UNRELIABLE, false, std::make_tuple(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint8_t>* >(nullptr)))
{
}

SOC_NADSomeIPProxy::~SOC_NADSomeIPProxy() {
    completed_.set_value();
}


SOC_NADSomeIPProxy::SignalEvent_Modem_softResetEvent& SOC_NADSomeIPProxy::getSignalEvent_Modem_softResetEvent() {
    return signalEvent_Modem_softReset_;
}
SOC_NADSomeIPProxy::SignalEvent_Modem_shutDownEvent& SOC_NADSomeIPProxy::getSignalEvent_Modem_shutDownEvent() {
    return signalEvent_Modem_shutDown_;
}

void SOC_NADSomeIPProxy::GetEvent_Modem_softReset(CommonAPI::CallStatus &_internalCallStatus, uint8_t &_Modem_softReset, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< uint8_t, CommonAPI::SomeIP::IntegerDeployment<uint8_t>> deploy_Modem_softReset(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint8_t>* >(nullptr));
    CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
        >,
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                uint8_t,
                CommonAPI::SomeIP::IntegerDeployment<uint8_t>
            >
        >
    >::callMethodWithReply(
        *this,
        CommonAPI::SomeIP::method_id_t(0xc8),
        false,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        _internalCallStatus,
        deploy_Modem_softReset);
    _Modem_softReset = deploy_Modem_softReset.getValue();
}

std::future<CommonAPI::CallStatus> SOC_NADSomeIPProxy::GetEvent_Modem_softResetAsync(GetEvent_Modem_softResetAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< uint8_t, CommonAPI::SomeIP::IntegerDeployment<uint8_t>> deploy_Modem_softReset(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint8_t>* >(nullptr));
    return CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
        >,
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                uint8_t,
                CommonAPI::SomeIP::IntegerDeployment<uint8_t>
            >
        >
    >::callMethodAsync(
        *this,
        CommonAPI::SomeIP::method_id_t(0xc8),
        false,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        [_callback] (CommonAPI::CallStatus _internalCallStatus, CommonAPI::Deployable< uint8_t, CommonAPI::SomeIP::IntegerDeployment<uint8_t> > _Modem_softReset) {
            if (_callback)
                _callback(_internalCallStatus, _Modem_softReset.getValue());
        },
        std::make_tuple(deploy_Modem_softReset));
}

void SOC_NADSomeIPProxy::GetEvent_Modem_shutDown(CommonAPI::CallStatus &_internalCallStatus, uint8_t &_Modem_shutDown, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< uint8_t, CommonAPI::SomeIP::IntegerDeployment<uint8_t>> deploy_Modem_shutDown(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint8_t>* >(nullptr));
    CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
        >,
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                uint8_t,
                CommonAPI::SomeIP::IntegerDeployment<uint8_t>
            >
        >
    >::callMethodWithReply(
        *this,
        CommonAPI::SomeIP::method_id_t(0xc9),
        false,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        _internalCallStatus,
        deploy_Modem_shutDown);
    _Modem_shutDown = deploy_Modem_shutDown.getValue();
}

std::future<CommonAPI::CallStatus> SOC_NADSomeIPProxy::GetEvent_Modem_shutDownAsync(GetEvent_Modem_shutDownAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< uint8_t, CommonAPI::SomeIP::IntegerDeployment<uint8_t>> deploy_Modem_shutDown(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint8_t>* >(nullptr));
    return CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
        >,
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                uint8_t,
                CommonAPI::SomeIP::IntegerDeployment<uint8_t>
            >
        >
    >::callMethodAsync(
        *this,
        CommonAPI::SomeIP::method_id_t(0xc9),
        false,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        [_callback] (CommonAPI::CallStatus _internalCallStatus, CommonAPI::Deployable< uint8_t, CommonAPI::SomeIP::IntegerDeployment<uint8_t> > _Modem_shutDown) {
            if (_callback)
                _callback(_internalCallStatus, _Modem_shutDown.getValue());
        },
        std::make_tuple(deploy_Modem_shutDown));
}

void SOC_NADSomeIPProxy::getOwnVersion(uint16_t& ownVersionMajor, uint16_t& ownVersionMinor) const {
    ownVersionMajor = 0;
    ownVersionMinor = 1;
}

std::future<void> SOC_NADSomeIPProxy::getCompletionFuture() {
    return completed_.get_future();
}

} // namespace iMicro
} // namespace v0
