/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.0.v202012010850.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V0_IMICRO_SOC__NTW__API_PROXY_HPP_
#define V0_IMICRO_SOC__NTW__API_PROXY_HPP_

#include <v0/iMicro/SOC_NTW_APIProxyBase.hpp>


#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/AttributeExtension.hpp>
#include <CommonAPI/Factory.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v0 {
namespace iMicro {

template <typename ... _AttributeExtensions>
class SOC_NTW_APIProxy
    : virtual public SOC_NTW_API,
      virtual public SOC_NTW_APIProxyBase,
      virtual public _AttributeExtensions... {
public:
    SOC_NTW_APIProxy(std::shared_ptr<CommonAPI::Proxy> delegate);
    ~SOC_NTW_APIProxy();

    typedef SOC_NTW_API InterfaceType;


    /**
     * Returns the CommonAPI address of the remote partner this proxy communicates with.
     */
    virtual const CommonAPI::Address &getAddress() const;

    /**
     * Returns true if the remote partner for this proxy is currently known to be available.
     */
    virtual bool isAvailable() const;

    /**
     * Returns true if the remote partner for this proxy is available.
     */
    virtual bool isAvailableBlocking() const;

    /**
     * Returns the wrapper class that is used to (de-)register for notifications about
     * the availability of the remote partner of this proxy.
     */
    virtual CommonAPI::ProxyStatusEvent& getProxyStatusEvent();

    /**
     * Returns the wrapper class that is used to access version information of the remote
     * partner of this proxy.
     */
    virtual CommonAPI::InterfaceVersionAttribute& getInterfaceVersionAttribute();

    virtual std::future<void> getCompletionFuture();

    /**
     * Calls SendEvent_NTW_COMM_StayActive with synchronous semantics.
     *
     * All const parameters are input parameters to this method.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void SendEvent_NTW_COMM_StayActive(uint8_t _NTW_COMM_StayActive, CommonAPI::CallStatus &_internalCallStatus, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls SendEvent_NTW_COMM_StayActive with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> SendEvent_NTW_COMM_StayActiveAsync(const uint8_t &_NTW_COMM_StayActive, SendEvent_NTW_COMM_StayActiveAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Returns the wrapper class that provides access to the attribute NTW_ComSync.
     */
    virtual NTW_ComSyncAttribute& getNTW_ComSyncAttribute() {
        return delegate_->getNTW_ComSyncAttribute();
    }



 private:
    std::shared_ptr< SOC_NTW_APIProxyBase> delegate_;
};

typedef SOC_NTW_APIProxy<> SOC_NTW_APIProxyDefault;

namespace SOC_NTW_APIExtensions {
    template <template <typename > class _ExtensionType>
    class NTW_ComSyncAttributeExtension {
     public:
        typedef _ExtensionType< SOC_NTW_APIProxyBase::NTW_ComSyncAttribute> extension_type;
    
        static_assert(std::is_base_of<typename CommonAPI::AttributeExtension< SOC_NTW_APIProxyBase::NTW_ComSyncAttribute>, extension_type>::value,
                      "Not CommonAPI Attribute Extension!");
    
        NTW_ComSyncAttributeExtension(SOC_NTW_APIProxyBase& proxy): attributeExtension_(proxy.getNTW_ComSyncAttribute()) {
        }
    
        inline extension_type& getNTW_ComSyncAttributeExtension() {
            return attributeExtension_;
        }
    
     private:
        extension_type attributeExtension_;
    };

} // namespace SOC_NTW_APIExtensions

//
// SOC_NTW_APIProxy Implementation
//
template <typename ... _AttributeExtensions>
SOC_NTW_APIProxy<_AttributeExtensions...>::SOC_NTW_APIProxy(std::shared_ptr<CommonAPI::Proxy> delegate):
        _AttributeExtensions(*(std::dynamic_pointer_cast< SOC_NTW_APIProxyBase>(delegate)))...,
        delegate_(std::dynamic_pointer_cast< SOC_NTW_APIProxyBase>(delegate)) {
}

template <typename ... _AttributeExtensions>
SOC_NTW_APIProxy<_AttributeExtensions...>::~SOC_NTW_APIProxy() {
}

template <typename ... _AttributeExtensions>
void SOC_NTW_APIProxy<_AttributeExtensions...>::SendEvent_NTW_COMM_StayActive(uint8_t _NTW_COMM_StayActive, CommonAPI::CallStatus &_internalCallStatus, const CommonAPI::CallInfo *_info) {
    delegate_->SendEvent_NTW_COMM_StayActive(_NTW_COMM_StayActive, _internalCallStatus, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> SOC_NTW_APIProxy<_AttributeExtensions...>::SendEvent_NTW_COMM_StayActiveAsync(const uint8_t &_NTW_COMM_StayActive, SendEvent_NTW_COMM_StayActiveAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    return delegate_->SendEvent_NTW_COMM_StayActiveAsync(_NTW_COMM_StayActive, _callback, _info);
}

template <typename ... _AttributeExtensions>
const CommonAPI::Address &SOC_NTW_APIProxy<_AttributeExtensions...>::getAddress() const {
    return delegate_->getAddress();
}

template <typename ... _AttributeExtensions>
bool SOC_NTW_APIProxy<_AttributeExtensions...>::isAvailable() const {
    return delegate_->isAvailable();
}

template <typename ... _AttributeExtensions>
bool SOC_NTW_APIProxy<_AttributeExtensions...>::isAvailableBlocking() const {
    return delegate_->isAvailableBlocking();
}

template <typename ... _AttributeExtensions>
CommonAPI::ProxyStatusEvent& SOC_NTW_APIProxy<_AttributeExtensions...>::getProxyStatusEvent() {
    return delegate_->getProxyStatusEvent();
}

template <typename ... _AttributeExtensions>
CommonAPI::InterfaceVersionAttribute& SOC_NTW_APIProxy<_AttributeExtensions...>::getInterfaceVersionAttribute() {
    return delegate_->getInterfaceVersionAttribute();
}


template <typename ... _AttributeExtensions>
std::future<void> SOC_NTW_APIProxy<_AttributeExtensions...>::getCompletionFuture() {
    return delegate_->getCompletionFuture();
}

} // namespace iMicro
} // namespace v0

namespace CommonAPI {
template<template<typename > class _AttributeExtension>
struct DefaultAttributeProxyHelper< ::v0::iMicro::SOC_NTW_APIProxy,
    _AttributeExtension> {
    typedef typename ::v0::iMicro::SOC_NTW_APIProxy<
            ::v0::iMicro::SOC_NTW_APIExtensions::NTW_ComSyncAttributeExtension<_AttributeExtension>
    > class_t;
};
}


// Compatibility
namespace v0_1 = v0;

#endif // V0_IMICRO_SOC__NTW__API_PROXY_HPP_
