/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.0.v202012010850.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V0_IMICRO_SOC__GPIO_PROXY_HPP_
#define V0_IMICRO_SOC__GPIO_PROXY_HPP_

#include <v0/iMicro/SOC_GPIOProxyBase.hpp>


#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif


#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v0 {
namespace iMicro {

template <typename ... _AttributeExtensions>
class SOC_GPIOProxy
    : virtual public SOC_GPIO,
      virtual public SOC_GPIOProxyBase,
      virtual public _AttributeExtensions... {
public:
    SOC_GPIOProxy(std::shared_ptr<CommonAPI::Proxy> delegate);
    ~SOC_GPIOProxy();

    typedef SOC_GPIO InterfaceType;


    /**
     * Returns the CommonAPI address of the remote partner this proxy communicates with.
     */
    virtual const CommonAPI::Address &getAddress() const;

    /**
     * Returns true if the remote partner for this proxy is currently known to be available.
     */
    virtual bool isAvailable() const;

    /**
     * Returns true if the remote partner for this proxy is available.
     */
    virtual bool isAvailableBlocking() const;

    /**
     * Returns the wrapper class that is used to (de-)register for notifications about
     * the availability of the remote partner of this proxy.
     */
    virtual CommonAPI::ProxyStatusEvent& getProxyStatusEvent();

    /**
     * Returns the wrapper class that is used to access version information of the remote
     * partner of this proxy.
     */
    virtual CommonAPI::InterfaceVersionAttribute& getInterfaceVersionAttribute();

    virtual std::future<void> getCompletionFuture();

    /**
     * Calls SendCommand_Gpio_reqRead with Fire&Forget semantics.
     *
     * All const parameters are input parameters to this method.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void SendCommand_Gpio_reqRead(::iMicro::iMicroStructs::gpio_channel_type _Gpio_reqRead, CommonAPI::CallStatus &_internalCallStatus);
    /**
     * Calls SendCommand_Gpio_reqWrite with Fire&Forget semantics.
     *
     * All const parameters are input parameters to this method.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void SendCommand_Gpio_reqWrite(::iMicro::iMicroStructs::gpio_status_type _Gpio_reqWrite, CommonAPI::CallStatus &_internalCallStatus);
    /**
     * Returns the wrapper class that provides access to the broadcast SignalResponse_Gpio_value.
     */
    virtual SignalResponse_Gpio_valueEvent& getSignalResponse_Gpio_valueEvent() {
        return delegate_->getSignalResponse_Gpio_valueEvent();
    }



 private:
    std::shared_ptr< SOC_GPIOProxyBase> delegate_;
};

typedef SOC_GPIOProxy<> SOC_GPIOProxyDefault;


//
// SOC_GPIOProxy Implementation
//
template <typename ... _AttributeExtensions>
SOC_GPIOProxy<_AttributeExtensions...>::SOC_GPIOProxy(std::shared_ptr<CommonAPI::Proxy> delegate):
        _AttributeExtensions(*(std::dynamic_pointer_cast< SOC_GPIOProxyBase>(delegate)))...,
        delegate_(std::dynamic_pointer_cast< SOC_GPIOProxyBase>(delegate)) {
}

template <typename ... _AttributeExtensions>
SOC_GPIOProxy<_AttributeExtensions...>::~SOC_GPIOProxy() {
}

template <typename ... _AttributeExtensions>
void SOC_GPIOProxy<_AttributeExtensions...>::SendCommand_Gpio_reqRead(::iMicro::iMicroStructs::gpio_channel_type _Gpio_reqRead, CommonAPI::CallStatus &_internalCallStatus) {
    delegate_->SendCommand_Gpio_reqRead(_Gpio_reqRead, _internalCallStatus);
}
template <typename ... _AttributeExtensions>
void SOC_GPIOProxy<_AttributeExtensions...>::SendCommand_Gpio_reqWrite(::iMicro::iMicroStructs::gpio_status_type _Gpio_reqWrite, CommonAPI::CallStatus &_internalCallStatus) {
    delegate_->SendCommand_Gpio_reqWrite(_Gpio_reqWrite, _internalCallStatus);
}

template <typename ... _AttributeExtensions>
const CommonAPI::Address &SOC_GPIOProxy<_AttributeExtensions...>::getAddress() const {
    return delegate_->getAddress();
}

template <typename ... _AttributeExtensions>
bool SOC_GPIOProxy<_AttributeExtensions...>::isAvailable() const {
    return delegate_->isAvailable();
}

template <typename ... _AttributeExtensions>
bool SOC_GPIOProxy<_AttributeExtensions...>::isAvailableBlocking() const {
    return delegate_->isAvailableBlocking();
}

template <typename ... _AttributeExtensions>
CommonAPI::ProxyStatusEvent& SOC_GPIOProxy<_AttributeExtensions...>::getProxyStatusEvent() {
    return delegate_->getProxyStatusEvent();
}

template <typename ... _AttributeExtensions>
CommonAPI::InterfaceVersionAttribute& SOC_GPIOProxy<_AttributeExtensions...>::getInterfaceVersionAttribute() {
    return delegate_->getInterfaceVersionAttribute();
}


template <typename ... _AttributeExtensions>
std::future<void> SOC_GPIOProxy<_AttributeExtensions...>::getCompletionFuture() {
    return delegate_->getCompletionFuture();
}

} // namespace iMicro
} // namespace v0



// Compatibility
namespace v0_1 = v0;

#endif // V0_IMICRO_SOC__GPIO_PROXY_HPP_
