/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.0.v202012010944.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
#ifndef V0_IMICRO_SOC__DEVICE_VC_SOMEIP_PROXY_HPP_
#define V0_IMICRO_SOC__DEVICE_VC_SOMEIP_PROXY_HPP_

#include <v0/iMicro/SOC_DeviceVCProxyBase.hpp>
#include <iMicro/iMicroStructsSomeIPDeployment.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/SomeIP/Factory.hpp>
#include <CommonAPI/SomeIP/Proxy.hpp>
#include <CommonAPI/SomeIP/Types.hpp>
#include <CommonAPI/SomeIP/Event.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <string>

# if defined(_MSC_VER)
#  if _MSC_VER >= 1300
/*
 * Diamond inheritance is used for the CommonAPI::Proxy base class.
 * The Microsoft compiler put warning (C4250) using a desired c++ feature: "Delegating to a sister class"
 * A powerful technique that arises from using virtual inheritance is to delegate a method from a class in another class
 * by using a common abstract base class. This is also called cross delegation.
 */
#    pragma warning( disable : 4250 )
#  endif
# endif

namespace v0 {
namespace iMicro {

class SOC_DeviceVCSomeIPProxy
    : virtual public SOC_DeviceVCProxyBase,
      virtual public CommonAPI::SomeIP::Proxy {
public:
    SOC_DeviceVCSomeIPProxy(
        const CommonAPI::SomeIP::Address &_address,
        const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection);

    virtual ~SOC_DeviceVCSomeIPProxy();

    virtual SignalEvent_DeviceVC_VC2NADHandshakeEvent& getSignalEvent_DeviceVC_VC2NADHandshakeEvent();

    virtual void SendResponse_DeviceVC_NAD2VCHandshake(::iMicro::iMicroStructs::DeviceVC_NAD2VCHandshake_type _DeviceVC_NAD2VCHandshake, CommonAPI::CallStatus &_internalCallStatus);

    virtual void GetEvent_DeviceVC_VC2NADHandshake(CommonAPI::CallStatus &_internalCallStatus, ::iMicro::iMicroStructs::DeviceVC_VC2NADHandshake_type &_DeviceVC_VC2NADHandshake, const CommonAPI::CallInfo *_info);

    virtual std::future<CommonAPI::CallStatus> GetEvent_DeviceVC_VC2NADHandshakeAsync(GetEvent_DeviceVC_VC2NADHandshakeAsyncCallback _callback, const CommonAPI::CallInfo *_info);

    virtual void getOwnVersion(uint16_t &_major, uint16_t &_minor) const;

    virtual std::future<void> getCompletionFuture();

private:
    CommonAPI::SomeIP::Event<SignalEvent_DeviceVC_VC2NADHandshakeEvent, CommonAPI::Deployable< ::iMicro::iMicroStructs::DeviceVC_VC2NADHandshake_type, ::iMicro::iMicroStructs_::DeviceVC_VC2NADHandshake_typeDeployment_t >> signalEvent_DeviceVC_VC2NADHandshake_;

    std::promise<void> completed_;
};

} // namespace iMicro
} // namespace v0

#endif // V0_IMICRO_SOC__Device_VC_SOMEIP_PROXY_HPP_
