/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.0.v202012010944.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
#include <v0/iMicro/SOC_Channel_CALIBSomeIPProxy.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/SomeIP/AddressTranslator.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v0 {
namespace iMicro {

std::shared_ptr<CommonAPI::SomeIP::Proxy> createSOC_Channel_CALIBSomeIPProxy(
    const CommonAPI::SomeIP::Address &_address,
    const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection) {
    return std::make_shared< SOC_Channel_CALIBSomeIPProxy>(_address, _connection);
}

void initializeSOC_Channel_CALIBSomeIPProxy() {
    CommonAPI::SomeIP::AddressTranslator::get()->insert(
        "local:iMicro.SOC_Channel_CALIB:v0_1:iMicro.SOC_Channel_CALIB",
        0x1255, 0x569b, 0, 1);
    CommonAPI::SomeIP::Factory::get()->registerProxyCreateMethod(
        "iMicro.SOC_Channel_CALIB:v0_1",
        &createSOC_Channel_CALIBSomeIPProxy);
}

INITIALIZER(registerSOC_Channel_CALIBSomeIPProxy) {
    CommonAPI::SomeIP::Factory::get()->registerInterface(initializeSOC_Channel_CALIBSomeIPProxy);
}

SOC_Channel_CALIBSomeIPProxy::SOC_Channel_CALIBSomeIPProxy(
    const CommonAPI::SomeIP::Address &_address,
    const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection)
        : CommonAPI::SomeIP::Proxy(_address, _connection),
          getRaw_(*this, 0x80f8, CommonAPI::SomeIP::event_id_t(0x80f8), CommonAPI::SomeIP::event_type_e::ET_EVENT , CommonAPI::SomeIP::reliability_type_e::RT_UNRELIABLE, false, std::make_tuple(static_cast< CommonAPI::SomeIP::ByteBufferDeployment* >(nullptr)))
{
}

SOC_Channel_CALIBSomeIPProxy::~SOC_Channel_CALIBSomeIPProxy() {
    completed_.set_value();
}


SOC_Channel_CALIBSomeIPProxy::GetRawEvent& SOC_Channel_CALIBSomeIPProxy::getGetRawEvent() {
    return getRaw_;
}

void SOC_Channel_CALIBSomeIPProxy::SendRaw(CommonAPI::ByteBuffer _data, CommonAPI::CallStatus &_internalCallStatus, uint32_t &_result, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< CommonAPI::ByteBuffer, CommonAPI::SomeIP::ByteBufferDeployment> deploy_data(_data, static_cast< CommonAPI::SomeIP::ByteBufferDeployment* >(nullptr));
    CommonAPI::Deployable< uint32_t, CommonAPI::SomeIP::IntegerDeployment<uint32_t>> deploy_result(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr));
    CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                CommonAPI::ByteBuffer,
                CommonAPI::SomeIP::ByteBufferDeployment
            >
        >,
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                uint32_t,
                CommonAPI::SomeIP::IntegerDeployment<uint32_t>
            >
        >
    >::callMethodWithReply(
        *this,
        CommonAPI::SomeIP::method_id_t(0xc2),
        false,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        deploy_data,
        _internalCallStatus,
        deploy_result);
    _result = deploy_result.getValue();
}

std::future<CommonAPI::CallStatus> SOC_Channel_CALIBSomeIPProxy::SendRawAsync(const CommonAPI::ByteBuffer &_data, SendRawAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< CommonAPI::ByteBuffer, CommonAPI::SomeIP::ByteBufferDeployment> deploy_data(_data, static_cast< CommonAPI::SomeIP::ByteBufferDeployment* >(nullptr));
    CommonAPI::Deployable< uint32_t, CommonAPI::SomeIP::IntegerDeployment<uint32_t>> deploy_result(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr));
    return CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                CommonAPI::ByteBuffer,
                CommonAPI::SomeIP::ByteBufferDeployment
            >
        >,
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                uint32_t,
                CommonAPI::SomeIP::IntegerDeployment<uint32_t>
            >
        >
    >::callMethodAsync(
        *this,
        CommonAPI::SomeIP::method_id_t(0xc2),
        false,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        deploy_data,
        [_callback] (CommonAPI::CallStatus _internalCallStatus, CommonAPI::Deployable< uint32_t, CommonAPI::SomeIP::IntegerDeployment<uint32_t> > _result) {
            if (_callback)
                _callback(_internalCallStatus, _result.getValue());
        },
        std::make_tuple(deploy_result));
}

void SOC_Channel_CALIBSomeIPProxy::getOwnVersion(uint16_t& ownVersionMajor, uint16_t& ownVersionMinor) const {
    ownVersionMajor = 0;
    ownVersionMinor = 1;
}

std::future<void> SOC_Channel_CALIBSomeIPProxy::getCompletionFuture() {
    return completed_.get_future();
}

} // namespace iMicro
} // namespace v0
