/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.0.v202012010850.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V0_IMICRO_SOC__MIC_STUB_HPP_
#define V0_IMICRO_SOC__MIC_STUB_HPP_

#include <functional>
#include <sstream>



#include <iMicro/iMicroStructs.hpp>
#include <iMicro/iMicroTypes.hpp>

#include <v0/iMicro/SOC_MIC.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/Deployment.hpp>
#include <CommonAPI/InputStream.hpp>
#include <CommonAPI/OutputStream.hpp>
#include <CommonAPI/Struct.hpp>
#include <cstdint>
#include <unordered_set>
#include <vector>


#include <CommonAPI/Stub.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v0 {
namespace iMicro {

/**
 * Receives messages from remote and handles all dispatching of deserialized calls
 * to a stub for the service SOC_MIC. Also provides means to send broadcasts
 * and attribute-changed-notifications of observable attributes as defined by this service.
 * An application developer should not need to bother with this class.
 */
class SOC_MICStubAdapter
    : public virtual CommonAPI::StubAdapter,
      public virtual SOC_MIC {
 public:
    /**
    * Sends a broadcast event for SignalResponse_Mic_status. Should not be called directly.
    * Instead, the "fire<broadcastName>Event" methods of the stub should be used.
    */
    virtual void fireSignalResponse_Mic_statusEvent(const ::iMicro::iMicroStructs::mic_status_type &_Mic_status) = 0;


    virtual void deactivateManagedInstances() = 0;


protected:
    /**
     * Defines properties for storing the ClientIds of clients / proxies that have
     * subscribed to the selective broadcasts
     */

};

/**
 * Defines the necessary callbacks to handle remote set events related to the attributes
 * defined in the IDL description for SOC_MIC.
 * For each attribute two callbacks are defined:
 * - a verification callback that allows to verify the requested value and to prevent setting
 *   e.g. an invalid value ("onRemoteSet<AttributeName>").
 * - an action callback to do local work after the attribute value has been changed
 *   ("onRemote<AttributeName>Changed").
 *
 * This class and the one below are the ones an application developer needs to have
 * a look at if he wants to implement a service.
 */
class SOC_MICStubRemoteEvent
{
public:
    virtual ~SOC_MICStubRemoteEvent() { }

};

/**
 * Defines the interface that must be implemented by any class that should provide
 * the service SOC_MIC to remote clients.
 * This class and the one above are the ones an application developer needs to have
 * a look at if he wants to implement a service.
 */
class SOC_MICStub
    : public virtual CommonAPI::Stub<SOC_MICStubAdapter, SOC_MICStubRemoteEvent>
{
public:

    virtual ~SOC_MICStub() {}
    void lockInterfaceVersionAttribute(bool _lockAccess) { static_cast<void>(_lockAccess); }
    bool hasElement(const uint32_t _id) const {
        return (_id < 3);
    }
    virtual const CommonAPI::Version& getInterfaceVersion(std::shared_ptr<CommonAPI::ClientId> _client) = 0;

    /// This is the method that will be called on remote calls on the method SendCommand_Mic_reqStatus.
    virtual void SendCommand_Mic_reqStatus(const std::shared_ptr<CommonAPI::ClientId> _client, ::iMicro::iMicroTypes::mic_id_enum _Mic_reqStatus) = 0;
    /// This is the method that will be called on remote calls on the method SendCommand_Mic_setStatus.
    virtual void SendCommand_Mic_setStatus(const std::shared_ptr<CommonAPI::ClientId> _client, ::iMicro::iMicroStructs::mic_status_type _Mic_setStatus) = 0;
    /// Sends a broadcast event for SignalResponse_Mic_status.
    virtual void fireSignalResponse_Mic_statusEvent(const ::iMicro::iMicroStructs::mic_status_type &_Mic_status) {
        auto stubAdapter = CommonAPI::Stub<SOC_MICStubAdapter, SOC_MICStubRemoteEvent>::stubAdapter_.lock();
        if (stubAdapter)
            stubAdapter->fireSignalResponse_Mic_statusEvent(_Mic_status);
    }


    using CommonAPI::Stub<SOC_MICStubAdapter, SOC_MICStubRemoteEvent>::initStubAdapter;
    typedef CommonAPI::Stub<SOC_MICStubAdapter, SOC_MICStubRemoteEvent>::StubAdapterType StubAdapterType;
    typedef CommonAPI::Stub<SOC_MICStubAdapter, SOC_MICStubRemoteEvent>::RemoteEventHandlerType RemoteEventHandlerType;
    typedef SOC_MICStubRemoteEvent RemoteEventType;
    typedef SOC_MIC StubInterface;
};

} // namespace iMicro
} // namespace v0


// Compatibility
namespace v0_1 = v0;

#endif // V0_IMICRO_SOC__MIC_STUB_HPP_
