/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.0.v202012010944.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
#include <v0/iMicro/SOC_DEMSomeIPProxy.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/SomeIP/AddressTranslator.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v0 {
namespace iMicro {

std::shared_ptr<CommonAPI::SomeIP::Proxy> createSOC_DEMSomeIPProxy(
    const CommonAPI::SomeIP::Address &_address,
    const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection) {
    return std::make_shared< SOC_DEMSomeIPProxy>(_address, _connection);
}

void initializeSOC_DEMSomeIPProxy() {
    CommonAPI::SomeIP::AddressTranslator::get()->insert(
        "local:iMicro.SOC_DEM:v0_1:iMicro.SOC_DEM",
        0x1245, 0x568b, 0, 1);
    CommonAPI::SomeIP::Factory::get()->registerProxyCreateMethod(
        "iMicro.SOC_DEM:v0_1",
        &createSOC_DEMSomeIPProxy);
}

INITIALIZER(registerSOC_DEMSomeIPProxy) {
    CommonAPI::SomeIP::Factory::get()->registerInterface(initializeSOC_DEMSomeIPProxy);
}

SOC_DEMSomeIPProxy::SOC_DEMSomeIPProxy(
    const CommonAPI::SomeIP::Address &_address,
    const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection)
        : CommonAPI::SomeIP::Proxy(_address, _connection),
          signalResponse_DEM_EventStatus_(*this, 0x80ff, CommonAPI::SomeIP::event_id_t(0x80ff), CommonAPI::SomeIP::event_type_e::ET_EVENT , CommonAPI::SomeIP::reliability_type_e::RT_UNRELIABLE, false, std::make_tuple(static_cast< ::iMicro::iMicroStructs_::dem_eventstatus_typeDeployment_t* >(nullptr)))
{
}

SOC_DEMSomeIPProxy::~SOC_DEMSomeIPProxy() {
    completed_.set_value();
}


SOC_DEMSomeIPProxy::SignalResponse_DEM_EventStatusEvent& SOC_DEMSomeIPProxy::getSignalResponse_DEM_EventStatusEvent() {
    return signalResponse_DEM_EventStatus_;
}

void SOC_DEMSomeIPProxy::SendEvent_DEM_SetEventStatusIMicro(::iMicro::iMicroStructs::dem_eventstatus_type _DEM_SetEventStatusIMicro, CommonAPI::CallStatus &_internalCallStatus, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< ::iMicro::iMicroStructs::dem_eventstatus_type, ::iMicro::iMicroStructs_::dem_eventstatus_typeDeployment_t> deploy_DEM_SetEventStatusIMicro(_DEM_SetEventStatusIMicro, static_cast< ::iMicro::iMicroStructs_::dem_eventstatus_typeDeployment_t* >(nullptr));
    CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                ::iMicro::iMicroStructs::dem_eventstatus_type,
                ::iMicro::iMicroStructs_::dem_eventstatus_typeDeployment_t
            >
        >,
        CommonAPI::SomeIP::SerializableArguments<
        >
    >::callMethodWithReply(
        *this,
        CommonAPI::SomeIP::method_id_t(0x36),
        false,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        deploy_DEM_SetEventStatusIMicro,
        _internalCallStatus);
}

std::future<CommonAPI::CallStatus> SOC_DEMSomeIPProxy::SendEvent_DEM_SetEventStatusIMicroAsync(const ::iMicro::iMicroStructs::dem_eventstatus_type &_DEM_SetEventStatusIMicro, SendEvent_DEM_SetEventStatusIMicroAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< ::iMicro::iMicroStructs::dem_eventstatus_type, ::iMicro::iMicroStructs_::dem_eventstatus_typeDeployment_t> deploy_DEM_SetEventStatusIMicro(_DEM_SetEventStatusIMicro, static_cast< ::iMicro::iMicroStructs_::dem_eventstatus_typeDeployment_t* >(nullptr));
    return CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                ::iMicro::iMicroStructs::dem_eventstatus_type,
                ::iMicro::iMicroStructs_::dem_eventstatus_typeDeployment_t
            >
        >,
        CommonAPI::SomeIP::SerializableArguments<
        >
    >::callMethodAsync(
        *this,
        CommonAPI::SomeIP::method_id_t(0x36),
        false,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        deploy_DEM_SetEventStatusIMicro,
        [_callback] (CommonAPI::CallStatus _internalCallStatus) {
            if (_callback)
                _callback(_internalCallStatus);
        },
        std::make_tuple());
}

void SOC_DEMSomeIPProxy::SendCommand_DEM_GetEventStatusIMicro(uint8_t _DEM_GetEventStatusIMicro, CommonAPI::CallStatus &_internalCallStatus) {
    CommonAPI::Deployable< uint8_t, CommonAPI::SomeIP::IntegerDeployment<uint8_t>> deploy_DEM_GetEventStatusIMicro(_DEM_GetEventStatusIMicro, static_cast< CommonAPI::SomeIP::IntegerDeployment<uint8_t>* >(nullptr));
    CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                uint8_t,
                CommonAPI::SomeIP::IntegerDeployment<uint8_t>
            >
        >,
        CommonAPI::SomeIP::SerializableArguments<
        >
    >::callMethod(
        *this,
        CommonAPI::SomeIP::method_id_t(0x37),
        false,
        false,
        deploy_DEM_GetEventStatusIMicro,
        _internalCallStatus);
}

void SOC_DEMSomeIPProxy::getOwnVersion(uint16_t& ownVersionMajor, uint16_t& ownVersionMinor) const {
    ownVersionMajor = 0;
    ownVersionMinor = 1;
}

std::future<void> SOC_DEMSomeIPProxy::getCompletionFuture() {
    return completed_.get_future();
}

} // namespace iMicro
} // namespace v0
