/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.0.v202012010850.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V0_IMICRO_SOC__ACC_Gyro_PROXY_HPP_
#define V0_IMICRO_SOC__ACC_Gyro_PROXY_HPP_

#include <v0/iMicro/SOC_ACCGyroProxyBase.hpp>


#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif


#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v0 {
namespace iMicro {

template <typename ... _AttributeExtensions>
class SOC_ACCGyroProxy
    : virtual public SOC_ACCGyro,
      virtual public SOC_ACCGyroProxyBase,
      virtual public _AttributeExtensions... {
public:
    SOC_ACCGyroProxy(std::shared_ptr<CommonAPI::Proxy> delegate);
    ~SOC_ACCGyroProxy();

    typedef SOC_ACCGyro InterfaceType;


    /**
     * Returns the CommonAPI address of the remote partner this proxy communicates with.
     */
    virtual const CommonAPI::Address &getAddress() const;

    /**
     * Returns true if the remote partner for this proxy is currently known to be available.
     */
    virtual bool isAvailable() const;

    /**
     * Returns true if the remote partner for this proxy is available.
     */
    virtual bool isAvailableBlocking() const;

    /**
     * Returns the wrapper class that is used to (de-)register for notifications about
     * the availability of the remote partner of this proxy.
     */
    virtual CommonAPI::ProxyStatusEvent& getProxyStatusEvent();

    /**
     * Returns the wrapper class that is used to access version information of the remote
     * partner of this proxy.
     */
    virtual CommonAPI::InterfaceVersionAttribute& getInterfaceVersionAttribute();

    virtual std::future<void> getCompletionFuture();

    /**
     * Calls SendCommand_AccGyro_req_6DValue with Fire&Forget semantics.
     *
     * All const parameters are input parameters to this method.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void SendCommand_AccGyro_req_6DValue(uint8_t _AccGyro_req_6DValue, CommonAPI::CallStatus &_internalCallStatus);
    /**
     * Calls SendCommand_AccGyro_setSettingAcquisition with Fire&Forget semantics.
     *
     * All const parameters are input parameters to this method.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void SendCommand_AccGyro_setSettingAcquisition(::iMicro::iMicroStructs::accgyro_set_settingacquisition_type _AccGyro_setSettingAcquisition, CommonAPI::CallStatus &_internalCallStatus);
    /**
     * Calls SendCommand_AccGyro_reqSettingAcquisition with Fire&Forget semantics.
     *
     * All const parameters are input parameters to this method.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void SendCommand_AccGyro_reqSettingAcquisition(uint8_t _AccGyro_reqSettingAcquisition, CommonAPI::CallStatus &_internalCallStatus);
    /**
     * Calls SendCommand_AccGyro_setPowerMode with Fire&Forget semantics.
     *
     * All const parameters are input parameters to this method.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void SendCommand_AccGyro_setPowerMode(::iMicro::iMicroStructs::accgyro_setpowermode_type _AccGyro_setPowerMode, CommonAPI::CallStatus &_internalCallStatus);
    /**
     * Calls SendCommand_AccGyro_setSlopeThreshold with Fire&Forget semantics.
     *
     * All const parameters are input parameters to this method.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void SendCommand_AccGyro_setSlopeThreshold(::iMicro::iMicroStructs::accgyro_setslopethreshold_type _AccGyro_setSlopeThreshold, CommonAPI::CallStatus &_internalCallStatus);
    /**
     * Calls SendCommand_AccGyro_enableUnsolicited with Fire&Forget semantics.
     *
     * All const parameters are input parameters to this method.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void SendCommand_AccGyro_enableUnsolicited(::iMicro::iMicroStructs::accgyro_enableunsolicited_type _AccGyro_enableUnsolicited, CommonAPI::CallStatus &_internalCallStatus);
    /**
     * Returns the wrapper class that provides access to the broadcast SignalResponse_AccGyro_6DValue.
     */
    virtual SignalResponse_AccGyro_6DValueEvent& getSignalResponse_AccGyro_6DValueEvent() {
        return delegate_->getSignalResponse_AccGyro_6DValueEvent();
    }
    /**
     * Returns the wrapper class that provides access to the broadcast SignalResponse_AccGyro_settingAcquisition.
     */
    virtual SignalResponse_AccGyro_settingAcquisitionEvent& getSignalResponse_AccGyro_settingAcquisitionEvent() {
        return delegate_->getSignalResponse_AccGyro_settingAcquisitionEvent();
    }
    /**
     * Returns the wrapper class that provides access to the broadcast SignalResponse_AccGyro_powerModeStatus.
     */
    virtual SignalResponse_AccGyro_powerModeStatusEvent& getSignalResponse_AccGyro_powerModeStatusEvent() {
        return delegate_->getSignalResponse_AccGyro_powerModeStatusEvent();
    }



 private:
    std::shared_ptr< SOC_ACCGyroProxyBase> delegate_;
};

typedef SOC_ACCGyroProxy<> SOC_ACCGyroProxyDefault;


//
// SOC_ACCGyroProxy Implementation
//
template <typename ... _AttributeExtensions>
SOC_ACCGyroProxy<_AttributeExtensions...>::SOC_ACCGyroProxy(std::shared_ptr<CommonAPI::Proxy> delegate):
        _AttributeExtensions(*(std::dynamic_pointer_cast< SOC_ACCGyroProxyBase>(delegate)))...,
        delegate_(std::dynamic_pointer_cast< SOC_ACCGyroProxyBase>(delegate)) {
}

template <typename ... _AttributeExtensions>
SOC_ACCGyroProxy<_AttributeExtensions...>::~SOC_ACCGyroProxy() {
}

template <typename ... _AttributeExtensions>
void SOC_ACCGyroProxy<_AttributeExtensions...>::SendCommand_AccGyro_req_6DValue(uint8_t _AccGyro_req_6DValue, CommonAPI::CallStatus &_internalCallStatus) {
    delegate_->SendCommand_AccGyro_req_6DValue(_AccGyro_req_6DValue, _internalCallStatus);
}
template <typename ... _AttributeExtensions>
void SOC_ACCGyroProxy<_AttributeExtensions...>::SendCommand_AccGyro_setSettingAcquisition(::iMicro::iMicroStructs::accgyro_set_settingacquisition_type _AccGyro_setSettingAcquisition, CommonAPI::CallStatus &_internalCallStatus) {
    delegate_->SendCommand_AccGyro_setSettingAcquisition(_AccGyro_setSettingAcquisition, _internalCallStatus);
}
template <typename ... _AttributeExtensions>
void SOC_ACCGyroProxy<_AttributeExtensions...>::SendCommand_AccGyro_reqSettingAcquisition(uint8_t _AccGyro_reqSettingAcquisition, CommonAPI::CallStatus &_internalCallStatus) {
    delegate_->SendCommand_AccGyro_reqSettingAcquisition(_AccGyro_reqSettingAcquisition, _internalCallStatus);
}
template <typename ... _AttributeExtensions>
void SOC_ACCGyroProxy<_AttributeExtensions...>::SendCommand_AccGyro_setPowerMode(::iMicro::iMicroStructs::accgyro_setpowermode_type _AccGyro_setPowerMode, CommonAPI::CallStatus &_internalCallStatus) {
    delegate_->SendCommand_AccGyro_setPowerMode(_AccGyro_setPowerMode, _internalCallStatus);
}
template <typename ... _AttributeExtensions>
void SOC_ACCGyroProxy<_AttributeExtensions...>::SendCommand_AccGyro_setSlopeThreshold(::iMicro::iMicroStructs::accgyro_setslopethreshold_type _AccGyro_setSlopeThreshold, CommonAPI::CallStatus &_internalCallStatus) {
    delegate_->SendCommand_AccGyro_setSlopeThreshold(_AccGyro_setSlopeThreshold, _internalCallStatus);
}
template <typename ... _AttributeExtensions>
void SOC_ACCGyroProxy<_AttributeExtensions...>::SendCommand_AccGyro_enableUnsolicited(::iMicro::iMicroStructs::accgyro_enableunsolicited_type _AccGyro_enableUnsolicited, CommonAPI::CallStatus &_internalCallStatus) {
    delegate_->SendCommand_AccGyro_enableUnsolicited(_AccGyro_enableUnsolicited, _internalCallStatus);
}

template <typename ... _AttributeExtensions>
const CommonAPI::Address &SOC_ACCGyroProxy<_AttributeExtensions...>::getAddress() const {
    return delegate_->getAddress();
}

template <typename ... _AttributeExtensions>
bool SOC_ACCGyroProxy<_AttributeExtensions...>::isAvailable() const {
    return delegate_->isAvailable();
}

template <typename ... _AttributeExtensions>
bool SOC_ACCGyroProxy<_AttributeExtensions...>::isAvailableBlocking() const {
    return delegate_->isAvailableBlocking();
}

template <typename ... _AttributeExtensions>
CommonAPI::ProxyStatusEvent& SOC_ACCGyroProxy<_AttributeExtensions...>::getProxyStatusEvent() {
    return delegate_->getProxyStatusEvent();
}

template <typename ... _AttributeExtensions>
CommonAPI::InterfaceVersionAttribute& SOC_ACCGyroProxy<_AttributeExtensions...>::getInterfaceVersionAttribute() {
    return delegate_->getInterfaceVersionAttribute();
}


template <typename ... _AttributeExtensions>
std::future<void> SOC_ACCGyroProxy<_AttributeExtensions...>::getCompletionFuture() {
    return delegate_->getCompletionFuture();
}

} // namespace iMicro
} // namespace v0



// Compatibility
namespace v0_1 = v0;

#endif // V0_IMICRO_SOC__ACC_Gyro_PROXY_HPP_
