/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.0.v202012010944.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
#ifndef V0_IMICRO_SOC__AMP_SOMEIP_STUB_ADAPTER_HPP_
#define V0_IMICRO_SOC__AMP_SOMEIP_STUB_ADAPTER_HPP_

#include <v0/iMicro/SOC_AMPStub.hpp>
#include <iMicro/iMicroStructsSomeIPDeployment.hpp>
#include <iMicro/iMicroTypesSomeIPDeployment.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/SomeIP/AddressTranslator.hpp>
#include <CommonAPI/SomeIP/StubAdapterHelper.hpp>
#include <CommonAPI/SomeIP/StubAdapter.hpp>
#include <CommonAPI/SomeIP/Factory.hpp>
#include <CommonAPI/SomeIP/Types.hpp>
#include <CommonAPI/SomeIP/Constants.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v0 {
namespace iMicro {

template <typename _Stub = ::v0::iMicro::SOC_AMPStub, typename... _Stubs>
class SOC_AMPSomeIPStubAdapterInternal
    : public virtual SOC_AMPStubAdapter,
      public CommonAPI::SomeIP::StubAdapterHelper< _Stub, _Stubs...>,
      public std::enable_shared_from_this< SOC_AMPSomeIPStubAdapterInternal<_Stub, _Stubs...>>
{
public:
    typedef CommonAPI::SomeIP::StubAdapterHelper< _Stub, _Stubs...> SOC_AMPSomeIPStubAdapterHelper;

    ~SOC_AMPSomeIPStubAdapterInternal() {
        deactivateManagedInstances();
        SOC_AMPSomeIPStubAdapterHelper::deinit();
    }

    void fireSignalResponse_Amp_registerValueEvent(const ::iMicro::iMicroStructs::amp_registervalue_type &_Amp_registerValue);

    void deactivateManagedInstances() {}
    
    CommonAPI::SomeIP::GetAttributeStubDispatcher<
        ::v0::iMicro::SOC_AMPStub,
        CommonAPI::Version
    > getSOC_AMPInterfaceVersionStubDispatcher;

    CommonAPI::SomeIP::MethodStubDispatcher<
        ::v0::iMicro::SOC_AMPStub,
        std::tuple< ::iMicro::iMicroTypes::standby_enum>,
        std::tuple< ::iMicro::iMicroTypes_::standby_enumDeployment_t>
    > sendCommand_Amp_setStandbyStubDispatcher;
    
    CommonAPI::SomeIP::MethodStubDispatcher<
        ::v0::iMicro::SOC_AMPStub,
        std::tuple< ::iMicro::iMicroTypes::mute_enum>,
        std::tuple< ::iMicro::iMicroTypes_::mute_enumDeployment_t>
    > sendCommand_Amp_muteStubDispatcher;
    
    CommonAPI::SomeIP::MethodStubDispatcher<
        ::v0::iMicro::SOC_AMPStub,
        std::tuple< ::iMicro::iMicroTypes::amp_register_id_enum>,
        std::tuple< ::iMicro::iMicroTypes_::amp_register_id_enumDeployment_t>
    > sendCommand_Amp_reqRegisterValueStubDispatcher;
    
    CommonAPI::SomeIP::MethodStubDispatcher<
        ::v0::iMicro::SOC_AMPStub,
        std::tuple< ::iMicro::iMicroStructs::amp_setregistervalue_type>,
        std::tuple< ::iMicro::iMicroStructs_::amp_setregistervalue_typeDeployment_t>
    > sendCommand_Amp_setRegisterValueStubDispatcher;
    
    SOC_AMPSomeIPStubAdapterInternal(
        const CommonAPI::SomeIP::Address &_address,
        const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection,
        const std::shared_ptr<CommonAPI::StubBase> &_stub):
        CommonAPI::SomeIP::StubAdapter(_address, _connection),
        SOC_AMPSomeIPStubAdapterHelper(
            _address,
            _connection,
            std::dynamic_pointer_cast< SOC_AMPStub>(_stub)),
        getSOC_AMPInterfaceVersionStubDispatcher(&SOC_AMPStub::lockInterfaceVersionAttribute, &SOC_AMPStub::getInterfaceVersion, false, true),
        sendCommand_Amp_setStandbyStubDispatcher(
            &SOC_AMPStub::SendCommand_Amp_setStandby,
            false,
            _stub->hasElement(0),
            std::make_tuple(static_cast< ::iMicro::iMicroTypes_::standby_enumDeployment_t* >(nullptr)))
        
        ,
        sendCommand_Amp_muteStubDispatcher(
            &SOC_AMPStub::SendCommand_Amp_mute,
            false,
            _stub->hasElement(1),
            std::make_tuple(static_cast< ::iMicro::iMicroTypes_::mute_enumDeployment_t* >(nullptr)))
        
        ,
        sendCommand_Amp_reqRegisterValueStubDispatcher(
            &SOC_AMPStub::SendCommand_Amp_reqRegisterValue,
            false,
            _stub->hasElement(2),
            std::make_tuple(static_cast< ::iMicro::iMicroTypes_::amp_register_id_enumDeployment_t* >(nullptr)))
        
        ,
        sendCommand_Amp_setRegisterValueStubDispatcher(
            &SOC_AMPStub::SendCommand_Amp_setRegisterValue,
            false,
            _stub->hasElement(3),
            std::make_tuple(static_cast< ::iMicro::iMicroStructs_::amp_setregistervalue_typeDeployment_t* >(nullptr)))
        
    {
        SOC_AMPSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x29) }, &sendCommand_Amp_setStandbyStubDispatcher );
        SOC_AMPSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x2a) }, &sendCommand_Amp_muteStubDispatcher );
        SOC_AMPSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x2b) }, &sendCommand_Amp_reqRegisterValueStubDispatcher );
        SOC_AMPSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x2c) }, &sendCommand_Amp_setRegisterValueStubDispatcher );
        // Provided events/fields
        {
            std::set<CommonAPI::SomeIP::eventgroup_id_t> itsEventGroups;
            itsEventGroups.insert(CommonAPI::SomeIP::eventgroup_id_t(0x8106));
            CommonAPI::SomeIP::StubAdapter::registerEvent(CommonAPI::SomeIP::event_id_t(0x8106), itsEventGroups, CommonAPI::SomeIP::event_type_e::ET_EVENT, CommonAPI::SomeIP::reliability_type_e::RT_UNRELIABLE);
        }
    }

    // Register/Unregister event handlers for selective broadcasts
    void registerSelectiveEventHandlers();
    void unregisterSelectiveEventHandlers();

};

template <typename _Stub, typename... _Stubs>
void SOC_AMPSomeIPStubAdapterInternal<_Stub, _Stubs...>::fireSignalResponse_Amp_registerValueEvent(const ::iMicro::iMicroStructs::amp_registervalue_type &_Amp_registerValue) {
    CommonAPI::Deployable< ::iMicro::iMicroStructs::amp_registervalue_type, ::iMicro::iMicroStructs_::amp_registervalue_typeDeployment_t> deployed_Amp_registerValue(_Amp_registerValue, static_cast< ::iMicro::iMicroStructs_::amp_registervalue_typeDeployment_t* >(nullptr));
    CommonAPI::SomeIP::StubEventHelper<CommonAPI::SomeIP::SerializableArguments<  CommonAPI::Deployable< ::iMicro::iMicroStructs::amp_registervalue_type, ::iMicro::iMicroStructs_::amp_registervalue_typeDeployment_t > 
    >>
        ::sendEvent(
            *this,
            CommonAPI::SomeIP::event_id_t(0x8106),
            false,
             deployed_Amp_registerValue 
    );
}


template <typename _Stub, typename... _Stubs>
void SOC_AMPSomeIPStubAdapterInternal<_Stub, _Stubs...>::registerSelectiveEventHandlers() {
}

template <typename _Stub, typename... _Stubs>
void SOC_AMPSomeIPStubAdapterInternal<_Stub, _Stubs...>::unregisterSelectiveEventHandlers() {
}

template <typename _Stub = ::v0::iMicro::SOC_AMPStub, typename... _Stubs>
class SOC_AMPSomeIPStubAdapter
    : public SOC_AMPSomeIPStubAdapterInternal<_Stub, _Stubs...> {
public:
    SOC_AMPSomeIPStubAdapter(const CommonAPI::SomeIP::Address &_address,
                                            const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection,
                                            const std::shared_ptr<CommonAPI::StubBase> &_stub)
        : CommonAPI::SomeIP::StubAdapter(_address, _connection),
          SOC_AMPSomeIPStubAdapterInternal<_Stub, _Stubs...>(_address, _connection, _stub) {
    }
};

} // namespace iMicro
} // namespace v0

#endif // V0_IMICRO_SOC__AMP_SOMEIP_STUB_ADAPTER_HPP_
