/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.0.v202012010944.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
#include <v0/iMicro/SOC_BSPSomeIPProxy.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/SomeIP/AddressTranslator.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v0 {
namespace iMicro {

std::shared_ptr<CommonAPI::SomeIP::Proxy> createSOC_BSPSomeIPProxy(
    const CommonAPI::SomeIP::Address &_address,
    const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection) {
    return std::make_shared< SOC_BSPSomeIPProxy>(_address, _connection);
}

void initializeSOC_BSPSomeIPProxy() {
    CommonAPI::SomeIP::AddressTranslator::get()->insert(
        "local:iMicro.SOC_BSP:v0_1:iMicro.SOC_BSP",
        0x1248, 0x568e, 0, 1);
    CommonAPI::SomeIP::Factory::get()->registerProxyCreateMethod(
        "iMicro.SOC_BSP:v0_1",
        &createSOC_BSPSomeIPProxy);
}

INITIALIZER(registerSOC_BSPSomeIPProxy) {
    CommonAPI::SomeIP::Factory::get()->registerInterface(initializeSOC_BSPSomeIPProxy);
}

SOC_BSPSomeIPProxy::SOC_BSPSomeIPProxy(
    const CommonAPI::SomeIP::Address &_address,
    const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection)
        : CommonAPI::SomeIP::Proxy(_address, _connection),
          vTM_SendTemp2Vuc_(*this, CommonAPI::SomeIP::eventgroup_id_t(0x4001), CommonAPI::SomeIP::event_id_t(0xc06a), CommonAPI::SomeIP::method_id_t(0x12c), false, CommonAPI::SomeIP::reliability_type_e::RT_UNRELIABLE, false, CommonAPI::SomeIP::method_id_t(0x6d), false, static_cast< ::iMicro::iMicroStructs_::VTM_SendTemp2Vuc_typeDeployment_t* >(nullptr)),
          signalCommand_BuB_status_(*this, 0x811d, CommonAPI::SomeIP::event_id_t(0x811d), CommonAPI::SomeIP::event_type_e::ET_EVENT , CommonAPI::SomeIP::reliability_type_e::RT_UNRELIABLE, false, std::make_tuple(static_cast< ::iMicro::iMicroStructs_::BuB_status_typeDeployment_t* >(nullptr)))
{
}

SOC_BSPSomeIPProxy::~SOC_BSPSomeIPProxy() {
    completed_.set_value();
}

SOC_BSPSomeIPProxy::VTM_SendTemp2VucAttribute& SOC_BSPSomeIPProxy::getVTM_SendTemp2VucAttribute() {
    return vTM_SendTemp2Vuc_;
}

SOC_BSPSomeIPProxy::SignalCommand_BuB_statusEvent& SOC_BSPSomeIPProxy::getSignalCommand_BuB_statusEvent() {
    return signalCommand_BuB_status_;
}

void SOC_BSPSomeIPProxy::SendCommand_BuB_reqStatus(uint8_t _BuB_reqStatus, CommonAPI::CallStatus &_internalCallStatus) {
    CommonAPI::Deployable< uint8_t, CommonAPI::SomeIP::IntegerDeployment<uint8_t>> deploy_BuB_reqStatus(_BuB_reqStatus, static_cast< CommonAPI::SomeIP::IntegerDeployment<uint8_t>* >(nullptr));
    CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                uint8_t,
                CommonAPI::SomeIP::IntegerDeployment<uint8_t>
            >
        >,
        CommonAPI::SomeIP::SerializableArguments<
        >
    >::callMethod(
        *this,
        CommonAPI::SomeIP::method_id_t(0x43),
        false,
        false,
        deploy_BuB_reqStatus,
        _internalCallStatus);
}

void SOC_BSPSomeIPProxy::getOwnVersion(uint16_t& ownVersionMajor, uint16_t& ownVersionMinor) const {
    ownVersionMajor = 0;
    ownVersionMinor = 1;
}

std::future<void> SOC_BSPSomeIPProxy::getCompletionFuture() {
    return completed_.get_future();
}

} // namespace iMicro
} // namespace v0
