/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.0.v202012010850.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V0_IMICRO_SOC__FOTA_PROXY_HPP_
#define V0_IMICRO_SOC__FOTA_PROXY_HPP_

#include <v0/iMicro/SOC_FOTAProxyBase.hpp>


#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/AttributeExtension.hpp>
#include <CommonAPI/Factory.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v0 {
namespace iMicro {

template <typename ... _AttributeExtensions>
class SOC_FOTAProxy
    : virtual public SOC_FOTA,
      virtual public SOC_FOTAProxyBase,
      virtual public _AttributeExtensions... {
public:
    SOC_FOTAProxy(std::shared_ptr<CommonAPI::Proxy> delegate);
    ~SOC_FOTAProxy();

    typedef SOC_FOTA InterfaceType;


    /**
     * Returns the CommonAPI address of the remote partner this proxy communicates with.
     */
    virtual const CommonAPI::Address &getAddress() const;

    /**
     * Returns true if the remote partner for this proxy is currently known to be available.
     */
    virtual bool isAvailable() const;

    /**
     * Returns true if the remote partner for this proxy is available.
     */
    virtual bool isAvailableBlocking() const;

    /**
     * Returns the wrapper class that is used to (de-)register for notifications about
     * the availability of the remote partner of this proxy.
     */
    virtual CommonAPI::ProxyStatusEvent& getProxyStatusEvent();

    /**
     * Returns the wrapper class that is used to access version information of the remote
     * partner of this proxy.
     */
    virtual CommonAPI::InterfaceVersionAttribute& getInterfaceVersionAttribute();

    virtual std::future<void> getCompletionFuture();

    /**
     * Calls SendEvent_Flasher_SOC with synchronous semantics.
     *
     * All const parameters are input parameters to this method.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void SendEvent_Flasher_SOC(::iMicro::iMicroTypes::Flasher_SOC_enum _Flasher_SOC, CommonAPI::CallStatus &_internalCallStatus, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls SendEvent_Flasher_SOC with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> SendEvent_Flasher_SOCAsync(const ::iMicro::iMicroTypes::Flasher_SOC_enum &_Flasher_SOC, SendEvent_Flasher_SOCAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls SendCommand_FOTA_STATUS with Fire&Forget semantics.
     *
     * All const parameters are input parameters to this method.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void SendCommand_FOTA_STATUS(::iMicro::iMicroStructs::FOTA_status_type _FOTA_STATUS, CommonAPI::CallStatus &_internalCallStatus);
    /*
     * description: 
     * Flasher MCU Enum
     */
    /**
     * Returns the wrapper class that provides access to the attribute Flasher_MCU.
     */
    virtual Flasher_MCUAttribute& getFlasher_MCUAttribute() {
        return delegate_->getFlasher_MCUAttribute();
    }



 private:
    std::shared_ptr< SOC_FOTAProxyBase> delegate_;
};

typedef SOC_FOTAProxy<> SOC_FOTAProxyDefault;

namespace SOC_FOTAExtensions {
    /*
     * description: 
     * Flasher MCU Enum
     */
    template <template <typename > class _ExtensionType>
    class Flasher_MCUAttributeExtension {
     public:
        typedef _ExtensionType< SOC_FOTAProxyBase::Flasher_MCUAttribute> extension_type;
    
        static_assert(std::is_base_of<typename CommonAPI::AttributeExtension< SOC_FOTAProxyBase::Flasher_MCUAttribute>, extension_type>::value,
                      "Not CommonAPI Attribute Extension!");
    
        Flasher_MCUAttributeExtension(SOC_FOTAProxyBase& proxy): attributeExtension_(proxy.getFlasher_MCUAttribute()) {
        }
    
        inline extension_type& getFlasher_MCUAttributeExtension() {
            return attributeExtension_;
        }
    
     private:
        extension_type attributeExtension_;
    };

} // namespace SOC_FOTAExtensions

//
// SOC_FOTAProxy Implementation
//
template <typename ... _AttributeExtensions>
SOC_FOTAProxy<_AttributeExtensions...>::SOC_FOTAProxy(std::shared_ptr<CommonAPI::Proxy> delegate):
        _AttributeExtensions(*(std::dynamic_pointer_cast< SOC_FOTAProxyBase>(delegate)))...,
        delegate_(std::dynamic_pointer_cast< SOC_FOTAProxyBase>(delegate)) {
}

template <typename ... _AttributeExtensions>
SOC_FOTAProxy<_AttributeExtensions...>::~SOC_FOTAProxy() {
}

template <typename ... _AttributeExtensions>
void SOC_FOTAProxy<_AttributeExtensions...>::SendEvent_Flasher_SOC(::iMicro::iMicroTypes::Flasher_SOC_enum _Flasher_SOC, CommonAPI::CallStatus &_internalCallStatus, const CommonAPI::CallInfo *_info) {
    if (!_Flasher_SOC.validate()) {
        _internalCallStatus = CommonAPI::CallStatus::INVALID_VALUE;
        return;
    }
    delegate_->SendEvent_Flasher_SOC(_Flasher_SOC, _internalCallStatus, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> SOC_FOTAProxy<_AttributeExtensions...>::SendEvent_Flasher_SOCAsync(const ::iMicro::iMicroTypes::Flasher_SOC_enum &_Flasher_SOC, SendEvent_Flasher_SOCAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    if (!_Flasher_SOC.validate()) {
        _callback(CommonAPI::CallStatus::INVALID_VALUE);
        std::promise<CommonAPI::CallStatus> promise;
        promise.set_value(CommonAPI::CallStatus::INVALID_VALUE);
        return promise.get_future();
    }
    return delegate_->SendEvent_Flasher_SOCAsync(_Flasher_SOC, _callback, _info);
}
template <typename ... _AttributeExtensions>
void SOC_FOTAProxy<_AttributeExtensions...>::SendCommand_FOTA_STATUS(::iMicro::iMicroStructs::FOTA_status_type _FOTA_STATUS, CommonAPI::CallStatus &_internalCallStatus) {
    delegate_->SendCommand_FOTA_STATUS(_FOTA_STATUS, _internalCallStatus);
}

template <typename ... _AttributeExtensions>
const CommonAPI::Address &SOC_FOTAProxy<_AttributeExtensions...>::getAddress() const {
    return delegate_->getAddress();
}

template <typename ... _AttributeExtensions>
bool SOC_FOTAProxy<_AttributeExtensions...>::isAvailable() const {
    return delegate_->isAvailable();
}

template <typename ... _AttributeExtensions>
bool SOC_FOTAProxy<_AttributeExtensions...>::isAvailableBlocking() const {
    return delegate_->isAvailableBlocking();
}

template <typename ... _AttributeExtensions>
CommonAPI::ProxyStatusEvent& SOC_FOTAProxy<_AttributeExtensions...>::getProxyStatusEvent() {
    return delegate_->getProxyStatusEvent();
}

template <typename ... _AttributeExtensions>
CommonAPI::InterfaceVersionAttribute& SOC_FOTAProxy<_AttributeExtensions...>::getInterfaceVersionAttribute() {
    return delegate_->getInterfaceVersionAttribute();
}


template <typename ... _AttributeExtensions>
std::future<void> SOC_FOTAProxy<_AttributeExtensions...>::getCompletionFuture() {
    return delegate_->getCompletionFuture();
}

} // namespace iMicro
} // namespace v0

namespace CommonAPI {
template<template<typename > class _AttributeExtension>
struct DefaultAttributeProxyHelper< ::v0::iMicro::SOC_FOTAProxy,
    _AttributeExtension> {
    typedef typename ::v0::iMicro::SOC_FOTAProxy<
            ::v0::iMicro::SOC_FOTAExtensions::Flasher_MCUAttributeExtension<_AttributeExtension>
    > class_t;
};
}


// Compatibility
namespace v0_1 = v0;

#endif // V0_IMICRO_SOC__FOTA_PROXY_HPP_
