/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.0.v202012010850.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V0_IMICRO_SOC__Device_VC_PROXY_BASE_HPP_
#define V0_IMICRO_SOC__Device_VC_PROXY_BASE_HPP_

#include <v0/iMicro/SOC_DeviceVC.hpp>


#include <iMicro/iMicroStructs.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/Deployment.hpp>
#include <CommonAPI/InputStream.hpp>
#include <CommonAPI/OutputStream.hpp>
#include <CommonAPI/Struct.hpp>
#include <cstdint>
#include <vector>

#include <CommonAPI/Event.hpp>
#include <CommonAPI/Proxy.hpp>
#include <functional>
#include <future>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v0 {
namespace iMicro {

class SOC_DeviceVCProxyBase
    : virtual public CommonAPI::Proxy {
public:
    typedef CommonAPI::Event<
        ::iMicro::iMicroStructs::DeviceVC_VC2NADHandshake_type
    > SignalEvent_DeviceVC_VC2NADHandshakeEvent;

    typedef std::function<void(const CommonAPI::CallStatus&, const ::iMicro::iMicroStructs::DeviceVC_VC2NADHandshake_type&)> GetEvent_DeviceVC_VC2NADHandshakeAsyncCallback;

    /**
     * @invariant Fire And Forget
     */
    virtual void SendResponse_DeviceVC_NAD2VCHandshake(::iMicro::iMicroStructs::DeviceVC_NAD2VCHandshake_type _DeviceVC_NAD2VCHandshake, CommonAPI::CallStatus &_internalCallStatus) = 0;
    virtual void GetEvent_DeviceVC_VC2NADHandshake(CommonAPI::CallStatus &_internalCallStatus, ::iMicro::iMicroStructs::DeviceVC_VC2NADHandshake_type &_DeviceVC_VC2NADHandshake, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> GetEvent_DeviceVC_VC2NADHandshakeAsync(GetEvent_DeviceVC_VC2NADHandshakeAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual SignalEvent_DeviceVC_VC2NADHandshakeEvent& getSignalEvent_DeviceVC_VC2NADHandshakeEvent() = 0;

    virtual std::future<void> getCompletionFuture() = 0;
};

} // namespace iMicro
} // namespace v0


// Compatibility
namespace v0_1 = v0;

#endif // V0_IMICRO_SOC__Device_VC_PROXY_BASE_HPP_
