/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.0.v202012010850.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V0_IMICRO_SOC__FIRST_STUB_HPP_
#define V0_IMICRO_SOC__FIRST_STUB_HPP_

#include <functional>
#include <sstream>



#include <iMicro/iMicroStructs.hpp>

#include <v0/iMicro/SOC_FIRST.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/Deployment.hpp>
#include <CommonAPI/InputStream.hpp>
#include <CommonAPI/OutputStream.hpp>
#include <CommonAPI/Struct.hpp>
#include <cstdint>
#include <vector>

#include <mutex>

#include <CommonAPI/Stub.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v0 {
namespace iMicro {

/**
 * Receives messages from remote and handles all dispatching of deserialized calls
 * to a stub for the service SOC_FIRST. Also provides means to send broadcasts
 * and attribute-changed-notifications of observable attributes as defined by this service.
 * An application developer should not need to bother with this class.
 */
class SOC_FIRSTStubAdapter
    : public virtual CommonAPI::StubAdapter,
      public virtual SOC_FIRST {
 public:
    ///Notifies all remote listeners about a change of value of the attribute LC_SYNCHRO.
    virtual void fireLC_SYNCHROAttributeChanged(const ::iMicro::iMicroStructs::IM_LC_Synchro_t &LC_SYNCHRO) = 0;
    ///Notifies all remote listeners about a change of value of the attribute VOLTAGE_STATE.
    virtual void fireVOLTAGE_STATEAttributeChanged(const ::iMicro::iMicroStructs::IM_VM_State_t &VOLTAGE_STATE) = 0;
    ///Notifies all remote listeners about a change of value of the attribute IM_VUC_ID_VOLTAGE_VALUE.
    virtual void fireIM_VUC_ID_VOLTAGE_VALUEAttributeChanged(const uint8_t &IM_VUC_ID_VOLTAGE_VALUE) = 0;
    ///Notifies all remote listeners about a change of value of the attribute LOG_DATA_CHECKSUM.
    virtual void fireLOG_DATA_CHECKSUMAttributeChanged(const ::iMicro::iMicroStructs::IM_LOGDATA_checksum_t &LOG_DATA_CHECKSUM) = 0;
    ///Notifies all remote listeners about a change of value of the attribute LOG_DATA_FULL.
    virtual void fireLOG_DATA_FULLAttributeChanged(const ::iMicro::iMicroStructs::IM_LOGDATA_data_t &LOG_DATA_FULL) = 0;
    ///Notifies all remote listeners about a change of value of the attribute hwid.
    virtual void fireHwidAttributeChanged(const ::iMicro::iMicroStructs::hwv_id_t &hwid) = 0;


    virtual void deactivateManagedInstances() = 0;

    void lockLC_SYNCHROAttribute(bool _lockAccess) {
        if (_lockAccess) {
            lC_SYNCHROMutex_.lock();
        } else {
            lC_SYNCHROMutex_.unlock();
        }
    }
    void lockVOLTAGE_STATEAttribute(bool _lockAccess) {
        if (_lockAccess) {
            vOLTAGE_STATEMutex_.lock();
        } else {
            vOLTAGE_STATEMutex_.unlock();
        }
    }
    void lockIM_VUC_ID_VOLTAGE_VALUEAttribute(bool _lockAccess) {
        if (_lockAccess) {
            iM_VUC_ID_VOLTAGE_VALUEMutex_.lock();
        } else {
            iM_VUC_ID_VOLTAGE_VALUEMutex_.unlock();
        }
    }
    void lockLOG_DATA_CHECKSUMAttribute(bool _lockAccess) {
        if (_lockAccess) {
            lOG_DATA_CHECKSUMMutex_.lock();
        } else {
            lOG_DATA_CHECKSUMMutex_.unlock();
        }
    }
    void lockLOG_DATA_FULLAttribute(bool _lockAccess) {
        if (_lockAccess) {
            lOG_DATA_FULLMutex_.lock();
        } else {
            lOG_DATA_FULLMutex_.unlock();
        }
    }
    void lockHwidAttribute(bool _lockAccess) {
        if (_lockAccess) {
            hwidMutex_.lock();
        } else {
            hwidMutex_.unlock();
        }
    }

protected:
    /**
     * Defines properties for storing the ClientIds of clients / proxies that have
     * subscribed to the selective broadcasts
     */
    std::recursive_mutex lC_SYNCHROMutex_;
    std::recursive_mutex vOLTAGE_STATEMutex_;
    std::recursive_mutex iM_VUC_ID_VOLTAGE_VALUEMutex_;
    std::recursive_mutex lOG_DATA_CHECKSUMMutex_;
    std::recursive_mutex lOG_DATA_FULLMutex_;
    std::recursive_mutex hwidMutex_;

};

/**
 * Defines the necessary callbacks to handle remote set events related to the attributes
 * defined in the IDL description for SOC_FIRST.
 * For each attribute two callbacks are defined:
 * - a verification callback that allows to verify the requested value and to prevent setting
 *   e.g. an invalid value ("onRemoteSet<AttributeName>").
 * - an action callback to do local work after the attribute value has been changed
 *   ("onRemote<AttributeName>Changed").
 *
 * This class and the one below are the ones an application developer needs to have
 * a look at if he wants to implement a service.
 */
class SOC_FIRSTStubRemoteEvent
{
public:
    virtual ~SOC_FIRSTStubRemoteEvent() { }

    /// Verification callback for remote set requests on the attribute LC_SYNCHRO
    virtual bool onRemoteSetLC_SYNCHROAttribute(const std::shared_ptr<CommonAPI::ClientId> _client, ::iMicro::iMicroStructs::IM_LC_Synchro_t _value) = 0;
    /// Action callback for remote set requests on the attribute LC_SYNCHRO
    virtual void onRemoteLC_SYNCHROAttributeChanged() = 0;
};

/**
 * Defines the interface that must be implemented by any class that should provide
 * the service SOC_FIRST to remote clients.
 * This class and the one above are the ones an application developer needs to have
 * a look at if he wants to implement a service.
 */
class SOC_FIRSTStub
    : public virtual CommonAPI::Stub<SOC_FIRSTStubAdapter, SOC_FIRSTStubRemoteEvent>
{
public:
    typedef std::function<void ()> SendEvent_Internal_Fan_SpeedReply_t;

    virtual ~SOC_FIRSTStub() {}
    void lockInterfaceVersionAttribute(bool _lockAccess) { static_cast<void>(_lockAccess); }
    bool hasElement(const uint32_t _id) const {
        return (_id < 7);
    }
    virtual const CommonAPI::Version& getInterfaceVersion(std::shared_ptr<CommonAPI::ClientId> _client) = 0;

    /*
     * description: 
     * Feedback from SoC for synchronization, From AIDA_FormMessages_module_iMicro_ONOFF_Vxxx.doc
     */
    /// Provides getter access to the attribute LC_SYNCHRO
    virtual const ::iMicro::iMicroStructs::IM_LC_Synchro_t &getLC_SYNCHROAttribute(const std::shared_ptr<CommonAPI::ClientId> _client) = 0;
    /// sets attribute with the given value and propagates it to the adapter
    virtual void fireLC_SYNCHROAttributeChanged(::iMicro::iMicroStructs::IM_LC_Synchro_t _value) {
    auto stubAdapter = CommonAPI::Stub<SOC_FIRSTStubAdapter, SOC_FIRSTStubRemoteEvent>::stubAdapter_.lock();
    if (stubAdapter)
        stubAdapter->fireLC_SYNCHROAttributeChanged(_value);
    }
    void lockLC_SYNCHROAttribute(bool _lockAccess) {
        auto stubAdapter = CommonAPI::Stub<SOC_FIRSTStubAdapter, SOC_FIRSTStubRemoteEvent>::stubAdapter_.lock();
        if (stubAdapter)
            stubAdapter->lockLC_SYNCHROAttribute(_lockAccess);
    }
    /// This is the method that will be called on remote calls on the method SendEvent_Internal_Fan_Speed.
    virtual void SendEvent_Internal_Fan_Speed(const std::shared_ptr<CommonAPI::ClientId> _client, uint8_t _Internal_Fan_Speed, SendEvent_Internal_Fan_SpeedReply_t _reply) = 0;
    /*
     * description: 
     * VTM, From AIDA_FormMessages_module_iMicro_WATCHDOG_AND_VTM_Vxxx.doc
     */
    /// Provides getter access to the attribute VOLTAGE_STATE
    virtual const ::iMicro::iMicroStructs::IM_VM_State_t &getVOLTAGE_STATEAttribute(const std::shared_ptr<CommonAPI::ClientId> _client) = 0;
    /// sets attribute with the given value and propagates it to the adapter
    virtual void fireVOLTAGE_STATEAttributeChanged(::iMicro::iMicroStructs::IM_VM_State_t _value) {
    auto stubAdapter = CommonAPI::Stub<SOC_FIRSTStubAdapter, SOC_FIRSTStubRemoteEvent>::stubAdapter_.lock();
    if (stubAdapter)
        stubAdapter->fireVOLTAGE_STATEAttributeChanged(_value);
    }
    void lockVOLTAGE_STATEAttribute(bool _lockAccess) {
        auto stubAdapter = CommonAPI::Stub<SOC_FIRSTStubAdapter, SOC_FIRSTStubRemoteEvent>::stubAdapter_.lock();
        if (stubAdapter)
            stubAdapter->lockVOLTAGE_STATEAttribute(_lockAccess);
    }
    /*
     * description: 
     * IM_VUC_ID_VOLTAGE_VALUE
     */
    /// Provides getter access to the attribute IM_VUC_ID_VOLTAGE_VALUE
    virtual const uint8_t &getIM_VUC_ID_VOLTAGE_VALUEAttribute(const std::shared_ptr<CommonAPI::ClientId> _client) = 0;
    /// sets attribute with the given value and propagates it to the adapter
    virtual void fireIM_VUC_ID_VOLTAGE_VALUEAttributeChanged(uint8_t _value) {
    auto stubAdapter = CommonAPI::Stub<SOC_FIRSTStubAdapter, SOC_FIRSTStubRemoteEvent>::stubAdapter_.lock();
    if (stubAdapter)
        stubAdapter->fireIM_VUC_ID_VOLTAGE_VALUEAttributeChanged(_value);
    }
    void lockIM_VUC_ID_VOLTAGE_VALUEAttribute(bool _lockAccess) {
        auto stubAdapter = CommonAPI::Stub<SOC_FIRSTStubAdapter, SOC_FIRSTStubRemoteEvent>::stubAdapter_.lock();
        if (stubAdapter)
            stubAdapter->lockIM_VUC_ID_VOLTAGE_VALUEAttribute(_lockAccess);
    }
    /*
     * description: 
     * LOGDATA, AIDA_FormMessages_module_iMicro_WATCHDOG_VTM_LOGISTIC_Vxxx.doc
     */
    /// Provides getter access to the attribute LOG_DATA_CHECKSUM
    virtual const ::iMicro::iMicroStructs::IM_LOGDATA_checksum_t &getLOG_DATA_CHECKSUMAttribute(const std::shared_ptr<CommonAPI::ClientId> _client) = 0;
    /// sets attribute with the given value and propagates it to the adapter
    virtual void fireLOG_DATA_CHECKSUMAttributeChanged(::iMicro::iMicroStructs::IM_LOGDATA_checksum_t _value) {
    auto stubAdapter = CommonAPI::Stub<SOC_FIRSTStubAdapter, SOC_FIRSTStubRemoteEvent>::stubAdapter_.lock();
    if (stubAdapter)
        stubAdapter->fireLOG_DATA_CHECKSUMAttributeChanged(_value);
    }
    void lockLOG_DATA_CHECKSUMAttribute(bool _lockAccess) {
        auto stubAdapter = CommonAPI::Stub<SOC_FIRSTStubAdapter, SOC_FIRSTStubRemoteEvent>::stubAdapter_.lock();
        if (stubAdapter)
            stubAdapter->lockLOG_DATA_CHECKSUMAttribute(_lockAccess);
    }
    /*
     * description: 
     * LOGDATA, AIDA_FormMessages_module_iMicro_WATCHDOG_VTM_LOGISTIC_Vxxx.doc
     */
    /// Provides getter access to the attribute LOG_DATA_FULL
    virtual const ::iMicro::iMicroStructs::IM_LOGDATA_data_t &getLOG_DATA_FULLAttribute(const std::shared_ptr<CommonAPI::ClientId> _client) = 0;
    /// sets attribute with the given value and propagates it to the adapter
    virtual void fireLOG_DATA_FULLAttributeChanged(::iMicro::iMicroStructs::IM_LOGDATA_data_t _value) {
    auto stubAdapter = CommonAPI::Stub<SOC_FIRSTStubAdapter, SOC_FIRSTStubRemoteEvent>::stubAdapter_.lock();
    if (stubAdapter)
        stubAdapter->fireLOG_DATA_FULLAttributeChanged(_value);
    }
    void lockLOG_DATA_FULLAttribute(bool _lockAccess) {
        auto stubAdapter = CommonAPI::Stub<SOC_FIRSTStubAdapter, SOC_FIRSTStubRemoteEvent>::stubAdapter_.lock();
        if (stubAdapter)
            stubAdapter->lockLOG_DATA_FULLAttribute(_lockAccess);
    }
    /// Provides getter access to the attribute hwid
    virtual const ::iMicro::iMicroStructs::hwv_id_t &getHwidAttribute(const std::shared_ptr<CommonAPI::ClientId> _client) = 0;
    /// sets attribute with the given value and propagates it to the adapter
    virtual void fireHwidAttributeChanged(::iMicro::iMicroStructs::hwv_id_t _value) {
    auto stubAdapter = CommonAPI::Stub<SOC_FIRSTStubAdapter, SOC_FIRSTStubRemoteEvent>::stubAdapter_.lock();
    if (stubAdapter)
        stubAdapter->fireHwidAttributeChanged(_value);
    }
    void lockHwidAttribute(bool _lockAccess) {
        auto stubAdapter = CommonAPI::Stub<SOC_FIRSTStubAdapter, SOC_FIRSTStubRemoteEvent>::stubAdapter_.lock();
        if (stubAdapter)
            stubAdapter->lockHwidAttribute(_lockAccess);
    }


    using CommonAPI::Stub<SOC_FIRSTStubAdapter, SOC_FIRSTStubRemoteEvent>::initStubAdapter;
    typedef CommonAPI::Stub<SOC_FIRSTStubAdapter, SOC_FIRSTStubRemoteEvent>::StubAdapterType StubAdapterType;
    typedef CommonAPI::Stub<SOC_FIRSTStubAdapter, SOC_FIRSTStubRemoteEvent>::RemoteEventHandlerType RemoteEventHandlerType;
    typedef SOC_FIRSTStubRemoteEvent RemoteEventType;
    typedef SOC_FIRST StubInterface;
};

} // namespace iMicro
} // namespace v0


// Compatibility
namespace v0_1 = v0;

#endif // V0_IMICRO_SOC__FIRST_STUB_HPP_
