/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.0.v202012010850.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V0_IMICRO_SOC__TAN_STUB_DEFAULT_HPP_
#define V0_IMICRO_SOC__TAN_STUB_DEFAULT_HPP_


#include <CommonAPI/Export.hpp>

#include <v0/iMicro/SOC_TANStub.hpp>
#include <cassert>
#include <sstream>

# if defined(_MSC_VER)
#  if _MSC_VER >= 1300
/*
 * Diamond inheritance is used for the CommonAPI::Proxy base class.
 * The Microsoft compiler put warning (C4250) using a desired c++ feature: "Delegating to a sister class"
 * A powerful technique that arises from using virtual inheritance is to delegate a method from a class in another class
 * by using a common abstract base class. This is also called cross delegation.
 */
#    pragma warning( disable : 4250 )
#  endif
# endif

namespace v0 {
namespace iMicro {

/**
 * Provides a default implementation for SOC_TANStubRemoteEvent and
 * SOC_TANStub. Method callbacks have an empty implementation,
 * remote set calls on attributes will always change the value of the attribute
 * to the one received.
 *
 * Override this stub if you only want to provide a subset of the functionality
 * that would be defined for this service, and/or if you do not need any non-default
 * behaviour.
 */
class COMMONAPI_EXPORT_CLASS_EXPLICIT SOC_TANStubDefault
    : public virtual SOC_TANStub {
public:
    COMMONAPI_EXPORT SOC_TANStubDefault()
        : remoteEventHandler_(this),
          interfaceVersion_(SOC_TAN::getInterfaceVersion()) {
    }

    COMMONAPI_EXPORT const CommonAPI::Version& getInterfaceVersion(std::shared_ptr<CommonAPI::ClientId> _client) {
        (void)_client;
        return interfaceVersion_;
    }

    COMMONAPI_EXPORT SOC_TANStubRemoteEvent* initStubAdapter(const std::shared_ptr< SOC_TANStubAdapter> &_adapter) {
        CommonAPI::Stub<SOC_TANStubAdapter, SOC_TANStubRemoteEvent>::stubAdapter_ = _adapter;
        return &remoteEventHandler_;
    }

    COMMONAPI_EXPORT virtual void SendCommand_TAN_requestVcPacket(const std::shared_ptr<CommonAPI::ClientId> _client, uint8_t _TAN_requestVcPacket) {
        (void)_client;
        (void)_TAN_requestVcPacket;
    }
    COMMONAPI_EXPORT virtual void SendEvent_TAN_asyncNadPacket(const std::shared_ptr<CommonAPI::ClientId> _client, ::iMicro::iMicroStructs::TAN_NadPacket_type _TAN_asyncNadPacket, SendEvent_TAN_asyncNadPacketReply_t _reply) {
        (void)_client;
        (void)_TAN_asyncNadPacket;
        _reply();
    }
    COMMONAPI_EXPORT virtual void SendResponse_TAN_responseNadPacket(const std::shared_ptr<CommonAPI::ClientId> _client, ::iMicro::iMicroStructs::TAN_NadPacket_type _TAN_responseNadPacket) {
        (void)_client;
        (void)_TAN_responseNadPacket;
    }
    COMMONAPI_EXPORT virtual void GetEvent_TAN_asyncVcPacket(const std::shared_ptr<CommonAPI::ClientId> _client, GetEvent_TAN_asyncVcPacketReply_t _reply) {
        (void)_client;
        ::iMicro::iMicroStructs::TAN_VcPacket_type TAN_asyncVcPacket = {};
        _reply(TAN_asyncVcPacket);
    }
    COMMONAPI_EXPORT virtual void fireSignalEvent_TAN_asyncVcPacketEvent(const ::iMicro::iMicroStructs::TAN_VcPacket_type &_TAN_asyncVcPacket) {
        SOC_TANStub::fireSignalEvent_TAN_asyncVcPacketEvent(_TAN_asyncVcPacket);
    }
    COMMONAPI_EXPORT virtual void fireSignalResponse_TAN_responseVcPacketEvent(const ::iMicro::iMicroStructs::TAN_VcPacket_type &_TAN_responseVcPacket) {
        SOC_TANStub::fireSignalResponse_TAN_responseVcPacketEvent(_TAN_responseVcPacket);
    }
    COMMONAPI_EXPORT virtual void fireSignalCommand_TAN_requestNadPacketEvent(const uint8_t &_TAN_requestNadPacket) {
        SOC_TANStub::fireSignalCommand_TAN_requestNadPacketEvent(_TAN_requestNadPacket);
    }


protected:
    class COMMONAPI_EXPORT_CLASS_EXPLICIT RemoteEventHandler: public virtual SOC_TANStubRemoteEvent {
    public:
        COMMONAPI_EXPORT RemoteEventHandler(SOC_TANStubDefault *_defaultStub)
            : 
              defaultStub_(_defaultStub) {
        }


    private:
        SOC_TANStubDefault *defaultStub_;
    };
protected:
    SOC_TANStubDefault::RemoteEventHandler remoteEventHandler_;

private:


    CommonAPI::Version interfaceVersion_;
};

} // namespace iMicro
} // namespace v0


// Compatibility
namespace v0_1 = v0;

#endif // V0_IMICRO_SOC__TAN_STUB_DEFAULT
